// GENERATED by scripts/gen-worker-api.mjs from packages/dev/manifold/lib/api/services/cross-section/cross-section.ts - do not edit.
// The kernel class is the source of the docs, the signatures and the member order.
// Regenerate with `npm run gen:worker-api` at the repository root.
import * as Inputs from "@bitbybit-dev/manifold/lib/api/inputs";
import { ManifoldWorkerManager } from "../../manifold-worker/manifold-worker-manager";
import { CrossSectionShapes } from "./shapes";
import { CrossSectionOperations } from "./operations";
import { CrossSectionBooleans } from "./booleans";
import { CrossSectionTransforms } from "./transforms";
import { CrossSectionEvaluate } from "./evaluate";

/**
 * Flat outlines in the Manifold kernel, the 2D shapes that `operations.extrude` and
 * `operations.revolve` turn into solids and that `slice` and `project` cut out of them. A
 * cross-section is one or more closed polygons in the XY plane, holes included; `shapes` builds
 * them, `booleans` combines them, `operations` offsets, hulls and extrudes them, `transforms` moves
 * them and `evaluate` measures them. The methods here convert between cross-sections and plain
 * point lists, and free the memory a cross-section holds.
 */
export class ManifoldCrossSection {
    public readonly shapes: CrossSectionShapes;
    public readonly operations: CrossSectionOperations;
    public readonly booleans: CrossSectionBooleans;
    public readonly transforms: CrossSectionTransforms;
    public readonly evaluate: CrossSectionEvaluate;

    constructor(
        private readonly manifoldWorkerManager: ManifoldWorkerManager
    ) {
        this.shapes = new CrossSectionShapes(manifoldWorkerManager);
        this.operations = new CrossSectionOperations(manifoldWorkerManager);
        this.booleans = new CrossSectionBooleans(manifoldWorkerManager);
        this.transforms = new CrossSectionTransforms(manifoldWorkerManager);
        this.evaluate = new CrossSectionEvaluate(manifoldWorkerManager);
    }

    /**
     * Builds a cross-section from one polygon given as points; only the X and Y of each point are
     * used.
     *
     * `fillRule` decides which regions of a self-crossing polygon count as inside;
     * `removeDuplicates` drops consecutive repeated points within `tolerance` first.
     * @param inputs - The polygon points, the fill rule and the duplicate handling
     * @returns The cross-section
     * @group create
     * @shortname cross section from points
     * @drawable true
     * @example
     * ```typescript
     * const outline = await bitbybit.manifold.crossSection.crossSectionFromPoints({
     *     points: [[0, 0, 0], [10, 0, 0], [10, 10, 0], [0, 10, 0]],
     *     fillRule: Bit.Inputs.Manifold.fillRuleEnum.positive,
     *     removeDuplicates: false,
     *     tolerance: 1e-7,
     * });
     * ```
     */
    crossSectionFromPoints(inputs: Inputs.Manifold.CrossSectionFromPolygonPointsDto): Promise<Inputs.Manifold.CrossSectionPointer> {
        return this.manifoldWorkerManager.genericCallToWorkerPromise("crossSection.crossSectionFromPoints", inputs);
    }

    /**
     * Builds a cross-section from several polygons given as points, for instance an outline and its
     * holes; only the X and Y of each point are used.
     *
     * `fillRule` decides which regions count as inside where polygons overlap; `removeDuplicates`
     * drops consecutive repeated points within `tolerance` first.
     * @param inputs - The polygons as point lists, the fill rule and the duplicate handling
     * @returns The cross-section
     * @group create
     * @shortname cross section from polygons
     * @drawable true
     * @example
     * ```typescript
     * const plate = await bitbybit.manifold.crossSection.crossSectionFromPolygons({
     *     polygonPoints: [outerPoints, holePoints],
     *     fillRule: Bit.Inputs.Manifold.fillRuleEnum.evenOdd,
     *     removeDuplicates: false,
     *     tolerance: 1e-7,
     * });
     * ```
     */
    crossSectionFromPolygons(inputs: Inputs.Manifold.CrossSectionFromPolygonsPointsDto): Promise<Inputs.Manifold.CrossSectionPointer> {
        return this.manifoldWorkerManager.genericCallToWorkerPromise("crossSection.crossSectionFromPolygons", inputs);
    }

    /**
     * Reads a cross-section back as its polygons, each a list of 2D points.
     * @param inputs - The cross-section
     * @returns One list of 2D points per polygon
     * @group decompose
     * @shortname cross section to polygons
     * @drawable false
     * @example
     * ```typescript
     * const polygons = await bitbybit.manifold.crossSection.crossSectionToPolygons({ crossSection: outline });
     * ```
     */
    crossSectionToPolygons(inputs: Inputs.Manifold.CrossSectionDto<Inputs.Manifold.CrossSectionPointer>): Promise<Inputs.Base.Vector2[][]> {
        return this.manifoldWorkerManager.genericCallToWorkerPromise("crossSection.crossSectionToPolygons", inputs);
    }

    /**
     * Reads a cross-section back as its polygons with 3D points, Z set to 0, ready for drawing as
     * polylines.
     * @param inputs - The cross-section
     * @returns One list of points per polygon
     * @group decompose
     * @shortname cross section to points
     * @drawable false
     * @example
     * ```typescript
     * const polylines = await bitbybit.manifold.crossSection.crossSectionToPoints({ crossSection: outline });
     * ```
     */
    crossSectionToPoints(inputs: Inputs.Manifold.CrossSectionDto<Inputs.Manifold.CrossSectionPointer>): Promise<Inputs.Base.Point3[][]> {
        return this.manifoldWorkerManager.genericCallToWorkerPromise("crossSection.crossSectionToPoints", inputs);
    }

    /**
     * Reads several cross-sections back as their polygons, as `crossSectionToPolygons` does for
     * one.
     * @param inputs - The cross-sections
     * @returns One polygon list per cross-section, in the same order
     * @group decompose
     * @shortname cross sections to polygons
     * @drawable false
     * @example
     * ```typescript
     * const polygons = await bitbybit.manifold.crossSection.crossSectionsToPolygons({ crossSections: [outline, hole] });
     * ```
     */
    crossSectionsToPolygons(inputs: Inputs.Manifold.CrossSectionsDto<Inputs.Manifold.CrossSectionPointer>): Promise<Inputs.Base.Vector2[][][]> {
        return this.manifoldWorkerManager.genericCallToWorkerPromise("crossSection.crossSectionsToPolygons", inputs);
    }

    /**
     * Reads several cross-sections back as polygons with 3D points, as `crossSectionToPoints` does
     * for one.
     * @param inputs - The cross-sections
     * @returns One list of point polygons per cross-section, in the same order
     * @group decompose
     * @shortname cross sections to points
     * @drawable false
     * @example
     * ```typescript
     * const polylines = await bitbybit.manifold.crossSection.crossSectionsToPoints({ crossSections: [outline, hole] });
     * ```
     */
    crossSectionsToPoints(inputs: Inputs.Manifold.CrossSectionsDto<Inputs.Manifold.CrossSectionPointer>): Promise<number[][][][]> {
        return this.manifoldWorkerManager.genericCallToWorkerPromise("crossSection.crossSectionsToPoints", inputs);
    }
}
