import { ResourcesInterface } from './resources.interface';

export const resourcesLt: ResourcesInterface = {
    bit_by_bit: 'BitasPoBito',
    app_menu_run_code: 'Paleisti Koda',
    app_menu_swap_canvas: 'Sukeisti Aplinkas',
    app_menu_support_us_on_patreon: 'Paremkite mus Patreone',
    app_menu_clean_canvas: 'Isvalyti Drobe',
    app_menu_more: 'Daugiau',
    app_menu_more_about: 'Apie',
    app_menu_more_settings: 'Pasirinktys',
    app_menu_more_examples: 'Pavyzdziai',
    app_menu_more_sponsors: 'Remejai',
    app_menu_more_community: 'Bendruomene',
    app_menu_more_export: 'Issaugoti',
    app_menu_more_import: 'Atidaryti',
    block_toolbox_category_scene: 'Scena',
    block_toolbox_category_core_types: 'Tipai',
    block_toolbox_category_core_vector: 'Vektoriai',
    block_toolbox_category_geom_point: 'Taskas',
    block_toolbox_category_geom_line: 'Linija',
    block_toolbox_category_geom_polyline: 'Polilinija',
    block_toolbox_category_geom_curve: 'Kreive',
    block_toolbox_category_geom_surface: 'Pavirsius',
    block_toolbox_category_loop: 'Ciklai',
    block_toolbox_category_logic: 'Logika',
    block_toolbox_category_math: 'Matematika',
    block_toolbox_category_lists: 'Rinkiniai',
    block_toolbox_category_colour: 'Spalvos',
    block_toolbox_category_text: 'Tekstas',
    block_toolbox_category_variables: 'Kintamieji',
    block_toolbox_category_functions: 'Funkcijos',
    block_point: 'Taskas',
    block_coordinate_x: 'Koordinate X',
    block_coordinate_y: 'Koordinate Y',
    block_coordinate_z: 'Koordinate Z',
    block_coordinate_short_x: 'X',
    block_coordinate_short_y: 'Y',
    block_coordinate_short_z: 'Z',
    block_points: 'Taskai',
    block_curve: 'Kreive',
    block_curves: 'Kreives',
    block_colour: 'Spalva',
    block_opacity: 'Matomumas',
    block_width: 'Storis',
    block_line: 'Linija',
    block_lines: 'Linijos',
    block_polyline: 'Polilinija',
    block_size: 'Dydis',
    block_surface: 'Pavirsius',
    block_surfaces: 'Pavirsiai',
    block_circle: 'Apskritimas',
    block_center: 'Centras',
    block_radius: 'Spindulys',
    block_min: 'Minimumas',
    block_max: 'Maksimumas',
    block_interval: 'Intervalas',
    block_scale: 'Didinimas',
    block_vector: 'Vektorius',
    block_vectors: 'Vektoriai',
    block_angle: 'Kampas',
    block_axis: 'Asis',
    block_u: 'U',
    block_v: 'V',
    block_uv: 'UV',
    block_transform: 'Transformacija',
    block_validation_required: 'privalo buti ivesta',
    block_validation_higher_or_equal: 'privalo buti daugiau arba lygu',
    block_validation_lower_or_equal: 'privalo buti maziau arba lygu',
    block_validation_of_length: 'privalomas elementu skaicius yra',
    block_validation_range: 'privalo buti tarp',
    block_validation_smaller_than: 'privalu buti mazesnis uz',
    block_validation_smaller_or_equal_than: 'privalo buti mazesnis arba lygus',
    block_validation_larger_than: 'privalo buti didesnis uz',
    block_validation_larger_or_equal_than: 'privalo buti didesnis arba lygus',
    block_babylon_input_curve: 'Piesti kreive',
    block_babylon_input_curves: 'Piesti kreives',
    block_babylon_input_colour: 'Spalva',
    block_babylon_input_opacity: 'Matomumas',
    block_babylon_input_width: 'Storis',
    block_babylon_input_draw_grid: 'Piesti tinkleli kurio plotis',
    block_babylon_input_draw_line: 'Piesti linija',
    block_babylon_input_draw_lines: 'Piesti linijas',
    block_babylon_input_draw_polyline: 'Piesti polilinija',
    block_babylon_input_draw_point: 'Piesti taska',
    block_babylon_input_draw_points: 'Piesti taskus',
    block_babylon_input_draw_surface: 'Piesti pavirsiu',
    block_babylon_input_draw_surfaces: 'Piesti pavirsius',
    block_babylon_input_scene_background_colour: 'Scenos fono spalva',
    block_babylon_input_size: 'Dydis',
    block_babylon_input_height: 'Aukstis',
    block_babylon_input_subdivisions: 'Sudalinimas',
    block_babylon_input_major_unit_frequency: 'Didziojo tinklelio tankumas',
    block_babylon_input_minor_unit_visibility: 'Mazojo tinklelio matomumas',
    block_babylon_input_back_face_culling: 'Galinio veido persvieciamumas',
    block_babylon_input_main_colour: 'Pagrindine spalva',
    block_babylon_input_secondary_colour: 'Antraeile spalva',
    block_babylon_input_grid_ratio: 'Tinklelio santykis',
    block_babylon_draw_curve_description: 'Piesti spalvota nurodyto storio kreive.',
    block_babylon_draw_curves_description: 'Piesti spalvotas nurodyto storio kreives.',
    block_babylon_draw_grid_description: 'Piesti zemes tinkleli kuris padeda orientuotis 3D erdveje.',
    block_babylon_draw_line_description: 'Piesti spalvota nurodyto storio linija.',
    block_babylon_draw_lines_description: 'Piesti spalvotas nurodyto storio linijas.',
    block_babylon_draw_point_description: 'Piesti spalvota nurodyto dydzio taska.',
    block_babylon_draw_points_description: 'Piesti spalvotus nurodyto dydzio taskus.',
    block_babylon_draw_polyline_description: 'Piesti spalvota nurodyto storio polilinija.',
    block_babylon_draw_surface_description: 'Piesti spalvota pavirsiu.',
    block_babylon_draw_surfaces_description: 'Piesti spalvotus pavirsius.',
    block_babylon_scene_background_colour_description: 'Pakeisti scenos fono spalva.',
    block_base_geometry_input_line_start_point: 'Linija su pradzios tasku',
    block_base_geometry_input_line_end_point: 'Galiniu tasku',
    block_base_geometry_line_description: 'Sukuria linijos objekta tarp dvieju tasku.',
    block_base_geometry_line_end_point: 'Galinis linijos taskas',
    block_base_geometry_line_end_point_description: 'Gauti galini linijos taska.',
    block_base_geometry_line_start_point: 'Pradinis linijos taskas',
    block_base_geometry_line_start_point_description: 'Gauti pradini linijos taska.',
    block_base_geometry_line_length: 'Linijos ilgis',
    block_base_geometry_line_length_description: 'Matuoti linijos ilgi.',
    block_base_geometry_line_convert_to_nurbs_curve: 'Kreive is linijos',
    block_base_geometry_line_convert_to_nurbs_curve_description: 'Konvertuoja linija i kreive.',
    block_base_geometry_polyline_convert_to_nurbs_curve: 'Kreive is polilinijos',
    block_base_geometry_polyline_convert_to_nurbs_curve_description: 'Konvertuoja polilinija i kreive.',
    block_base_geometry_line_reverse: 'Apgrezti linija',
    block_base_geometry_line_reverse_description: 'Apgrezia linijos krypti. Pradinis taskas tampa galiniu, o galinis pirminiu.',
    block_base_geometry_point_description: 'Sukuria taska erdveje.',
    block_base_geometry_point_distance: 'Atstumas tarp pirmo tasko',
    block_base_geometry_point_distance_second_point: 'Antro tasko',
    block_base_geometry_point_distance_description: 'Matuoja atstuma tarp dvieju tasku.',
    block_base_geometry_point_x: 'X tasko koordinate',
    block_base_geometry_point_x_description: 'Gauna tasko x koordinate.',
    block_base_geometry_point_y: 'Y tasko koordinate',
    block_base_geometry_point_y_description: 'Gauna tasko y koordinate.',
    block_base_geometry_point_z: 'Z tasko koordinate',
    block_base_geometry_point_z_description: 'Gauna tasko z koordinate.',
    block_base_geometry_polyline: 'Polilinija is tasku',
    block_base_geometry_polyline_description: 'Sukuria polilinija tarp tasku.',
    block_base_geometry_polyline_length: 'Polilinijos ilgis',
    block_base_geometry_polyline_length_description: 'Matuoti polilinijos ilgi.',
    block_base_geometry_polyline_points: 'Polilinijos taskai',
    block_base_geometry_polyline_points_description: 'Gauna polilinijos taskus.',
    block_base_geometry_polyline_points_count: 'Tasku skaicius polilinijoje',
    block_base_geometry_polyline_points_count_description: 'Suskaiciuoja tasku skaiciu polilinijoje.',
    block_base_geometry_polyline_reverse: 'Apgrezti polilinija',
    block_base_geometry_polyline_reverse_description: 'Apgrezia polilinijos krypti. Pradinis taskas tampa galiniu, o galinis pirminiu.',
    block_base_geometry_shape_circle_center: 'Apskritimas su centru',
    block_base_geometry_shape_rectangle_center: 'Kvadratas su centru',
    block_base_geometry_shape_x_axis: 'X asis',
    block_base_geometry_shape_y_axis: 'Y asis',
    block_verb_core_interval_input_min: 'Intervalas su minimumu',
    block_verb_core_interval_input_max: 'Maksimumu',
    block_verb_core_interval_description: 'Sukuria intervala tarp mininumo ir maksimumo. Minimumo verte privalo buti mazesne uz maksimumo.',
    block_verb_core_interval_get_max: 'Maksimumo verte intervale',
    block_verb_core_interval_get_max_description: 'Gauna intervalo maksimumo verte.',
    block_verb_core_interval_get_min: 'Minimumo verte intervale',
    block_verb_core_interval_get_min_description: 'Gauna intervalo minimumo verte.',
    block_babylon_input_transformation_scale_center: 'Centras',
    block_babylon_input_transformation_scale_uniform: 'Didinti kartais',
    block_babylon_transformation_scale_uniform_description: 'Didinti arba mazinti objekta kartais',
    block_babylon_input_transformation_scale_xyz: 'Didinimas XYZ vektoriumi',
    block_babylon_transformation_scale_xyz_description: 'Sukuria didinomo transformacija, kuri objekta gali didinti skirtingais dydziais xyz kryptimis.',
    block_babylon_input_transformation_scale_center_uniform: 'Didinti kartais',
    block_babylon_transformation_scale_center_uniform_description: 'Sukuria didinimo transformacija, kuri objekta plecia aplink taska erdveje.',
    block_babylon_input_transformation_scale_center_xyz: 'Didinimas XYZ vektoriumi',
    block_babylon_transformation_scale_center_xyz_description: 'Sukuria didinomo transformacija, kuri objekta gali didinti skirtingais dydziais xyz kryptimis aplink taska.',
    block_babylon_input_transformation_translation_xyz: 'Perkelti XYZ kryptimi',
    block_babylon_transformation_translation_xyz_description: 'Perkelia objekta XYZ kryptimi i nauja lokacija.',
    block_babylon_input_transformation_rotation_center_x: 'Sukti aplink X asi kampu',
    block_babylon_transformation_rotation_center_x_description: 'Suka objekta aplink X asi ir duota taska.',
    block_babylon_input_transformation_rotation_center_y: 'Sukti aplink Y asi kampu',
    block_babylon_transformation_rotation_center_y_description: 'Suka objekta aplink Y asi ir duota taska.',
    block_babylon_input_transformation_rotation_center_z: 'Sukti aplink Z asi kampu',
    block_babylon_transformation_rotation_center_z_description: 'Suka objekta aplink Z asi ir duota taska.',
    block_babylon_input_transformation_rotation_center_angle: 'Sukti kampu',
    block_babylon_input_transformation_rotation_center_axis: 'Aplink asi',
    block_babylon_transformation_rotation_center_axis_description: 'Suka objekta aplink pasirinkta asi ir duota taska.',
    block_verb_geom_curve_transform_curve: 'Transformuoti kreive',
    block_verb_geom_curve_transform_transformation: 'Transformacija',
    block_verb_geom_curve_transform_description: 'Transformuoja kreive su duota transformacija.',
    block_verb_geom_surface_transform_surface: 'Transformuoti pavirsiu',
    block_verb_geom_surface_transform_transformation: 'Transformacija',
    block_verb_geom_surface_transform_description: 'Transformuoja pavirsiu su duota transformacija.',
    block_base_geom_point_transform_point: 'Transformuoti taska',
    block_base_geom_point_transform_transformation: 'Transformacija',
    block_base_geom_point_transform_description: 'Transformuoti taska su duota transformacija.',
    block_base_geom_points_transform_points: 'Transformuoti taskus',
    block_base_geom_points_transform_transformation: 'Transformacija',
    block_base_geom_points_transform_description: 'Transformuoti taskus su duota transformacija.',
    block_base_geom_line_transform_line: 'Transformuoti linija',
    block_base_geom_line_transform_transformation: 'Transformacija',
    block_base_geom_line_transform_description: 'Transformuoti linija su duota transformacija.',
    block_base_geom_polyline_transform_polyline: 'Transformuoti polilinija',
    block_base_geom_polyline_transform_transformation: 'Transformacija',
    block_base_geom_polyline_transform_description: 'Transformuoti polilinija su duota transformacija.',
    block_verb_core_uv_input_u: 'UV su U',
    block_verb_core_uv_input_v: 'V',
    block_verb_core_uv_description: 'Sukuria UV parametra.',
    block_verb_core_uv_get_u: 'Guati U dali is UV',
    block_verb_core_uv_get_v: 'Gauti V dali is UV',
    block_verb_core_uv_get_u_description: 'Gauna U parametra is UV.',
    block_verb_core_uv_get_v_description: 'Gauna V parametra is UV.',
    block_verb_core_vector_description: 'Sukuria vektoriu is XYZ koordinaciu.',
    block_verb_core_vector_add_input_first: 'Sudeti vektoriu',
    block_verb_core_vector_add_input_second: 'Su vektoriumi',
    block_verb_core_vector_add_description: 'Sudeda du vektorius.',
    block_verb_core_vector_add_all_input_vectors: 'Sudeti visus vektorius',
    block_verb_core_vector_add_all_description: 'Sudeda visus vektorius.',
    block_verb_core_vector_all_input: 'Visi binarai teigiami',
    block_verb_core_vector_all_description: 'Patikrina ar visi binarai kolekcijoje yra teigiami',
};
