import { ResourcesInterface } from './resources.interface';

export const resourcesLt: ResourcesInterface = {
    bit_by_bit: 'BitasPoBito',
    app_menu_run_code: 'Paleisti Kodą',
    app_menu_swap_canvas: 'Sukeisti Aplinkas',
    app_menu_support_us_on_patreon: 'Paremkite mus Patreone',
    app_menu_clean_canvas: 'Išvalyti Drobę',
    app_menu_more: 'Daugiau',
    app_menu_more_about: 'Apie',
    app_menu_more_settings: 'Pasirinktys',
    app_menu_more_examples: 'Pavyzdžiai',
    app_menu_more_sponsors: 'Remėjai',
    app_menu_more_community: 'Bendruomenė',
    app_menu_more_export: 'Išsaugoti',
    app_menu_more_import: 'Atidaryti',
    block_toolbox_category_scene: 'Scena',
    block_toolbox_category_core_types: 'Tipai',
    block_toolbox_category_core_transforms: 'Transformacijos',
    block_toolbox_category_core_vector: 'Vektoriai',
    block_toolbox_category_geom_point: 'Taškas',
    block_toolbox_category_geom_line: 'Linija',
    block_toolbox_category_geom_polyline: 'Polilinija',
    block_toolbox_category_geom_curve: 'Kreivė',
    block_toolbox_category_geom_surface: 'Paviršius',
    block_toolbox_category_loop: 'Ciklai',
    block_toolbox_category_logic: 'Logika',
    block_toolbox_category_math: 'Matematika',
    block_toolbox_category_lists: 'Rinkiniai',
    block_toolbox_category_colour: 'Spalvos',
    block_toolbox_category_text: 'Tekstas',
    block_toolbox_category_variables: 'Kintamieji',
    block_toolbox_category_functions: 'Funkcijos',
    block_point: 'Taškas',
    block_coordinate_x: 'Koordinatė X',
    block_coordinate_y: 'Koordinatė Y',
    block_coordinate_z: 'Koordinatė Z',
    block_coordinate_short_x: 'X',
    block_coordinate_short_y: 'Y',
    block_coordinate_short_z: 'Z',
    block_points: 'Taškai',
    block_curve: 'Kreivė',
    block_curves: 'Kreivės',
    block_colour: 'Spalva',
    block_opacity: 'Matomumas',
    block_width: 'Storis',
    block_line: 'Linija',
    block_lines: 'Linijos',
    block_polyline: 'Polilinija',
    block_size: 'Dydis',
    block_surface: 'Paviršius',
    block_surfaces: 'Paviršiai',
    block_circle: 'Apskritimas',
    block_center: 'Centras',
    block_radius: 'Spindulys',
    block_min: 'Minimumas',
    block_max: 'Maksimumas',
    block_interval: 'Intervalas',
    block_integer: 'Sveikas skaičius',
    block_scale: 'Didinimas',
    block_vector: 'Vektorius',
    block_vectors: 'Vektoriai',
    block_angle: 'Kampas',
    block_axis: 'Ašis',
    block_u: 'U',
    block_v: 'V',
    block_uv: 'UV',
    block_use_v: 'Naudoti V',
    block_distance: 'Atstumas',
    block_scalar: 'Skaičius',
    block_fraction: 'Frakcija',
    block_transform: 'Transformacija',
    block_step: 'Žingsnis',
    block_reference: 'Etalonas',
    block_knots: 'Saitai',
    block_knots_u: 'Saitai U',
    block_knots_v: 'Saitai V',
    block_weights: 'Svoriai',
    block_degree: 'Laipsnis',
    block_degree_u: 'Laipsnis U',
    block_degree_v: 'Laipsnis V',
    block_length: 'Ilgis',
    block_num_derivatives: 'Išvestinių skaičius',
    block_parameter: 'Parametras',
    block_parameter_u: 'Parametras U',
    block_parameter_v: 'Parametras V',
    block_subdivision: 'Sudalinimai',
    block_tolerance: 'Tolerancija',
    block_validation_required: 'privalo būti įvesta',
    block_validation_higher_or_equal: 'privalo būti daugiau arba lygu',
    block_validation_lower_or_equal: 'privalo būti maziau arba lygu',
    block_validation_of_length: 'privalomas elementų skaičius yra',
    block_validation_range: 'privalo būti tarp',
    block_validation_smaller_than: 'privalu būti mažesnis už',
    block_validation_smaller_or_equal_than: 'privalo būti mažesnis arba lygus',
    block_validation_larger_than: 'privalo būti didesnis už',
    block_validation_larger_or_equal_than: 'privalo būti didesnis arba lygus',
    block_babylon_input_curve: 'Piešti kreivę',
    block_babylon_input_curves: 'Piešti kreives',
    block_babylon_input_colour: 'Spalva',
    block_babylon_input_opacity: 'Matomumas',
    block_babylon_input_width: 'Storis',
    block_babylon_input_draw_grid: 'Piešti tinklelį kurio plotis',
    block_babylon_input_draw_line: 'Piešti liniją',
    block_babylon_input_draw_lines: 'Piešti linijas',
    block_babylon_input_draw_polyline: 'Piešti poliliniją',
    block_babylon_input_draw_point: 'Piešti tašką',
    block_babylon_input_draw_points: 'Piešti taškus',
    block_babylon_input_draw_surface: 'Piešti paviršių',
    block_babylon_input_draw_surfaces: 'Piešti paviršius',
    block_babylon_input_scene_background_colour: 'Scenos fono spalva',
    block_babylon_input_size: 'Dydis',
    block_babylon_input_height: 'Aukštis',
    block_babylon_input_subdivisions: 'Sudalinimas',
    block_babylon_input_major_unit_frequency: 'Didžiojo tinklelio tankumas',
    block_babylon_input_minor_unit_visibility: 'Mažojo tinklelio matomumas',
    block_babylon_input_back_face_culling: 'Galinio veido peršviečiamumas',
    block_babylon_input_main_colour: 'Pagrindinė spalva',
    block_babylon_input_secondary_colour: 'Antraeilė spalva',
    block_babylon_input_grid_ratio: 'Tinklelio santykis',
    block_babylon_draw_curve_description: 'Piešti spalvotą nurodyto storio kreivę.',
    block_babylon_draw_curves_description: 'Piešti spalvotas nurodyto storio kreives.',
    block_babylon_draw_grid_description: 'Piešti žemės tinklelį, kuris padeda orientuotis 3D erdvėje.',
    block_babylon_draw_line_description: 'Piešti spalvotą nurodyto storio liniją.',
    block_babylon_draw_lines_description: 'Piešti spalvotas nurodyto storio linijas.',
    block_babylon_draw_point_description: 'Piešti spalvotą nurodyto dydžio tašką.',
    block_babylon_draw_points_description: 'Piešti spalvotus nurodyto dydžio taškus.',
    block_babylon_draw_polyline_description: 'Piešti spalvotą nurodyto storio poliliniją.',
    block_babylon_draw_surface_description: 'Piešti spalvotą paviršių.',
    block_babylon_draw_surfaces_description: 'Piešti spalvotus paviršius.',
    block_babylon_scene_background_colour_description: 'Pakeisti scenos fono spalvą.',
    block_base_geometry_input_line_start_point: 'Linija su pradžios tašku',
    block_base_geometry_input_line_end_point: 'Galiniu tašku',
    block_base_geometry_line_description: 'Sukuria liniją tarp dviejų taškų.',
    block_base_geometry_line_end_point: 'Galinis linijos taškas',
    block_base_geometry_line_end_point_description: 'Gauti galinį linijos tašką.',
    block_base_geometry_line_start_point: 'Pradinis linijos taškas',
    block_base_geometry_line_start_point_description: 'Gauti pradinį linijos tašką.',
    block_base_geometry_line_length: 'Linijos ilgis',
    block_base_geometry_line_length_description: 'Matuoti linijos ilgį.',
    block_base_geometry_line_convert_to_nurbs_curve: 'Kreivė iš linijos',
    block_base_geometry_line_convert_to_nurbs_curve_description: 'Konvertuoja liniją į kreivę.',
    block_base_geometry_polyline_convert_to_nurbs_curve: 'Kreivė iš polilinijos',
    block_base_geometry_polyline_convert_to_nurbs_curve_description: 'Konvertuoja poliliniją į kreivę.',
    block_base_geometry_line_reverse: 'Apgręžti liniją',
    block_base_geometry_line_reverse_description: 'Apgręžia linijos kryptį. Pradinis taškas tampa galiniu, o galinis pradiniu.',
    block_base_geometry_point_description: 'Sukuria tašką erdvėje.',
    block_base_geometry_point_distance: 'Atstumas tarp pirmo taško',
    block_base_geometry_point_distance_second_point: 'Antro taško',
    block_base_geometry_point_distance_description: 'Matuoja atstumą tarp dviejų taškų.',
    block_base_geometry_point_x: 'X taško koordinatė',
    block_base_geometry_point_x_description: 'Gauna taško x koordinatę.',
    block_base_geometry_point_y: 'Y taško koordinatė',
    block_base_geometry_point_y_description: 'Gauna taško y koordinatę.',
    block_base_geometry_point_z: 'Z taško koordinatė',
    block_base_geometry_point_z_description: 'Gauna taško z koordinatę.',
    block_base_geometry_polyline: 'Polilinija iš taškų',
    block_base_geometry_polyline_description: 'Sukuria poliliniją per taškus.',
    block_base_geometry_polyline_length: 'Polilinijos ilgis',
    block_base_geometry_polyline_length_description: 'Matuoti polilinijos ilgį.',
    block_base_geometry_polyline_points: 'Polilinijos taškai',
    block_base_geometry_polyline_points_description: 'Gauna polilinijos taškus.',
    block_base_geometry_polyline_points_count: 'Taškų skaičius polilinijoje',
    block_base_geometry_polyline_points_count_description: 'Suskaičiuoja taškų skaičių polilinijoje.',
    block_base_geometry_polyline_reverse: 'Apgręžti poliliniją',
    block_base_geometry_polyline_reverse_description: 'Apgręžia polilinijos kryptį. Pradinis taškas tampa galiniu, o galinis pradiniu.',
    block_base_geometry_shape_circle_center: 'Apskritimas su centru',
    block_base_geometry_shape_rectangle_center: 'Kvadratas su centru',
    block_base_geometry_shape_x_axis: 'X ašis',
    block_base_geometry_shape_y_axis: 'Y ašis',
    block_verb_core_interval_input_min: 'Intervalas su minimumu',
    block_verb_core_interval_input_max: 'Maksimumu',
    block_verb_core_interval_description: 'Sukuria intervalą tarp mininumo ir maksimumo. Minimumo vertė privalo būti mažesnė už maksimumo.',
    block_verb_core_interval_get_max: 'Maksimumo vertė intervale',
    block_verb_core_interval_get_max_description: 'Gauna intervalo maksimumo vertę.',
    block_verb_core_interval_get_min: 'Minimumo vertė intervale',
    block_verb_core_interval_get_min_description: 'Gauna intervalo minimumo vertę.',
    block_babylon_input_transformation_scale_center: 'Centras',
    block_babylon_input_transformation_scale_uniform: 'Didinti kartais',
    block_babylon_transformation_scale_uniform_description: 'Didinti arba mažinti objektą kartais',
    block_babylon_input_transformation_scale_xyz: 'Didinimas XYZ vektoriumi',
    block_babylon_transformation_scale_xyz_description: 'Sukuria didinomo transformaciją, kuri objektą gali didinti skirtingais dydžiais xyz kryptimis.',
    block_babylon_input_transformation_scale_center_uniform: 'Didinti kartais',
    block_babylon_transformation_scale_center_uniform_description: 'Sukuria didinimo transformacija, kuri objekta plecia aplink taska erdveje.',
    block_babylon_input_transformation_scale_center_xyz: 'Didinimas XYZ vektoriumi',
    block_babylon_transformation_scale_center_xyz_description: 'Sukuria didinomo transformaciją, kuri objektą gali didinti skirtingais dydžiais xyz kryptimis aplink tašką.',
    block_babylon_input_transformation_translation_xyz: 'Perkelti XYZ kryptimi',
    block_babylon_transformation_translation_xyz_description: 'Perkelia objektą XYZ kryptimi į naują lokaciją.',
    block_babylon_input_transformation_rotation_center_x: 'Sukti aplink X ašį kampu',
    block_babylon_transformation_rotation_center_x_description: 'Suka objektą aplink X ašį ir duotą tašką.',
    block_babylon_input_transformation_rotation_center_y: 'Sukti aplink Y ašį kampu',
    block_babylon_transformation_rotation_center_y_description: 'Suka objektą aplink Y ašį ir duotą tašką.',
    block_babylon_input_transformation_rotation_center_z: 'Sukti aplink Z ašį kampu',
    block_babylon_transformation_rotation_center_z_description: 'Suka objektą aplink Z ašį ir duotą tašką.',
    block_babylon_input_transformation_rotation_center_angle: 'Sukti kampu',
    block_babylon_input_transformation_rotation_center_axis: 'Aplink ašį',
    block_babylon_transformation_rotation_center_axis_description: 'Suka objektą aplink pasirinktą ašį ir duotą tašką.',
    block_verb_geom_curve_transform_curve: 'Transformuoti kreivę',
    block_verb_geom_curve_transform_transformation: 'Transformacija',
    block_verb_geom_curve_transform_description: 'Transformuoja kreivę su duota transformacija.',
    block_verb_geom_surface_transform_surface: 'Transformuoti paviršių',
    block_verb_geom_surface_transform_transformation: 'Transformacija',
    block_verb_geom_surface_transform_description: 'Transformuoja paviršių su duota transformacija.',
    block_base_geom_point_transform_point: 'Transformuoti tašką',
    block_base_geom_point_transform_transformation: 'Transformacija',
    block_base_geom_point_transform_description: 'Transformuoti tašką su duota transformacija.',
    block_base_geom_points_transform_points: 'Transformuoti taškus',
    block_base_geom_points_transform_transformation: 'Transformacija',
    block_base_geom_points_transform_description: 'Transformuoti taškus su duota transformacija.',
    block_base_geom_line_transform_line: 'Transformuoti liniją',
    block_base_geom_line_transform_transformation: 'Transformacija',
    block_base_geom_line_transform_description: 'Transformuoti liniją su duota transformacija.',
    block_base_geom_polyline_transform_polyline: 'Transformuoti poliliniją',
    block_base_geom_polyline_transform_transformation: 'Transformacija',
    block_base_geom_polyline_transform_description: 'Transformuoti poliliniją su duota transformacija.',
    block_verb_core_uv_input_u: 'UV su U',
    block_verb_core_uv_input_v: 'V',
    block_verb_core_uv_description: 'Sukuria UV parametrą.',
    block_verb_core_uv_get_u: 'Guati U dalį iš UV',
    block_verb_core_uv_get_v: 'Gauti V dalį iš UV',
    block_verb_core_uv_get_u_description: 'Gauna U parametrą iš UV.',
    block_verb_core_uv_get_v_description: 'Gauna V parametrą iš UV.',
    block_verb_core_vector_description: 'Sukuria vektorių iš XYZ koordinačių.',
    block_verb_core_vector_add_input_first: 'Sudėti vektorių',
    block_verb_core_vector_add_input_second: 'Su vektoriumi',
    block_verb_core_vector_add_description: 'Sudeda du vektorius.',
    block_verb_core_vector_sub_input_first: 'Atimti vektorių',
    block_verb_core_vector_sub_input_second: 'Iš vektoriaus',
    block_verb_core_vector_sub_description: 'Dviejų vektorių atimtis.',
    block_verb_core_vector_add_all_input_vectors: 'Sudėti visus vektorius',
    block_verb_core_vector_add_all_description: 'Sudeda visus vektorius.',
    block_verb_core_vector_all_input: 'Visi binarai teigiami',
    block_verb_core_vector_all_description: 'Patikrina ar visi binarai kolekcijoje yra teigiami',
    block_verb_core_vector_angle_between_input_first: 'Kampas tarp pirmo vektoriaus',
    block_verb_core_vector_angle_between_input_second: 'Antro vektoriaus',
    block_verb_core_vector_angle_between_description: 'Matuoja kampą tarp dviejų vektorių.',
    block_verb_core_vector_angle_between_normalized_2d_input_first: 'Normalizuotas 2d kampas tarp pirmo vektoriaus',
    block_verb_core_vector_angle_between_normalized_2d_input_second: 'Antro vektoriaus',
    block_verb_core_vector_angle_between_normalized_2d_description: 'Matuoja normalizuotą 2d kampą tarp dviejų vektorių.',
    block_verb_core_vector_cross_input_first: 'Kryžminti vektorių',
    block_verb_core_vector_cross_input_second: 'Su vektoriumi',
    block_verb_core_vector_cross_description: 'Sukryžmina du vektorius.',
    block_verb_core_vector_distance_input_first: 'Atstumas tarp taško',
    block_verb_core_vector_distance_input_second: 'Ir taško',
    block_verb_core_vector_distance_description: 'Matuoja atstumą tarp dviejų taškų.',
    block_verb_core_vector_distance_squared_input_first: 'Kvadratinis atstumas tarp taško',
    block_verb_core_vector_distance_squared_input_second: 'Ir taško',
    block_verb_core_vector_distance_squared_description: 'Matuoja kvadratinį Euklido atstumą tarp dviejų taškų.',
    block_verb_core_vector_div_input_vector: 'Dalinti vektorių',
    block_verb_core_vector_div_input_scalar: 'Iš skaičiaus',
    block_verb_core_vector_div_description: 'Dalina vektorių iš skaičiaus.',
    block_verb_core_vector_domain_input_vector: 'Vektoriaus domenas',
    block_verb_core_vector_domain_description: 'Matuoja vektoriaus domeną.',
    block_verb_core_vector_dot_input_vector: 'Taškinis produktas tarp vektoriaus',
    block_verb_core_vector_dot_input_scalar: 'Ir vektoriaus',
    block_verb_core_vector_dot_description: 'Matuoja taškinį produktą tarp dviejų vektorių.',
    block_verb_core_vector_finite_input_vector: 'Tikrinti begalybes vektoriuje',
    block_verb_core_vector_finite_description: 'Tikrina ar vektoriuje yra begalinių elementų ir gražina binarine būlių kolekciją kiekvienam elementui.',
    block_verb_core_vector_is_zero_input_vector: 'Ar nulinis vektorius',
    block_verb_core_vector_is_zero_description: 'Patikrina ar vektorius yra nulinis.',
    block_verb_core_vector_lerp_fraction: 'Taškas frakcijoje',
    block_verb_core_vector_lerp_input_first: 'Tarp vektoriaus',
    block_verb_core_vector_lerp_input_second: 'Ir vektoriaus',
    block_verb_core_vector_lerp_description: 'Gražina tašką tarp dviejų vektorių davus frakcinį parametrą.',
    block_verb_core_vector_max_input_vector: 'Didžiausias skaičius vektoriuje',
    block_verb_core_vector_max_description: 'Gražina didžiausią skaičių vektoriuje.',
    block_verb_core_vector_min_input_vector: 'Mažiausias skaičius vektoriuje',
    block_verb_core_vector_min_description: 'Gražina mažiausią skaičių vektoriuje.',
    block_verb_core_vector_mul_input_vector: 'Dauginti vektorių',
    block_verb_core_vector_mul_input_scalar: 'Iš skaičiaus',
    block_verb_core_vector_mul_description: 'Daugina vektorių iš skaičiaus.',
    block_verb_core_vector_negate_input_vector: 'Negatyvus vektorius',
    block_verb_core_vector_negate_description: 'Gražina negatyvų vektorių.',
    block_verb_core_vector_norm_input_vector: 'Vektoriaus norma',
    block_verb_core_vector_norm_description: 'Gražina vektoriaus ilgį nuo nulinių xyz koordinačių.',
    block_verb_core_vector_norm_squared_input_vector: 'Vektoriaus normos kvadratas',
    block_verb_core_vector_norm_squared_description: 'Gražina normos kvadaratą vektoriui',
    block_verb_core_vector_normalized_input_vector: 'Normalizuotas vektorius',
    block_verb_core_vector_normalized_description: 'Gražina normalizuotą vektorių, kurio ilgis lygus 1, o kryptis nekinta.',
    block_verb_core_vector_on_ray_input_vector: 'Kryptimi vektoriaus',
    block_verb_core_vector_on_ray_input_point: 'Perkelti tašką',
    block_verb_core_vector_on_ray_input_distance: 'Atstumu',
    block_verb_core_vector_on_ray_description: 'Perkelia tašką duotu atstumu į kitą vietą vektoriaus kryptimi.',
    block_verb_core_vector_positive_angle_between_input_first: 'Teigiamas kampas tarp vektoriaus',
    block_verb_core_vector_positive_angle_between_input_second: 'Antro vektoriaus',
    block_verb_core_vector_positive_angle_between_input_reference: 'Ir etaloninio vektoriaus',
    block_verb_core_vector_positive_angle_between_description: 'Gražina teigiamą kampą tarp dviejų vektorių naudojant etaloninė kryptį.',
    block_verb_core_vector_signed_angle_between_input_first: 'Ženklintas kampas tarp vektoriaus',
    block_verb_core_vector_signed_angle_between_input_second: 'Antro vektoriaus',
    block_verb_core_vector_signed_angle_between_input_reference: 'Ir etaloninio vektoriaus',
    block_verb_core_vector_signed_angle_between_description: 'Gražina ženklintą +/- kampą tarp dviejų vektorių naudojant etaloninę kryptį.',
    block_verb_core_vector_range_input_max: 'Diapozonas iki maksimalios ribos',
    block_verb_core_vector_range_description: 'Sukuria skaičių rinkinį nuo 0 iki maksimalios ribos.',
    block_verb_core_vector_span_input_min: 'Skaičių diapozonas tarp minimumo',
    block_verb_core_vector_span_input_max: 'Ir maksimumo',
    block_verb_core_vector_span_input_step: 'Žingsniu',
    block_verb_core_vector_span_description: 'Sukuria skaičių rinkinį tarp minimumo ir maksimumo nurodytu žingsniu.',
    block_verb_core_vector_sum_input_vector: 'Susumuoti visus vektoriaus elementus',
    block_verb_core_vector_sum_description: 'Susumuoja visus vektoriaus elementus.',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_knots: 'Kreivė su saitais',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_control_points: 'Kontroliniais taškais',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_weights: 'Svoriais',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_degree: 'Ir laipsniu',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_description: 'Sukuria duoto laipsnio kreivę su saitais, kontroliniais taškais ir svoriais.',
    block_verb_geometry_nurbs_curve_by_points_inputs_points: 'Kreivė kuri eina per taškus',
    block_verb_geometry_nurbs_curve_by_points_inputs_degree: 'Laipsnis',
    block_verb_geometry_nurbs_curve_by_points_description: 'Sukurti kreivę, kuri eina per duotus taškus ir laipsnį.',
    block_verb_geometry_nurbs_curve_clone_input_curve: 'Klonuoti kreivę',
    block_verb_geometry_nurbs_curve_clone_description: 'Klonuoja kreivę.',
    block_verb_geometry_nurbs_curve_closest_param_input_curve: 'Arčiausias parametras ant kreivės',
    block_verb_geometry_nurbs_curve_closest_param_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_curve_closest_param_description: 'Randa arčiausią kreivės parametrą nuo duoto taško.',
    block_verb_geometry_nurbs_curve_closest_params_input_curve: 'Arčiausi parametrai ant kreivės',
    block_verb_geometry_nurbs_curve_closest_params_input_points: 'Nuo taškų',
    block_verb_geometry_nurbs_curve_closest_params_description: 'Randa arčiausius kreivės parametrus nuo duotų taškų kolekcijos.',
    block_verb_geometry_nurbs_curve_closest_point_input_curve: 'Arčiausias taškas ant kreivės',
    block_verb_geometry_nurbs_curve_closest_point_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_curve_closest_point_description: 'Randa arčiausią tašką ant kreivės nuo duoto taško.',
    block_verb_geometry_nurbs_curve_closest_points_input_curve: 'Arčiausi taškai ant kreivės',
    block_verb_geometry_nurbs_curve_closest_points_input_points: 'Nuo taškų',
    block_verb_geometry_nurbs_curve_closest_points_description: 'Randa arčiausius kreivės taškus nuo duotų taškų kolekcijos.',
    block_verb_geometry_nurbs_curve_degree_input_curve: 'Kreivės laipsnis',
    block_verb_geometry_nurbs_curve_degree_description: 'Gražina kreivės laipsnį.',
    block_verb_geometry_nurbs_curve_derivatives_input_curve: 'Kreivės išvestinės',
    block_verb_geometry_nurbs_curve_derivatives_input_parameter: 'Ant parametro',
    block_verb_geometry_nurbs_curve_derivatives_input_num_derivatives: 'Išvestinių skaičius',
    block_verb_geometry_nurbs_curve_derivatives_description: 'Gauna nurodytą skaičių kreivės išvestinių ant parametro.',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_params_input_curve: 'Sudalinti kreivę į parametrus',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_params_input_subdivison_number: 'Segmentų skaičius',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_params_description: 'Sudalina kreivę lygiu arkos ilgiu į duotą segmentų skaicių ir gražina kreivės parametrų vertes.',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_points_input_curve: 'Sudalinti kreivę į taškus',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_points_input_subdivison_number: 'Segmentų skaičius',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_points_description: 'Sudalina kreivę lygiu arkos ilgiu į duotą segmentų skaičių ir gražina taškus ant kreivės.',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_params_input_curve: 'Sudalinti kreivę į parametrus',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_params_input_arc_length: 'Arkos ilgiu',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_params_description: 'Sudalina kreivę į parametrus arkos ilgiu.',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_points_input_curve: 'Sudalinti kreivę į taškus',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_points_input_arc_length: 'Arkos ilgiu',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_points_description: 'Sudalina kreivę į taškus arkos ilgiu.',
    block_verb_geometry_nurbs_curve_domain_input_curve: 'Kreivės domenas',
    block_verb_geometry_nurbs_curve_domain_description: 'Gražina kreivės domeną.',
    block_verb_geometry_nurbs_curve_knots_input_curve: 'Kreivės saitai',
    block_verb_geometry_nurbs_curve_knots_description: 'Gražina kreivės saitus.',
    block_verb_geometry_nurbs_curve_length_input_curve: 'Kreivės ilgis',
    block_verb_geometry_nurbs_curve_length_description: 'Gražina kreivės ilgį.',
    block_verb_geometry_nurbs_curve_length_at_param_input_curve: 'Kreivės ilgis',
    block_verb_geometry_nurbs_curve_length_at_param_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_length_at_param_description: 'Matuoja kreivės ilgį ant parametro.',
    block_verb_geometry_nurbs_curve_param_at_length_input_curve: 'Parametras ant kreivės',
    block_verb_geometry_nurbs_curve_param_at_length_input_length: 'Atstume',
    block_verb_geometry_nurbs_curve_param_at_length_input_tolerance: 'Su tolerancija',
    block_verb_geometry_nurbs_curve_param_at_length_description: 'Gražina kreivės parametrą duotu atustumu nuo kreivės pradžios taško.',
    block_verb_geometry_nurbs_curve_reverse_input_curve: 'Apgręžti kreivę',
    block_verb_geometry_nurbs_curve_reverse_description: 'Apgręžia kreivę.',
    block_verb_geometry_nurbs_curve_split_input_curve: 'Perkirpti kreivę',
    block_verb_geometry_nurbs_curve_split_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_split_description: 'Perkerpa kreivę į dvi dalis ties parametru ir gražina dvi kreives.',
    block_verb_geometry_nurbs_curve_tangent_input_curve: 'Kreivės tangentas',
    block_verb_geometry_nurbs_curve_tangent_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_tangent_description: 'Gražina tangentinį kreivės vektorių ties duotu parametru.',
    block_verb_geometry_nurbs_curve_tessellate_input_curve: 'Išskaidyti kreivę',
    block_verb_geometry_nurbs_curve_tessellate_input_tolerance: 'Su tolerancija',
    block_verb_geometry_nurbs_curve_tessellate_description: 'Išskaido kreivę į taškus duota tolerancija.',
    block_verb_geometry_nurbs_curve_weights_input_curve: 'Kreivės svoriai',
    block_verb_geometry_nurbs_curve_weights_description: 'Gražina kreivės svorius',
    block_verb_geometry_nurbs_surface_boundaries_input_surface: 'Kraštinės kreivės paviršiuje',
    block_verb_geometry_nurbs_surface_boundaries_description: 'Gražina 4 paviršiaus kraštus kreivių pavidalu.',
    block_verb_geometry_nurbs_surface_by_corners_input_point1: 'Paviršius su pirmo kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_input_point2: 'Antro kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_input_point3: 'Trečio kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_input_point4: 'Ketvirto kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_description: 'Sukuria paviršių ių keturių kampų.',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_knots_u: 'Paviršius su u saitais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_knots_v: 'V saitais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_points: 'Kontroliniais taškais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_weights: 'svoriais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_degree_u: 'U laipsniu',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_degree_v: 'V laipsniu',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_description: 'Sukuria paviršių iš uv saitų, taškų, svorių ir uv laipsniais.',
    blocK_verb_geometry_nurbs_surface_by_lofting_curves_input_curves: 'Paviršius vedamas per kreives',
    blocK_verb_geometry_nurbs_surface_by_lofting_curves_input_degree_v: 'V laipsnio',
    blocK_verb_geometry_nurbs_surface_by_lofting_curves_description: 'Paviršius sudaromas per kreivių rinkinį.',
    block_verb_geometry_nurbs_surface_clone_input_surface: 'Klonuoti paviršių',
    block_verb_geometry_nurbs_surface_clone_description: 'Klonuoja paviršių.',
    block_verb_geometry_nurbs_surface_closest_param_input_surface: 'Arčiausias uv parametras ant paviršiaus',
    block_verb_geometry_nurbs_surface_closest_param_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_surface_closest_param_description: 'Randa arčiausią uv parametrą ant paviršiaus nuo duoto taško.',
    block_verb_geometry_nurbs_surface_closest_point_input_surface: 'Arčiausias taškas ant paviršiaus',
    block_verb_geometry_nurbs_surface_closest_point_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_surface_closest_point_description: 'Randa arčiausią tašką ant paviršiaus nuo duoto taško.',
    block_verb_geometry_nurbs_surface_control_points_input_surface: 'Kontroliniai paviršiaus taškai',
    block_verb_geometry_nurbs_surface_control_points_description: 'Gražina kontrolinius paviršiaus taškus.',
    block_verb_geometry_nurbs_surface_degree_u_input_surface: 'Paviršiaus u laipsnis',
    block_verb_geometry_nurbs_surface_degree_u_points_description: 'Gražina paviršiaus u laipsnį.',
    block_verb_geometry_nurbs_surface_degree_v_input_surface: 'Paviršiaus v laipsnis',
    block_verb_geometry_nurbs_surface_degree_v_points_description: 'Gražina paviršiaus v laipsnį.',
    block_verb_geometry_nurbs_surface_derivatives_input_surface: 'Paviršiaus išvestinės',
    block_verb_geometry_nurbs_surface_derivatives_input_u: 'Ant parametro u',
    block_verb_geometry_nurbs_surface_derivatives_input_v: 'Ir parametro v',
    block_verb_geometry_nurbs_surface_derivatives_input_num_derivatives: 'Išvestinių skaičius',
    block_verb_geometry_nurbs_surface_derivatives_description: 'Gražina paviršiaus išvestines ant uv koordinatės parametro.',
    block_verb_geometry_nurbs_surface_domain_u_input_surface: 'U paviršiaus domenas',
    block_verb_geometry_nurbs_surface_domain_u_description: 'Gražina u paviršiaus domeną intervalo pavidalu.',
    block_verb_geometry_nurbs_surface_domain_v_input_surface: 'V paviršiaus domenas',
    block_verb_geometry_nurbs_surface_domain_v_description: 'Gražina v paviršiaus domeną intervalo pavidalu.',
    block_verb_geometry_nurbs_surface_isocurve_input_surface: 'Izokreivė ant paviršiaus',
    block_verb_geometry_nurbs_surface_isocurve_input_parameter: 'Ties parametru',
    block_verb_geometry_nurbs_surface_isocurve_input_use_v: 'Naudojant v kryptį',
    block_verb_geometry_nurbs_surface_isocurve_description: 'Gauna izokreivę ant paviršiaus parametro u arba v kryptimi.',
    block_verb_geometry_nurbs_surface_knots_u_input_surface: 'Saitai u kryptimi ant paviršiaus',
    block_verb_geometry_nurbs_surface_knots_u_description: 'Gauna u saitus ant paviršiaus.',
    block_verb_geometry_nurbs_surface_knots_v_input_surface: 'Saitai v kryptimi ant paviršiaus',
    block_verb_geometry_nurbs_surface_knots_v_description: 'Gauna v saitus ant paviršiaus.',
    block_verb_geometry_nurbs_surface_normal_input_surface: 'Paviršiaus statmuo',
    block_verb_geometry_nurbs_surface_normal_input_u: 'Ant u koordinatės',
    block_verb_geometry_nurbs_surface_normal_input_v: 'Ir v koordinatės',
    block_verb_geometry_nurbs_surface_normal_description: 'Gauna paviršiaus statmenį ant uv koordinačių.',
    block_verb_geometry_nurbs_surface_point_input_surface: 'Paviršiaus taškas',
    block_verb_geometry_nurbs_surface_point_input_u: 'Ant u koordinatės',
    block_verb_geometry_nurbs_surface_point_input_v: 'Ir v koordinatės',
    block_verb_geometry_nurbs_surface_point_description: 'Gauna paviršiaus tašką ant uv koordinačių.',
    block_verb_geometry_nurbs_surface_reverse_input_surface: 'Apgręžti paviršių',
    block_verb_geometry_nurbs_surface_reverse_description: 'Apgręžia paviršiaus uv kryptis.',
    block_verb_geometry_nurbs_surface_split_input_surface: 'Padalinti paviršių',
    block_verb_geometry_nurbs_surface_split_input_parameter: 'Ties parametru',
    block_verb_geometry_nurbs_surface_split_input_use_v: 'Naudojant v kryptį',
    block_verb_geometry_nurbs_surface_split_description: 'Padalina paviršių į dvi dalis ties parametru.',
    block_verb_geometry_nurbs_surface_weights_input_surface: 'Paviršiaus svoriai',
    block_verb_geometry_nurbs_surface_weights_description: 'Gražina paviršiaus svorius.',
};
