import { ResourcesInterface } from './resources.interface';

export const resourcesLt: ResourcesInterface = {
    block_point: 'Taskas',
    block_points: 'Taskai',
    block_curve: 'Kreive',
    block_curves: 'Kreives',
    block_colour: 'Spalva',
    block_opacity: 'Matomumas',
    block_width: 'Storis',
    block_line: 'Linija',
    block_lines: 'Linijos',
    block_polyline: 'Polilinija',
    block_size: 'Dydis',
    block_validation_required: 'privalo buti ivesta',
    block_validation_higher_or_equal: 'privalo buti daugiau arba lygu',
    block_validation_lower_or_equal: 'privalo buti maziau arba lygu',
    block_validation_of_length: 'privalomas elementu skaicius yra',
    block_validation_range: 'privalo buti tarp',
    block_babylon_input_curve: 'Piesti kreive',
    block_babylon_input_curves: 'Piesti kreives',
    block_babylon_input_colour: 'Spalva',
    block_babylon_input_opacity: 'Matomumas',
    block_babylon_input_width: 'Storis',
    block_babylon_input_draw_grid: 'Piesti tinkleli kurio plotis',
    block_babylon_input_draw_line: 'Piesti linija',
    block_babylon_input_draw_lines: 'Piesti linijas',
    block_babylon_input_draw_polyline: 'Piesti polilinija',
    block_babylon_input_draw_point: 'Piesti taska',
    block_babylon_input_draw_points: 'Piesti taskus',
    block_babylon_input_size: 'Dydis',
    block_babylon_input_height: 'Aukstis',
    block_babylon_input_subdivisions: 'Sudalinimas',
    block_babylon_input_major_unit_frequency: 'Didziojo tinklelio tankumas',
    block_babylon_input_minor_unit_visibility: 'Mazojo tinklelio matomumas',
    block_babylon_input_back_face_culling: 'Galinio veido persvieciamumas',
    block_babylon_input_main_colour: 'Pagrindine spalva',
    block_babylon_input_secondary_colour: 'Antraeile spalva',
    block_babylon_input_grid_ratio: 'Tinklelio santykis',
    block_babylon_draw_curve_description: 'Piesti spalvota nurodyto storio kreive',
    block_babylon_draw_curves_description: 'Piesti spalvotas nurodyto storio kreives',
    block_babylon_draw_grid_description: 'Piesti zemes tinkleli kuris padeda orientuotis 3D erdveje',
    block_babylon_draw_line_description: 'Piesti spalvota nurodyto storio linija',
    block_babylon_draw_lines_description: 'Piesti spalvotas nurodyto storio linijas',
    block_babylon_draw_point_description: 'Piesti spalvota nurodyto dydzio taska',
    block_babylon_draw_points_description: 'Piesti spalvotus nurodyto dydzio taskus',
    block_babylon_draw_polyline_description: 'Piesti spalvota nurodyto storio polilinija'
};
