// GENERATED by scripts/gen-dto-meta.mjs from the inputs DTOs - do not edit; regenerate with `npm run gen:dto-meta`.
/* eslint-disable @typescript-eslint/no-namespace */
import { WithDefaults } from "@bitbybit-dev/base";
import * as Inputs from "../inputs";
export * from "@bitbybit-dev/base/lib/api/resolved-inputs";

/**
 * The IFC inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace IFC {
    export type AddBeamDto<T> = WithDefaults<Inputs.IFC.AddBeamDto<T>, "profile" | "rotation">;
    export type AddColumnDto<T> = WithDefaults<Inputs.IFC.AddColumnDto<T>, "position" | "baseOffset" | "profile" | "rotation">;
    export type AddDoorDto<T> = WithDefaults<Inputs.IFC.AddDoorDto<T>, "sill">;
    export type AddDoorTypeDto<T> = WithDefaults<Inputs.IFC.AddDoorTypeDto<T>, "name" | "operation" | "handle">;
    export type AddLayerSetDto<T> = WithDefaults<Inputs.IFC.AddLayerSetDto<T>, "name">;
    export type AddMaterialDto<T> = WithDefaults<Inputs.IFC.AddMaterialDto<T>, "name" | "transparency">;
    export type AddMemberDto<T> = WithDefaults<Inputs.IFC.AddMemberDto<T>, "predefinedType" | "profile" | "rotation">;
    export type AddOpeningDto<T> = WithDefaults<Inputs.IFC.AddOpeningDto<T>, "sill">;
    export type AddPropertySetDto<T> = WithDefaults<Inputs.IFC.AddPropertySetDto<T>, "name">;
    export type AddRoofDto<T> = WithDefaults<Inputs.IFC.AddRoofDto<T>, "kind" | "pitch" | "overhang" | "baseOffset">;
    export type AddSlabDto<T> = WithDefaults<Inputs.IFC.AddSlabDto<T>, "topOffset" | "predefinedType">;
    export type AddSlabOpeningDto<T> = Inputs.IFC.AddSlabOpeningDto<T>;
    export type AddSpaceDto<T> = WithDefaults<Inputs.IFC.AddSpaceDto<T>, "baseOffset" | "predefinedType">;
    export type AddStoreyDto<T> = WithDefaults<Inputs.IFC.AddStoreyDto<T>, "name" | "elevation">;
    export type AddTerrainDto<T> = WithDefaults<Inputs.IFC.AddTerrainDto<T>, "name" | "elevation">;
    export type AddTreeDto<T> = WithDefaults<Inputs.IFC.AddTreeDto<T>, "name" | "species" | "position" | "elevation">;
    export type AddWallDto<T> = WithDefaults<Inputs.IFC.AddWallDto<T>, "alignment" | "baseOffset" | "predefinedType">;
    export type AddWallTypeDto<T> = WithDefaults<Inputs.IFC.AddWallTypeDto<T>, "name" | "predefinedType">;
    export type AddWindowDto<T> = Inputs.IFC.AddWindowDto<T>;
    export type AddWindowTypeDto<T> = WithDefaults<Inputs.IFC.AddWindowTypeDto<T>, "name">;
    export type ClipWallByRoofDto<T> = Inputs.IFC.ClipWallByRoofDto<T>;
    export type ClipWallDto<T> = WithDefaults<Inputs.IFC.ClipWallDto<T>, "normal">;
    export type ComputeQuantitiesDto<T> = Inputs.IFC.ComputeQuantitiesDto<T>;
    export type ConnectWallsDto<T> = Inputs.IFC.ConnectWallsDto<T>;
    export type CreateModelDto = WithDefaults<Inputs.IFC.CreateModelDto, "name" | "siteName" | "buildingName" | "lengthUnit">;
    export type EditOpeningDto<T> = Inputs.IFC.EditOpeningDto<T>;
    export type EditWallDto<T> = Inputs.IFC.EditWallDto<T>;
    export type ElementDto<T> = Inputs.IFC.ElementDto<T>;
    export type ElementInfoDto = WithDefaults<Inputs.IFC.ElementInfoDto, "globalId" | "type" | "name" | "storey">;
    export type ElementsDto<T> = WithDefaults<Inputs.IFC.ElementsDto<T>, "type">;
    export type GeometryDto<T> = Inputs.IFC.GeometryDto<T>;
    export type GeometryProblemDto = WithDefaults<Inputs.IFC.GeometryProblemDto, "globalId" | "type" | "message">;
    export type GetAttributeDto<T> = WithDefaults<Inputs.IFC.GetAttributeDto<T>, "attribute">;
    export type GlobalIdOfDto<T> = Inputs.IFC.GlobalIdOfDto<T>;
    export type MaterialLayerDto = Inputs.IFC.MaterialLayerDto;
    export type MemberSharedDto<T> = WithDefaults<Inputs.IFC.MemberSharedDto<T>, "profile" | "rotation">;
    export type ModelDto<T> = Inputs.IFC.ModelDto<T>;
    export type ModelSummaryDto = WithDefaults<Inputs.IFC.ModelSummaryDto, "schema" | "editable" | "project" | "millimetresPerUnit" | "entities" | "storeys" | "elementCounts">;
    export type MoveElementDto<T> = WithDefaults<Inputs.IFC.MoveElementDto<T>, "translation" | "rotation">;
    export type PropertyDto = WithDefaults<Inputs.IFC.PropertyDto, "name">;
    export type PropertySetInfoDto = WithDefaults<Inputs.IFC.PropertySetInfoDto, "name" | "properties">;
    export type QuantitySetInfoDto = WithDefaults<Inputs.IFC.QuantitySetInfoDto, "name" | "quantities">;
    export type ReadModelDto = Inputs.IFC.ReadModelDto;
    export type RemovePropertySetDto<T> = WithDefaults<Inputs.IFC.RemovePropertySetDto<T>, "name">;
    export type RemovePropertyValuesDto<T> = WithDefaults<Inputs.IFC.RemovePropertyValuesDto<T>, "name">;
    export type SetAttributeDto<T> = WithDefaults<Inputs.IFC.SetAttributeDto<T>, "attribute">;
    export type SetPropertyValuesDto<T> = WithDefaults<Inputs.IFC.SetPropertyValuesDto<T>, "name">;
    export type SetStoreyElevationDto<T> = WithDefaults<Inputs.IFC.SetStoreyElevationDto<T>, "elevation">;
    export type SpaceInfoDto = WithDefaults<Inputs.IFC.SpaceInfoDto, "globalId" | "name" | "longName" | "storey" | "area" | "height">;
    export type SpacesDto<T> = Inputs.IFC.SpacesDto<T>;
    export type StoreyInfoDto = WithDefaults<Inputs.IFC.StoreyInfoDto, "globalId" | "name" | "elevation">;
    export type WallDto<T> = Inputs.IFC.WallDto<T>;
    export type WallJoinInfoDto = WithDefaults<Inputs.IFC.WallJoinInfoDto, "other" | "at" | "otherAt">;
    export type WallParametersDto = WithDefaults<Inputs.IFC.WallParametersDto, "globalId" | "name" | "storey" | "start" | "end" | "height" | "baseOffset" | "thickness" | "offset" | "alignment" | "layerSet" | "wallType" | "joins" | "openings" | "clippings">;
    export type WriteModelDto<T> = WithDefaults<Inputs.IFC.WriteModelDto<T>, "fileName">;
}
