import { createDateConvertToDateStringBlock } from './date-convert-to-date-string';
import { createDateConvertToIsoStringBlock } from './date-convert-to-iso-string';
import { createDateConvertToJSONBlock } from './date-convert-to-json';
import { createDateConvertToStringBlock } from './date-convert-to-string';
import { createDateConvertToTimeStringBlock } from './date-convert-to-time-string';
import { createDateConvertToUtcStringBlock } from './date-convert-to-utc-string';
import { createDateCreateBlock } from './date-create';
import { createDateCreateUnixTimestampBlock } from './date-create-unix-timestamp';
import { createDateNowBlock } from './date-now';
import { createDateParseBlock } from './date-parse';
import { createDateCreateUtcBlock } from './date-utc';
import { createDateGetDateBlock } from './get-date';
import { createDateGetDayBlock } from './get-day';
import { createDateGetFullYearBlock } from './get-full-year';
import { createDateGetHoursBlock } from './get-hours';
import { createDateGetMillisecondsBlock } from './get-milliseconds';
import { createDateGetMinutesBlock } from './get-minutes';
import { createDateGetMonthBlock } from './get-month';
import { createDateGetSecondsBlock } from './get-seconds';
import { createDateGetTimeBlock } from './get-time';
import { createDateGetTimeZoneOffsetBlock } from './get-time-zone-offset';
import { createDateGetUtcDateBlock } from './get-utc-date';
import { createDateGetUtcDayBlock } from './get-utc-day';
import { createDateGetUtcFullYearBlock } from './get-utc-full-year';
import { createDateGetUtcHoursBlock } from './get-utc-hours';
import { createDateGetUtcMillisecondsBlock } from './get-utc-milliseconds';
import { createDateGetUtcMinutesBlock } from './get-utc-minutes';
import { createDateGetUtcMonthBlock } from './get-utc-month';
import { createDateGetUtcSecondsBlock } from './get-utc-seconds';
import { createDateSetDateBlock } from './set-date';
import { createDateSetDayBlock } from './set-day';
import { createDateSetFullYearBlock } from './set-full-year';
import { createDateSetHoursBlock } from './set-hours';
import { createDateSetMillisecondsBlock } from './set-milliseconds';
import { createDateSetMinutesBlock } from './set-minutes';
import { createDateSetMonthBlock } from './set-month';
import { createDateSetSecondsBlock } from './set-seconds';
import { createDateSetTimeBlock } from './set-time';
import { createDateSetUtcDateBlock } from './set-utc-date';
import { createDateSetUtcDayBlock } from './set-utc-day';
import { createDateSetUtcFullYearBlock } from './set-utc-full-year';
import { createDateSetUtcHoursBlock } from './set-utc-hours';
import { createDateSetUtcMillisecondsBlock } from './set-utc-milliseconds';
import { createDateSetUtcMinutesBlock } from './set-utc-minutes';
import { createDateSetUtcMonthBlock } from './set-utc-month';
import { createDateSetUtcSecondsBlock } from './set-utc-seconds';

export function assembleDateBlocks() {
    createDateCreateBlock();
    createDateCreateUnixTimestampBlock();
    createDateCreateUtcBlock();
    createDateNowBlock();
    createDateParseBlock();
    createDateGetDateBlock();
    createDateGetDayBlock();
    createDateGetFullYearBlock();
    createDateGetHoursBlock();
    createDateGetMillisecondsBlock();
    createDateGetMinutesBlock();
    createDateGetMonthBlock();
    createDateGetSecondsBlock();
    createDateGetTimeBlock();
    createDateGetTimeZoneOffsetBlock();
    createDateGetUtcDateBlock();
    createDateGetUtcDayBlock();
    createDateGetUtcFullYearBlock();
    createDateGetUtcSecondsBlock();
    createDateGetUtcHoursBlock();
    createDateGetUtcMillisecondsBlock();
    createDateGetUtcMinutesBlock();
    createDateGetUtcMonthBlock();
    createDateGetUtcMillisecondsBlock();

    createDateSetDateBlock();
    createDateSetDayBlock();
    createDateSetFullYearBlock();
    createDateSetHoursBlock();
    createDateSetMillisecondsBlock();
    createDateSetMinutesBlock();
    createDateSetMonthBlock();
    createDateSetSecondsBlock();
    createDateSetTimeBlock();

    createDateSetUtcDateBlock();
    createDateSetUtcDayBlock();
    createDateSetUtcFullYearBlock();
    createDateSetUtcHoursBlock();
    createDateSetUtcMillisecondsBlock();
    createDateSetUtcMinutesBlock();
    createDateSetUtcMonthBlock();
    createDateSetUtcSecondsBlock();

    createDateConvertToDateStringBlock();
    createDateConvertToIsoStringBlock();
    createDateConvertToJSONBlock();
    createDateConvertToStringBlock();
    createDateConvertToTimeStringBlock();
    createDateConvertToUtcStringBlock();
}
