import { ResourcesInterface } from './resources.interface';

export const resourcesLt: ResourcesInterface = Object.freeze({
    bit_by_bit: 'BitasPoBito',
    app_menu_run_code: 'Paleisti Kodą',
    app_menu_swap_canvas: 'Sukeisti Aplinkas',
    app_menu_support_us_on_patreon: 'Paremkite mus Patreone',
    app_menu_clean_canvas: 'Išvalyti Drobę',
    app_menu_more: 'Daugiau',
    app_menu_more_about: 'Apie',
    app_menu_more_home: 'BitByBit Namai',
    app_menu_more_about_paragraph_first: 'BitasPoBito yra internetinė aplikacija paremta atviro kodo, bendruomenės ir prieinamumo idėjomis, kuri kūrėjams padeda programuoti geometrinius kūnus. Paprasta vizualinio programavimo kalba tinka visiems amžiams ir gali tarnauti kaip įrankis skirtas parametriniam dizainui, edukacijai, duomenų vizualizavimui, menams, skaitmeninei manufaktūrai kurti. Vartotojo sąsaja turėtų būti gerai pažįstama žmonėms, kurie jau yra išbandę įrankius, tokius kaip Scratch ar Blockly.Games. Skirtumas tas, jog BitasPoBito pateikia pažangius trimačio modeliavimo algoritmus, kurie leidžia atlikti begalę parametrinių užduočių. Platformos tikslas - supaprastinti programavimą, leisti vartotojams išsaugoti, įkelti ir dalintis skriptais bei prisijungti prie Discord bendruomenės. Prisijunkite ir tapkite šio įrankio ateities dalimi.',
    app_menu_more_about_paragraph_second: 'Programavimo kalba, kuri buvo pritaikyta BitasPoBito aplikacijoje gali būti naudojama kurti įvairius trimačius kūnus ir struktūras. Pradedant paprastais taškais, linijomis ir baigiant NURBS paviršiais. Šis modelis padeda kūrėjams mokytis eksperimentuojant. Trijų dimensijų aplinka, kuri buvo integruota į šį įrankį užtikrina greitą grįžtamąjį ryšį tarp kūrėjo ir kūrinio. Tai labai svarbu norint, kad vartotojas džiaugtųsi mokymosi procesu.',
    app_menu_more_about_paragraph_third: 'BitasPoBito savo Core versijoje visada liks laisvas ir nemokamas vartotojams. Algoritmai, kurie bus įdedami į Core versiją nebus išimami vėlesnėse versijose pelno siekimo tikslais. Minimalizmo ir paprastumo principais vadovaujamės visuose dizaino sprendimuose. Aplikacijos vartotojams nereikia registruotis jokiose sistemose ar instaliuoti naršyklių priedų. BitasPoBito kūrėjai nesiruošia vartotojų sekti analitiniais tikslais, kurie galėtų sumažinti aplikacijos greitį ar būti blokuojami naršyklių priedais. Negalėjome rasti geresnio pradinio puslapio aplikacijai nei pati aplikacija. Internetinis BitasPoBito puslapis iš karto paleidžia drobę, kurioje galite komponuoti algoritmus ir modeliuoti trimačius kūnus.',
    app_menu_more_about_paragraph_fourth: 'Bendruomenės nariai yra skatinami prisijungti prie forumo Discord platformoje, dalintis savo kūryba, užduoti klausimus, mokyti kitus, įkvėpti vienas kitą ir augti. Taip pat aktyviai ieškome Patronų ir rėmėjų, kurie padėtų palaikyti platformos kūrimą ir tobulinimą. Jūsų nuomonė svarbi, prisijunkite.',
    app_menu_more_about_paragraph_fifth: 'BitasPoBito didžiuojasi naudodamas šias puikias technologijas. BitasPoBito neegzistuotų be Blockly, BabylonJS ir VerbNurbs karkaso. Liksime visada dėkingi žmonėms ir bendruomenėms, kurios juos sukūrė.',
    app_menu_more_about_paragraph_sixth: 'BitasPoBito yra alfa versijoje. Būkite atsargūs. Mes stengiamės išvengti, bet negarantuojame atgalinio suderinamumo. Naujos versijos alfa etape gali "sugadinti" jūsų senus skriptus. Platforma aktyviai tobulinama, todėl negalime užtikrinti stabilumo.',
    app_menu_more_about_sub_header_first: 'Principai',
    app_menu_more_about_sub_header_second: 'Bendruomenė',
    app_menu_more_about_sub_header_third: 'Ačiū kitiems atviro kodo projektams!',
    app_menu_more_about_sub_header_fourth: 'Svarbu!',
    app_menu_more_about_sub_header_fifth: 'Licencija',
    app_menu_more_settings: 'Pasirinktys',
    app_menu_more_settings_explanation_save: 'Pasirinktys bus išsaugoti jūsų kitam vizitui.',
    app_menu_more_examples: 'Pavyzdžiai',
    app_menu_more_examples_explanation: 'Šie pavyzdžiai padeda pažinti ir suprasti 3D algoritmų pasaulį.',
    app_menu_more_examples_newbie: 'Naujokams',
    app_menu_more_examples_newbie_polyline_between_three_points_title: 'Polilinija tarp trijų taškų',
    app_menu_more_examples_newbie_polyline_between_three_points_description: 'Šis paprastas pavyzdys sukuria tris taškus ir per juos perveda poliliniją.',
    app_menu_more_examples_newbie_nurbs_curve_along_points_title: 'Kreivė per taškus',
    app_menu_more_examples_newbie_nurbs_curve_along_points_description: 'Iš 7 kontrolinių taškų sukuriama kreivė, kuri vėliau sudalinama į 20 lygaus ilgio atkarpų.',
    app_menu_more_examples_newbie_transformation_circle_title: 'Transformuotas apskritimas',
    app_menu_more_examples_newbie_transformation_circle_description: 'Šis pavyzdys demonstruoja, kaip naudojant elementarias dydžio ir rotacijos transformacijas iš paprasto apskritimo galima sukurti intriguojančią linijinę struktūrą.',
    app_menu_more_examples_newbie_standard_surfaces_title: 'Standartiniai paviršiai',
    app_menu_more_examples_newbie_standard_surfaces_description: 'Parodo kaip sukurti standartinius NURBS paviršius. Sfera, kūgis, cilindras, kėlinys, sukinys ir juostinis paviršiai yra sudėti į vieną sceną.',
    app_menu_more_examples_newbie_curve_to_gcode_title: 'Kreivės transformacija į GKodą',
    app_menu_more_examples_newbie_curve_to_gcode_description: 'Rodo kaip kreivės geometrijos informacija gali būti transformuojama į GKodą CNC mašinoms. Kai skriptas atidaromas, atsiranda dialogas su kodu, kurį vartotojas gali išsaugoti kietąjame diske. Taškai modelyje yra sužymėti.',
    app_menu_more_examples_street_smart: 'Gatvių Grudintiems',
    app_menu_more_examples_street_smart_virtual_folds_in_iteration_title: 'Virtualūs paviršiai',
    app_menu_more_examples_street_smart_virtual_folds_in_iteration_description: 'Iteracijos pagalba sukurti paviršiai varijuoja spalva ir dydžiu. Panaudojus labai paprastą kodą galima sukurti sudėtingą trimatę skulptūrą.',
    app_menu_more_examples_street_smart_kinetic_surfaces_title: 'Kinetiniai paviršiai',
    app_menu_more_examples_street_smart_kinetic_surfaces_description: 'Pavyzdys demonstruoja kaip realaus laiko simuliacijos gali būti atliktos naudojant renderiavimo ciklą. Kinetinė struktūra keičiasi bėgant laikui ir reprezentuoja papildomą dimensiją, kurią programuoti yra lengva ir paprasta.',
    app_menu_more_examples_street_smart_lines_between_two_surfaces_title: 'Linijos tarp dviejų paviršių',
    app_menu_more_examples_street_smart_lines_between_two_surfaces_description: 'Du vienas virš kito egzistuojantys paviršiai sudalinami izokreivėmis. Izokreivės savo ruožtu sudalinamos pradžios ir galo taškais, kurie jungiami į karkasines linijas tarp dviejų paviršių.',
    app_menu_more_examples_ninja_magic_spiral_title: 'Magiška spiralė',
    app_menu_more_examples_ninja_magic_spiral_description: 'Spiralės žavi savo grožiu ir yra populiarios tarp gamtoje paplitusių algoritmų. Šis pavyzdys parodo kaip galima suprogramuoti tokią spiralę patiems.',
    app_menu_more_examples_ninja_living_landscape_title: 'Gyvas reljefas',
    app_menu_more_examples_ninja_living_landscape_description: 'Šis pavyzdys rodo kaip agentais pagrįstos simuliacijos gali būti programuojamos mūsų platformoje. Parametrinis reljefas adaptuojasi prie sugeneruotų agentų kintantį aukštį.',
    app_menu_more_examples_ninja_crypto_data_visualziation_title: 'Kripto valiutų',
    app_menu_more_examples_ninja_crypto_data_visualziation_description: '3D data visualization opens up additional layer for understanding your information. This example demonstrates 3D charts of some popular crypto currencies. Communication with coingecko api is implemented via Http components, data is assembled and visualized via 3D tags and polylines.',
    app_menu_more_examples_ninja: 'Nindzėms',
    app_menu_more_sponsors: 'Remėjai ir Partneriai',
    app_menu_more_sponsors_explanation: 'Šiuo metu projektas remėjų neturi. Jei norėtumėte mus paremti mums būtų malonu įdėti jūsų logo šioje remėjų lentoje.',
    app_menu_more_sponsors_email: 'Jei norėtumėte mums padėti, kreipkitės elektroniniu paštu',
app_menu_more_community: 'Bendruomenė',
    app_menu_more_export: 'Išsaugoti',
    app_menu_more_import: 'Atidaryti',
    app_button_close: 'Uždaryti',
    app_button_save: 'Išsaugoti',
    app_button_cancel: 'Atšaukti',
    app_button_create: 'Kurti',
    app_languages: 'Kalbos',
    app_languages_lithuanian: 'Lietuvių',
    app_languages_english: 'Anglų',
    app_default_file_name: 'failas',
    app_default_file_extension: 'txt',
    app_prompt_value: 'Įvestis',
    app_prompt_value_placeholder: 'Vertė',
    app_print_save_dialog_text: 'Tekstas',
    app_print_save_dialog_file_extension: 'Tipas',
    app_print_save_dialog_file_name: 'Failo Pavadinimas',
    app_placeholder_text: 'Įveskite tekstą',
    app_save_dialog_title: 'Išsaugoti',
    app_print_save_dialog_title: 'Peržiūrėti ir išsaugoti',
    app_print_save_dialog_text_to_save: 'Tekstas išsaugojimui',
    app_print_save_dialog_export: 'Išsaugoti į failą',
    app_print_save_dialog_file_format: 'Įveskite savo teksto formatą, tokį kaip txt, csv ir panašiai.',
    block_toolbox_category_scene: 'Scena',
    block_toolbox_category_core_types: 'Baziniai Tipai',
    block_toolbox_category_core_transforms: 'Transformacijos',
    block_toolbox_category_core_node: 'Koordinačių Sistemos',
    block_toolbox_category_core_vector: 'Vektoriai',
    block_toolbox_category_geom_point: 'Taškas',
    block_toolbox_category_geom_line: 'Linija',
    block_toolbox_category_geom_polyline: 'Polilinija',
    block_toolbox_category_geom_curve: 'Kreivė',
    block_toolbox_category_geom_circle: 'Apskritimą',
    block_toolbox_category_geom_ellipse: 'Elipsę',
    block_toolbox_category_geom_surface: 'Paviršius',
    block_toolbox_category_geom_solid: 'Kūnai',
    block_toolbox_category_geom_plane: 'Plokštuma',
    block_toolbox_category_geom_cone: 'Kūgį',
    block_toolbox_category_geom_sweep: 'Juostinį',
    block_toolbox_category_geom_revolution: 'Sukinį',
    block_toolbox_category_geom_cylinder: 'Cilindrą',
    block_toolbox_category_geom_extrusion: 'Iškėlimą',
    block_toolbox_category_geom_sphere: 'Sferą',
    block_toolbox_category_date: 'Data',
    block_toolbox_category_geom_tag: 'Žyma',
    block_toolbox_category_intersect: 'Susikirtimai',
    block_toolbox_category_create: 'Kurti',
    block_toolbox_category_2d_path: '2D Kelias',
    block_toolbox_category_2d_polygon: '2D Formos',
    block_toolbox_category_boolean: 'Būlio Operacijos',
    block_toolbox_category_3d_solid: '3D Kūnai',
    block_toolbox_category_extrusion: 'Iškėlimas',
    block_toolbox_category_draw: 'Piešti',
    block_toolbox_category_apply: 'Naudoti',
    block_toolbox_category_apply_get: 'Gauti',
    block_toolbox_category_apply_set: 'Priskirti',
    block_toolbox_category_apply_convert: 'Konvertuoti',
    block_toolbox_category_loop: 'Ciklai',
    block_toolbox_category_logic: 'Logika',
    block_toolbox_category_math: 'Matematika',
    block_toolbox_category_lists: 'Rinkiniai',
    block_toolbox_category_colour: 'Spalvos',
    block_toolbox_category_text: 'Tekstas',
    block_toolbox_category_variables: 'Kintamieji',
    block_toolbox_category_functions: 'Funkcijos',
    block_toolbox_category_io: 'IO',
    block_toolbox_category_io_text: 'Tekstas',
    block_toolbox_category_io_json: 'JSON',
    block_toolbox_category_io_http: 'HTTP',
    block_toolbox_category_time: 'Laikas',
    block_number: 'Skaičius',
    block_modulus: 'Modulis',
    block_year: 'Metai',
    block_month: 'Mėnuo',
    block_day: 'Diena',
    block_weekday: 'Savaitės diena',
    block_hour: 'Valanda',
    block_minute: 'Minutė',
    block_second: 'Sekundė',
    block_milliseconds: 'Milisekundės',
    block_point: 'Taškas',
    block_closed: 'Uždaras',
    block_opened: 'Atviras',
    block_2d_path: 'Kelias',
    block_2d_paths: 'Keliai',
    block_url: 'URL Nuoroda',
    block_shape: 'Figūra',
    block_holes: 'Kiaurymės',
    block_text_tag: 'Teksto žyma',
    block_text_tags: 'Teksto žymos',
    block_body: 'Kūnas',
    block_unix_timestamp: 'Unix laiko žyma',
    block_date: 'Data',
    block_time: 'Time',
    block_computing: 'Laukiama',
    block_coordinate_x: 'Koordinatė X',
    block_coordinate_y: 'Koordinatė Y',
    block_coordinate_z: 'Koordinatė Z',
    block_coordinate_short_x: 'X',
    block_coordinate_short_y: 'Y',
    block_coordinate_short_z: 'Z',
    block_number_to_round: 'Skaičius apvalinimui',
    block_decimal_places: 'Skaitmenys po kablelio',
    block_height: 'Aukštis',
    block_points: 'Taškai',
    block_polygon: 'Poligonas',
    block_polygons: 'Poligonai',
    block_number_points: 'Taškų skaičius',
    block_text: 'Tekstas',
    block_json: 'JSON',
    block_path: 'Vieta',
    block_value: 'Vertė',
    block_param: 'Parametras',
    block_name: 'Pavadinimas',
    block_query: 'Užklausa',
    block_paths_values: 'Vietos ir vertės',
    block_number_to_remap: 'Transformuoti skaičių',
    block_source_interval: 'Kilmės intervalas',
    block_target_interval: 'Tikslo intervalas',
    block_curve: 'Kreivė',
    block_curves: 'Kreivės',
    block_colour: 'Spalva',
    block_opacity: 'Matomumas',
    block_width: 'Storis',
    block_line: 'Linija',
    block_node: 'Koordinačių sistema',
    block_nodes: 'Koordinačių sistemos',
    block_lines: 'Linijos',
    block_polyline: 'Polilinija',
    block_size: 'Dydis',
    block_updatable: 'Atnaujinimas',
    block_position: 'Pozicija',
    block_rotation: 'Rotacija',
    block_mesh: 'Tinklas',
    block_solid: 'Kūnas',
    block_solids: 'Kūnai',
    block_adapt_depth: 'Pritaikyti gyliui',
    block_surface: 'Paviršius',
    block_surfaces: 'Paviršiai',
    block_sphere: 'Sfera',
    block_revolution: 'Sukinys',
    block_extrusion: 'Iškeltas Paviršius',
    block_cone: 'Kūgis',
    block_cylinder: 'Cilindras',
    block_circle: 'Apskritimas',
    block_ellipse: 'Elipsė',
    block_center: 'Centras',
    block_radius: 'Spindulys',
    block_resolution: 'Rezoliucija',
    block_segments: 'Segmentai',
    block_profile: 'Profilis',
    block_promise: 'Pažadas',
    block_timeout: 'Atidėjimas',
    block_rail: 'Bėgis',
    block_sweep: 'Juostas Paviršius',
    block_direction: 'Kryptis',
    block_min: 'Minimumas',
    block_max: 'Maksimumas',
    block_interval: 'Intervalas',
    block_interval_handler: 'Intervalo prižiūrėtojas',
    block_timeout_handler: 'Atidėjimo prižiūrėtojas',
    block_integer: 'Sveikas skaičius',
    block_scale: 'Didinimas',
    block_vector: 'Vektorius',
    block_vectors: 'Vektoriai',
    block_angle: 'Kampas',
    block_axis: 'Ašis',
    block_x_axis: 'X Ašis',
    block_y_axis: 'Y Ašis',
    block_min_angle: 'Mažasis kampas',
    block_max_angle: 'Didysis kampas',
    block_base: 'Bazė',
    block_u: 'U',
    block_v: 'V',
    block_uv: 'UV',
    block_use_v: 'Naudoti V',
    block_distance: 'Atstumas',
    block_scalar: 'Skaičius',
    block_fraction: 'Frakcija',
    block_transform: 'Transformacija',
    block_step: 'Žingsnis',
    block_steps: 'Žingsniai',
    block_reference: 'Etalonas',
    block_knots: 'Saitai',
    block_knots_u: 'Saitai U',
    block_knots_v: 'Saitai V',
    block_weights: 'Svoriai',
    block_degree: 'Laipsnis',
    block_degree_u: 'Laipsnis U',
    block_degree_v: 'Laipsnis V',
    block_length: 'Ilgis',
    block_num_derivatives: 'Išvestinių skaičius',
    block_parameter: 'Parametras',
    block_parameter_u: 'Parametras U',
    block_parameter_v: 'Parametras V',
    block_subdivision: 'Sudalinimai',
    block_tolerance: 'Tolerancija',
    block_intersection: 'Susikirtimas',
    block_intersections: 'Susikirtimai',
    block_validation_required: 'privalo egzistuoti',
    block_validation_higher_or_equal: 'privalo būti daugiau arba lygu',
    block_validation_lower_or_equal: 'privalo būti maziau arba lygu',
    block_validation_of_length: 'privalomas elementų skaičius yra',
    block_validation_range: 'privalo būti tarp',
    block_validation_smaller_than: 'privalu būti mažesnis už',
    block_validation_smaller_or_equal_than: 'privalo būti mažesnis arba lygus',
    block_validation_larger_than: 'privalo būti didesnis už',
    block_validation_larger_or_equal_than: 'privalo būti didesnis arba lygus',
    block_babylon_input_curve: 'Piešiama',
    block_babylon_input_curve_2: 'iš kreivės',
    block_babylon_input_curve_variable: 'kreivėsTinklas',
    block_babylon_input_curves: 'Piešiamos',
    block_babylon_input_curves_2: 'iš kreivių',
    block_babylon_input_curves_variable: 'kreiviųTinklas',
    block_babylon_input_colour: 'Spalva',
    block_babylon_input_opacity: 'Matomumas',
    block_babylon_input_width: 'Storis',
    block_babylon_input_draw_grid_variable: 'tinklelis',
    block_babylon_input_draw_grid: 'Piešiamas',
    block_babylon_input_draw_grid_2: 'kurio plotis',
    block_babylon_input_draw_line: 'Piešiamas',
    block_babylon_input_draw_line_2: 'iš linijos',
    block_babylon_input_draw_line_variable: 'linijosTinklas',
    block_babylon_input_draw_lines: 'Piešiamas',
    block_babylon_input_draw_lines_2: 'iš linijų',
    block_babylon_input_draw_lines_variable: 'linijųTinklas',
    block_babylon_input_draw_node: 'Piešiama koordinačių sistema',
    block_babylon_input_draw_node_color_x: 'Ašies X spalva',
    block_babylon_input_draw_node_color_y: 'Ašies Y spalva',
    block_babylon_input_draw_node_color_z: 'Ašies Z spalva',
    block_babylon_input_draw_node_description: 'Piešia koordinačių sistemos ašis.',
    block_babylon_input_draw_nodes: 'Piešiamos koordinačių sistemos',
    block_babylon_input_draw_nodes_color_x: 'Ašies X spalva',
    block_babylon_input_draw_nodes_color_y: 'Ašies Y spalva',
    block_babylon_input_draw_nodes_color_z: 'Ašies Z spalva',
    block_babylon_input_draw_nodes_description: 'Piešia koordinačių sistemų ašis.',
    block_babylon_draw_csg_mesh_input_csg_mesh_variable: 'kūnoTinklas',
    block_babylon_draw_csg_mesh_input_csg_mesh: 'Piešiamas',
    block_babylon_draw_csg_mesh_input_csg_mesh_2: 'Iš kūno',
    block_babylon_draw_csg_mesh_description: 'Piešia kūno tinklą.',
    block_babylon_draw_csg_meshes_input_csg_meshes_variable: 'kūnųTinklas',
    block_babylon_draw_csg_meshes_input_csg_meshes: 'Piešiamas',
    block_babylon_draw_csg_meshes_input_csg_meshes_2: 'Iš kūnų',
    block_babylon_draw_csg_meshes_description: 'Piešia kūnų tinklą.',
    block_babylon_draw_csg_primitive_2d_polygon_input_csg_primitive_2d_polygon_variable: 'poligonoTinklas',
    block_babylon_draw_csg_primitive_2d_polygon_input_csg_primitive_2d_polygon: 'Piešiamas',
    block_babylon_draw_csg_primitive_2d_polygon_input_csg_primitive_2d_polygon_2: 'Iš poligono',
    block_babylon_draw_csg_primitive_2d_polygon_description: 'Piešia poligoną',
    block_babylon_input_draw_polylines: 'Piešiamas',
    block_babylon_input_draw_polylines_2: 'iš polilinijų',
    block_babylon_input_draw_polylines_variable: 'polilinijųTinklas',
    block_babylon_input_draw_polyline: 'Piešiamas',
    block_babylon_input_draw_polyline_2: 'iš polilinijų',
    block_babylon_input_draw_polyline_variable: 'polilinijosTinklas',
    block_babylon_input_draw_2d_path: 'Piešiamas',
    block_babylon_input_draw_2d_path_2: 'iš kelio',
    block_babylon_input_draw_2d_path_variable: 'kelioTinklas',
    block_babylon_input_draw_point: 'Piešiamas',
    block_babylon_input_draw_point_2: 'iš taško',
    block_babylon_input_draw_point_variable: 'taškoTinklas',
    block_babylon_input_draw_points: 'Piešiamas',
    block_babylon_input_draw_points_2: 'iš taškų',
    block_babylon_input_draw_points_variable: 'taškųTinklas',
    block_babylon_input_draw_surface: 'Piešiamas',
    block_babylon_input_draw_surface_variable: 'paviršiausTinklas',
    block_babylon_input_draw_surface_2: 'iš paviršių',
    block_babylon_input_draw_surfaces: 'Piešiamas',
    block_babylon_input_draw_surfaces_variable: 'paviršiųTinklas',
    block_babylon_input_draw_surfaces_2: 'iš paviršių',
    block_babylon_update_input_register_render_loop_listener: 'Klausytis piešimo ciklo',
    block_babylon_update_input_update: 'Ir atnaujinti',
    block_babylon_update_input_time_passed: 'praėjęsLaikas',
    block_babylon_update_description: 'Paleidžia atnaujinimo kodą piešimo cikle ir suteikia informaciją apie laiką, praėjusį nuo praeito piešimo ciklo.',
    block_babylon_input_scene_background_colour: 'Scenos fono spalva',
    block_babylon_input_size: 'Dydis',
    block_babylon_input_updatable: 'Atnaujintinas',
    block_babylon_input_height: 'Aukštis',
    block_babylon_input_subdivisions: 'Sudalinimas',
    block_babylon_input_major_unit_frequency: 'Didžiojo tinklelio tankumas',
    block_babylon_input_minor_unit_visibility: 'Mažojo tinklelio matomumas',
    block_babylon_input_back_face_culling: 'Galinio veido peršviečiamumas',
    block_babylon_input_main_colour: 'Pagrindinė spalva',
    block_babylon_input_secondary_colour: 'Antraeilė spalva',
    block_babylon_input_grid_ratio: 'Tinklelio santykis',
    block_babylon_draw_curve_description: 'Piešti spalvotą nurodyto storio kreivę.',
    block_babylon_draw_curves_description: 'Piešti spalvotas nurodyto storio kreives.',
    block_babylon_draw_grid_description: 'Piešti žemės tinklelį, kuris padeda orientuotis 3D erdvėje.',
    block_babylon_draw_line_description: 'Piešti spalvotą nurodyto storio liniją.',
    block_babylon_draw_lines_description: 'Piešti spalvotas nurodyto storio linijas.',
    block_babylon_draw_point_description: 'Piešti spalvotą nurodyto dydžio tašką.',
    block_babylon_draw_points_description: 'Piešti spalvotus nurodyto dydžio taškus.',
    block_babylon_draw_polyline_description: 'Piešti spalvotą nurodyto storio poliliniją.',
    block_babylon_draw_2d_path_description: 'Piešti spalvotą nurodyto storio kelią.',
    block_babylon_draw_polylines_description: 'Piešti spalvotas nurodyto storio polilinijas.',
    block_babylon_draw_surface_description: 'Piešti spalvotą paviršių.',
    block_babylon_draw_surfaces_description: 'Piešti spalvotus paviršius.',
    block_babylon_scene_background_colour_description: 'Pakeisti scenos fono spalvą.',
    block_base_geometry_input_line_start_point: 'Linija su pradžios tašku',
    block_base_geometry_input_line_end_point: 'Galiniu tašku',
    block_base_geometry_line_description: 'Sukuria liniją tarp dviejų taškų.',
    block_base_geometry_line_end_point: 'Galinis linijos taškas',
    block_base_geometry_line_end_point_description: 'Gauti galinį linijos tašką.',
    block_base_geometry_line_start_point: 'Pradinis linijos taškas',
    block_base_geometry_line_start_point_description: 'Gauti pradinį linijos tašką.',
    block_base_geometry_line_length: 'Linijos ilgis',
    block_base_geometry_line_length_description: 'Matuoti linijos ilgį.',
    block_base_geometry_line_convert_to_nurbs_curve: 'Kreivė iš linijos',
    block_base_geometry_line_convert_to_nurbs_curve_description: 'Konvertuoja liniją į kreivę.',
    block_base_geometry_polyline_convert_to_nurbs_curve: 'Kreivė iš polilinijos',
    block_base_geometry_polyline_convert_to_nurbs_curve_description: 'Konvertuoja poliliniją į kreivę.',
    block_base_geometry_line_reverse: 'Apgręžti liniją',
    block_base_geometry_line_reverse_description: 'Apgręžia linijos kryptį. Pradinis taškas tampa galiniu, o galinis pradiniu.',
    block_base_geometry_point_description: 'Sukuria tašką erdvėje.',
    block_base_geometry_point_2d_description: 'Sukuria 2d tašką XY plokštumoje.',
    block_base_geometry_point_distance: 'Atstumas tarp pirmo taško',
    block_base_geometry_point_distance_second_point: 'Antro taško',
    block_base_geometry_point_distance_description: 'Matuoja atstumą tarp dviejų taškų.',
    block_base_geometry_point_x: 'X taško koordinatė',
    block_base_geometry_point_x_description: 'Gauna taško x koordinatę.',
    block_base_geometry_point_y: 'Y taško koordinatė',
    block_base_geometry_point_y_description: 'Gauna taško y koordinatę.',
    block_base_geometry_point_z: 'Z taško koordinatė',
    block_base_geometry_point_z_description: 'Gauna taško z koordinatę.',
    block_base_geometry_polyline: 'Polilinija iš taškų',
    block_base_geometry_polyline_description: 'Sukuria poliliniją per taškus.',
    block_base_geometry_polyline_length: 'Polilinijos ilgis',
    block_base_geometry_polyline_length_description: 'Matuoti polilinijos ilgį.',
    block_base_geometry_polyline_points: 'Polilinijos taškai',
    block_base_geometry_polyline_points_description: 'Gauna polilinijos taškus.',
    block_base_geometry_polyline_points_count: 'Taškų skaičius polilinijoje',
    block_base_geometry_polyline_points_count_description: 'Suskaičiuoja taškų skaičių polilinijoje.',
    block_base_geometry_polyline_reverse: 'Apgręžti poliliniją',
    block_base_geometry_polyline_reverse_description: 'Apgręžia polilinijos kryptį. Pradinis taškas tampa galiniu, o galinis pradiniu.',
    block_verb_core_interval_input_min: 'Intervalas su minimumu',
    block_verb_core_interval_input_max: 'Maksimumu',
    block_verb_core_interval_description: 'Sukuria intervalą tarp mininumo ir maksimumo. Minimumo vertė privalo būti mažesnė už maksimumo.',
    block_verb_core_interval_get_max: 'Maksimumo vertė intervale',
    block_verb_core_interval_get_max_description: 'Gauna intervalo maksimumo vertę.',
    block_verb_core_interval_get_min: 'Minimumo vertė intervale',
    block_verb_core_interval_get_min_description: 'Gauna intervalo minimumo vertę.',
    block_babylon_input_transformation_scale_center: 'Centras',
    block_babylon_input_transformation_scale_uniform: 'Didinti kartais',
    block_babylon_transformation_scale_uniform_description: 'Didinti arba mažinti objektą kartais',
    block_babylon_input_transformation_scale_xyz: 'Didinimas XYZ vektoriumi',
    block_babylon_transformation_scale_xyz_description: 'Sukuria didinomo transformaciją, kuri objektą gali didinti skirtingais dydžiais xyz kryptimis.',
    block_babylon_input_transformation_scale_center_uniform: 'Didinti kartais',
    block_babylon_transformation_scale_center_uniform_description: 'Sukuria didinimo transformacija, kuri objekta plecia aplink taska erdveje.',
    block_babylon_input_transformation_scale_center_xyz: 'Didinimas XYZ vektoriumi',
    block_babylon_transformation_scale_center_xyz_description: 'Sukuria didinomo transformaciją, kuri objektą gali didinti skirtingais dydžiais xyz kryptimis aplink tašką.',
    block_babylon_input_transformation_translation_xyz: 'Perkelti XYZ kryptimi',
    block_babylon_transformation_translation_xyz_description: 'Perkelia objektą XYZ kryptimi į naują lokaciją.',
    block_babylon_input_transformation_rotation_center_x: 'Sukti aplink X ašį kampu',
    block_babylon_transformation_rotation_center_x_description: 'Suka objektą aplink X ašį ir duotą tašką.',
    block_babylon_input_transformation_rotation_center_y: 'Sukti aplink Y ašį kampu',
    block_babylon_transformation_rotation_center_y_description: 'Suka objektą aplink Y ašį ir duotą tašką.',
    block_babylon_input_transformation_rotation_center_z: 'Sukti aplink Z ašį kampu',
    block_babylon_transformation_rotation_center_z_description: 'Suka objektą aplink Z ašį ir duotą tašką.',
    block_babylon_input_transformation_rotation_center_angle: 'Sukti kampu',
    block_babylon_input_transformation_rotation_center_axis: 'Aplink ašį',
    block_babylon_transformation_rotation_center_axis_description: 'Suka objektą aplink pasirinktą ašį ir duotą tašką.',
    block_verb_geom_curve_transform_curve: 'Transformuoti kreivę',
    block_verb_geom_curve_transform_transformation: 'Transformacija',
    block_verb_geom_curve_transform_description: 'Transformuoja kreivę su duota transformacija.',
    block_verb_geom_curves_transform_curves: 'Transformuoti kreives',
    block_verb_geom_curves_transform_transformation: 'Transformacija',
    block_verb_geom_curves_transform_description: 'Transformuoja kreives su duota transformacija.',
    block_verb_geom_surface_transform_surface: 'Transformuoti paviršių',
    block_verb_geom_surface_transform_transformation: 'Transformacija',
    block_verb_geom_surface_transform_description: 'Transformuoja paviršių su duota transformacija.',
    block_base_geom_point_transform_point: 'Transformuoti tašką',
    block_base_geom_point_transform_transformation: 'Transformacija',
    block_base_geom_point_transform_description: 'Transformuoti tašką su duota transformacija.',
    block_base_geom_points_transform_points: 'Transformuoti taškus',
    block_base_geom_points_transform_transformation: 'Transformacija',
    block_base_geom_points_transform_description: 'Transformuoti taškus su duota transformacija.',
    block_base_geom_point_closest_from_points_input_point: 'Arčiausias taškas tarp taško',
    block_base_geom_point_closest_from_points_input_points: 'Ir taškų',
    block_base_geom_point_closest_from_points_description: 'Randa arčiausią tašką nuo taško iki taškų rinkinio.',
    block_base_geom_point_closest_from_points_index_input_point: 'Arčiausias taško indeksas tarp taško',
    block_base_geom_point_closest_from_points_index_input_points: 'Ir taškų',
    block_base_geom_point_closest_from_points_index_description: 'Randa arčiausio taško indeksą nuo taško iki taškų rinkinio.',
    block_base_geom_point_closest_from_points_distance_input_point: 'Arčiausias atstumas tarp taško',
    block_base_geom_point_closest_from_points_distance_input_points: 'Ir taškų',
    block_base_geom_point_closest_from_points_distance_description: 'Randa arčiausią atstumą nuo taško iki taškų rinkinio.',
    block_base_geom_line_transform_line: 'Transformuoti liniją',
    block_base_geom_line_transform_transformation: 'Transformacija',
    block_base_geom_line_transform_description: 'Transformuoti liniją su duota transformacija.',
    block_base_geom_polyline_transform_polyline: 'Transformuoti poliliniją',
    block_base_geom_polyline_transform_transformation: 'Transformacija',
    block_base_geom_polyline_transform_description: 'Transformuoti poliliniją su duota transformacija.',
    block_verb_core_uv_input_u: 'UV su U',
    block_verb_core_uv_input_v: 'V',
    block_verb_core_uv_description: 'Sukuria UV parametrą.',
    block_verb_core_uv_get_u: 'Guati U dalį iš UV',
    block_verb_core_uv_get_v: 'Gauti V dalį iš UV',
    block_verb_core_uv_get_u_description: 'Gauna U parametrą iš UV.',
    block_verb_core_uv_get_v_description: 'Gauna V parametrą iš UV.',
    block_verb_core_vector_description: 'Sukuria vektorių iš XYZ koordinačių.',
    block_verb_core_vector_add_input_first: 'Sudėti vektorių',
    block_verb_core_vector_add_input_second: 'Su vektoriumi',
    block_verb_core_vector_add_description: 'Sudeda du vektorius.',
    block_verb_core_vector_sub_input_first: 'Atimti vektorių',
    block_verb_core_vector_sub_input_second: 'Iš vektoriaus',
    block_verb_core_vector_sub_description: 'Dviejų vektorių atimtis.',
    block_verb_core_vector_add_all_input_vectors: 'Sudėti visus vektorius',
    block_verb_core_vector_add_all_description: 'Sudeda visus vektorius.',
    block_verb_core_vector_all_input: 'Visi binarai teigiami',
    block_verb_core_vector_all_description: 'Patikrina ar visi binarai kolekcijoje yra teigiami',
    block_verb_core_vector_angle_between_input_first: 'Kampas tarp pirmo vektoriaus',
    block_verb_core_vector_angle_between_input_second: 'Antro vektoriaus',
    block_verb_core_vector_angle_between_description: 'Matuoja kampą tarp dviejų vektorių.',
    block_verb_core_vector_angle_between_normalized_2d_input_first: 'Normalizuotas 2d kampas tarp pirmo vektoriaus',
    block_verb_core_vector_angle_between_normalized_2d_input_second: 'Antro vektoriaus',
    block_verb_core_vector_angle_between_normalized_2d_description: 'Matuoja normalizuotą 2d kampą tarp dviejų vektorių.',
    block_verb_core_vector_cross_input_first: 'Kryžminti vektorių',
    block_verb_core_vector_cross_input_second: 'Su vektoriumi',
    block_verb_core_vector_cross_description: 'Sukryžmina du vektorius.',
    block_verb_core_vector_distance_input_first: 'Atstumas tarp taško',
    block_verb_core_vector_distance_input_second: 'Ir taško',
    block_verb_core_vector_distance_description: 'Matuoja atstumą tarp dviejų taškų.',
    block_verb_core_vector_distance_squared_input_first: 'Kvadratinis atstumas tarp taško',
    block_verb_core_vector_distance_squared_input_second: 'Ir taško',
    block_verb_core_vector_distance_squared_description: 'Matuoja kvadratinį Euklido atstumą tarp dviejų taškų.',
    block_verb_core_vector_div_input_vector: 'Dalinti vektorių',
    block_verb_core_vector_div_input_scalar: 'Iš skaičiaus',
    block_verb_core_vector_div_description: 'Dalina vektorių iš skaičiaus.',
    block_verb_core_vector_domain_input_vector: 'Vektoriaus domenas',
    block_verb_core_vector_domain_description: 'Matuoja vektoriaus domeną.',
    block_verb_core_vector_dot_input_vector: 'Taškinis produktas tarp vektoriaus',
    block_verb_core_vector_dot_input_scalar: 'Ir vektoriaus',
    block_verb_core_vector_dot_description: 'Matuoja taškinį produktą tarp dviejų vektorių.',
    block_verb_core_vector_finite_input_vector: 'Tikrinti begalybes vektoriuje',
    block_verb_core_vector_finite_description: 'Tikrina ar vektoriuje yra begalinių elementų ir grąžina binarine būlių kolekciją kiekvienam elementui.',
    block_verb_core_vector_is_zero_input_vector: 'Ar nulinis vektorius',
    block_verb_core_vector_is_zero_description: 'Patikrina ar vektorius yra nulinis.',
    block_verb_core_vector_lerp_fraction: 'Taškas frakcijoje',
    block_verb_core_vector_lerp_input_first: 'Tarp vektoriaus',
    block_verb_core_vector_lerp_input_second: 'Ir vektoriaus',
    block_verb_core_vector_lerp_description: 'Grąžina tašką tarp dviejų vektorių davus frakcinį parametrą.',
    block_verb_core_vector_max_input_vector: 'Didžiausias skaičius vektoriuje',
    block_verb_core_vector_max_description: 'Grąžina didžiausią skaičių vektoriuje.',
    block_verb_core_vector_min_input_vector: 'Mažiausias skaičius vektoriuje',
    block_verb_core_vector_min_description: 'Grąžina mažiausią skaičių vektoriuje.',
    block_verb_core_vector_mul_input_vector: 'Dauginti vektorių',
    block_verb_core_vector_mul_input_scalar: 'Iš skaičiaus',
    block_verb_core_vector_mul_description: 'Daugina vektorių iš skaičiaus.',
    block_verb_core_vector_negate_input_vector: 'Negatyvus vektorius',
    block_verb_core_vector_negate_description: 'Grąžina negatyvų vektorių.',
    block_verb_core_vector_norm_input_vector: 'Vektoriaus norma',
    block_verb_core_vector_norm_description: 'Grąžina vektoriaus ilgį nuo nulinių xyz koordinačių.',
    block_verb_core_vector_norm_squared_input_vector: 'Vektoriaus normos kvadratas',
    block_verb_core_vector_norm_squared_description: 'Grąžina normos kvadaratą vektoriui',
    block_verb_core_vector_normalized_input_vector: 'Normalizuotas vektorius',
    block_verb_core_vector_normalized_description: 'Grąžina normalizuotą vektorių, kurio ilgis lygus 1, o kryptis nekinta.',
    block_verb_core_vector_on_ray_input_vector: 'Kryptimi vektoriaus',
    block_verb_core_vector_on_ray_input_point: 'Perkelti tašką',
    block_verb_core_vector_on_ray_input_distance: 'Atstumu',
    block_verb_core_vector_on_ray_description: 'Perkelia tašką duotu atstumu į kitą vietą vektoriaus kryptimi.',
    block_verb_core_vector_positive_angle_between_input_first: 'Teigiamas kampas tarp vektoriaus',
    block_verb_core_vector_positive_angle_between_input_second: 'Antro vektoriaus',
    block_verb_core_vector_positive_angle_between_input_reference: 'Ir etaloninio vektoriaus',
    block_verb_core_vector_positive_angle_between_description: 'Grąžina teigiamą kampą tarp dviejų vektorių naudojant etaloninė kryptį.',
    block_verb_core_vector_signed_angle_between_input_first: 'Ženklintas kampas tarp vektoriaus',
    block_verb_core_vector_signed_angle_between_input_second: 'Antro vektoriaus',
    block_verb_core_vector_signed_angle_between_input_reference: 'Ir etaloninio vektoriaus',
    block_verb_core_vector_signed_angle_between_description: 'Grąžina ženklintą +/- kampą tarp dviejų vektorių naudojant etaloninę kryptį.',
    block_verb_core_vector_range_input_max: 'Diapozonas iki maksimalios ribos',
    block_verb_core_vector_range_description: 'Sukuria skaičių rinkinį nuo 0 iki maksimalios ribos.',
    block_verb_core_vector_span_input_min: 'Skaičių diapozonas tarp minimumo',
    block_verb_core_vector_span_input_max: 'Ir maksimumo',
    block_verb_core_vector_span_input_step: 'Žingsniu',
    block_verb_core_vector_span_description: 'Sukuria skaičių rinkinį tarp minimumo ir maksimumo nurodytu žingsniu.',
    block_verb_core_vector_sum_input_vector: 'Susumuoti visus vektoriaus elementus',
    block_verb_core_vector_sum_description: 'Susumuoja visus vektoriaus elementus.',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_knots: 'Kreivė su saitais',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_control_points: 'Kontroliniais taškais',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_weights: 'Svoriais',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_input_degree: 'Ir laipsniu',
    block_verb_geometry_nurbs_curve_by_knots_control_points_weights_description: 'Sukuria duoto laipsnio kreivę su saitais, kontroliniais taškais ir svoriais.',
    block_verb_geometry_nurbs_curve_by_points_inputs_points: 'Kreivė kuri eina per taškus',
    block_verb_geometry_nurbs_curve_by_points_inputs_degree: 'Laipsnis',
    block_verb_geometry_nurbs_curve_by_points_description: 'Sukurti kreivę, kuri eina per duotus taškus ir laipsnį.',
    block_verb_geometry_nurbs_curve_clone_input_curve: 'Klonuoti kreivę',
    block_verb_geometry_nurbs_curve_clone_description: 'Klonuoja kreivę.',
    block_verb_geometry_nurbs_curve_closest_param_input_curve: 'Arčiausias parametras ant kreivės',
    block_verb_geometry_nurbs_curve_closest_param_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_curve_closest_param_description: 'Randa arčiausią kreivės parametrą nuo duoto taško.',
    block_verb_geometry_nurbs_curve_closest_params_input_curve: 'Arčiausi parametrai ant kreivės',
    block_verb_geometry_nurbs_curve_closest_params_input_points: 'Nuo taškų',
    block_verb_geometry_nurbs_curve_closest_params_description: 'Randa arčiausius kreivės parametrus nuo duotų taškų kolekcijos.',
    block_verb_geometry_nurbs_curve_closest_point_input_curve: 'Arčiausias taškas ant kreivės',
    block_verb_geometry_nurbs_curve_closest_point_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_curve_closest_point_description: 'Randa arčiausią tašką ant kreivės nuo duoto taško.',
    block_verb_geometry_nurbs_curve_closest_points_input_curve: 'Arčiausi taškai ant kreivės',
    block_verb_geometry_nurbs_curve_closest_points_input_points: 'Nuo taškų',
    block_verb_geometry_nurbs_curve_closest_points_description: 'Randa arčiausius kreivės taškus nuo duotų taškų kolekcijos.',
    block_verb_geometry_nurbs_curve_degree_input_curve: 'Kreivės laipsnis',
    block_verb_geometry_nurbs_curve_degree_description: 'Grąžina kreivės laipsnį.',
    block_verb_geometry_nurbs_curve_derivatives_input_curve: 'Kreivės išvestinės',
    block_verb_geometry_nurbs_curve_derivatives_input_parameter: 'Ant parametro',
    block_verb_geometry_nurbs_curve_derivatives_input_num_derivatives: 'Išvestinių skaičius',
    block_verb_geometry_nurbs_curve_derivatives_description: 'Gauna nurodytą skaičių kreivės išvestinių ant parametro.',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_params_input_curve: 'Sudalinti kreivę į parametrus',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_params_input_subdivison_number: 'Segmentų skaičius',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_params_description: 'Sudalina kreivę lygiu arkos ilgiu į duotą segmentų skaicių ir grąžina kreivės parametrų vertes.',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_points_input_curve: 'Sudalinti kreivę į taškus',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_points_input_subdivison_number: 'Segmentų skaičius',
    block_verb_geometry_nurbs_curve_divide_by_equal_arc_length_points_description: 'Sudalina kreivę lygiu arkos ilgiu į duotą segmentų skaičių ir grąžina taškus ant kreivės.',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_params_input_curve: 'Sudalinti kreivę į parametrus',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_params_input_arc_length: 'Arkos ilgiu',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_params_description: 'Sudalina kreivę į parametrus arkos ilgiu.',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_points_input_curve: 'Sudalinti kreivę į taškus',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_points_input_arc_length: 'Arkos ilgiu',
    block_verb_geometry_nurbs_curve_divide_by_arc_length_points_description: 'Sudalina kreivę į taškus arkos ilgiu.',
    block_verb_geometry_nurbs_curves_divide_by_equal_arc_length_points_input_curves: 'Sudalinti kreives į taškus',
    block_verb_geometry_nurbs_curves_divide_by_equal_arc_length_points_input_subdivison_number: 'Segmentų skaičius',
    block_verb_geometry_nurbs_curves_divide_by_equal_arc_length_points_description: 'Sudalina kreives lygiu arkos ilgiu į duotą segmentų skaičių ir grąžina taškus.',
    block_verb_geometry_nurbs_curves_divide_by_arc_length_points_input_curves: 'Sudalinti kreives į taškus',
    block_verb_geometry_nurbs_curves_divide_by_arc_length_points_input_arc_length: 'Arkos ilgiu',
    block_verb_geometry_nurbs_curves_divide_by_arc_length_points_description: 'Sudalina kreives į taškus arkos ilgiu.',
    block_verb_geometry_nurbs_curve_domain_input_curve: 'Kreivės domenas',
    block_verb_geometry_nurbs_curve_domain_description: 'Grąžina kreivės domeną.',
    block_verb_geometry_nurbs_curve_knots_input_curve: 'Kreivės saitai',
    block_verb_geometry_nurbs_curve_knots_description: 'Grąžina kreivės saitus.',
    block_verb_geometry_nurbs_curve_length_input_curve: 'Kreivės ilgis',
    block_verb_geometry_nurbs_curve_length_description: 'Grąžina kreivės ilgį.',
    block_verb_geometry_nurbs_curve_length_at_param_input_curve: 'Kreivės ilgis',
    block_verb_geometry_nurbs_curve_length_at_param_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_length_at_param_description: 'Matuoja kreivės ilgį ant parametro.',
    block_verb_geometry_nurbs_curve_param_at_length_input_curve: 'Parametras ant kreivės',
    block_verb_geometry_nurbs_curve_param_at_length_input_length: 'Atstume',
    block_verb_geometry_nurbs_curve_param_at_length_input_tolerance: 'Su tolerancija',
    block_verb_geometry_nurbs_curve_param_at_length_description: 'Grąžina kreivės parametrą duotu atustumu nuo kreivės pradžios taško.',
    block_verb_geometry_nurbs_curve_reverse_input_curve: 'Apgręžti kreivę',
    block_verb_geometry_nurbs_curve_reverse_description: 'Apgręžia kreivę.',
    block_verb_geometry_nurbs_curve_split_input_curve: 'Perkirpti kreivę',
    block_verb_geometry_nurbs_curve_split_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_split_description: 'Perkerpa kreivę į dvi dalis ties parametru ir grąžina dvi kreives.',
    block_verb_geometry_nurbs_curve_tangent_input_curve: 'Kreivės tangentas',
    block_verb_geometry_nurbs_curve_tangent_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_tangent_description: 'Grąžina tangentinį kreivės vektorių ties duotu parametru.',
    block_verb_geometry_nurbs_curve_tessellate_input_curve: 'Išskaidyti kreivę',
    block_verb_geometry_nurbs_curve_tessellate_input_tolerance: 'Su tolerancija',
    block_verb_geometry_nurbs_curve_tessellate_description: 'Išskaido kreivę į taškus duota tolerancija.',
    block_verb_geometry_nurbs_curve_weights_input_curve: 'Kreivės svoriai',
    block_verb_geometry_nurbs_curve_weights_description: 'Grąžina kreivės svorius',
    block_verb_geometry_nurbs_surface_boundaries_input_surface: 'Kraštinės kreivės paviršiuje',
    block_verb_geometry_nurbs_surface_boundaries_description: 'Grąžina 4 paviršiaus kraštus kreivių pavidalu.',
    block_verb_geometry_nurbs_surface_by_corners_input_point1: 'Paviršius su pirmo kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_input_point2: 'Antro kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_input_point3: 'Trečio kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_input_point4: 'Ketvirto kampo tašku',
    block_verb_geometry_nurbs_surface_by_corners_description: 'Sukuria paviršių ių keturių kampų.',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_knots_u: 'Paviršius su u saitais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_knots_v: 'V saitais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_points: 'Kontroliniais taškais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_weights: 'svoriais',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_degree_u: 'U laipsniu',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_input_degree_v: 'V laipsniu',
    block_verb_geometry_nurbs_surface_by_knots_control_points_weights_description: 'Sukuria paviršių iš uv saitų, taškų, svorių ir uv laipsniais.',
    block_verb_geometry_nurbs_surface_by_lofting_curves_input_curves: 'Paviršius vedamas per kreives',
    block_verb_geometry_nurbs_surface_by_lofting_curves_input_degree_v: 'V laipsnio',
    block_verb_geometry_nurbs_surface_by_lofting_curves_description: 'Paviršius sudaromas per kreivių rinkinį.',
    block_verb_geometry_nurbs_surface_clone_input_surface: 'Klonuoti paviršių',
    block_verb_geometry_nurbs_surface_clone_description: 'Klonuoja paviršių.',
    block_verb_geometry_nurbs_surface_closest_param_input_surface: 'Arčiausias uv parametras ant paviršiaus',
    block_verb_geometry_nurbs_surface_closest_param_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_surface_closest_param_description: 'Randa arčiausią uv parametrą ant paviršiaus nuo duoto taško.',
    block_verb_geometry_nurbs_surface_closest_point_input_surface: 'Arčiausias taškas ant paviršiaus',
    block_verb_geometry_nurbs_surface_closest_point_input_point: 'Nuo taško',
    block_verb_geometry_nurbs_surface_closest_point_description: 'Randa arčiausią tašką ant paviršiaus nuo duoto taško.',
    block_verb_geometry_nurbs_surface_control_points_input_surface: 'Kontroliniai paviršiaus taškai',
    block_verb_geometry_nurbs_surface_control_points_description: 'Grąžina kontrolinius paviršiaus taškus.',
    block_verb_geometry_nurbs_surface_degree_u_input_surface: 'Paviršiaus u laipsnis',
    block_verb_geometry_nurbs_surface_degree_u_points_description: 'Grąžina paviršiaus u laipsnį.',
    block_verb_geometry_nurbs_surface_degree_v_input_surface: 'Paviršiaus v laipsnis',
    block_verb_geometry_nurbs_surface_degree_v_points_description: 'Grąžina paviršiaus v laipsnį.',
    block_verb_geometry_nurbs_surface_derivatives_input_surface: 'Paviršiaus išvestinės',
    block_verb_geometry_nurbs_surface_derivatives_input_u: 'Ant parametro u',
    block_verb_geometry_nurbs_surface_derivatives_input_v: 'Ir parametro v',
    block_verb_geometry_nurbs_surface_derivatives_input_num_derivatives: 'Išvestinių skaičius',
    block_verb_geometry_nurbs_surface_derivatives_description: 'Grąžina paviršiaus išvestines ant uv koordinatės parametro.',
    block_verb_geometry_nurbs_surface_domain_u_input_surface: 'U paviršiaus domenas',
    block_verb_geometry_nurbs_surface_domain_u_description: 'Grąžina u paviršiaus domeną intervalo pavidalu.',
    block_verb_geometry_nurbs_surface_domain_v_input_surface: 'V paviršiaus domenas',
    block_verb_geometry_nurbs_surface_domain_v_description: 'Grąžina v paviršiaus domeną intervalo pavidalu.',
    block_verb_geometry_nurbs_surface_isocurve_input_surface: 'Izokreivė ant paviršiaus',
    block_verb_geometry_nurbs_surface_isocurve_input_parameter: 'Ties parametru',
    block_verb_geometry_nurbs_surface_isocurve_input_use_v: 'Naudojant v kryptį',
    block_verb_geometry_nurbs_surface_isocurve_description: 'Gauna izokreivę ant paviršiaus parametro u arba v kryptimi.',
    block_verb_geometry_nurbs_surface_knots_u_input_surface: 'Saitai u kryptimi ant paviršiaus',
    block_verb_geometry_nurbs_surface_knots_u_description: 'Gauna u saitus ant paviršiaus.',
    block_verb_geometry_nurbs_surface_knots_v_input_surface: 'Saitai v kryptimi ant paviršiaus',
    block_verb_geometry_nurbs_surface_knots_v_description: 'Gauna v saitus ant paviršiaus.',
    block_verb_geometry_nurbs_surface_normal_input_surface: 'Paviršiaus statmuo',
    block_verb_geometry_nurbs_surface_normal_input_u: 'Ant u koordinatės',
    block_verb_geometry_nurbs_surface_normal_input_v: 'Ir v koordinatės',
    block_verb_geometry_nurbs_surface_normal_description: 'Gauna paviršiaus statmenį ant uv koordinačių.',
    block_verb_geometry_nurbs_surface_point_input_surface: 'Paviršiaus taškas',
    block_verb_geometry_nurbs_surface_point_input_u: 'Ant u koordinatės',
    block_verb_geometry_nurbs_surface_point_input_v: 'Ir v koordinatės',
    block_verb_geometry_nurbs_surface_point_description: 'Gauna paviršiaus tašką ant uv koordinačių.',
    block_verb_geometry_nurbs_surface_reverse_input_surface: 'Apgręžti paviršių',
    block_verb_geometry_nurbs_surface_reverse_description: 'Apgręžia paviršiaus uv kryptis.',
    block_verb_geometry_nurbs_surface_split_input_surface: 'Padalinti paviršių',
    block_verb_geometry_nurbs_surface_split_input_parameter: 'Ties parametru',
    block_verb_geometry_nurbs_surface_split_input_use_v: 'Naudojant v kryptį',
    block_verb_geometry_nurbs_surface_split_description: 'Padalina paviršių į dvi dalis ties parametru.',
    block_verb_geometry_nurbs_surface_weights_input_surface: 'Paviršiaus svoriai',
    block_verb_geometry_nurbs_surface_weights_description: 'Grąžina paviršiaus svorius.',
    block_verb_geometry_spherical_surface_input_center: 'Sferinio paviršiaus centras',
    block_verb_geometry_spherical_surface_input_radius: 'Spindulys',
    block_verb_geometry_spherical_surface_description: 'Sukuria sferinį duoto spindulio paviršių.',
    block_verb_geometry_spherical_surface_center_input_sphere: 'Sferos centras',
    block_verb_geometry_spherical_surface_center_description: 'Grąžina sferos centrą.',
    block_verb_geometry_spherical_surface_radius_input_sphere: 'Sferos spindulys',
    block_verb_geometry_spherical_surface_radius_description: 'Grąžina sferos spindlį.',
    block_verb_geometry_nurbs_curve_circle_input_center: 'Apskritimas su centru',
    block_verb_geometry_nurbs_curve_circle_input_x_axis: 'X ašimi',
    block_verb_geometry_nurbs_curve_circle_input_y_axis: 'Y ašimi',
    block_verb_geometry_nurbs_curve_circle_input_radius: 'Spinduliu',
    block_verb_geometry_nurbs_curve_circle_description: 'Sukuria duoto spindulio apskritimą ties centru ant xy plokštumos.',
    block_verb_geometry_nurbs_curve_arc_input_center: 'Arka su centru',
    block_verb_geometry_nurbs_curve_arc_input_x_axis: 'X ašimi',
    block_verb_geometry_nurbs_curve_arc_input_y_axis: 'Y ašimi',
    block_verb_geometry_nurbs_curve_arc_input_radius: 'Spinduliu',
    block_verb_geometry_nurbs_curve_arc_input_min_angle: 'Mažuoju kampu',
    block_verb_geometry_nurbs_curve_arc_input_max_angle: 'Didžiuoju kampu',
    block_verb_geometry_nurbs_curve_arc_description: 'Sukuria duoto spindulio ir ribos kampų arką ties centru ant xy plokštumos',
    block_verb_geometry_nurbs_curve_circle_radius_input_circle: 'Arkos arba apskritimo spindulys',
    block_verb_geometry_nurbs_curve_circle_radius_description: 'Grąžina arkos arba apskritimo spindulį.',
    block_verb_geometry_nurbs_curve_circle_center_input_circle: 'Arkos arba apskritimo centras',
    block_verb_geometry_nurbs_curve_circle_center_description: 'Grąžina arkos arba apskritimo centrą.',
    block_verb_geometry_nurbs_curve_circle_x_axis_input_circle: 'Arkos arba apskritimo x ašis',
    block_verb_geometry_nurbs_curve_circle_x_axis_description: 'Grąžina arkos arba apskritimo x ašį.',
    block_verb_geometry_nurbs_curve_circle_y_axis_input_circle: 'Arkos arba apskritimo y ašis',
    block_verb_geometry_nurbs_curve_circle_y_axis_description: 'Grąžina arkos arba apskritimo y ašį.',
    block_verb_geometry_nurbs_curve_circle_min_angle_input_circle: 'Mažasis arkos kampas',
    block_verb_geometry_nurbs_curve_circle_min_angle_description: 'Grąžina mažąjį arkos kampą.',
    block_verb_geometry_nurbs_curve_circle_max_angle_input_circle: 'Didysis arkos kampas',
    block_verb_geometry_nurbs_curve_circle_max_angle_description: 'Grąžina didyjį arkos kampą.',
    block_verb_geometry_bezier_curve_inputs_points: 'Bezier kreivė tarp taškų',
    block_verb_geometry_bezier_curve_inputs_weights: 'Ir svorių',
    block_verb_geometry_bezier_curve_description: 'Sukuria Bezier kreivę tarp taškų ir svorių.',
    block_verb_geometry_nurbs_curve_ellipse_arc_input_center: 'Elipsės arka su centru',
    block_verb_geometry_nurbs_curve_ellipse_arc_input_x_axis: 'X ašimi',
    block_verb_geometry_nurbs_curve_ellipse_arc_input_y_axis: 'Y ašimi',
    block_verb_geometry_nurbs_curve_ellipse_arc_input_min_angle: 'Mažuoju kampu',
    block_verb_geometry_nurbs_curve_ellipse_arc_input_max_angle: 'Didžiuoju kampu',
    block_verb_geometry_nurbs_curve_ellipse_arc_description: 'Sukuria elipsės arką xy ašių ilgiais ir ribos kampais.',
    block_verb_geometry_nurbs_curve_ellipse_input_center: 'Ellipse with center',
    block_verb_geometry_nurbs_curve_ellipse_input_x_axis: 'X axis',
    block_verb_geometry_nurbs_curve_ellipse_input_y_axis: 'Y axis',
    block_verb_geometry_nurbs_curve_ellipse_description: 'Creates the ellipse with different xy axis lengths around a center.',
    block_verb_geometry_nurbs_curve_ellipse_center_input_ellipse: 'Elipsės ar jos arkos centras',
    block_verb_geometry_nurbs_curve_ellipse_center_description: 'Grąžina elipsės ar jos arkos  centrą.',
    block_verb_geometry_nurbs_curve_ellipse_x_axis_input_ellipse: 'Elipsės ar jos arkos x ašis',
    block_verb_geometry_nurbs_curve_ellipse_x_axis_description: 'Grąžina elipsės ar jos arkos x ašį.',
    block_verb_geometry_nurbs_curve_ellipse_y_axis_input_ellipse: 'Elipsės ar jos arkos y ašis',
    block_verb_geometry_nurbs_curve_ellipse_y_axis_description: 'Grąžina elipsės ar jos arkos y ašį.',
    block_verb_geometry_nurbs_curve_ellipse_min_angle_input_ellipse: 'Mažasis elipsės arkos kampas',
    block_verb_geometry_nurbs_curve_ellipse_min_angle_description: 'Grąžina mažąjį elipsės arkos kampą.',
    block_verb_geometry_nurbs_curve_ellipse_max_angle_input_ellipse: 'Didysis elipsės arkos kampas',
    block_verb_geometry_nurbs_curve_ellipse_max_angle_description: 'Grąžina didyjį elipsės arkos kampą.',
    block_verb_geometry_conical_surface_input_axis: 'Kūgis ant ašies',
    block_verb_geometry_conical_surface_input_base: 'Bazės',
    block_verb_geometry_conical_surface_input_x_axis: 'X ašis',
    block_verb_geometry_conical_surface_input_radius: 'Spindulys',
    block_verb_geometry_conical_surface_input_height: 'Aukštis',
    block_verb_geometry_conical_surface_description: 'Sukuria kūgį.',
    block_verb_geometry_conical_surface_base_input_cone: 'Kūgio bazė',
    block_verb_geometry_conical_surface_base_description: 'Grąžina kūgio bazės tašką.',
    block_verb_geometry_conical_surface_axis_input_cone: 'Kūgio ašis',
    block_verb_geometry_conical_surface_axis_description: 'Grąžina pagrindinę kūgio ašį.',
    block_verb_geometry_conical_surface_x_axis_input_cone: 'Kūgio x ašis',
    block_verb_geometry_conical_surface_x_axis_description: 'Grąžina kūgio x ašį.',
    block_verb_geometry_conical_surface_radius_input_cone: 'Kūgio spindulys',
    block_verb_geometry_conical_surface_radius_description: 'Grąžina kūgio spindulį.',
    block_verb_geometry_conical_surface_height_input_cone: 'Kūgio aukšis',
    block_verb_geometry_conical_surface_height_description: 'Grąžina kūgio aukštį.',
    block_verb_geometry_extruded_surface_input_profile: 'Profilio kreivės iškėlimas',
    block_verb_geometry_extruded_surface_input_direction: 'Kryptimi',
    block_verb_geometry_extruded_surface_description: 'Iškelia profilio kreivę duota kryptimi ir sukuria paviršių.',    
    block_verb_geometry_extruded_surface_direction_input_extrusion: 'Iškelto paviršiaus kryptis',
    block_verb_geometry_extruded_surface_direction_description: 'Grąžina iškelto paviršiaus kryptį.',
    block_verb_geometry_extruded_surface_profile_input_extrusion: 'Iškelto paviršiaus profilis',
    block_verb_geometry_extruded_surface_profile_description: 'Grąžina iškelto paviršiaus profilio kreivę.',
    block_verb_geometry_cylindrical_surface_input_axis: 'Cilindras ant ašies',
    block_verb_geometry_cylindrical_surface_input_base: 'Bazės',
    block_verb_geometry_cylindrical_surface_input_x_axis: 'X ašis',
    block_verb_geometry_cylindrical_surface_input_radius: 'Spindulys',
    block_verb_geometry_cylindrical_surface_input_height: 'Aukštis',
    block_verb_geometry_cylindrical_surface_description: 'Sukuria cilindrą.',
    block_verb_geometry_cylindrical_surface_base_input_cylinder: 'Cilindro bazė',
    block_verb_geometry_cylindrical_surface_base_description: 'Grąžina cilindro bazės tašką.',
    block_verb_geometry_cylindrical_surface_axis_input_cylinder: 'Cilindro ašis',
    block_verb_geometry_cylindrical_surface_axis_description: 'Grąžina cilindro ašį.',
    block_verb_geometry_cylindrical_surface_x_axis_input_cylinder: 'Cilindro x ašis',
    block_verb_geometry_cylindrical_surface_x_axis_description: 'Grąžina cilindro x ašį.',
    block_verb_geometry_cylindrical_surface_radius_input_cylinder: 'Cilindro spindulys',
    block_verb_geometry_cylindrical_surface_radius_description: 'Grąžina cilindro spindulį.',
    block_verb_geometry_cylindrical_surface_height_input_cylinder: 'Cilindro aukšis',
    block_verb_geometry_cylindrical_surface_height_description: 'Grąžina cilindro aukštį.',
    block_verb_geometry_revolved_surface_input_profile: 'Sukti profilį',
    block_verb_geometry_revolved_surface_input_center: 'Ant centro',
    block_verb_geometry_revolved_surface_input_axis: 'Aplink ašį',
    block_verb_geometry_revolved_surface_input_angle: 'Kampu',
    block_verb_geometry_revolved_surface_description: 'Suka profilio kreivę ant centro aplink ašį kampu ir sukuria sukinio paviršių.',
    block_verb_geometry_revolved_surface_center_input_revolution: 'Sukinio centras',
    block_verb_geometry_revolved_surface_center_description: 'Grąžina sukinio centro tašką.',
    block_verb_geometry_revolved_surface_axis_input_revolution: 'Sukinio ašis',
    block_verb_geometry_revolved_surface_axis_description: 'Grąžina sukinio rotacijos ašį.',
    block_verb_geometry_revolved_surface_profile_input_revolution: 'Sukinio profilis',
    block_verb_geometry_revolved_surface_profile_description: 'Grąžina sukinio profilio kreivę.',
    block_verb_geometry_revolved_surface_angle_input_revolution: 'Sukinio kampas',
    block_verb_geometry_revolved_surface_angle_description: 'Grąžina sukinio rotacijos kampą.',
    block_verb_geometry_swept_surface_input_profile: 'Juosti profilio kreivę',
    block_verb_geometry_swept_surface_input_rail: 'Pagal bėgio kreivę',
    block_verb_geometry_swept_surface_description: 'Juosia profilio kreivę pagal bėgio kreivę ir sukuria paviršių.',
    block_verb_geometry_swept_surface_profile_input_sweep: 'Juosto paviršiaus profilis',
    block_verb_geometry_swept_surface_profile_description: 'Grąžina juosto paviršiaus profilį.',
    block_verb_geometry_swept_surface_rail_input_sweep: 'Juosto paviršiaus bėgis',
    block_verb_geometry_swept_surface_rail_description: 'Grąžina juosto paviršiaus bėgį.',
    block_base_geom_point_spiral_input_phi: 'Phi parametras',
    block_base_geom_point_spiral_input_increase: 'Plėtimosi indeksas',
    block_base_geom_point_spiral_input_factor: 'Spiralė su faktoriumi',
    block_base_geom_point_spiral_input_radius: 'Spinduliu',
    block_base_geom_point_spiral_input_number_points: 'Taškų skaičiumi',
    block_base_geom_point_spiral_description: 'Sukuria taškų rinkinį išsidėsčiusį and spiralės.',
    block_base_geometry_lines_input_start_points: 'Linijos nuo pradžios taškų',
    block_base_geometry_lines_input_end_points: 'Iki galo taškų',
    block_base_geometry_lines_description: 'Sukuria linijų rinkinį tarp pradžios ir galo taškų.',
    block_base_geometry_point_list_input_point: 'Dauginimo taškas',
    block_base_geometry_point_list_input_amount_of_points: 'Taškų skaičius',
    block_base_geometry_point_list_description: 'Sukuria rinkinį taškų toje pačioje xyz koordinatėje.',
    block_verb_geometry_intersect_curve_curve_input_first_curve: 'Sukerta kreivę',
    block_verb_geometry_intersect_curve_curve_input_second_curve: 'Su kreive',
    block_verb_geometry_intersect_curve_curve_input_tolerance: 'Tolerancija',
    block_verb_geometry_intersect_curve_curve_description: 'Sukerta dvi kreives ir grąžina kreivių susikirtimo rezultatus.',
    block_verb_geometry_intersect_curve_surface_input_curve: 'Sukerte kreivę',
    block_verb_geometry_intersect_curve_surface_input_surface: 'Su paviršiumi',
    block_verb_geometry_intersect_curve_surface_description: 'Sukerta kreivę su paviršiumi ir grąžina susikirtimo rezultatus.',
    block_verb_geometry_intersect_surface_surface_input_curve: 'Sukerta paviršių',
    block_verb_geometry_intersect_surface_surface_input_surface: 'Su paviršiumi',
    block_verb_geometry_intersect_surface_surface_description: 'Sukerta paviršių su paviršiumi ir grąžina susikirtimo rezultatus.',
    block_base_geometry_lines_convert_to_nurbs_curves: 'Kreivės iš linijų',
    block_base_geometry_lines_convert_to_nurbs_curves_description: 'Konvertuoja linijas į kreives.',
    block_verb_geometry_intersect_curve_curve_first_params_input_intersections: 'Pirmos kreivės parametrai ant kreivių susikirtimų',
    block_verb_geometry_intersect_curve_curve_first_params_description: 'Grąžina pirmos kreivės parametrus ant kreivių susikirtimų.',
    block_verb_geometry_intersect_curve_curve_second_params_input_intersections: 'Antros kreivės parametrai ant kreivių susikirtimų',
    block_verb_geometry_intersect_curve_curve_second_params_description: 'Antros kreivės parametrai ant kreivių susikirtimų.',
    block_verb_geometry_intersect_curve_curve_first_points_input_intersections: 'Pirmos kreivės taškai ant kreivių susikirtimų',
    block_verb_geometry_intersect_curve_curve_first_points_description: 'Grąžina pirmos kreivės taškus ant kreivių susikirtimų.',
    block_verb_geometry_intersect_curve_curve_second_points_input_intersections: 'Antros kreivės taškai ant kreivių susikirtimų',
    block_verb_geometry_intersect_curve_curve_second_points_description: 'Grąžina antros kreivės taškus ant kreivių susikirtimų.',
    block_verb_geometry_intersect_curve_surface_curve_params_input_intersections: 'Kreivės parametrai ant kreivės-paviršiaus susikirtimų',
    block_verb_geometry_intersect_curve_surface_curve_params_description: 'Grąžina kreivės parametrus ant kreivės-paviršiaus susikirtimų.',
    block_verb_geometry_intersect_curve_surface_surface_params_input_intersections: 'Paviršiaus UV parametrai ant kreivės-paviršiaus susikirtimų',
    block_verb_geometry_intersect_curve_surface_surface_params_description: 'Grąžina paviršiaus UV parametrus ant kreivės-paviršiaus susikirtimų.',
    block_verb_geometry_intersect_curve_surface_curve_points_input_intersections: 'Kreivės taškai ant kreivės-paviršiaus susikirtimų',
    block_verb_geometry_intersect_curve_surface_curve_points_description: 'Grąžina kreivės taškus ant kreivės-paviršiaus susikirtimų.',
    block_verb_geometry_intersect_curve_surface_surface_points_input_intersections: 'Paviršiaus taškai ant kreivės-paviršiaus susikirtimų',
    block_verb_geometry_intersect_curve_surface_surface_points_description: 'Grąžina paviršiaus taškus ant kreivės-paviršiaus susikirtimų.',
    block_base_geometry_lines_between_points_input_points: 'Linijos tarp taškų',
    block_base_geometry_lines_between_points_description: 'Sukuria linijas tarp taškų segmentais.',
    block_base_lists_group_list_elements_input_list: 'Rinkinys grupavimui',
    block_base_lists_group_list_elements_input_segmented: 'Segmentuotas',
    block_base_lists_group_list_elements_input_number_of_elements: 'Skaičius elementų grupėje',
    block_base_lists_group_list_elements_description: 'Sugrupuoja rinkinį į mažesnes duoto elementų skaičiaus grupes. Jei buvo pasirinktas segmentavimas, paskutinis kiekvienos grupės elementas taps pirmu sekančios grupės elementu. Tai gali lemti visuminį elementų padidėjimą.',
    block_verb_geometry_nurbs_curve_point_at_param_input_curve: 'Taškas ant kreivės',
    block_verb_geometry_nurbs_curve_point_at_param_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curve_point_at_param_description: 'Gauna tašką ant kreivės ties parametru.',
    block_verb_geometry_nurbs_curves_points_at_param_input_curve: 'Taškai ant kreicių',
    block_verb_geometry_nurbs_curves_points_at_param_input_param: 'Ties parametru',
    block_verb_geometry_nurbs_curves_points_at_param_description: 'Gauna taškus ant kreivių ties parametru.',
    block_verb_geometry_nurbs_curve_start_point_input_curve: 'Pradinis kreivės taškas',
    block_verb_geometry_nurbs_curve_start_point_description: 'Gauna pradinį kreivės tašką.',
    block_verb_geometry_nurbs_curve_end_point_input_curve: 'Galinis kreivės taškas',
    block_verb_geometry_nurbs_curve_end_point_description: 'Gauna galinį kreivės tašką',
    block_babylon_draw_surfaces_colours_input_surfaces: 'Piešiami',
    block_babylon_draw_surfaces_colours_input_surfaces_variable: 'paviršiųTinklai',
    block_babylon_draw_surfaces_colours_input_surfaces_2: 'iš paviršių',
    block_babylon_draw_surfaces_colours_input_colours: 'Spalvomis',
    block_babylon_draw_surfaces_colours_input_opacity: 'Matomumas',
    block_babylon_draw_surfaces_colours_description: 'Piešia paviršius skirtingomis spalvomis. Spalvų ir paviršių skaičius rinkiniuose turi sutapti.',
    block_base_math_remap_number_input_number_to_remap: 'Transformuoti skaičių',
    block_base_math_remap_number_input_source_interval: 'Kilmės intervalas',
    block_base_math_remap_number_input_target_interval: 'Tikslo intervalas',
    block_base_math_remap_number_description: 'Transformuoja skaičiaus vertę iš kilmės intervalo į tikslo intervalą.',
    block_verb_geometry_nurbs_curves_start_points_input_curve: 'Pradiniai kreivių taškai',
    block_verb_geometry_nurbs_curves_start_points_description: 'Gauna pradinius kreivės taškus.',
    block_verb_geometry_nurbs_curves_end_points_input_curve: 'Galiniai kreivės taškai',
    block_verb_geometry_nurbs_curves_end_points_description: 'Gauna galinius kreivės taškus.',
    block_base_io_print_save_input_text: 'Spausdinti ir išsaugoti į failą',
    block_base_io_print_save_description: 'Leidžia išspausdinti tekstą ir išsaugoti jį pasirinkto formato faile. Šis komponentas leidžia jums paruošti kodą, kuris perkeltų informaciją iš kodo į csv, gcode ar kito tipo failus.',
    block_base_io_save_input_text: 'Išsaugoti į failą',
    block_base_io_save_description: 'Išsaugo failą į pasirinktu pavadinimu ir tipu į norimą lokaciją. Šis komponentas nerodo teksto prieš išsaugant. Ši funkcija skirta didesnio dydžio tekstams.',
    block_base_io_import_text_file_input_text_file: 'Įkelti tekstinį failą',
    block_base_io_import_text_file_description: 'Įkelia failą, nuskaito turinį ir grąžina tekstą, kurį toliau galite manipuliuoti kodu.',
    block_base_time_catch_input_promise_one: 'Kai įvyksta',
    block_base_time_catch_var_error: 'klaida',
    block_base_time_catch_input_promise_two: 'išpildant pažadą',
    block_base_time_catch_statement_catch: 'Pagauti',
    block_base_time_catch_description: 'Pagauna klaidą jei tokia įvyko, kai asinchroninis kodas darė skaičiavimus.',
    block_base_time_then_input_promise_one: 'Kai grąžinamas',
    block_base_time_then_var_result: 'rezultatas',
    block_base_time_then_input_promise_two: 'išpildyto pažado',
    block_base_time_then_statement_catch: 'Tada',
    block_base_time_then_description: 'Kai sėkmingai išpildomas pažadas šis komponentas gali interpretuoti jo rezultatus.',    
    block_base_io_http_get_input_url: 'Http gavimo (get) url nuoroda',
    block_base_io_http_get_input_options: 'Nustatymai',
    block_base_io_http_get_description: 'Http gavimo (get) veiksmas su nustatymais.',
    block_base_io_http_put_input_url: 'Http dėjimo (put) url nuoroda',
    block_base_io_http_put_input_body: 'Kūnas',
    block_base_io_http_put_input_options: 'Nustatymai',
    block_base_io_http_put_description: 'Http dėjimas (put) su nustatymais.',
    block_base_io_http_patch_input_url: 'Http klijavimo (patch) url nuoroda',
    block_base_io_http_patch_input_body: 'Kūnas',
    block_base_io_http_patch_input_options: 'Nustatymai',
    block_base_io_http_patch_description: 'Http klijavimo (patch) url nuoroda.',
    block_base_io_http_post_input_url: 'Http siuntimo (post) url nuoroda',
    block_base_io_http_post_input_body: 'Kūnas',
    block_base_io_http_post_input_options: 'Nustatymai',
    block_base_io_http_post_description: 'Http siuntimas (post) su nustatymais.',
    block_base_io_http_delete_input_url: 'Http ištrynimo (delete) url nuoroda',
    block_base_io_http_delete_input_options: 'Nustatymai',
    block_base_io_http_delete_description: 'Http ištrynimas (delete) su nustatymais.',
    block_base_io_http_options_input_headers: 'Http nustatymai su antraštėm (headers)',
    block_base_io_http_options_input_params: 'Parametrais',
    block_base_io_http_options_input_with_credentials: 'Naudoti įgaliojimus',
    block_base_io_http_options_description: 'Sukuria Http nustatymus su antraštėmis, parametrais ir įgaliojimais. Visos įvestys yra neprivalomos, bet jei egzistuos ims viršenybę prieš standartines vertes.',
    block_base_io_http_header_input_name: 'Http antraštės (header) pavadinimas',
    block_base_io_http_header_input_value: 'Vertė',
    block_base_io_http_header_description: 'Sukuria Http antraštę su vardu ir verte, kuri gali būti prijungta prie rinkinio naudojamo Http nustatymų komponente.',
    block_base_io_http_param_input_name: 'Http parametro pavadinimas',
    block_base_io_http_param_input_value: 'Vertė',
    block_base_io_http_param_description: 'Sukuria Http parametrą su vardu ir verte, kuri gali būti prijungta prie rinkinio naudojamo Http nustatymų komponente.',  
    block_base_io_json_path_query_input_json: 'Nagrinėti JSON',
    block_base_io_json_path_query_input_query: 'Su užklausa',
    block_base_io_json_path_query_description: 'Gauna specifinę JSON objekto dalį pateikus "JSON Path" užklausą.',
    block_base_io_json_set_path_value_input_json: 'Diegti JSON',
    block_base_io_json_set_path_value_input_path: 'Į vietą',
    block_base_io_json_set_path_value_input_value: 'Vertę',
    block_base_io_json_set_path_value_description: 'Diegia vertę į pasirinktą JSON objekto vietą.',
    block_base_time_execute_later_input_timeout: 'Paleisti kodą po',
    block_base_time_execute_later_input_unit: 'sekundžių',
    block_base_time_execute_later_statement_then: 'Tada',
    block_base_time_execute_later_description: 'Paleidžia kodą praėjus nurodytam sekundžių skaičiui.',
    block_base_time_execute_at_interval_input_interval: 'Paleisti kodą kas',
    block_base_time_execute_at_interval_input_unit: 'sekundžių',
    block_base_time_execute_at_interval_statement_then: 'Tada',
    block_base_time_execute_at_interval_description: 'Paleisti kodą duotu sekundžių intervalu.',
    block_base_time_execute_at_interval_with_handler_input_interval: 'Paleisti kodą kas',
    block_base_time_execute_at_interval_with_handler_input_unit: 'sekundžių ir grąžinti prižiūrėtoją',
    block_base_time_execute_at_interval_with_handler_statement_then: 'Tada',
    block_base_time_execute_at_interval_with_handler_description: 'Paleisti kodą duotu sekundžių intervalu ir grąžinti intervalo prižiūrėtoją, kuris gali būti naudojamas sustabdyti intervalą.',    
    block_base_time_clear_interval_input_interval_handler: 'Sustabdyti intervalą',
    block_base_time_clear_interval_description: 'Sustabdo intervalą davus intervalo prižiūrėtojo objektą.',
    block_base_time_clear_timeout_input_timeout_handler: 'Sustabdyti atidėtą paleidimą',
    block_base_time_clear_timeout_description: 'Sustabdo atidėtą paleidimą, kuris dar neįvyko.',
    block_base_io_json_empty_object_input_json: 'Tuščias JSON objektas',
    block_base_io_json_empty_object_description: 'Sukuria ir grąžina tuščią JSON struktūros objektą.',
    block_base_io_json_preview_input_json: 'Parodyti JSON objektą',
    block_base_io_json_preview_description: 'Parodo ir leidžia išsaugoti JSON objektą.',
    block_base_io_json_set_paths_values_input_json: 'Diegti JSON',
    block_base_io_json_set_paths_values_input_paths_values: 'Vietas ir vertes',
    block_base_io_json_set_paths_values_description: 'Diegia vertes į pasirinktas JSON objekto vietas.',
    block_base_io_json_path_value_input_path: 'Vieta',
    block_base_io_json_path_value_input_value: 'JSON vertė',
    block_base_io_json_path_value_description: 'Sukuria vertės ir vietos porą, kuri gali būti naudojama kuriant ar keičiant JSON objektą.',
    block_base_geometry_text_tag_input_text: 'Teksto žyma',
    block_base_geometry_text_tag_input_position: 'Ant taško',
    block_base_geometry_text_tag_input_color: 'Spalva',
    block_base_geometry_text_tag_input_size: 'Dydis',
    block_base_geometry_text_tag_input_adapt_depth: 'Pritaikyti dydį gyliui',
    block_base_geometry_text_tag_description: 'Sukuria norimo dydžio ir spalvos teksto žymą ant pasirinkto taško.',
    block_base_geometry_draw_text_tags_input_text_tags: 'Piešiamos teksto',
    block_base_geometry_draw_text_tags_input_text_tags_variable: 'žymos',
    block_base_geometry_draw_text_tags_description: 'Piašia teksto žymų rinkinį.',
    block_base_geometry_draw_text_tag_input_text_tag: 'Piešiama teksto',
    block_base_geometry_draw_text_tag_input_text_tag_variable: 'žyma',
    block_base_geometry_draw_text_tag_description: 'Piešia vieną teksto žymą.',
    block_base_math_round_to_decimals_input_number_to_round: 'Apvalinti skaičių',
    block_base_math_round_to_decimals_input_decimal_places: 'Iki skaitmenų po kablelio',
    block_base_math_round_to_decimals_description: 'Apvalina skaičių iki norimo skaitmenų po kablelio skaičiaus.',
    block_base_math_random_input_random: 'Atsitiktinis nuo 0 iki 1',
    block_base_math_random_description: 'Sugeneruoja atsitiktinį skaičių nuo 0 iki 1',
    block_base_date_now_input_date: 'Data dabar',
    block_base_date_now_description: 'Sukuria dabartinio momento datą.',
    block_base_date_parse_input_date: 'Unix laiko žyma iš datos',
    block_base_date_parse_description: 'Paverčia datą į unix laiko žymą.',
    block_base_date_create_unix_timestamp_input_unix_timestamp: 'Data iš unix laiko žymos',
    block_base_date_create_unix_timestamp_description: 'Sukuria datą iš unix laiko žymos.',
    block_base_date_create_input_year: 'Data su metais',
    block_base_date_create_input_month: 'Mėnesiu',
    block_base_date_create_input_day: 'Diena',
    block_base_date_create_input_hour: 'Valanda',
    block_base_date_create_input_minute: 'Minutė',
    block_base_date_create_input_second: 'Sekundė',
    block_base_date_create_description: 'Sukuria datą iš metų, mėnesio, dienos, valandos, minutės ir sekundės sudedamųjų.',
    block_base_date_create_utc_input_year: 'UTC Data su metais',
    block_base_date_create_utc_input_month: 'Mėnesiu',
    block_base_date_create_utc_input_day: 'Diena',
    block_base_date_create_utc_input_hour: 'Valanda',
    block_base_date_create_utc_input_minute: 'Minutė',
    block_base_date_create_utc_input_second: 'Sekundė',
    block_base_date_create_utc_description: 'Sukuria datą iš metų, mėnesio, dienos, valandos, minutės ir sekundės sudedamųjų.',
    block_base_date_get_date_input_date: 'Diena datoje',
    block_base_date_get_date_description: 'Grąžina dieną iš datos.',
    block_base_date_get_day_input_date: 'Savaitės diena datoje',
    block_base_date_get_day_description: 'Grąžina savaitės dieną datoje.',
    block_base_date_get_full_year_input_date: 'Pilni metai datoje',
    block_base_date_get_full_year_description: 'Grąžina datos pilnus metus.',
    block_base_date_get_hours_input_date: 'Valandos datoje',
    block_base_date_get_hours_description: 'Grąžina valandas datoje.',
    block_base_date_get_milliseconds_input_date: 'Milisekundės datoje',
    block_base_date_get_milliseconds_description: 'Grąžina datos milisekundes.',
    block_base_date_get_minutes_input_date: 'Minutės datoje ',
    block_base_date_get_minutes_description: 'Grąžina datos minutes.',
    block_base_date_get_month_input_date: 'Mėnuo datoje',
    block_base_date_get_month_description: 'Grąžina mėnesį datoje.',
    block_base_date_get_seconds_input_date: 'Sekundės datoje',
    block_base_date_get_seconds_description: 'Grąžina datos sekundes.',
    block_base_date_get_time_input_date: 'Laikas datoje',
    block_base_date_get_time_description: 'Grąžina laiką datoje.',
    block_base_date_get_time_zone_offset_input_date: 'Laiko zonos skirtumas datoje',
    block_base_date_get_time_zone_offset_description: 'Gauna datos laiko zonos skirtumą.',
    block_base_date_get_year_input_date: 'Metai datoje',
    block_base_date_get_year_description: 'Grąžina datos metus.',
    block_base_date_get_utc_date_input_date: 'UTC Diena datoje',
    block_base_date_get_utc_date_description: 'Grąžina UTC dieną iš datos.',
    block_base_date_get_utc_day_input_date: 'UTC Savaitės diena datoje',
    block_base_date_get_utc_day_description: 'Grąžina utc savaitės dieną datoje.',
    block_base_date_get_utc_full_year_input_date: 'UTC pilni metai datoje',
    block_base_date_get_utc_full_year_description: 'Grąžina UTC datos pilnus metus.',
    block_base_date_get_utc_hours_input_date: 'UTC valandos datoje',
    block_base_date_get_utc_hours_description: 'Grąžina UTC valandas datoje.',
    block_base_date_get_utc_milliseconds_input_date: 'UTC milisekundės datoje',
    block_base_date_get_utc_milliseconds_description: 'Grąžina UTC datos milisekundes.',
    block_base_date_get_utc_minutes_input_date: 'UTC Minutės datoje ',
    block_base_date_get_utc_minutes_description: 'Grąžina UTC datos minutes.',
    block_base_date_get_utc_month_input_date: 'UTC Mėnuo datoje',
    block_base_date_get_utc_month_description: 'Grąžina UTC mėnesį datoje.',
    block_base_date_get_utc_seconds_input_date: 'UTC Sekundės datoje',
    block_base_date_get_utc_seconds_description: 'Grąžina UTC datos sekundes.',
    block_base_date_get_utc_year_input_date: 'UTC metai datoje',
    block_base_date_get_utc_year_description: 'Grąžina UTC datos metus.',
    block_base_date_set_date_input_date: 'Datai',
    block_base_date_set_date_input_day: 'Priskirti dieną',
    block_base_date_set_date_description: 'Priskiria dieną datai.',
    block_base_date_set_day_input_date: 'Datai',
    block_base_date_set_day_input_week_day: 'Priskirti savaitės dieną',
    block_base_date_set_day_description: 'Priskiria savaitės dieną datai.',
    block_base_date_set_full_year_input_date: 'Datai',
    block_base_date_set_full_year_input_full_year: 'Priskirti pilnus metus',
    block_base_date_set_full_year_description: 'Priskiria pilnus metus datai.',
    block_base_date_set_hours_input_date: 'Datai',
    block_base_date_set_hours_input_hours: 'Priskirti valandas',
    block_base_date_set_hours_description: 'Priskiria valandas datai.',
    block_base_date_set_milliseconds_input_date: 'Datai',
    block_base_date_set_milliseconds_input_milliseconds: 'Priskirti milisekundes',
    block_base_date_set_milliseconds_description: 'Priskiria milisekundes datai.',
    block_base_date_set_minutes_input_date: 'Datai',
    block_base_date_set_minutes_input_minutes: 'Priskirti minutes',
    block_base_date_set_minutes_description: 'Priskiria minutes datai.',
    block_base_date_set_month_input_date: 'Datai',
    block_base_date_set_month_input_month: 'Priskirti mėnesį',
    block_base_date_set_month_description: 'Priskiria mėnesį datai.',
    block_base_date_set_seconds_input_date: 'Datai',
    block_base_date_set_seconds_input_seconds: 'Priskirti sekundes',
    block_base_date_set_seconds_description: 'Priskiria sekundes datai.',
    block_base_date_set_time_input_date: 'Datai',
    block_base_date_set_time_input_time: 'Priskirti laiką',
    block_base_date_set_time_description: 'Priskiria laiką datai.',
    block_base_date_set_year_input_date: 'Datai',
    block_base_date_set_year_input_year: 'Priskirti metus',
    block_base_date_set_year_description: 'Priskiria metus datai.',
    block_base_date_set_utc_date_input_date: 'UTC Datai',
    block_base_date_set_utc_date_input_day: 'Priskirti dieną',
    block_base_date_set_utc_date_description: 'Priskiria dieną UTC datai.',
    block_base_date_set_utc_day_input_date: 'UTC Datai',
    block_base_date_set_utc_day_input_week_day: 'Priskirti savaitės dieną',
    block_base_date_set_utc_day_description: 'Priskiria savaitės dieną UTC datai.',
    block_base_date_set_utc_full_year_input_date: 'UTC Datai',
    block_base_date_set_utc_full_year_input_full_year: 'Priskirti pilnus metus',
    block_base_date_set_utc_full_year_description: 'Priskiria pilnus metus UTC datai.',
    block_base_date_set_utc_hours_input_date: 'UTC Datai',
    block_base_date_set_utc_hours_input_hours: 'Priskirti valandas',
    block_base_date_set_utc_hours_description: 'Priskiria valandas UTC datai.',
    block_base_date_set_utc_milliseconds_input_date: 'UTC Datai',
    block_base_date_set_utc_milliseconds_input_milliseconds: 'Priskirti milisekundes',
    block_base_date_set_utc_milliseconds_description: 'Priskiria milisekundes UTC datai.',
    block_base_date_set_utc_minutes_input_date: 'UTC Datai',
    block_base_date_set_utc_minutes_input_minutes: 'Priskirti minutes',
    block_base_date_set_utc_minutes_description: 'Priskiria minutes UTC datai.',
    block_base_date_set_utc_month_input_date: 'UTC Datai',
    block_base_date_set_utc_month_input_month: 'Priskirti mėnesį',
    block_base_date_set_utc_month_description: 'Priskiria mėnesį UTC datai.',
    block_base_date_set_utc_seconds_input_date: 'UTC Datai',
    block_base_date_set_utc_seconds_input_seconds: 'Priskirti sekundes',
    block_base_date_set_utc_seconds_description: 'Priskiria sekundes UTC datai.',
    block_base_date_set_utc_time_input_date: 'UTC Datai',
    block_base_date_set_utc_time_input_time: 'Priskirti laiką',
    block_base_date_set_utc_time_description: 'Priskiria laiką UTC datai.',
    block_base_date_set_utc_year_input_date: 'UTC Datai',
    block_base_date_set_utc_year_input_year: 'Priskirti metus',
    block_base_date_set_utc_year_description: 'Priskiria metus UTC datai.',
    block_base_date_convert_to_string_input_date: 'Tekstas iš datos',
    block_base_date_convert_to_string_description: 'Konvertuoja datą į tekstą - Pvz. "Wed Jul 28 1993 14:39:07 GMT+0200 (CEST)"',
    block_base_date_convert_to_iso_string_input_date: 'ISO tekstas iš datos',
    block_base_date_convert_to_iso_string_description: 'Konvertuoja datą į ISO tekstą - Pvz. "2011-10-05T14:48:00.000Z"',
    block_base_date_convert_to_utc_string_input_date: 'UTC tekstas iš datos',
    block_base_date_convert_to_utc_string_description: 'Konvertuoja datą į UTC tekstą - Pvz. "Wed, 14 Jun 2017 07:00:00 GMT"',
    block_base_date_convert_to_date_string_input_date: 'Datos tekstas iš datos',
    block_base_date_convert_to_date_string_description: 'Konvertuoja datą į datos tekstą - Pvz. "Wed Jul 28 1993"',
    block_base_date_convert_to_time_string_input_date: 'Laiko tekstas iš datos',
    block_base_date_convert_to_time_string_description: 'Konvertuoja datą į laiko tekstą - Pvz. "23:15:30 GMT+0200 (CEST)"',
    block_base_date_convert_to_json_input_date: 'JSON iš datos',
    block_base_date_convert_to_json_description: 'Konvertuoja datą į JSON objektą.',
    block_base_math_modulus_input_number: 'Skaičiaus',
    block_base_math_modulus_input_modulus: 'Modulis',
    block_base_math_modulus_description: 'Suskaičiuoja skaičiaus modulį.',
    block_base_clear_all_drawn_input_clear_all_drawn: 'Išvalyti pieštus objektus',
    block_base_clear_all_drawn_description: 'Išvalo pieštus objektus ir atlaisvina atmintį.',
    block_babylon_mesh_create_polygon_from_points_input_shape: 'Poligonas iš figūros taškų',
    block_babylon_mesh_create_polygon_from_points_input_holes: 'Ir kiaurymių',
    block_babylon_mesh_create_polygon_from_points_description: 'Sukuria poligoną iš figūros taškų ir skylių.',
    block_babylon_node_from_rotation_input_origin: 'Koordinačių sistema ant taško',
    block_babylon_node_from_rotation_input_rotation: 'Rotacija',
    block_babylon_node_from_rotation_input_parent: 'Koordinačių sistemoje',
    block_babylon_node_from_rotation_description: 'Sukuria koordinačių sistemą globalioje arba kamieninėje koordinačių sistemoje.',
    block_babylon_node_world_input_world: 'Nauja koordinačių sistema',
    block_babylon_node_world_description: 'Sukuria naują koordinačių sistemą pagrįstą pasaulio nulinėmis koordinatėmis.',
    block_babylon_node_get_root_input_root: 'Pasaulio koordinačių sistema',
    block_babylon_node_get_root_description: 'Grąžina bazinę pasaulio koordinačių sistemą.',
    block_babylon_node_get_rotation_quaternion_input_node: 'Rotacijos kvaternijonas iš koordinačių sistemos',
    block_babylon_node_get_rotation_quaternion_description: 'Grąžina koordinačių sistemos rotacijos kvaternijoną.',
    block_babylon_node_get_rotation_input_node: 'Rotacijos vektorius iš koordinačių sistemos',
    block_babylon_node_get_rotation_description: 'Grąžina koordinačių sistemos rotacijos vektorių aplink x, y ir z ašis.',
    block_babylon_node_get_absolute_position_input_node: 'Absoliuti pozicija iš koordinačių sistemos',
    block_babylon_node_get_absolute_position_description: 'Grąžina absoliutų koordinačių sistemos pradžios taška.',
    block_babylon_node_get_position_expressed_in_local_space_input_node: 'Ppozicija lokalioje erdvėje iš koord. sistemos',
    block_babylon_node_get_position_expressed_in_local_space_description: 'Grąžina koordinačių sistemos pozicijos taška išreikštą lokalioje erdvėje.',
    block_babylon_node_get_absolute_rotation_quaternion_input_node: 'Absoliutus rotacijos kvaternijonas iš koord. sistemos',
    block_babylon_node_get_absolute_rotation_quaternion_description: 'Grąžina koordinačių sistemos abosliutų rotacijos kvaternijoną.',
    block_babylon_node_get_absolute_up_vector_input_node: 'Absoliutus viršaus (y) vektorius iš koord. sistemos',
    block_babylon_node_get_absolute_up_vector_description: 'Grąžina absoliutų viršaus (y) ašies vektorių iš koordinačių sistemos.',
    block_babylon_node_get_absolute_right_vector_input_node: 'Absoliutus dešinės (x) vektorius iš koord. sistemos',
    block_babylon_node_get_absolute_right_vector_description: 'Grąžina absoliutų dešinės (x) ašies vektorių iš koordinačių sistemos.',
    block_babylon_node_get_absolute_forward_vector_input_node: 'Absoliutus priekio (z) vektorius iš koord. sistemos',
    block_babylon_node_get_absolute_forward_vector_description: 'Grąžina absoliutų priekio (z) ašies vektorių iš koordinačių sistemos.',
    block_babylon_node_rotate_input_node: 'Sukti koordinačių sistemą',
    block_babylon_node_rotate_input_axis: 'Aplink ašį',
    block_babylon_node_rotate_input_amount: 'Kampu',
    block_babylon_node_rotate_description: 'Suka koordinačių sistemą aplink ašį kampu.',
    block_babylon_node_rotate_around_input_node: 'Sukti koordinačių sistemą',
    block_babylon_node_rotate_around_position: 'Aplink poziciją',
    block_babylon_node_rotate_around_input_axis: 'Ir ašį',
    block_babylon_node_rotate_around_input_amount: 'Kampu',
    block_babylon_node_rotate_around_description: 'Suka koordinačių sistemą aplink duotą tašką ir ašį kampu.',
    block_babylon_node_set_absolute_position_input_node: 'Koordinačių sistemai',
    block_babylon_node_set_absolute_position_input_position: 'Priskirti absoliučią poziciją',
    block_babylon_node_set_absolute_position_description: 'Priskiria absoliučią poziciją koordinačių sistemai pasaulio atžvilgiu.',
    block_babylon_node_set_direction_input_node: 'Koordinačių sistemai',
    block_babylon_node_set_direction_input_direction: 'Priskirti kryptį',
    block_babylon_node_set_direction_description: 'Priskiria lokalios krypties vektorių koordinačių sistemai.',
    block_babylon_node_set_parent_input_node: 'Koordinačių sistemai',
    block_babylon_node_set_parent_input_parent_node: 'Priskirti bazinę koordinačių sistemą',
    block_babylon_node_set_parent_description: 'Įvaikina koordinačių sistemą kitos sistemos atžvilgiu.',
    block_babylon_node_translate_input_node: 'Paslinkti koordinačių sistemą',
    block_babylon_node_translate_input_direction: 'Kryptimi',
    block_babylon_node_translate_input_distance: 'Ir atstumu',
    block_babylon_node_translate_description: 'Paslenka koordinačių sistemą nurodyta kryptimi ir duotu atstumu.',
    block_babylon_node_get_parent_input_node: 'Koordinačių sistemos tėvas',
    block_babylon_node_get_parent_description: 'Grąžina tėvinę koordinačių sistemą duotai koordinačių sistemai.',
    block_babylon_node_get_children_input_node: 'Koordinačių sistemos vaikai',
    block_babylon_node_get_children_description: 'Grąžina visus koordinačių sistemos vaikus',
    block_csg_primitive_2d_rectangle_input_center: 'Stačiakampis poligonas ant centrinio taško',
    block_csg_primitive_2d_rectangle_input_width: 'Plotis',
    block_csg_primitive_2d_rectangle_input_length: 'Ilgis',
    block_csg_primitive_2d_rectangle_description: 'Sukuria nurodyto dydžio stačiakampį ant centinio taško.',
    block_csg_extrude_linear_polygon_input_polygon: 'Linijinis iškėlimas iš poligono',
    block_csg_extrude_linear_polygon_input_height: 'Aukštis',
    block_csg_extrude_linear_polygon_input_twist_angle: 'Sukimosi kampas',
    block_csg_extrude_linear_polygon_input_twist_steps: 'Sukimosi žingsniai',
    block_csg_extrude_linear_polygon_description: 'Iškelia poligoną linijiniu būdu į trimatį kūną.',
    block_csg_extrude_linear_polygon_objects_input_polygons: 'Linijinis iškėlimas iš poligonų',
    block_csg_extrude_linear_polygon_objects_input_height: 'Aukštis',
    block_csg_extrude_linear_polygon_objects_input_twist_angle: 'Sukimosi kampas',
    block_csg_extrude_linear_polygon_objects_input_twist_steps: 'Sukimosi žingsniai',
    block_csg_extrude_linear_polygon_objects_description: 'Iškelia poligonus linijiniu būdu į trimačius kūnus.',
    block_csg_primitive_2d_polygon_input_points: 'Poligonas iš taškų',
    block_csg_primitive_2d_polygon_description: 'Sukuria poligoną iš 2D taškų rinkinio.',
    block_csg_transform_input_csg_mesh: 'Transformuoti kūną',
    block_csg_transform_input_transformation: 'Transformacija',
    block_csg_transform_description: 'Transformuoja kūną su duota transformacija.',
    block_csg_sphere_input_center: 'Sferos kūnas ant centrinio taško',
    block_csg_sphere_input_radius: 'Radiusas',
    block_csg_sphere_input_segments: 'Segmentai',
    block_csg_sphere_description: 'Sukuria sferos kūną ant duoto taško, radiuso. Rezoliucija kontroliuoja sferos sudalinimą (kuo daugiau, tuo lėtesni bus skaičiavimai).',
    block_csg_cube_input_center: 'Kubas ant centrinio taško',
    block_csg_cube_input_size: 'Dydis',
    block_csg_cube_description: 'Sukuria nurodyto dydžio kubą ant duoto taško.',
    block_csg_subtract_input_subtract_object: 'Atimti kūną',
    block_csg_subtract_input_subtract_from_object: 'Iš kūno',
    block_csg_subtract_description: 'Atima kūną iš kūno ir grąžiną likutį',
    block_csg_union_input_union_object: 'Sujungti kūną',
    block_csg_union_input_with_object: 'Su kūnu',
    block_csg_union_description: 'Sujungia du kūnus į vieną.',
    block_csg_intersect_input_intersect_object: 'Sukirsti kūną',
    block_csg_intersect_input_with_object: 'Su kūnu',
    block_csg_intersect_description: 'Sukerta du kūnus ir grąžina naują kūną.',
    block_csg_color_input_color: 'Priskirti spalvą',
    block_csg_color_input_object: 'Kūnui',
    block_csg_color_description: 'Priskiria spalvą kūnui.',
    block_csg_cuboid_input_center: 'Stačiakampis gretasienis ant centrinio taško',
    block_csg_cuboid_input_width: 'Plotis',
    block_csg_cuboid_input_length: 'Ilgis',
    block_csg_cuboid_input_height: 'Aukštis',
    block_csg_cuboid_description: 'Sukuria duoto dydžio stačiakampį gretasienį ant centrinio taško.',
    block_csg_union_objects_input_objects: 'Sujungti kūnus',
    block_csg_union_objects_description: 'Sujungia kūnų rinkinį į vieną kūną.',
    block_csg_subtract_objects_input_objects: 'Atimti kūnus',
    block_csg_subtract_objects_description: 'Atima kūnų rinkinį.',
    block_csg_intersect_objects_input_objects: 'Sukirsti kūnus',
    block_csg_intersect_objects_description: 'Sukerta kūnus ',
    block_csg_extrude_rectangular_points_input_points: 'Kvadratinis kelio taškų iškėlimas',
    block_csg_extrude_rectangular_points_input_height: 'Aukštis',
    block_csg_extrude_rectangular_points_input_size: 'Plotis',
    block_csg_extrude_rectangular_points_description: 'Sukuria kvadratinį kelio taškų iškėlimą į viršų.',
    block_csg_extrude_rectangular_path_input_path: 'Kvadratinis XZ kelio iškėlimas',
    block_csg_extrude_rectangular_path_input_height: 'Aukštis',
    block_csg_extrude_rectangular_path_input_size: 'Plotis',
    block_csg_extrude_rectangular_path_description: 'Sukuria kvadratinį XZ kelio iškėlimą į viršų.',
    block_csg_extrude_rectangular_paths_input_paths: 'Kvadratinis XZ kelių rinkinio iškėlimas',
    block_csg_extrude_rectangular_paths_input_height: 'Aikštis',
    block_csg_extrude_rectangular_paths_input_size: 'Plotis',
    block_csg_extrude_rectangular_paths_description: 'Sukuria kvadratinį XZ kelių rinkinio iškėlima į viršų.',
    block_csg_primitive_2d_path_from_points_input_points: 'Kelias iš XZ taškų',
    block_csg_primitive_2d_path_from_points_input_closed: 'Uždaras',
    block_csg_primitive_2d_path_from_points_description: 'Sukuria XZ kelią iš duotų taškų rinkinio.',
    block_csg_primitive_2d_path_close_input_close: 'Uždaryti XZ kelią',
    block_csg_primitive_2d_path_close_description: 'Uždaro XZ kelią sujungiant segmentu paskutinį tašką su pirmu.',
    block_csg_primitive_2d_path_append_points_input_path: 'Pratęsti kelią',
    block_csg_primitive_2d_path_append_points_input_points: 'Su taškais',
    block_csg_primitive_2d_path_append_points_description: 'Pratęsia kelią taškų rinkiniu.',
    block_csg_primitive_2d_path_append_arc_input_path: 'Pratęsti arka kelią',
    block_csg_primitive_2d_path_append_arc_input_end_point: 'Su XZ galiniu tašku',
    block_csg_primitive_2d_path_append_arc_input_radius_x: 'X spindulys',
    block_csg_primitive_2d_path_append_arc_input_radius_z: 'Z spindulys',
    block_csg_primitive_2d_path_append_arc_input_x_axis_rotation: 'X ašies rotacija',
    block_csg_primitive_2d_path_append_arc_input_clockwise: 'Pagal laikrodžio rodyklę',
    block_csg_primitive_2d_path_append_arc_input_large: 'Didelis',
    block_csg_primitive_2d_path_append_arc_input_segments: 'Segmentų skaičius',
    block_csg_primitive_2d_path_append_arc_description: 'Pratęsia kelią arka į duotą tašką laikantis nurodytų parametrų.',
    block_csg_primitive_2d_path_append_polyline_input_path: 'Pratęsti kelią',
    block_csg_primitive_2d_path_append_polyline_input_polyline: 'Su polilinija',
    block_csg_primitive_2d_path_append_polyline_description: 'Pratęsia kelią su polilinija.',
    block_csg_primitive_2d_path_append_curve_input_path: 'Pratęsti kelią',
    block_csg_primitive_2d_path_append_curve_input_curve: 'Su kreive',
    block_csg_primitive_2d_path_append_curve_description: 'Pratęsia kelią su kreive konvertuojant ją į taškus.',
    block_csg_primitive_2d_path_empty_input_path: 'Tuščias kelias',
    block_csg_primitive_2d_path_empty_description: 'Sukuria tuščią kelią, kurį galima pratęsti.',
    block_csg_primitive_2d_path_from_polyline_input_polyline: 'Kelias iš XZ polilinijos',
    block_csg_primitive_2d_path_from_polyline_input_closed: 'Uždaras',
    block_csg_primitive_2d_path_from_polyline_description: 'Sukuria kelią iš polilinijos.',
    block_csg_primitive_2d_path_from_curve_input_curve: 'Kelias iš XZ kreivės',
    block_csg_primitive_2d_path_from_curve_input_closed: 'Uždaras',
    block_csg_primitive_2d_path_from_curve_description: 'Sukuria kelią iš kreivės.'
});
