import { createPrimitive2dPolygonBlock } from './primitive-2d-polygon';
import { createExtrudeLinearPolygonBlock } from './extrude-linear-polygon';
import { createExtrudeLinearPolygonObjectsBlock } from './extrude-linear-polygon-objects';
import { createPrimitive2dRectangleBlock } from './primitive-2d-rectangle';
import { createCsgTransformBlock } from './csg-transform';
import { createPrimitiveSphereBlock } from './primitive-sphere';
import { createPrimitiveCubeBlock } from './primitive-cube';
import { createBooleanSubtractBlock } from './boolean-subtract';
import { createBooleanUnionBlock } from './boolean-union';
import { createBooleanIntersectBlock } from './boolean-intersect';
import { createCsgColourBlock } from './csg-colour';
import { createPrimitiveCuboidBlock } from './primitive-cuboid';
import { createBooleanIntersectObjectsBlock } from './boolean-intersect-objects';
import { createBooleanUnionObjectsBlock } from './boolean-union-objects';
import { createBooleanSubtractObjectsBlock } from './boolean-subtract-objects';
import { createExtrudeRectangularPointsBlock } from './extrude-rectanglar-points';
import { createPrimitive2dPathFromPointsBlock } from './primitive-2d-path-from-points';
import { createExtrudeRectangularPathBlock } from './extrude-rectanglar-path';
import { createPrimitive2dPathCloseBlock } from './primitive-2d-path-close';
import { createPrimitive2dPathAppendPointsBlock } from './primitive-2d-path-append-points';
import { createPrimitive2dPathAppendArcBlock } from './primitive-2d-path-append-arc';
import { createPrimitive2dPathAppendPolylineBlock } from './primitive-2d-path-append-polyline';
import { createPrimitive2dPathAppendCurveBlock } from './primitive-2d-path-append-curve';

export function assembleCsgBlocks(): void {
    createPrimitive2dPolygonBlock();
    createPrimitive2dRectangleBlock();
    createPrimitive2dPathFromPointsBlock();
    createExtrudeLinearPolygonBlock();
    createExtrudeLinearPolygonObjectsBlock();
    createExtrudeRectangularPointsBlock();
    createExtrudeRectangularPathBlock();
    createPrimitiveSphereBlock();
    createPrimitiveCubeBlock();
    createBooleanSubtractBlock();
    createBooleanSubtractObjectsBlock();
    createBooleanUnionBlock();
    createBooleanUnionObjectsBlock();
    createBooleanIntersectBlock();
    createBooleanIntersectObjectsBlock();
    createCsgTransformBlock();
    createCsgColourBlock();
    createPrimitiveCuboidBlock();
    createPrimitive2dPathCloseBlock();
    createPrimitive2dPathAppendPointsBlock();
    createPrimitive2dPathAppendArcBlock();
    createPrimitive2dPathAppendPolylineBlock();
    createPrimitive2dPathAppendCurveBlock();
}
