// GENERATED by scripts/gen-worker-api.mjs from packages/dev/occt/lib/services/geom/geom.ts - do not edit.
// The kernel class is the source of the docs, the signatures and the member order.
// Regenerate with `npm run gen:worker-api` at the repository root.
import { OCCTWorkerManager } from "../../../occ-worker/occ-worker-manager";
import { OCCTCurves } from "./curves";
import { OCCTSurfaces } from "./surfaces";

/**
 * The geometric layer beneath the topology: the mathematical curves and surfaces themselves,
 * separate from the edges and faces that carry them. Use it when you need to evaluate a curve at a
 * parameter, ask a surface for its normal, or build geometry that has no topological wrapper yet.
 */
export class OCCTGeom {
    public readonly curves: OCCTCurves;
    public readonly surfaces: OCCTSurfaces;

    constructor(
        occWorkerManager: OCCTWorkerManager
    ) {
        this.curves = new OCCTCurves(occWorkerManager);
        this.surfaces = new OCCTSurfaces(occWorkerManager);
    }
}
