import { createChamferEdgesBlock } from './shapes-edge-chamfer-edges';
import { createBooleanDifferenceBlock } from './booleans-difference';
import { createDrawShapeBlock } from './draw-shape';
import { createExtrudeBlock } from './operations-extrude';
import { createFacesCreateCircleBlock } from './shapes-face-create-circle-face';
import { createFilletEdgesBlock } from './shapes-edge-fillet-edges';
import { createLoftBlock } from './operations-loft';
import { createOffsetBlock } from './operations-offset';
import { createRevolveBlock } from './operations-revolve';
import { createBoxBlock } from './shapes-solid-create-box';
import { createConeBlock } from './shapes-solid-create-cone';
import { createCylinderBlock } from './shapes-solid-create-cylinder';
import { createSphereBlock } from './shapes-solid-create-sphere';
import { createBooleanUnionBlock } from './booleans-union';
import { createWiresCreateBezierBlock } from './shapes-wire-create-bezier';
import { createWiresCreateBSplineBlock } from './shapes-wire-create-bspline';
import { createWiresCreateCircleBlock } from './shapes-wire-create-circle';
import { createBooleanIntersectionBlock } from './booleans-intersection';
import { createWiresCreatePolygonBlock } from './shapes-wire-create-polygon';
import { createFacesCreatePolygonBlock } from './shapes-face-create-polygon';
import { createTransformRotateBlock } from './transforms-rotate';
import { createTransformScaleBlock } from './transforms-scale';
import { createTransformTranslateBlock } from './transforms-translate';
import { createTransformTransformBlock } from './transforms-transform';
import { createRotatedExtrudeBlock } from './operations-rotated-extrude';
import { createPipeBlock } from './operations-pipe';
import { createFacesGetFaceBlock } from './shapes-face-get-face';
import { createEdgesGetEdgeBlock } from './shapes-edge-get-edge';
import { createWiresGetWireBlock } from './shapes-wire-get-wire';
import { createIOShapeToStepFileBlock } from './io-shape-to-step-file';
import { createIOImportStepOrIgesFileBlock } from './io-import-step-or-iges-file';
import { createCompoundMakeCompoundBlock } from './shapes-compound-make-compound';
import { createSolidMakeThickSolidSimpleBlock } from './operations-make-thick-solid-simple';
import { createFacesCreateFaceFromWireBlock } from './shapes-face-create-face-from-wire';
import { createDrawShapeMeshBlock } from './draw-shape-mesh';

export function assembleOCCTBlocks(): void {
    createBoxBlock();
    createDrawShapeBlock();
    createDrawShapeMeshBlock();
    createSphereBlock();
    createConeBlock();
    createCylinderBlock();
    createWiresCreateBSplineBlock();
    createWiresCreateBezierBlock();
    createWiresCreateCircleBlock();
    createOffsetBlock();
    createExtrudeBlock();
    createLoftBlock();
    createRevolveBlock();
    createFilletEdgesBlock();
    createChamferEdgesBlock();
    createBooleanUnionBlock();
    createBooleanDifferenceBlock();
    createBooleanIntersectionBlock();
    createWiresCreatePolygonBlock();
    createFacesCreateCircleBlock();
    createFacesGetFaceBlock();
    createFacesCreateFaceFromWireBlock();
    createFacesCreatePolygonBlock();
    createTransformRotateBlock();
    createTransformScaleBlock();
    createTransformTranslateBlock();
    createTransformTransformBlock();
    createRotatedExtrudeBlock();
    createPipeBlock();
    createEdgesGetEdgeBlock();
    createWiresGetWireBlock();
    createIOShapeToStepFileBlock();
    createIOImportStepOrIgesFileBlock();
    createCompoundMakeCompoundBlock();
    createSolidMakeThickSolidSimpleBlock();
}
