import { createCoreVector3Block } from './core-vector';
import { createCoreVectorAddBlock } from './core-vector-add';
import { createCoreVectorAddAllBlock } from './core-vector-add-all';
import { createCoreVectorAllBlock } from './core-vector-all';
import { createCoreVectorAngleBetweenBlock } from './core-vector-angle-between';
import { createCoreVectorAngleBetweenNormalized2dBlock } from './core-vector-angle-between-normalized-2d';
import { createCoreVectorCrossBlock } from './core-vector-cross';
import { createCoreVectorDistanceBlock } from './core-vector-distance';
import { createCoreVectorDistanceSquaredBlock } from './core-vector-distance-squared';
import { createCoreVectorDivBlock } from './core-vector-div';
import { createCoreVectorDomainBlock } from './core-vector-domain';
import { createCoreVectorDotBlock } from './core-vector-dot';
import { createCoreVectorFiniteBlock } from './core-vector-finite';
import { createCoreVectorIsZeroBlock } from './core-vector-is-zero';
import { createCoreVectorLerpBlock } from './core-vector-lerp';
import { createCoreVectorMaxBlock } from './core-vector-max';
import { createCoreVectorMinBlock } from './core-vector-min';
import { createCoreVectorMulBlock } from './core-vector-mul';
import { createCoreVectorNegateBlock } from './core-vector-negate';
import { createCoreVectorNormBlock } from './core-vector-norm';
import { createCoreVectorNormSquaredBlock } from './core-vector-norm-squared';
import { createCoreVectorNormalizedBlock } from './core-vector-normalized';
import { createCoreVectorOnRayBlock } from './core-vector-on-ray';
import { createCoreVectorPositiveAngleBetweenBlock } from './core-vector-positive-angle-between';
import { createCoreVectorRangeBlock } from './core-vector-range';
import { createCoreVectorSignedAngleBetweenBlock } from './core-vector-signed-angle-between';
import { createCoreVectorSpanBlock } from './core-vector-span';
import { createCoreVectorSubBlock } from './core-vector-sub';
import { createCoreVectorSumBlock } from './core-vector-sum';

export function assembleVectorBlocks() {
    createCoreVector3Block();
    createCoreVectorAngleBetweenBlock();
    createCoreVectorAngleBetweenNormalized2dBlock();
    createCoreVectorDistanceBlock();
    createCoreVectorDomainBlock();
    createCoreVectorMaxBlock();
    createCoreVectorMinBlock();
    createCoreVectorNegateBlock();
    createCoreVectorPositiveAngleBetweenBlock();
    createCoreVectorRangeBlock();
    createCoreVectorSignedAngleBetweenBlock();
    createCoreVectorSpanBlock();
    createCoreVectorAllBlock();
    createCoreVectorFiniteBlock();
    createCoreVectorSumBlock();
    createCoreVectorNormalizedBlock();
    createCoreVectorCrossBlock();
    createCoreVectorOnRayBlock();
    createCoreVectorLerpBlock();
    createCoreVectorDistanceSquaredBlock();
    createCoreVectorAddBlock();
    createCoreVectorAddAllBlock();
    createCoreVectorDivBlock();
    createCoreVectorDotBlock();
    createCoreVectorIsZeroBlock();
    createCoreVectorMulBlock();
    createCoreVectorNormBlock();
    createCoreVectorNormSquaredBlock();
    createCoreVectorSubBlock();
}
