// GENERATED by scripts/gen-dto-meta.mjs from the inputs DTOs - do not edit; regenerate with `npm run gen:dto-meta`.
/* eslint-disable @typescript-eslint/no-namespace */
import { WithDefaults } from "@bitbybit-dev/base";
import * as Inputs from "../inputs";
export type { Asset, CSV, JSON, JSCAD, Manifold, OCCT, Tag, Time, Verb, Color, Dates, Frame, IO, Line, Lists, Logic, Math, Mesh, Point, Polyline, Text, Transforms, Vector } from "@bitbybit-dev/core/lib/api/resolved-inputs";

/**
 * The Draw inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace Draw {
    export type DrawAny<U, E extends Inputs.Draw.Entity = Inputs.Draw.Entity> = Inputs.Draw.DrawAny<U, E>;
    export type DrawBasicGeometryOptions = WithDefaults<Inputs.Draw.DrawBasicGeometryOptions, "colours" | "colorMapStrategy" | "size" | "opacity" | "updatable" | "hidden" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity" | "arrowSize" | "arrowAngle">;
    export type DrawFrameOptions = WithDefaults<Inputs.Draw.DrawFrameOptions, "size" | "colorX" | "colorY" | "colorZ" | "drawPlane" | "colorPlane" | "lineWidth" | "updatable">;
    export type DrawManifoldOrCrossSectionOptions = WithDefaults<Inputs.Draw.DrawManifoldOrCrossSectionOptions, "faceOpacity" | "faceColour" | "crossSectionColour" | "crossSectionWidth" | "crossSectionOpacity" | "computeNormals" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity">;
    export type DrawOcctShapeOptions = WithDefaults<Inputs.Draw.DrawOcctShapeOptions, "faceOpacity" | "edgeOpacity" | "edgeColour" | "faceColour" | "vertexColour" | "edgeWidth" | "vertexSize" | "drawEdges" | "drawFaces" | "drawVertices" | "precision" | "angularDeflection" | "relativeDeflection" | "drawEdgeIndexes" | "edgeIndexHeight" | "edgeIndexColour" | "drawFaceIndexes" | "faceIndexHeight" | "faceIndexColour" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity" | "edgeArrowSize" | "edgeArrowAngle" | "keepMeshData" | "allowQualityDecrease" | "forceFaceDeflection" | "drawIsoCurves" | "isoCurvesU" | "isoCurvesV" | "isoCurvesColour" | "surfaceAnalysis" | "draftDirection">;
    export type GenericPBRMaterialDto = WithDefaults<Inputs.Draw.GenericPBRMaterialDto, "name" | "baseColor" | "metallic" | "roughness" | "alpha" | "emissiveColor" | "emissiveIntensity" | "zOffset" | "zOffsetUnits" | "alphaMode" | "alphaCutoff" | "doubleSided" | "wireframe" | "unlit">;
    export type GenericTextureDto = WithDefaults<Inputs.Draw.GenericTextureDto, "name" | "uScale" | "vScale" | "uOffset" | "vOffset" | "wAng" | "invertY" | "invertZ" | "samplingMode">;
}

/**
 * The ThreeJSCamera inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace ThreeJSCamera {
    export type CameraDto = Inputs.ThreeJSCamera.CameraDto;
    export type FocusObjectDto = WithDefaults<Inputs.ThreeJSCamera.FocusObjectDto, "padding">;
    export type OrbitCameraControllerDto = Inputs.ThreeJSCamera.OrbitCameraControllerDto;
    export type OrbitCameraDto = WithDefaults<Inputs.ThreeJSCamera.OrbitCameraDto, "pivotPoint" | "distance" | "pitch" | "yaw" | "distanceMin" | "distanceMax" | "pitchAngleMin" | "pitchAngleMax" | "orbitSensitivity" | "distanceSensitivity" | "panSensitivity" | "inertiaFactor" | "autoRender" | "frameOnStart" | "enableDamping" | "dampingFactor">;
    export type PivotPointDto = WithDefaults<Inputs.ThreeJSCamera.PivotPointDto, "pivotPoint">;
    export type PositionDto = WithDefaults<Inputs.ThreeJSCamera.PositionDto, "position">;
    export type ResetCameraDto = WithDefaults<Inputs.ThreeJSCamera.ResetCameraDto, "yaw" | "pitch" | "distance">;
    export type SetDistanceLimitsDto = WithDefaults<Inputs.ThreeJSCamera.SetDistanceLimitsDto, "min" | "max">;
    export type SetPitchLimitsDto = WithDefaults<Inputs.ThreeJSCamera.SetPitchLimitsDto, "min" | "max">;
}

/**
 * The ThreeJSScene inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace ThreeJSScene {
    export type InitThreeJSDto = WithDefaults<Inputs.ThreeJSScene.InitThreeJSDto, "sceneSize" | "backgroundColor" | "enableShadows" | "enableGround" | "groundCenter" | "groundScaleFactor" | "groundColor" | "groundOpacity" | "hemisphereLightSkyColor" | "hemisphereLightGroundColor" | "hemisphereLightIntensity" | "directionalLightColor" | "directionalLightIntensity" | "shadowMapSize" | "enableOrbitCamera">;
}
