// GENERATED by scripts/gen-dto-meta.mjs from the inputs DTOs - do not edit.
// Regenerate with `npm run gen:dto-meta` at the repository root.
/* eslint-disable @typescript-eslint/no-namespace */
import { WithDefaults } from "@bitbybit-dev/base";
import * as Inputs from "../inputs";
export type { Asset, CSV, JSON, JSCAD, Manifold, OCCT, Tag, Time, Verb, Color, Dates, IO, Line, Lists, Logic, Math, Mesh, Point, Polyline, Text, Transforms, Vector } from "@bitbybit-dev/core/lib/api/resolved-inputs";

/**
 * The Draw inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace Draw {
    export type DrawAny<U, E extends Inputs.Draw.Entity = Inputs.Draw.Entity> = Inputs.Draw.DrawAny<U, E>;
    export type DrawBasicGeometryOptions = WithDefaults<Inputs.Draw.DrawBasicGeometryOptions, "colours" | "colorMapStrategy" | "size" | "opacity" | "updatable" | "hidden" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity" | "arrowSize" | "arrowAngle">;
    export type DrawManifoldOrCrossSectionOptions = WithDefaults<Inputs.Draw.DrawManifoldOrCrossSectionOptions, "faceOpacity" | "faceColour" | "crossSectionColour" | "crossSectionWidth" | "crossSectionOpacity" | "computeNormals" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity">;
    export type DrawOcctShapeOptions = WithDefaults<Inputs.Draw.DrawOcctShapeOptions, "faceOpacity" | "edgeOpacity" | "edgeColour" | "faceColour" | "vertexColour" | "edgeWidth" | "vertexSize" | "drawEdges" | "drawFaces" | "drawVertices" | "precision" | "drawEdgeIndexes" | "edgeIndexHeight" | "edgeIndexColour" | "drawFaceIndexes" | "faceIndexHeight" | "faceIndexColour" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity" | "edgeArrowSize" | "edgeArrowAngle" | "keepMeshData" | "allowQualityDecrease" | "forceFaceDeflection">;
    export type GenericPBRMaterialDto = WithDefaults<Inputs.Draw.GenericPBRMaterialDto, "name" | "baseColor" | "metallic" | "roughness" | "alpha" | "emissiveColor" | "emissiveIntensity" | "zOffset" | "zOffsetUnits" | "alphaMode" | "alphaCutoff" | "doubleSided" | "wireframe" | "unlit">;
    export type GenericTextureDto = WithDefaults<Inputs.Draw.GenericTextureDto, "name" | "uScale" | "vScale" | "uOffset" | "vOffset" | "wAng" | "invertY" | "invertZ" | "samplingMode">;
}

/**
 * The PlayCanvasCamera inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace PlayCanvasCamera {
    export type CameraDto = Inputs.PlayCanvasCamera.CameraDto;
    export type FocusEntityDto = Inputs.PlayCanvasCamera.FocusEntityDto;
    export type OrbitCameraDto = WithDefaults<Inputs.PlayCanvasCamera.OrbitCameraDto, "pivotPoint" | "distance" | "pitch" | "yaw" | "distanceMin" | "distanceMax" | "pitchAngleMin" | "pitchAngleMax" | "orbitSensitivity" | "distanceSensitivity" | "inertiaFactor" | "autoRender" | "frameOnStart">;
    export type PivotPointDto = WithDefaults<Inputs.PlayCanvasCamera.PivotPointDto, "pivotPoint">;
    export type PositionDto = WithDefaults<Inputs.PlayCanvasCamera.PositionDto, "position">;
    export type ResetCameraDto = WithDefaults<Inputs.PlayCanvasCamera.ResetCameraDto, "yaw" | "pitch" | "distance">;
}

/**
 * The PlayCanvasScene inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace PlayCanvasScene {
    export type InitPlayCanvasDto = WithDefaults<Inputs.PlayCanvasScene.InitPlayCanvasDto, "sceneSize" | "backgroundColor" | "enableShadows" | "enableGround" | "groundCenter" | "groundScaleFactor" | "groundColor" | "groundOpacity" | "ambientLightColor" | "ambientLightIntensity" | "directionalLightColor" | "directionalLightIntensity" | "shadowMapSize" | "enableOrbitCamera">;
}
