#!/usr/bin/env node
// Regenerates src/guides.generated.ts from the public guide pages, so `get_guide` serves the words
// the pages show and nothing else. `--check` compares instead of writing; the test beside the
// generated file asserts the same equality, so a page edit without a regeneration fails twice.
// Section ids must be unique across the pages; the splitter refuses a repeated one.
//
//   npm run sync:guides          (builds first: the splitter is shared with the package)
//   npm run check:guides
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { splitGuidePages } from "../dist/guides-split.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PAGES = ["agentic-cad", "design-documents"].map((name) => ({
    file: resolve(ROOT, `../../../docs/learn/using-ai-with-bitbybit/${name}.md`),
    url: `https://learn.bitbybit.dev/learn/using-ai-with-bitbybit/${name}`,
}));
const OUTPUT = resolve(ROOT, "src/guides.generated.ts");

export function renderGuides(pages) {
    const sections = splitGuidePages(pages);
    return [
        "import type { GuideSection } from \"./guides-split.js\";",
        "",
        "/** Where the first guide is published; every section links back to its own page. */",
        `export const GUIDE_PAGE_URL = ${JSON.stringify(pages[0].url)};`,
        "",
        "/**",
        " * The sections of the public guides, generated by scripts/sync-guides.mjs from",
        ` * ${PAGES.map((page) => `docs/learn/using-ai-with-bitbybit/${page.url.split("/").pop()}.md`).join(" and ")}.`,
        " * Do not edit: run `npm run sync:guides`.",
        " */",
        `export const GUIDES: readonly GuideSection[] = ${JSON.stringify(sections, null, 4)};`,
        "",
    ].join("\n");
}

const check = process.argv.includes("--check");
const pages = PAGES.map((page) => ({ url: page.url, markdown: readFileSync(page.file, "utf8") }));
const rendered = renderGuides(pages);
const current = readFileSync(OUTPUT, "utf8");
if (check) {
    if (rendered !== current) {
        console.error("src/guides.generated.ts is not what the guide pages produce - run `npm run sync:guides` and commit the result");
        process.exit(1);
    }
    console.log("src/guides.generated.ts matches the guide pages");
} else if (rendered === current) {
    console.log("src/guides.generated.ts is already current");
} else {
    writeFileSync(OUTPUT, rendered);
    console.log(`wrote src/guides.generated.ts (${splitGuidePages(pages).length} sections)`);
}
