// GENERATED by scripts/gen-worker-api.mjs from packages/dev/occt/lib/services/design/design.ts and packages/dev/occt-worker/lib/api-hand/occt/design.ts - do not edit; regenerate with `npm run gen:worker-api`.
import { Inputs, Models } from "@bitbybit-dev/occt";
import { OCCTWorkerManager } from "../../occ-worker/occ-worker-manager";
import { buildWithScripts } from "../../occ-worker/design-scripts";

/**
 * Builds parametric parts and assemblies kept as data: a part document holds typed parameters,
 * configurations, an ordered list of features and the parts they make, with materials, appearance,
 * properties such as part numbers and connectors; an assembly document places parts and other
 * assemblies, fastened by their connectors.
 *
 * Features find faces and edges by the feature that made them and the role it made them in, so a
 * reference keeps pointing at the same face when the parameters change. Sketches come from `sketch`,
 * the operations from `operations`, `booleans`, `fillets` and `features`.
 *
 * Experimental: the document format may still change before its first stable version, and
 * documents written before then are not migrated.
 * @beta
 */
export class OCCTDesign {
    constructor(
        private readonly occWorkerManager: OCCTWorkerManager,
    ) {
    }

    /**
     * Checks a design document without building it and lists every problem found.
     *
     * Each problem carries the JSON pointer of the value it is about, such as `/features/2/radius`,
     * and a message. An assembly is checked with the `documents` it places, whose problems come
     * under their position, such as `/documents/2`. Undefined properties and bad expressions count.
     * @param inputs - The document to check
     * @returns The problems, empty when there are none
     * @group document
     * @shortname validate design
     * @drawable false
     * @example
     * ```typescript
     * const issues = await bitbybit.occt.design.validate({
     *     document: { schemaVersion: 1, parameters: { size: 10 }, features: [{ id: "block", type: "extrude", profile: "base", distance: "size" }] },
     * });
     * console.log(issues[0]?.path, issues[0]?.message);
     * ```
     */
    validate(inputs: Inputs.OCCT.DesignDocumentDto): Promise<Models.OCCT.DesignIssue[]> {
        return this.occWorkerManager.genericCallToWorkerPromise("design.validate", inputs);
    }

    /**
     * Works out the version of a design document, the value a component's `version` pins its source
     * with.
     *
     * The version is the SHA-256 of the document's canonical JSON (RFC 8785) without what only
     * editors and tools read, such as `meta` but its name, `extras`, labels, descriptions and
     * reference hints, so editing those keeps it.
     * @param inputs - The document; `documents` is not read
     * @returns The version, 64 lower-case hexadecimal digits
     * @group document
     * @shortname design version
     * @drawable false
     * @example
     * ```typescript
     * const version = await bitbybit.occt.design.versionOf({
     *     document: { schemaVersion: 1, id: "3f2c9a1e-5b7d-4e8f-9a0b-1c2d3e4f5a6b", features: [] },
     * });
     * console.log(version);
     * ```
     */
    versionOf(inputs: Inputs.OCCT.DesignDocumentDto): Promise<string> {
        return this.occWorkerManager.genericCallToWorkerPromise("design.versionOf", inputs);
    }

    /**
     * Builds the parts of a design document, with a configuration's values and then `parameters`
     * replacing the document's own.
     *
     * A document `validate` faults is refused. A failed feature is reported and what uses it
     * skipped; unchanged features are reused. `structure` exports the parts to STEP and glTF through
     * `assembly.manager.buildAssemblyDocument`; an assembly adds components and a bill of materials.
     * @param inputs - The document, the configuration and the parameter values to build it with
     * @returns The parts, a report per feature, the problems found after the features ran, and the parameter values used
     * @group document
     * @shortname build design
     * @drawable true
     * @example
     * ```typescript
     * const { parts, report } = await bitbybit.occt.design.build({
     *     document: { schemaVersion: 1, parameters: { width: 40, height: 10 }, features: [
     *         { id: "base", type: "sketch", on: { plane: "XY" }, pen: [{ type: "hLine", length: "width" }, { type: "vLine", length: 20 }, { type: "hLine", length: "-width" }, { type: "close" }] },
     *         { id: "plate", type: "extrude", profile: "base", distance: "height" },
     *     ], parts: [{ id: "plate", body: "plate", properties: { partNumber: "PL-{width}x{height}" } }] },
     *     parameters: { width: 60 },
     * });
     * console.log(parts[0]?.properties.partNumber);
     * ```
     */
    build(inputs: Inputs.OCCT.DesignBuildDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.DesignBuildResult<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("design.build", inputs);
    }

    /**
     * Builds a design document whose script features run here, on the main thread, as the kernel runs no
     * code: it builds, runs the code of every script the build lists as `pending`, and builds again
     * with what each made, until no script waits.
     *
     * A script's code is the asset its feature names, given in `assets` as an import's file is, and
     * is the body of an async function given `inputs`, the feature's params with bodies as shapes and
     * references as indexes, and `occt`, this package's API: it returns a shape, or `{ shape, roles }`
     * naming faces by role, such as `{ shape, roles: { tooth: [3, 4] } }`. Run only documents whose
     * scripts you trust: their code runs with the rights of the page that runs it.
     * @param inputs - The document, the configuration, the values, the assets with each script's code, and the documents an assembly places
     * @returns What the last build made: the parts, a report per feature and the problems found, as `build` returns them
     * @group document
     * @shortname build design with scripts
     * @drawable true
     * @ignore true
     * @example
     * ```typescript
     * const code = "const box = await occt.shapes.solid.createBox({ width: inputs.size, length: inputs.size, height: 2, center: [0, 0, 0] }); return { shape: box, roles: { slab: [0, 1, 2, 3, 4, 5] } };";
     * const result = await bitbybit.occt.design.buildWithScripts({
     *     document: {
     *         schemaVersion: 1,
     *         parameters: { size: 20 },
     *         assets: [{ id: "slab", uri: "slab.js", sha256: "be4375e273b65ebd4034cef2a4e3c9b5a9141f6b92abcd3796fc624369fa231d" }],
     *         features: [{ id: "slab", type: "script", script: "slab", params: { size: { expr: "size" } } }],
     *     },
     *     assets: { slab: code },
     * });
     * console.log(result.report[0]?.status);
     * ```
     */
    buildWithScripts(inputs: Inputs.OCCT.DesignBuildDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.DesignBuildResult<Inputs.OCCT.TopoDSShapePointer>> {
        return buildWithScripts(this.occWorkerManager, inputs);
    }

    /**
     * Writes a hint onto every face reference of a part document: what the faces it resolves to are
     * like in a build with the configuration and values given, so a later build can find them again
     * by likeness if an edit loses their names.
     *
     * Hints record the body's box and, for each face, its surface type, its area and centre relative
     * to the body, its normal and the names of the faces next to it. They are left out of the
     * document's version, and a build reads them only for a reference whose faces are lost (see
     * `rebind`). A reference that resolves to different faces in different places, such as a connector
     * set's axis, gets no hint. Write them when a document is saved.
     * @param inputs - The part document, and the configuration, values and asset contents to build it with
     * @returns The document with a hint on every face reference the build resolved
     * @group document
     * @shortname design hints
     * @drawable false
     * @ignore true
     * @example
     * ```typescript
     * const hinted = await bitbybit.occt.design.withHints({
     *     document: { schemaVersion: 1, features: [
     *         { id: "base", type: "sketch", on: { plane: "XY" }, pen: [{ type: "hLine", length: 4 }, { type: "vLine", length: 4 }, { type: "hLine", length: -4 }, { type: "close" }] },
     *         { id: "block", type: "extrude", profile: "base", distance: 2 },
     *     ], parts: [{ id: "block", body: "block", appearance: { faces: [{ faces: { of: "block", role: "end", count: 1 }, color: "#ff0000" }] } }] },
     * });
     * console.log(hinted.parts?.[0]?.appearance?.faces?.[0]?.faces.hint);
     * ```
     */
    withHints(inputs: Inputs.OCCT.DesignBuildDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.DesignPartDocument> {
        return this.occWorkerManager.genericCallToWorkerPromise("design.withHints", inputs);
    }

    /**
     * Writes a design document as TypeScript that builds the same parts with this package's own
     * calls, for the configuration and parameter values given.
     *
     * Parameters become constants and expressions TypeScript over them, so dimensions stay editable.
     * The faces and edges features pick are written as the indexes this build finds. A document that
     * does not build with these values is refused.
     * @param inputs - The document, the configuration and the parameter values to write it for
     * @returns The TypeScript, ending with the parts drawn
     * @group document
     * @shortname design to typescript
     * @drawable false
     * @ignore true
     * @example
     * ```typescript
     * const code = await bitbybit.occt.design.toTypeScript({
     *     document: { schemaVersion: 1, parameters: { width: 40 }, features: [
     *         { id: "base", type: "sketch", on: { plane: "XY" }, pen: [{ type: "hLine", length: "width" }, { type: "vLine", length: 20 }, { type: "hLine", length: "-width" }, { type: "close" }] },
     *         { id: "plate", type: "extrude", profile: "base", distance: 10 },
     *     ] },
     * });
     * console.log(code);
     * ```
     */
    toTypeScript(inputs: Inputs.OCCT.DesignBuildDto<Inputs.OCCT.TopoDSShapePointer>): Promise<string> {
        return this.occWorkerManager.genericCallToWorkerPromise("design.toTypeScript", inputs);
    }

    /**
     * Probes a fillet or chamfer feature of a part document: the faces and edges its reference
     * finds, and the largest radius or distance that builds a valid solid.
     *
     * The features before it are built with the values given, its reference is resolved without
     * checking counts, and values are tried, the document's own first, up to `maxAttempts`.
     * @param inputs - The document, the feature's id, the values to build with and how many values to try
     * @returns The faces and edges found, whether the document's value builds, and the range the largest value that builds lies in
     * @group document
     * @shortname probe design fillet
     * @drawable false
     * @ignore true
     * @example
     * ```typescript
     * const probe = await bitbybit.occt.design.probeFillet({
     *     document: { schemaVersion: 1, features: [
     *         { id: "base", type: "sketch", on: { plane: "XY" }, pen: [{ type: "hLine", length: 40 }, { type: "vLine", length: 20 }, { type: "hLine", length: -40 }, { type: "close" }] },
     *         { id: "plate", type: "extrude", profile: "base", distance: 10 },
     *         { id: "round", type: "fillet", body: "plate", radius: 2, edges: { between: [{ of: "plate", role: "end" }, { of: "plate", role: "side" }], count: 4 } },
     *     ] },
     *     feature: "round",
     * });
     * console.log(probe.edges.length, probe.builds, probe.largest, probe.smallestFailing);
     * ```
     */
    probeFillet(inputs: Inputs.OCCT.DesignProbeFilletDto): Promise<Models.OCCT.DesignFilletProbe> {
        return this.occWorkerManager.genericCallToWorkerPromise("design.probeFillet", inputs);
    }
}
