// GENERATED by scripts/gen-worker-api.mjs from packages/dev/occt/lib/services/features/features.ts - do not edit; regenerate with `npm run gen:worker-api`.
import { Inputs, Models } from "@bitbybit-dev/occt";
import { OCCTWorkerManager } from "../../occ-worker/occ-worker-manager";

/**
 * Local modelling features on solids: holes drilled at frames, bosses and pockets from a profile
 * sketched on a face, tapered and revolved ones, ribs and grooves from a wire, and faces removed or
 * pushed and pulled. Each method returns a new shape and leaves the one it was given as it is; faces
 * are counted from 0 as `shapes.face.getFaces` and the face selectors count them. Sweeps that need no
 * base, such as `operations.sweepEvolved`, live in `operations`.
 */
export class OCCTFeatures {
    constructor(
        private readonly occWorkerManager: OCCTWorkerManager,
    ) {
    }

    /**
     * Drills plain holes into a shape, one at each frame: its origin is where the hole enters and its
     * normal points out of the material.
     *
     * `depth` 0 drills through the whole shape; `tipAngle` 0 leaves a flat bottom and 118 the point of
     * a twist drill, in degrees. Holes that meet are cut as one.
     * @param inputs - The shape, the frames and the size of the holes
     * @returns The drilled shape
     * @group holes
     * @shortname holes
     * @drawable true
     * @example
     * ```typescript
     * const plate = await bitbybit.occt.shapes.solid.createBox({ width: 20, length: 20, height: 5, center: [0, 2.5, 0] });
     * const drilled = await bitbybit.occt.features.holes({
     *     shape: plate,
     *     frames: [
     *         { origin: [5, 5, 5], normal: [0, 1, 0], direction: [1, 0, 0] },
     *         { origin: [-5, 5, -5], normal: [0, 1, 0], direction: [1, 0, 0] },
     *     ],
     *     diameter: 3,
     *     depth: 0,
     *     tipAngle: 0,
     * });
     * ```
     */
    holes(inputs: Inputs.OCCT.HolesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.holes", inputs);
    }

    /**
     * Drills holes as `holes` does, and reports a history for the shape, then one per hole in the
     * order of `frames`.
     *
     * `histories[i + 1].faces.flat()` lists every face hole `i` left in the shape.
     * @param inputs - The shape, the frames and the size of the holes
     * @returns The drilled shape and one history for the shape, then one per hole
     * @group holes
     * @shortname holes with history
     * @drawable false
     * @example
     * ```typescript
     * const { shape, histories } = await bitbybit.occt.features.holesWithHistory({
     *     shape: plate,
     *     frames: [{ origin: [5, 5, 5], normal: [0, 1, 0], direction: [1, 0, 0] }],
     *     diameter: 3,
     *     depth: 0,
     *     tipAngle: 0,
     * });
     * const firstHoleFaces = histories[1].faces.flat();
     * ```
     */
    holesWithHistory(inputs: Inputs.OCCT.HolesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.holesWithHistory", inputs);
    }

    /**
     * Drills holes as `holes` does, each with a wider, flat-bottomed counterbore at its mouth that
     * sinks a screw head below the surface.
     *
     * The counterbore must be wider than the hole and, in a hole of a given `depth`, shallower than
     * it; a hole that breaks either rule is refused.
     * @param inputs - The shape, the frames, the size of the holes and the size of the counterbores
     * @returns The drilled shape
     * @group holes
     * @shortname counterbored holes
     * @drawable true
     * @example
     * ```typescript
     * const drilled = await bitbybit.occt.features.counterboredHoles({
     *     shape: plate,
     *     frames: [{ origin: [0, 5, 0], normal: [0, 1, 0], direction: [1, 0, 0] }],
     *     diameter: 3.4,
     *     depth: 0,
     *     tipAngle: 0,
     *     counterboreDiameter: 6.5,
     *     counterboreDepth: 3.4,
     * });
     * ```
     */
    counterboredHoles(inputs: Inputs.OCCT.CounterboredHolesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.counterboredHoles", inputs);
    }

    /**
     * Drills holes as `counterboredHoles` does, and reports a history for the shape, then one per hole in the
     * order of `frames`.
     *
     * `histories[i + 1].faces.flat()` lists every face hole `i` left in the shape.
     * @param inputs - The shape, the frames, the size of the holes and the size of the counterbores
     * @returns The drilled shape and one history for the shape, then one per hole
     * @group holes
     * @shortname counterbored holes with history
     * @drawable false
     * @example
     * ```typescript
     * const { shape, histories } = await bitbybit.occt.features.counterboredHolesWithHistory({
     *     shape: plate,
     *     frames: [{ origin: [5, 5, 5], normal: [0, 1, 0], direction: [1, 0, 0] }],
     *     diameter: 3.4,
     *     depth: 0,
     *     tipAngle: 0,
     *     counterboreDiameter: 6.5,
     *     counterboreDepth: 3.4,
     * });
     * const firstHoleFaces = histories[1].faces.flat();
     * ```
     */
    counterboredHolesWithHistory(inputs: Inputs.OCCT.CounterboredHolesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.counterboredHolesWithHistory", inputs);
    }

    /**
     * Drills holes as `holes` does, each with a cone-shaped countersink at its mouth that sinks a
     * flat screw head flush with the surface.
     *
     * `countersinkAngle` is the cone's full angle in degrees. The countersink must be wider than the
     * hole and end above the bottom of a hole of a given `depth`.
     * @param inputs - The shape, the frames, the size of the holes and the size of the countersinks
     * @returns The drilled shape
     * @group holes
     * @shortname countersunk holes
     * @drawable true
     * @example
     * ```typescript
     * const drilled = await bitbybit.occt.features.countersunkHoles({
     *     shape: plate,
     *     frames: [{ origin: [0, 5, 0], normal: [0, 1, 0], direction: [1, 0, 0] }],
     *     diameter: 3.4,
     *     depth: 0,
     *     tipAngle: 0,
     *     countersinkDiameter: 6.5,
     *     countersinkAngle: 90,
     * });
     * ```
     */
    countersunkHoles(inputs: Inputs.OCCT.CountersunkHolesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.countersunkHoles", inputs);
    }

    /**
     * Drills holes as `countersunkHoles` does, and reports a history for the shape, then one per hole in the
     * order of `frames`.
     *
     * `histories[i + 1].faces.flat()` lists every face hole `i` left in the shape.
     * @param inputs - The shape, the frames, the size of the holes and the size of the countersinks
     * @returns The drilled shape and one history for the shape, then one per hole
     * @group holes
     * @shortname countersunk holes with history
     * @drawable false
     * @example
     * ```typescript
     * const { shape, histories } = await bitbybit.occt.features.countersunkHolesWithHistory({
     *     shape: plate,
     *     frames: [{ origin: [5, 5, 5], normal: [0, 1, 0], direction: [1, 0, 0] }],
     *     diameter: 3.4,
     *     depth: 0,
     *     tipAngle: 0,
     *     countersinkDiameter: 6.5,
     *     countersinkAngle: 90,
     * });
     * const firstHoleFaces = histories[1].faces.flat();
     * ```
     */
    countersunkHolesWithHistory(inputs: Inputs.OCCT.CountersunkHolesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.countersunkHolesWithHistory", inputs);
    }

    /**
     * Removes faces from a solid and closes the gap by extending the faces around them, as when a
     * hole or a rounded edge is deleted from a part.
     *
     * The shape must hold solids only; a gap its neighbours cannot close, such as the top of a box
     * leaves, is refused rather than left open.
     * @param inputs - The shape and the faces to remove
     * @returns The shape without the faces
     * @group faces
     * @shortname remove faces
     * @drawable true
     * @example
     * ```typescript
     * const walls = await bitbybit.occt.select.faces.ofType({ shape: drilled, type: Bit.Inputs.OCCT.surfaceTypeEnum.cylinder });
     * const filled = await bitbybit.occt.features.removeFaces({ shape: drilled, indexes: walls });
     * ```
     */
    removeFaces(inputs: Inputs.OCCT.RemoveFacesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.removeFaces", inputs);
    }

    /**
     * Removes faces as `removeFaces` does, and reports one history, the shape's: a removed face's
     * `faces` entry is empty, and each face that stays lists the face it became, grown over the gap.
     * @param inputs - The shape and the faces to remove
     * @returns The shape without the faces, and the history of the shape as the one entry of `histories`
     * @group faces
     * @shortname remove faces with history
     * @drawable false
     * @example
     * ```typescript
     * const walls = await bitbybit.occt.select.faces.ofType({ shape: drilled, type: Bit.Inputs.OCCT.surfaceTypeEnum.cylinder });
     * const { shape, histories: [history] } = await bitbybit.occt.features.removeFacesWithHistory({ shape: drilled, indexes: walls });
     * const topNow = history.faces[0];
     * ```
     */
    removeFacesWithHistory(inputs: Inputs.OCCT.RemoveFacesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.removeFacesWithHistory", inputs);
    }

    /**
     * Moves faces of a shape along their outward normals and stretches the faces around them to
     * follow, such as raising the top of a block.
     *
     * `distance` moves every chosen face, a negative one inward; `distances` gives one per index
     * instead. Each solid of a compound moves on its own and stays a solid.
     * @param inputs - The shape, the faces and how far to move them
     * @returns The shape with the faces moved
     * @group faces
     * @shortname push pull faces
     * @drawable true
     * @example
     * ```typescript
     * const top = await bitbybit.occt.select.faces.facing({ shape: block, direction: [0, 1, 0], angle: 0 });
     * const taller = await bitbybit.occt.features.pushPullFaces({ shape: block, indexes: top, distance: 2 });
     * ```
     */
    pushPullFaces(inputs: Inputs.OCCT.PushPullFacesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.pushPullFaces", inputs);
    }

    /**
     * Moves faces as `pushPullFaces` does, and reports one history, the shape's: each face, edge and
     * vertex lists what it became, so a moved face is followed to where it went, curved ones too.
     * @param inputs - The shape, the faces and how far to move them
     * @returns The shape with the faces moved, and the history of the shape as the one entry of `histories`
     * @group faces
     * @shortname push pull faces with history
     * @drawable false
     * @example
     * ```typescript
     * const [wall] = await bitbybit.occt.select.faces.ofType({ shape: rod, type: Bit.Inputs.OCCT.surfaceTypeEnum.cylinder });
     * const { shape, histories: [history] } = await bitbybit.occt.features.pushPullFacesWithHistory({ shape: rod, indexes: [wall], distance: 1 });
     * const [movedWall] = history.faces[wall];
     * ```
     */
    pushPullFacesWithHistory(inputs: Inputs.OCCT.PushPullFacesDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.pushPullFacesWithHistory", inputs);
    }

    /**
     * Grows a boss out of a base by sweeping a profile face that lies on one of its faces along
     * `direction`.
     *
     * `extent` stops it after `length`, at the face `untilFaceIndex` names, such as the underside of
     * an overhang, or through all of the base in its way, which needs base ahead of it.
     * @param inputs - The base, the profile, its sketch face, the direction and how far to go
     * @returns The base with the boss
     * @group forms
     * @shortname boss
     * @drawable true
     * @example
     * ```typescript
     * const block = await bitbybit.occt.shapes.solid.createBox({ width: 10, length: 10, height: 10, center: [0, 5, 0] });
     * const [top] = await bitbybit.occt.select.faces.facing({ shape: block, direction: [0, 1, 0], angle: 0 });
     * const profile = await bitbybit.occt.shapes.face.createSquareFace({ size: 2, center: [0, 10, 0], direction: [0, 1, 0] });
     * const bossed = await bitbybit.occt.features.boss({ shape: block, profile, sketchFaceIndex: top, direction: [0, 1, 0], length: 3 });
     * ```
     */
    boss(inputs: Inputs.OCCT.PrismFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.boss", inputs);
    }

    /**
     * Grows a boss as `boss` does, and reports two histories: the base's, then the profile's, whose
     * `facesFromEdges` holds the side each profile edge swept and `lastFaces` the far end.
     *
     * A face the kernel leaves unreported is found from where it lies, and left out when it could
     * belong to more than one input.
     * @param inputs - The base, the profile, its sketch face, the direction and how far to go
     * @returns The base with the boss, and the histories of the base and of the profile
     * @group forms
     * @shortname boss with history
     * @drawable false
     * @example
     * ```typescript
     * const { shape, histories } = await bitbybit.occt.features.bossWithHistory({ shape: block, profile, sketchFaceIndex: top, direction: [0, 1, 0], length: 3 });
     * const [baseHistory, profileHistory] = histories;
     * const bossTop = profileHistory.lastFaces;
     * ```
     */
    bossWithHistory(inputs: Inputs.OCCT.PrismFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.bossWithHistory", inputs);
    }

    /**
     * Cuts a pocket into a base by sweeping a profile face that lies on one of its faces along
     * `direction`, which points into the base.
     *
     * `extent` stops it after `length`, at the face `untilFaceIndex` names, such as the ceiling of a
     * void or the far side of the base, or through all of it.
     * @param inputs - The base, the profile, its sketch face, the direction and how far to go
     * @returns The base with the pocket
     * @group forms
     * @shortname pocket
     * @drawable true
     * @example
     * ```typescript
     * const [top] = await bitbybit.occt.select.faces.facing({ shape: block, direction: [0, 1, 0], angle: 0 });
     * const profile = await bitbybit.occt.shapes.face.createSquareFace({ size: 2, center: [0, 10, 0], direction: [0, 1, 0] });
     * const pocketed = await bitbybit.occt.features.pocket({ shape: block, profile, sketchFaceIndex: top, direction: [0, -1, 0], length: 3 });
     * ```
     */
    pocket(inputs: Inputs.OCCT.PrismFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.pocket", inputs);
    }

    /**
     * Cuts a pocket as `pocket` does, and reports two histories: the base's, then the profile's,
     * whose `facesFromEdges` holds the wall each profile edge swept and `lastFaces` the floor.
     *
     * A face the kernel leaves unreported is found from where it lies, and left out when it could
     * belong to more than one input.
     * @param inputs - The base, the profile, its sketch face, the direction and how far to go
     * @returns The base with the pocket, and the histories of the base and of the profile
     * @group forms
     * @shortname pocket with history
     * @drawable false
     * @example
     * ```typescript
     * const { shape, histories } = await bitbybit.occt.features.pocketWithHistory({ shape: block, profile, sketchFaceIndex: top, direction: [0, -1, 0], length: 3 });
     * const floor = histories[1].lastFaces;
     * const walls = histories[1].facesFromEdges.flat();
     * ```
     */
    pocketWithHistory(inputs: Inputs.OCCT.PrismFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Models.OCCT.ShapeWithHistories<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.pocketWithHistory", inputs);
    }

    /**
     * Grows a boss out of a base as `boss` does, straight out of the sketch face, with its sides
     * leaning by `angle` degrees.
     *
     * A positive angle narrows the boss as it rises from the sketch face, a negative one widens it
     * and rounds its outer corners. `extent` works as for `boss`.
     * @param inputs - The base, the profile, its sketch face, the draft angle in degrees and how far to go
     * @returns The base with the tapered boss
     * @group forms
     * @shortname tapered boss
     * @drawable true
     * @example
     * ```typescript
     * const [top] = await bitbybit.occt.select.faces.facing({ shape: block, direction: [0, 1, 0], angle: 0 });
     * const profile = await bitbybit.occt.shapes.face.createSquareFace({ size: 2, center: [0, 10, 0], direction: [0, 1, 0] });
     * const bossed = await bitbybit.occt.features.taperedBoss({ shape: block, profile, sketchFaceIndex: top, angle: 10, length: 3 });
     * ```
     */
    taperedBoss(inputs: Inputs.OCCT.TaperedPrismFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.taperedBoss", inputs);
    }

    /**
     * Cuts a pocket into a base as `pocket` does, straight in from the sketch face, with its sides
     * leaning by `angle` degrees.
     *
     * A positive angle narrows the pocket as it deepens, a negative one widens it. The kernel cannot
     * stop a tapered pocket at the far side of the base; run it through all instead.
     * @param inputs - The base, the profile, its sketch face, the draft angle in degrees and how far to go
     * @returns The base with the tapered pocket
     * @group forms
     * @shortname tapered pocket
     * @drawable true
     * @example
     * ```typescript
     * const [top] = await bitbybit.occt.select.faces.facing({ shape: block, direction: [0, 1, 0], angle: 0 });
     * const profile = await bitbybit.occt.shapes.face.createSquareFace({ size: 2, center: [0, 10, 0], direction: [0, 1, 0] });
     * const pocketed = await bitbybit.occt.features.taperedPocket({ shape: block, profile, sketchFaceIndex: top, angle: 5, length: 3 });
     * ```
     */
    taperedPocket(inputs: Inputs.OCCT.TaperedPrismFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.taperedPocket", inputs);
    }

    /**
     * Adds a ring to a base by turning a profile face about an axis, such as a collar round a shaft:
     * the profile lies on a face of the base, in a plane through the axis.
     *
     * `angle` is in degrees and follows the right-hand rule about `axisDirection`; 360 makes a whole
     * ring.
     * @param inputs - The base, the profile, its sketch face, the axis and the angle in degrees
     * @returns The base with the ring
     * @group forms
     * @shortname revolved boss
     * @drawable true
     * @example
     * ```typescript
     * const shaft = await bitbybit.occt.shapes.solid.createCylinder({ radius: 5, height: 10, center: [0, 0, 0], direction: [0, 1, 0] });
     * const [side] = await bitbybit.occt.select.faces.ofType({ shape: shaft, type: Bit.Inputs.OCCT.surfaceTypeEnum.cylinder });
     * const profile = await bitbybit.occt.shapes.face.createRectangleFace({ width: 2, length: 1, center: [5.5, 5, 0], direction: [0, 0, 1] });
     * const collared = await bitbybit.occt.features.revolvedBoss({ shape: shaft, profile, sketchFaceIndex: side, axisOrigin: [0, 0, 0], axisDirection: [0, 1, 0], angle: 360 });
     * ```
     */
    revolvedBoss(inputs: Inputs.OCCT.RevolvedFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.revolvedBoss", inputs);
    }

    /**
     * Cuts a groove round a base by turning a profile face about an axis, such as the seat of a
     * circlip on a shaft: the profile lies on a face of the base, in a plane through the axis.
     *
     * `angle` is in degrees and follows the right-hand rule about `axisDirection`; 360 cuts all the
     * way round.
     * @param inputs - The base, the profile, its sketch face, the axis and the angle in degrees
     * @returns The base with the groove
     * @group forms
     * @shortname revolved pocket
     * @drawable true
     * @example
     * ```typescript
     * const [side] = await bitbybit.occt.select.faces.ofType({ shape: shaft, type: Bit.Inputs.OCCT.surfaceTypeEnum.cylinder });
     * const profile = await bitbybit.occt.shapes.face.createRectangleFace({ width: 2, length: 1, center: [4.5, 5, 0], direction: [0, 0, 1] });
     * const grooved = await bitbybit.occt.features.revolvedPocket({ shape: shaft, profile, sketchFaceIndex: side, axisOrigin: [0, 0, 0], axisDirection: [0, 1, 0], angle: 360 });
     * ```
     */
    revolvedPocket(inputs: Inputs.OCCT.RevolvedFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSFacePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.revolvedPocket", inputs);
    }

    /**
     * Adds a rib to a base: the region between a wire and the base's faces, on the wire's left as it
     * runs seen from the side the frame's normal points to, filled and thickened across the plane.
     *
     * A wire across the inside corner of an L fills the corner; an edge is made into a wire first.
     * @param inputs - The base, the wire, the plane it lies in and the thickness on each side
     * @returns The base with the rib
     * @group forms
     * @shortname rib
     * @drawable true
     * @example
     * ```typescript
     * const wire = await bitbybit.occt.shapes.wire.createPolylineWire({ points: [[12, 2, 0], [2, 12, 0]] });
     * const ribbed = await bitbybit.occt.features.rib({
     *     shape: bracket,
     *     wire,
     *     frame: { origin: [0, 0, 0], normal: [0, 0, 1], direction: [1, 0, 0] },
     *     thickness: 0.5,
     *     otherSideThickness: 0.5,
     * });
     * ```
     */
    rib(inputs: Inputs.OCCT.RibFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSWirePointer | Inputs.OCCT.TopoDSEdgePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.rib", inputs);
    }

    /**
     * Cuts a groove into a base: the part of the base's section on the left of a wire as it runs,
     * seen from the side the frame's normal points to, removed across the plane.
     *
     * A wire bent round a corner keeps the region inside the bend and cuts the rest; an edge is made
     * into a wire first.
     * @param inputs - The base, the wire, the plane it lies in and the thickness on each side
     * @returns The base with the groove
     * @group forms
     * @shortname groove
     * @drawable true
     * @example
     * ```typescript
     * const wire = await bitbybit.occt.shapes.wire.createPolylineWire({ points: [[10, 12, 0], [10, 5, 0], [22, 5, 0]] });
     * const grooved = await bitbybit.occt.features.groove({
     *     shape: block,
     *     wire,
     *     frame: { origin: [0, 0, 0], normal: [0, 0, -1], direction: [1, 0, 0] },
     *     thickness: 0.5,
     *     otherSideThickness: 0.5,
     * });
     * ```
     */
    groove(inputs: Inputs.OCCT.RibFeatureDto<Inputs.OCCT.TopoDSShapePointer, Inputs.OCCT.TopoDSWirePointer | Inputs.OCCT.TopoDSEdgePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("features.groove", inputs);
    }
}
