// GENERATED by scripts/gen-worker-api.mjs from packages/dev/occt/lib/services/io.ts - do not edit.
// The kernel class is the source of the docs, the signatures and the member order; hand-written members come from packages/dev/occt-worker/lib/api-hand/occt/io.ts.
// Regenerate with `npm run gen:worker-api` at the repository root.
import { Inputs, Models } from "@bitbybit-dev/occt";
import { OCCTWorkerManager } from "../../occ-worker/occ-worker-manager";
import { IO } from "@bitbybit-dev/base/lib/api/inputs";
import { Resolved } from "@bitbybit-dev/occt";
import { resolveDto } from "@bitbybit-dev/base";

/**
 * Reading and writing OpenCascade shapes in exchange formats: STEP, IGES, STL and BREP in; STEP, STL,
 * BREP, OBJ, PLY, SVG and DXF out; STEP to glTF conversion with the assembly tree, colors and names
 * preserved, and a STEP assembly structure as JSON. Files travel as text or binary data, never as
 * paths. OpenCascade treats Z as up while this library treats Y as up, so the `adjustYtoZ` and
 * `adjustZtoY` flags swap the axes on the way out and in.
 */
export class OCCTIO {
    constructor(
        readonly occWorkerManager: OCCTWorkerManager,
    ) {
    }

    /**
     * Writes a shape as STEP, the standard exchange format for exact CAD geometry, and starts a
     * browser download of the file.
     *
     * With `adjustYtoZ` true the shape is turned so this library's Y-up becomes STEP's Z-up;
     * `fromRightHanded` skips the mirror that swap otherwise includes. `fileName` names the download
     * and `tryDownload` false skips it. `saveShapeSTEPAndReturn` gives the file's text instead.
     * @param inputs - The shape, the file name, the axis adjustment and the download options
     * @returns Nothing; the download starts when the file is ready
     * @group io
     * @shortname save step
     * @drawable false
     * @example
     * ```typescript
     * await bitbybit.occt.io.saveShapeSTEP({ shape: box, fileName: "box.step", adjustYtoZ: true, tryDownload: true });
     * ```
     */
    async saveShapeSTEP(inputs: Inputs.OCCT.SaveStepDto<Inputs.OCCT.TopoDSShapePointer>): Promise<void> {
        const resolved = resolveDto(Inputs.OCCT.SaveStepDto, inputs) as Resolved.OCCT.SaveStepDto<Inputs.OCCT.TopoDSShapePointer>;
        await this.saveShapeSTEPAndReturn(resolved);
    }

    /**
     * Writes a shape as STEP, the standard exchange format for exact CAD geometry, and returns the
     * file's text.
     *
     * With `adjustYtoZ` true the shape is turned so this library's Y-up becomes STEP's Z-up;
     * `fromRightHanded` skips the mirror that swap otherwise includes. `fileName` and `tryDownload`
     * matter only where a browser download can be started.
     * @param inputs - The shape, the file name, the axis adjustment and the download options
     * @returns The STEP file as text
     * @group io
     * @shortname save step and return
     * @drawable false
     * @example
     * ```typescript
     * const step = await bitbybit.occt.io.saveShapeSTEPAndReturn({ shape: box, fileName: "box.step", adjustYtoZ: true, tryDownload: false });
     * ```
     */
    async saveShapeSTEPAndReturn(inputs: Inputs.OCCT.SaveStepDto<Inputs.OCCT.TopoDSShapePointer>): Promise<string> {
        const resolved = resolveDto(Inputs.OCCT.SaveStepDto, inputs) as Resolved.OCCT.SaveStepDto<Inputs.OCCT.TopoDSShapePointer>;
        const text = await this.occWorkerManager.genericCallToWorkerPromise<string>("io.saveShapeSTEP", resolved);
        this.downloadStep(text, resolved);
        return text;
    }

    /**
     * Triangulates a shape, writes it as STL, the mesh format 3D printers read, and starts a browser
     * download of the file.
     *
     * `precision` is the meshing tolerance in model units, `adjustYtoZ` turns Y-up into Z-up and
     * `binary` writes the smaller binary form. `fileName` names the download, `tryDownload` false
     * skips it. `saveShapeStlAndReturn` gives the file instead.
     * @param inputs - The shape, the file name, the meshing precision, the axis adjustment, the form and the download options
     * @returns Nothing; the download starts when the file is ready
     * @group io
     * @shortname save stl
     * @drawable false
     * @example
     * ```typescript
     * await bitbybit.occt.io.saveShapeStl({ shape: box, fileName: "box.stl", precision: 0.01, adjustYtoZ: true, tryDownload: true, binary: true });
     * ```
     */
    async saveShapeStl(inputs: Inputs.OCCT.SaveStlDto<Inputs.OCCT.TopoDSShapePointer>): Promise<void> {
        const resolved = resolveDto(Inputs.OCCT.SaveStlDto, inputs) as Resolved.OCCT.SaveStlDto<Inputs.OCCT.TopoDSShapePointer>;
        await this.saveShapeStlAndReturn(resolved);
    }

    /**
     * Triangulates a shape and writes it as STL, the mesh format 3D printers and slicers read,
     * returning the file's text, or its bytes when `binary` is true.
     *
     * `precision` is the meshing tolerance in model units; smaller values follow curved surfaces
     * more closely. `adjustYtoZ` turns Y-up into Z-up. `fileName` and `tryDownload` only matter
     * where a download can start.
     * @param inputs - The shape, the file name, the meshing precision, the axis adjustment, the form and the download options
     * @returns The STL file as text, or as bytes when `binary` is true
     * @group io
     * @shortname save stl return
     * @drawable false
     * @example
     * ```typescript
     * const stl = await bitbybit.occt.io.saveShapeStlAndReturn({ shape: box, fileName: "box.stl", precision: 0.01, adjustYtoZ: true, tryDownload: false });
     * const bytes = await bitbybit.occt.io.saveShapeStlAndReturn({ shape: box, fileName: "box.stl", precision: 0.01, adjustYtoZ: true, tryDownload: false, binary: true });
     * ```
     */
    async saveShapeStlAndReturn(inputs: Inputs.OCCT.SaveStlDto<Inputs.OCCT.TopoDSShapePointer>): Promise<string | Uint8Array> {
        const resolved = resolveDto(Inputs.OCCT.SaveStlDto, inputs) as Resolved.OCCT.SaveStlDto<Inputs.OCCT.TopoDSShapePointer>;
        const stl = await this.occWorkerManager.genericCallToWorkerPromise<string | Uint8Array>("io.saveShapeStl", resolved);
        this.downloadStl(stl, resolved);
        return stl;
    }

    private downloadStep(text: string, resolved: Resolved.OCCT.SaveStepDto<Inputs.OCCT.TopoDSShapePointer>): void {
        if (resolved.tryDownload && document) {
            const blob = new Blob([text], { type: "text/plain" });
            const blobUrl = URL.createObjectURL(blob);

            let fileName = resolved.fileName;
            if (!fileName.toLowerCase().includes(".step")) {
                fileName += ".step";
            }
            const fileLink = document.createElement("a");
            fileLink.href = blobUrl;
            fileLink.target = "_self";
            fileLink.download = fileName;
            fileLink.click();
            fileLink.remove();
        }
    }

    private downloadStl(stl: string | Uint8Array, resolved: Resolved.OCCT.SaveStlDto<Inputs.OCCT.TopoDSShapePointer>): void {
        if (resolved.tryDownload) {
            this.downloadFile(stl, resolved.fileName, "application/stl");
        }
    }

    /**
     * Writes a shape as BREP, the text format that keeps its exact geometry and topology, and starts
     * a browser download of the file.
     *
     * `io.loadBrep` reads the file back into the same shape. `fileName` names the download and
     * `tryDownload` false skips it; `saveShapeBrepAndReturn` gives the text instead.
     * @param inputs - The shape, the file name and the download option
     * @returns Nothing; the download starts when the file is ready
     * @group io
     * @shortname save brep
     * @drawable false
     * @example
     * ```typescript
     * await bitbybit.occt.io.saveShapeBrep({ shape: box, fileName: "box.brep", tryDownload: true });
     * ```
     */
    async saveShapeBrep(inputs: Inputs.OCCT.SaveBrepDto<Inputs.OCCT.TopoDSShapePointer>): Promise<void> {
        const resolved = resolveDto(Inputs.OCCT.SaveBrepDto, inputs) as Resolved.OCCT.SaveBrepDto<Inputs.OCCT.TopoDSShapePointer>;
        await this.saveShapeBrepAndReturn(resolved);
    }

    /**
     * Writes a shape as BREP, the text format that keeps its exact geometry and topology, and
     * returns the file's text.
     *
     * `io.loadBrep` reads the text back into the same shape, placement and orientation included.
     * `fileName` and `tryDownload` only matter where a download can start.
     * @param inputs - The shape, the file name and the download option
     * @returns The BREP file as text
     * @group io
     * @shortname save brep and return
     * @drawable false
     * @example
     * ```typescript
     * const brep = await bitbybit.occt.io.saveShapeBrepAndReturn({ shape: box, fileName: "box.brep", tryDownload: false });
     * const copy = await bitbybit.occt.io.loadBrep({ brepData: brep });
     * ```
     */
    async saveShapeBrepAndReturn(inputs: Inputs.OCCT.SaveBrepDto<Inputs.OCCT.TopoDSShapePointer>): Promise<string> {
        const resolved = resolveDto(Inputs.OCCT.SaveBrepDto, inputs) as Resolved.OCCT.SaveBrepDto<Inputs.OCCT.TopoDSShapePointer>;
        const text = await this.occWorkerManager.genericCallToWorkerPromise<string>("io.saveShapeBrep", resolved);
        if (resolved.tryDownload) {
            this.downloadFile(text, resolved.fileName, "text/plain");
        }
        return text;
    }

    /**
     * Triangulates a shape, writes it as OBJ, the mesh format most 3D programs read, and starts a
     * browser download of the file.
     *
     * `precision` is the meshing tolerance in model units and `adjustYtoZ` turns Y-up into Z-up. The
     * file name may hold no spaces or slashes; `tryDownload` false skips the download, and
     * `saveShapeObjAndReturn` gives the text instead.
     * @param inputs - The shape, the file name, the meshing precision, the axis adjustment and the download option
     * @returns Nothing; the download starts when the file is ready
     * @group io
     * @shortname save obj
     * @drawable false
     * @example
     * ```typescript
     * await bitbybit.occt.io.saveShapeObj({ shape: box, fileName: "box.obj", precision: 0.01, adjustYtoZ: false, tryDownload: true });
     * ```
     */
    async saveShapeObj(inputs: Inputs.OCCT.SaveObjDto<Inputs.OCCT.TopoDSShapePointer>): Promise<void> {
        const resolved = resolveDto(Inputs.OCCT.SaveObjDto, inputs) as Resolved.OCCT.SaveObjDto<Inputs.OCCT.TopoDSShapePointer>;
        await this.saveShapeObjAndReturn(resolved);
    }

    /**
     * Triangulates a shape and writes it as OBJ, the mesh format most 3D programs read, returning
     * the file's text.
     *
     * `precision` is the meshing tolerance in model units, `adjustYtoZ` turns Y-up into Z-up, and
     * coordinates keep six decimals. `mtl` stays empty, since a shape carries no colors;
     * `assembly.manager.exportDocumentToObj` writes colored parts.
     * @param inputs - The shape, the file name, the meshing precision, the axis adjustment and the download option
     * @returns The OBJ text, with an empty material library text
     * @group io
     * @shortname save obj and return
     * @drawable false
     * @example
     * ```typescript
     * const files = await bitbybit.occt.io.saveShapeObjAndReturn({ shape: box, fileName: "box.obj", precision: 0.01, adjustYtoZ: false, tryDownload: false });
     * console.log(files.obj);
     * ```
     */
    async saveShapeObjAndReturn(inputs: Inputs.OCCT.SaveObjDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ObjFiles> {
        const resolved = resolveDto(Inputs.OCCT.SaveObjDto, inputs) as Resolved.OCCT.SaveObjDto<Inputs.OCCT.TopoDSShapePointer>;
        const files = await this.occWorkerManager.genericCallToWorkerPromise<Models.OCCT.ObjFiles>("io.saveShapeObj", resolved);
        if (resolved.tryDownload) {
            this.downloadObj(files, resolved.fileName);
        }
        return files;
    }

    /**
     * Triangulates a shape, writes it as ASCII PLY with a normal per vertex, and starts a browser
     * download of the file.
     *
     * `precision` is the meshing tolerance in model units and `adjustYtoZ` turns Y-up into Z-up.
     * `fileName` names the download and `tryDownload` false skips it; `saveShapePlyAndReturn` gives
     * the text instead.
     * @param inputs - The shape, the file name, the meshing precision, the axis adjustment and the download option
     * @returns Nothing; the download starts when the file is ready
     * @group io
     * @shortname save ply
     * @drawable false
     * @example
     * ```typescript
     * await bitbybit.occt.io.saveShapePly({ shape: box, fileName: "box.ply", precision: 0.01, adjustYtoZ: false, tryDownload: true });
     * ```
     */
    async saveShapePly(inputs: Inputs.OCCT.SavePlyDto<Inputs.OCCT.TopoDSShapePointer>): Promise<void> {
        const resolved = resolveDto(Inputs.OCCT.SavePlyDto, inputs) as Resolved.OCCT.SavePlyDto<Inputs.OCCT.TopoDSShapePointer>;
        await this.saveShapePlyAndReturn(resolved);
    }

    /**
     * Triangulates a shape and writes it as ASCII PLY with a normal per vertex, a mesh format
     * scanning tools read, returning the file's text.
     *
     * Coordinates keep six significant digits, so past 1000 units they keep two decimals.
     * `precision` is the meshing tolerance in model units and `adjustYtoZ` turns Y-up into Z-up.
     * @param inputs - The shape, the file name, the meshing precision, the axis adjustment and the download option
     * @returns The PLY file as text
     * @group io
     * @shortname save ply and return
     * @drawable false
     * @example
     * ```typescript
     * const ply = await bitbybit.occt.io.saveShapePlyAndReturn({ shape: box, fileName: "box.ply", precision: 0.01, adjustYtoZ: false, tryDownload: false });
     * ```
     */
    async saveShapePlyAndReturn(inputs: Inputs.OCCT.SavePlyDto<Inputs.OCCT.TopoDSShapePointer>): Promise<string> {
        const resolved = resolveDto(Inputs.OCCT.SavePlyDto, inputs) as Resolved.OCCT.SavePlyDto<Inputs.OCCT.TopoDSShapePointer>;
        const text = await this.occWorkerManager.genericCallToWorkerPromise<string>("io.saveShapePly", resolved);
        if (resolved.tryDownload) {
            this.downloadFile(text, resolved.fileName, "text/plain");
        }
        return text;
    }

    /**
     * Draws the edges a view of a shape sees as an SVG drawing, with the hidden edges dashed when
     * asked, and starts a browser download of the file.
     *
     * The drawing shows the view from the frame's normal side, x running right along its direction.
     * `tryDownload` false skips the download; `saveShapeSvgAndReturn` gives the text instead.
     * @param inputs - The shape, the view, whether to draw hidden edges, the precision and the download options
     * @returns Nothing; the download starts when the file is ready
     * @group io
     * @shortname save svg
     * @drawable false
     * @example
     * ```typescript
     * const view = { origin: [0, 0, 0], normal: [0, 1, 0], direction: [1, 0, 0] };
     * await bitbybit.occt.io.saveShapeSvg({ shape: part, frame: view, drawHidden: true, precision: 0.01, fileName: "top.svg", tryDownload: true });
     * ```
     */
    async saveShapeSvg(inputs: Inputs.OCCT.SaveSvgDto<Inputs.OCCT.TopoDSShapePointer>): Promise<void> {
        const resolved = resolveDto(Inputs.OCCT.SaveSvgDto, inputs) as Resolved.OCCT.SaveSvgDto<Inputs.OCCT.TopoDSShapePointer>;
        await this.saveShapeSvgAndReturn(resolved);
    }

    /**
     * Draws the edges a view of a shape sees as an SVG drawing, with the hidden edges dashed when
     * asked, and returns the file's text.
     *
     * It shows the view from the frame's normal side in model units, x running right along the
     * frame's direction and y up, so the file holds each point as x and minus y.
     * @param inputs - The shape, the view, whether to draw hidden edges, the precision and the download options
     * @returns The SVG file as text
     * @group io
     * @shortname save svg and return
     * @drawable false
     * @example
     * ```typescript
     * const view = { origin: [0, 0, 0], normal: [1, 1, 1], direction: [1, -1, 0] };
     * const svg = await bitbybit.occt.io.saveShapeSvgAndReturn({ shape: box, frame: view, drawHidden: true, precision: 0.01, fileName: "box.svg", tryDownload: false });
     * ```
     */
    async saveShapeSvgAndReturn(inputs: Inputs.OCCT.SaveSvgDto<Inputs.OCCT.TopoDSShapePointer>): Promise<string> {
        const resolved = resolveDto(Inputs.OCCT.SaveSvgDto, inputs) as Resolved.OCCT.SaveSvgDto<Inputs.OCCT.TopoDSShapePointer>;
        const text = await this.occWorkerManager.genericCallToWorkerPromise<string>("io.saveShapeSvg", resolved);
        if (resolved.tryDownload) {
            this.downloadFile(text, resolved.fileName, "image/svg+xml");
        }
        return text;
    }

    private downloadObj(files: Models.OCCT.ObjFiles, fileName: string): void {
        this.downloadFile(files.obj, fileName, "model/obj");
        const library = /^mtllib (.+)$/m.exec(files.obj)?.[1]?.trim();
        if (library !== undefined && files.mtl !== "") {
            this.downloadFile(files.mtl, library, "model/mtl");
        }
    }

    private downloadFile(content: string | Uint8Array, fileName: string, type: string): void {
        if (typeof document === "undefined") {
            return;
        }
        const blob = new Blob([typeof content === "string" ? content : content.slice()], { type });
        const fileLink = document.createElement("a");
        fileLink.href = URL.createObjectURL(blob);
        fileLink.target = "_self";
        fileLink.download = fileName;
        fileLink.click();
        fileLink.remove();
    }

    /**
     * Reads an STL file, ASCII or binary, into a shape: one planar face per triangle, or one face
     * that carries the whole mesh.
     *
     * With `asFaces` true the faces share their corners' edges in a compound that
     * `shapeFix.sewWithReport` can join into a shell. `adjustZtoY` turns Z-up into Y-up, and a file
     * without triangles is refused.
     * @param inputs - The STL file, the face option and the axis adjustment
     * @returns A compound of triangular faces, or one face that carries the mesh
     * @group io
     * @shortname load stl
     * @drawable true
     * @example
     * ```typescript
     * const mesh = await bitbybit.occt.io.loadStl({ stlData: stlText, asFaces: true, adjustZtoY: true });
     * const sewn = await bitbybit.occt.shapeFix.sewWithReport({ shapes: [mesh], tolerance: 1e-6 });
     * ```
     */
    async loadStl(inputs: Inputs.OCCT.LoadStlDto): Promise<Inputs.OCCT.TopoDSShapePointer> {
        const resolved = resolveDto(Inputs.OCCT.LoadStlDto, inputs) as Resolved.OCCT.LoadStlDto;
        const stlData = await this.occWorkerManager.prepareStepData(resolved.stlData);
        return this.occWorkerManager.genericCallToWorkerPromise("io.loadStl", { ...resolved, stlData });
    }

    /**
     * Reads a BREP file, the text format that keeps a shape's exact geometry and topology, back into
     * the shape `io.saveShapeBrep` wrote.
     *
     * The shape keeps its placement and orientation. Text that is not a whole BREP file, such as
     * one cut short, is refused, and so is a damaged one, with where it is damaged.
     * @param inputs - The BREP file
     * @returns The shape the file holds
     * @group io
     * @shortname load brep
     * @drawable true
     * @example
     * ```typescript
     * const brep = await bitbybit.occt.io.saveShapeBrepAndReturn({ shape: box, fileName: "box.brep", tryDownload: false });
     * const copy = await bitbybit.occt.io.loadBrep({ brepData: brep });
     * ```
     */
    async loadBrep(inputs: Inputs.OCCT.LoadBrepDto): Promise<Inputs.OCCT.TopoDSShapePointer> {
        const brepData = await this.occWorkerManager.prepareStepData(inputs.brepData);
        return this.occWorkerManager.genericCallToWorkerPromise("io.loadBrep", { ...inputs, brepData });
    }

    /**
     * Turns the wires of a shape into DXF path records, the first step of a 2D DXF export.
     *
     * The shape must lie flat on the XZ ground plane, since DXF drawings are two-dimensional. The
     * deflection settings say how closely curved edges are followed. Give the paths a layer with
     * `dxfPathsWithLayer` and write the file with `dxfCreate`.
     * @param inputs - The shape and the deflection settings
     * @returns The DXF paths
     * @group dxf
     * @shortname shape to dxf paths
     * @drawable false
     * @example
     * ```typescript
     * const paths = await bitbybit.occt.io.shapeToDxfPaths({
     *     shape: flatOutline,
     *     angularDeflection: 0.1,
     *     curvatureDeflection: 0.1,
     *     minimumOfPoints: 2,
     *     uTolerance: 1e-9,
     *     minimumLength: 1e-7,
     * });
     * ```
     */
    shapeToDxfPaths(inputs: Inputs.OCCT.ShapeToDxfPathsDto<Inputs.OCCT.TopoDSShapePointer>): Promise<IO.DxfPathDto[]> {
        return this.occWorkerManager.genericCallToWorkerPromise("io.shapeToDxfPaths", inputs);
    }

    /**
     * Puts DXF paths on a named layer with a color, making one part of a DXF drawing.
     *
     * A drawing may hold several parts, each with its own layer and color; `dxfCreate` writes them
     * into one file.
     * @param inputs - The paths, the layer name and the color
     * @returns The paths as one layered part
     * @group dxf
     * @shortname dxf paths with layer
     * @drawable false
     * @example
     * ```typescript
     * const part = await bitbybit.occt.io.dxfPathsWithLayer({ paths, layer: "cut", color: "#ff0000" });
     * ```
     */
    dxfPathsWithLayer(inputs: Inputs.OCCT.DxfPathsWithLayerDto): Promise<IO.DxfPathsPartDto> {
        return this.occWorkerManager.genericCallToWorkerPromise("io.dxfPathsWithLayer", inputs);
    }

    /**
     * Writes DXF parts into one DXF file and returns its text.
     *
     * `colorFormat` chooses AutoCAD's indexed colors or true color, `acadVersion` the DXF version:
     * AC1009 is R12, the most widely readable, AC1015 is 2000. `fileName` and `tryDownload` matter
     * only where a browser download can be started.
     * @param inputs - The layered parts, the color format, the DXF version and the download options
     * @returns The DXF file as text
     * @group dxf
     * @shortname dxf create
     * @drawable false
     * @example
     * ```typescript
     * const dxf = await bitbybit.occt.io.dxfCreate({
     *     pathsParts: [part],
     *     colorFormat: Bit.Inputs.OCCT.dxfColorFormatEnum.aci,
     *     acadVersion: Bit.Inputs.OCCT.dxfAcadVersionEnum.AC1009,
     *     fileName: "drawing.dxf",
     *     tryDownload: false,
     * });
     * ```
     */
    dxfCreate(inputs: Inputs.OCCT.DxfPathsPartsListDto): Promise<string> {
        const resolved = resolveDto(Inputs.OCCT.DxfPathsPartsListDto, inputs) as Resolved.OCCT.DxfPathsPartsListDto;
        return this.occWorkerManager.genericCallToWorkerPromise<string>("io.dxfCreate", resolved).then(s => {
            if (resolved.tryDownload && document) {
                const blob = new Blob([s], { type: "application/stl" });
                const blobUrl = URL.createObjectURL(blob);

                const fileName = resolved.fileName;

                const fileLink = document.createElement("a");
                fileLink.href = blobUrl;
                fileLink.target = "_self";
                fileLink.download = fileName;
                fileLink.click();
                fileLink.remove();
            }
            return s;
        });
    }

    /**
     * Converts a STEP file into a binary glTF (GLB), keeping the assembly tree as glTF nodes along
     * with part names, colors, materials and placements.
     *
     * `stepData` is the file as text, ArrayBuffer or Uint8Array. The mesh settings say how finely
     * curved surfaces are triangulated: `meshPrecision` is the deflection, `meshAngle` the angular
     * deflection. Z-up becomes glTF's Y-up. Failure throws.
     * @param inputs - The STEP file content and the meshing settings
     * @returns The GLB file as bytes
     * @group assembly
     * @shortname step to gltf
     * @drawable false
     * @example
     * ```typescript
     * const glb = await bitbybit.occt.io.convertStepToGltf({ stepData: stepText, meshPrecision: 0.005, meshAngle: 0.5, meshRelative: true, internalVerticesMode: false, controlSurfaceDeflection: false });
     * ```
     */
    async convertStepToGltf(inputs: Inputs.OCCT.ConvertStepToGltfDto): Promise<Uint8Array> {
        const resolved = resolveDto(Inputs.OCCT.ConvertStepToGltfDto, inputs) as Resolved.OCCT.ConvertStepToGltfDto;
        const stepData = await this.occWorkerManager.prepareStepData(resolved.stepData);
        return this.occWorkerManager.genericCallToWorkerPromise("io.convertStepToGltf", { ...resolved, stepData });
    }

    /**
     * Converts a STEP file into a binary glTF (GLB) like `convertStepToGltf`, with every option
     * exposed.
     *
     * The read flags choose what to take from the file (colors, names, materials, layers,
     * properties), the mesh settings how finely to triangulate, the export settings how the glTF is
     * written (merged faces, 16-bit indexes, naming, scale). Switch off what you do not need.
     * @param inputs - The STEP file content and the reading, meshing and export settings
     * @returns The GLB file as bytes
     * @group assembly
     * @shortname step to gltf advanced
     * @drawable false
     * @example
     * ```typescript
     * const options = new Bit.Inputs.OCCT.ConvertStepToGltfAdvancedDto();
     * options.stepData = stepText;
     * options.readColors = true;
     * options.readNames = true;
     * options.meshDeflection = 0.005;
     * options.mergeFaces = true;
     * options.adjustZtoY = true;
     * const glb = await bitbybit.occt.io.convertStepToGltfAdvanced(options);
     * ```
     */
    async convertStepToGltfAdvanced(inputs: Inputs.OCCT.ConvertStepToGltfAdvancedDto): Promise<Uint8Array> {
        const resolved = resolveDto(Inputs.OCCT.ConvertStepToGltfAdvancedDto, inputs) as Resolved.OCCT.ConvertStepToGltfAdvancedDto;
        const stepData = await this.occWorkerManager.prepareStepData(resolved.stepData);
        return this.occWorkerManager.genericCallToWorkerPromise("io.convertStepToGltfAdvanced", { ...resolved, stepData });
    }

    /**
     * Converts a STEP file into a binary glTF (GLB) like `convertStepToGltf` and compresses the
     * geometry with Draco, which makes the file much smaller at the cost of a Draco-capable loader.
     *
     * The Draco settings set the compression level and how many bits positions, normals, texture
     * coordinates and colors keep; fewer bits mean a smaller file and less precision.
     * @param inputs - The STEP file content, the meshing settings and the Draco settings
     * @returns The GLB file as bytes
     * @group assembly
     * @shortname step to gltf with draco
     * @drawable false
     * @example
     * ```typescript
     * const options = new Bit.Inputs.OCCT.ConvertStepToGltfWithDracoDto();
     * options.stepData = stepText;
     * options.meshPrecision = 0.005;
     * options.dracoCompressionLevel = 7;
     * options.dracoQuantizePositionBits = 14;
     * const glb = await bitbybit.occt.io.convertStepToGltfWithDraco(options);
     * ```
     */
    async convertStepToGltfWithDraco(inputs: Inputs.OCCT.ConvertStepToGltfWithDracoDto): Promise<Uint8Array> {
        const resolved = resolveDto(Inputs.OCCT.ConvertStepToGltfWithDracoDto, inputs) as Resolved.OCCT.ConvertStepToGltfWithDracoDto;
        const stepData = await this.occWorkerManager.prepareStepData(resolved.stepData);
        return this.occWorkerManager.genericCallToWorkerPromise("io.convertStepToGltfWithDraco", { ...resolved, stepData });
    }

    /**
     * Converts a STEP file into a binary glTF (GLB) with every reading, meshing and writing option
     * exposed, as `convertStepToGltfAdvanced` does, and compresses the geometry with Draco.
     *
     * The Draco settings set the compression level and how many bits positions, normals, texture
     * coordinates and colors keep; fewer bits mean a smaller file and less precision.
     * @param inputs - The STEP file content, the reading, meshing and export settings, and the Draco settings
     * @returns The GLB file as bytes
     * @group assembly
     * @shortname step to gltf advanced with draco
     * @drawable false
     * @example
     * ```typescript
     * const options = new Bit.Inputs.OCCT.ConvertStepToGltfAdvancedWithDracoDto();
     * options.stepData = stepText;
     * options.readColors = true;
     * options.meshDeflection = 0.005;
     * options.dracoCompressionLevel = 7;
     * const glb = await bitbybit.occt.io.convertStepToGltfAdvancedWithDraco(options);
     * ```
     */
    async convertStepToGltfAdvancedWithDraco(inputs: Inputs.OCCT.ConvertStepToGltfAdvancedWithDracoDto): Promise<Uint8Array> {
        const resolved = resolveDto(Inputs.OCCT.ConvertStepToGltfAdvancedWithDracoDto, inputs) as Resolved.OCCT.ConvertStepToGltfAdvancedWithDracoDto;
        const stepData = await this.occWorkerManager.prepareStepData(resolved.stepData);
        return this.occWorkerManager.genericCallToWorkerPromise("io.convertStepToGltfAdvancedWithDraco", { ...resolved, stepData });
    }

    /**
     * Reads the assembly structure of a STEP file without building geometry: every part and
     * sub-assembly as a node with its id, name, whether it is an assembly, its visibility, its
     * color and its placement matrix.
     *
     * The nodes come in depth-first order, so children follow their parent. A file that cannot be
     * parsed reports its error in the result.
     * @param inputs - The STEP file content
     * @returns The list of nodes, the format version and any error
     * @group assembly
     * @shortname parse step to json
     * @drawable false
     * @example
     * ```typescript
     * const tree = await bitbybit.occt.io.parseStepToJson({ stepData: stepText });
     * console.log(tree.nodes.map(n => n.name));
     * ```
     */
    async parseStepToJson(inputs: Inputs.OCCT.ParseStepAssemblyToJsonDto): Promise<Models.OCCT.AssemblyJsonResult> {
        // Convert File/Blob to ArrayBuffer before sending to worker
        const stepData = await this.occWorkerManager.prepareStepData(inputs.stepData);
        const preparedInputs = {
            ...inputs,
            stepData
        };
        return this.occWorkerManager.genericCallToWorkerPromise("io.parseStepToJson", preparedInputs);
    }
}
