// GENERATED by scripts/gen-worker-api.mjs from packages/dev/occt/lib/services/shape-fix.ts - do not edit.
// The kernel class is the source of the docs, the signatures and the member order.
// Regenerate with `npm run gen:worker-api` at the repository root.
import { Inputs, Models } from "@bitbybit-dev/occt";
import { OCCTWorkerManager } from "../../occ-worker/occ-worker-manager";

/**
 * Checks and repairs for OpenCascade shapes that came out of a file or an operation with defects:
 * gaps between edges, edges too short to matter, faces turned the wrong way, shells left open,
 * tolerances that drifted. `validityReport` says what is wrong and where, and `freeBoundaries` shows
 * the rims of openings; `basicShapeRepair` is the general fix, the shell, solid and sewing fixes and
 * the wire fixes handle the rest. Every repair returns a new shape.
 */
export class OCCTShapeFix {
    constructor(
        private readonly occWorkerManager: OCCTWorkerManager,
    ) {
    }

    /**
     * Runs the kernel's general repair over a shape: closes small gaps, fixes wire and face defects
     * and brings tolerances into the given range.
     *
     * `precision` is the size of defect to look for, `minTolerance` and `maxTolerance` bound the
     * tolerances the repaired shape may carry, all in model units. Try it first on any shape that
     * fails `shapes.shape.isValid`.
     * @param inputs - The shape and the precision and tolerance bounds
     * @returns The repaired shape
     * @group shape
     * @shortname basic shape repair
     * @drawable true
     * @example
     * ```typescript
     * const fixed = await bitbybit.occt.shapeFix.basicShapeRepair({ shape: imported, precision: 0.001, maxTolerance: 0.01, minTolerance: 0.0001 });
     * ```
     */
    basicShapeRepair(inputs: Inputs.OCCT.BasicShapeRepairDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.basicShapeRepair", inputs);
    }

    /**
     * Removes edges shorter than `precsmall` from a wire and closes the gaps they leave, so a tiny
     * sliver no longer breaks a fillet or a face.
     *
     * With `lockvtx` true the existing vertices are kept in place; otherwise they may move to close
     * the gap. A `precsmall` of 0 uses the wire's own tolerance.
     * @param inputs - The wire, whether to keep vertices fixed and the length below which an edge counts as small
     * @returns The cleaned wire
     * @group wire
     * @shortname fix small edge
     * @drawable true
     * @example
     * ```typescript
     * const clean = await bitbybit.occt.shapeFix.fixSmallEdgeOnWire({ shape: wire, lockvtx: false, precsmall: 0.001 });
     * ```
     */
    fixSmallEdgeOnWire(inputs: Inputs.OCCT.FixSmallEdgesInWireDto<Inputs.OCCT.TopoDSWirePointer>): Promise<Inputs.OCCT.TopoDSWirePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.fixSmallEdgeOnWire", inputs);
    }

    /**
     * Rebuilds a wire so its edges run head to tail in one direction along it.
     *
     * A wire assembled from loose edges can hold edges pointing against the flow; this walks the
     * wire in order and joins the edges again the right way round, which some operations need.
     * @param inputs - The wire
     * @returns The wire with consistently oriented edges
     * @group wire
     * @shortname fix edge orientations
     * @drawable true
     * @example
     * ```typescript
     * const ordered = await bitbybit.occt.shapeFix.fixEdgeOrientationsAlongWire({ shape: wire });
     * ```
     */
    fixEdgeOrientationsAlongWire(inputs: Inputs.OCCT.ShapeDto<Inputs.OCCT.TopoDSWirePointer>): Promise<Inputs.OCCT.TopoDSWirePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.fixEdgeOrientationsAlongWire", inputs);
    }

    /**
     * Checks a shape as `shapes.shape.isValid` does and reports each faulty sub-shape with the checks
     * it fails, and the spread of its tolerances.
     *
     * A fault's index is the one the getter of its kind uses: `shapes.face.getFace` with a face
     * fault's index gives that face. Overlapping faces are not looked for;
     * `analysis.clashes.selfIntersections` finds those.
     * @param inputs - The shape to check
     * @returns Whether the shape is valid, its faults and its smallest, largest and average tolerance
     * @group shape
     * @shortname validity report
     * @drawable false
     * @example
     * ```typescript
     * const report = await bitbybit.occt.shapeFix.validityReport({ shape: imported });
     * const badFaces = report.faults.filter(fault => fault.type === Bit.Inputs.OCCT.shapeTypeEnum.face).map(fault => fault.index);
     * ```
     */
    validityReport(inputs: Inputs.OCCT.ShapeDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.ValidityReport> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.validityReport", inputs);
    }

    /**
     * Finds the edges of a shape that bound only one face, joined into wires: the rims of an open
     * shell's openings, or a lone face's outline and holes.
     *
     * Wires that close on themselves come back in `closed`, the rest in `open`; a closed solid has
     * none. Edges closer than `tolerance`, in model units, count as one.
     * @param inputs - The shape and the tolerance
     * @returns Two compounds of wires, the closed and the open ones
     * @group shape
     * @shortname free boundaries
     * @drawable false
     * @example
     * ```typescript
     * const rims = await bitbybit.occt.shapeFix.freeBoundaries({ shape: openShell, tolerance: 1e-7 });
     * const holes = await bitbybit.occt.shapes.wire.getWires({ shape: rims.closed });
     * ```
     */
    freeBoundaries(inputs: Inputs.OCCT.ShapeWithToleranceDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.FreeBoundaries<Inputs.OCCT.TopoDSCompoundPointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.freeBoundaries", inputs);
    }

    /**
     * Repairs a shell: turns its faces so they all face the same way and fixes its faces and edges.
     *
     * When the faces cannot all be turned one way, as on a strip given a half twist, the result is
     * a compound of shells. A shape that is not a shell is refused.
     * @param inputs - The shell to repair
     * @returns The repaired shell, or a compound of shells
     * @group shell
     * @shortname fix shell
     * @drawable true
     * @example
     * ```typescript
     * const shell = await bitbybit.occt.shapes.shell.sewFaces({ shapes: faces, tolerance: 1e-7 });
     * const fixed = await bitbybit.occt.shapeFix.fixShell({ shape: shell });
     * ```
     */
    fixShell(inputs: Inputs.OCCT.ShapeDto<Inputs.OCCT.TopoDSShellPointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.fixShell", inputs);
    }

    /**
     * Repairs a solid, or makes one from a closed shell, with its shells fixed and turned so the
     * material is inside.
     *
     * A shell that encloses nothing comes back fixed but still a shell, and shells that fix into
     * separate solids come back as a compound of them. Other kinds of shape are refused.
     * @param inputs - The solid or shell to repair
     * @returns The repaired solid, or a shell or a compound when no single solid can be made
     * @group solid
     * @shortname fix solid
     * @drawable true
     * @example
     * ```typescript
     * const shell = await bitbybit.occt.shapes.shell.sewFaces({ shapes: faces, tolerance: 1e-7 });
     * const solid = await bitbybit.occt.shapeFix.fixSolid({ shape: shell });
     * ```
     */
    fixSolid(inputs: Inputs.OCCT.ShapeDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.fixSolid", inputs);
    }

    /**
     * Turns a closed solid so its material is inside, which gives an inside-out solid its positive
     * volume back; only the orientation changes.
     *
     * A shape that is not a solid, a solid without a shell and a solid whose shell has an opening
     * are refused.
     * @param inputs - The closed solid
     * @returns The solid, oriented with its material inside
     * @group solid
     * @shortname orient closed solid
     * @drawable true
     * @example
     * ```typescript
     * const oriented = await bitbybit.occt.shapeFix.orientClosedSolid({ shape: insideOut });
     * const volume = await bitbybit.occt.shapes.solid.getSolidVolume({ shape: oriented });
     * ```
     */
    orientClosedSolid(inputs: Inputs.OCCT.ShapeDto<Inputs.OCCT.TopoDSSolidPointer>): Promise<Inputs.OCCT.TopoDSSolidPointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.orientClosedSolid", inputs);
    }

    /**
     * Sews the faces of shapes together along edges that lie within `tolerance` of each other, as
     * `shapes.shell.sewFaces` does, and reports what it joined and what it left open.
     *
     * `freeEdges` holds the edges left bounding only one face; with `nonManifold` true an edge may
     * join more than two faces. The shapes given are left as they were.
     * @param inputs - The shapes, the tolerance and whether an edge may join more than two faces
     * @returns The sewn shape, the free edges and the counts of free, multiple, sewn and degenerate edges
     * @group shape
     * @shortname sew with report
     * @drawable false
     * @example
     * ```typescript
     * const sewn = await bitbybit.occt.shapeFix.sewWithReport({ shapes: faces, tolerance: 1e-4, nonManifold: false });
     * const closed = sewn.freeEdgeCount === 0;
     * ```
     */
    sewWithReport(inputs: Inputs.OCCT.SewWithReportDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Models.OCCT.SewReport<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("shapeFix.sewWithReport", inputs);
    }
}
