/* eslint-disable @typescript-eslint/no-namespace */
import { Base } from "./base-inputs";
// GENERATED by scripts/gen-inputs.mjs from the fragments in ./jscad/ - do not edit; edit a fragment and run `npm run gen:inputs`.

/**
 * Every parameter object the JSCAD kernel accepts. JSCAD models by combining primitives with
 * booleans, expansions, hulls and extrusions, working on tessellated geometry rather than exact
 * surfaces, so its DTOs carry mesh-level settings - segment counts, corner styles, expansion deltas -
 * where the OCCT equivalents would carry tolerances.
 * 
 * It is lighter and quicker to start with than OCCT and a good fit when a shape is a combination of
 * simple volumes and manufacturing-grade surface accuracy is not required. Names repeat across
 * kernels: the CircleDto here is not the one in Inputs.OCCT.
 */
export namespace JSCAD {
    /** A 2D point or vector, `[x, y]`. */
    export type JSCADVec2 = [number, number];

    /** A 3D point or vector, `[x, y, z]`. */
    export type JSCADVec3 = [number, number, number];

    /** A 4x4 transformation matrix, in column-major order. */
    export type JSCADMat4 = [
        number, number, number, number,
        number, number, number, number,
        number, number, number, number,
        number, number, number, number,
    ];

    /** A plane, `[normalX, normalY, normalZ, distanceFromOrigin]`. */
    export type JSCADPlane = [number, number, number, number];

    /** A color, either `[r, g, b]` or `[r, g, b, a]`, each channel from 0 to 1. */
    export type JSCADColor = [number, number, number] | [number, number, number, number];

    /** A convex polygon in 3D - the face of a solid. */
    export type JSCADPoly3 = {
        vertices: JSCADVec3[];
        color?: JSCADColor;
        plane?: JSCADPlane;
    };

    /** 2D geometry: a closed region, held as the edges that bound it. */
    export type JSCADGeom2 = {
        sides: [JSCADVec2, JSCADVec2][];
        transforms: JSCADMat4;
        color?: JSCADColor;
    };

    /** 3D geometry: a solid, held as the polygons that enclose it. */
    export type JSCADGeom3 = {
        polygons: JSCADPoly3[];
        transforms: JSCADMat4;
        color?: JSCADColor;
    };

    /** A 2D path: an open or closed sequence of points, with no enclosed area. */
    export type JSCADPath2 = {
        points: JSCADVec2[];
        isClosed: boolean;
        transforms: JSCADMat4;
        color?: JSCADColor;
    };

    /**
     * Anything JSCAD hands back: a 2D region, a 3D solid, or a 2D path. The three share no members
     * beyond their transform, so narrow on the one you want - `"polygons" in entity` for a solid,
     * `"isClosed" in entity` for a path, `"sides" in entity` for a 2D region.
     *
     * These are structural mirrors of the library's own types rather than imports of them, so the
     * published declarations stay self-contained; jscad-entity.test.ts fails the build if the two
     * ever stop matching.
     */
    export type JSCADEntity = JSCADGeom2 | JSCADGeom3 | JSCADPath2;

    /** A geometry flattened for rendering: triangle positions, normals, indices and its transform. */
    export type JSCADMeshData = {
        positions: number[];
        normals: number[];
        indices: number[];
        transforms: JSCADMat4;
    };

    /**
     * A polyline as a plain list of points, the form `polygon.createFromPolyline`,
     * `path.createFromPolyline` and `path.appendPolyline` read; only X and Y of each point are used by
     * them.
     */
    export class PolylinePropertiesDto {
        /**
         * Provide options without default values
         */
        constructor(points?: Base.Point3[], isClosed?: boolean) {
            if (points !== undefined) { this.points = points; }
            if (isClosed !== undefined) { this.isClosed = isClosed; }
        }
        /**
         * The corner points in order, given in 3D; JSCAD methods use only X and Y
         */
        points!: Base.Point3[];
        /**
         * Whether the last point joins back to the first; the JSCAD methods decide closure on their own
         * and ignore this flag
         */
        isClosed?: boolean | undefined = false;
        /**
         * A color carried along with the polyline for drawing, as a hex string or an RGB list; the
         * JSCAD methods ignore it
         */
        color?: string | number[] | undefined;
    }
    /**
     * How the corners of an expanded or rounded solid are formed.
     */
    export enum solidCornerTypeEnum {
        /**
         * Edges will meet at a corner
         */
        edge = "edge",
        /**
         * Edges will be rounded on the corner
         */
        round = "round",
        /**
         * Edges will be chamfered on the corner
         */
        chamfer = "chamfer",
    }
    /**
     * Horizontal alignment of JSCAD text against its anchor point.
     */
    export enum jscadTextAlignEnum {
        /**
         * Aligns text to the left
         */
        left = "left",
        /**
         * Aligns text to the center
         */
        center = "center",
        /**
         * Aligns text to the right
         */
        right = "right",
    }
    /**
     * Feeds `toPolygonPoints` and `shapeToMesh` on the JSCAD service with the one entity to turn into
     * triangles or mesh data; a 2D shape is given a tiny thickness on the way.
     */
    export class MeshDto {
        constructor(mesh?: JSCADEntity) {
            if (mesh !== undefined) { this.mesh = mesh; }
        }
        /**
         * The solid to convert; a flat 2D shape works too and is given a tiny thickness first
         */
        mesh!: JSCADEntity;
    }

    /**
     * Feeds `shapesToMeshes` on the JSCAD service with the entities to turn into mesh data, one result
     * per entry in the same order.
     */
    export class MeshesDto {
        constructor(meshes?: JSCADEntity[]) {
            if (meshes !== undefined) { this.meshes = meshes; }
        }
        /**
         * The solids to convert, in the order the results should come back; flat 2D shapes work too
         */
        meshes!: JSCADEntity[];
    }
    /**
     * The options `draw.drawAnyAsync` passes on when the entity is one JSCAD solid or 2D shape: color,
     * opacity, visibility, the two-sided rendering and the mesh to reuse when redrawing.
     */
    export class DrawSolidMeshDto<T> {
        /**
         * Provide options without default values
         */
        constructor(mesh?: JSCADEntity, opacity?: number, colours?: string | string[], updatable?: boolean, hidden?: boolean, jscadMesh?: T, drawTwoSided?: boolean, backFaceColour?: string, backFaceOpacity?: number) {
            if (mesh !== undefined) { this.mesh = mesh; }
            if (opacity !== undefined) { this.opacity = opacity; }
            if (colours !== undefined) { this.colours = colours; }
            if (updatable !== undefined) { this.updatable = updatable; }
            if (hidden !== undefined) { this.hidden = hidden; }
            if (jscadMesh !== undefined) { this.jscadMesh = jscadMesh; }
            if (drawTwoSided !== undefined) { this.drawTwoSided = drawTwoSided; }
            if (backFaceColour !== undefined) { this.backFaceColour = backFaceColour; }
            if (backFaceOpacity !== undefined) { this.backFaceOpacity = backFaceOpacity; }
        }
        /**
         * The solid or flat 2D shape to draw; it is converted to mesh data on the way
         */
        mesh!: JSCADEntity;
        /**
         * How opaque the faces are, from 0 for invisible to 1 for solid
         * @default 1
         * @minimum 0
         * @maximum 1
         * @step 0.1
         */
        opacity = 1;
        /**
         * Hex color of the faces; a list uses its first entry. An entity colored with `colors.colorize`
         * keeps its own color instead
         * @default #444444
         */
        colours: string | string[] = "#444444";
        /**
         * When true, the drawn mesh can be refreshed in place on later draws by passing it back as
         * `jscadMesh`
         * @default false
         */
        updatable = false;
        /**
         * When true, the mesh is created but not shown until it is made visible
         * @default false
         */
        hidden = false;
        /**
         * A mesh from an earlier draw to refresh instead of creating a new one; used only when
         * `updatable` is true
         * @default undefined
         * @optional true
         * @ignore true
         */
        jscadMesh?: T | undefined;
        /**
         * When true, the back of every face is drawn as well, in `backFaceColour`, which helps to see
         * face orientation
         * @default true
         */
        drawTwoSided = true;
        /**
         * Hex color of the back faces, the side the face normal points away from; used only when
         * `drawTwoSided` is true
         * @default #0000ff
         */
        backFaceColour = "#0000ff";
        /**
         * How opaque the back faces are, from 0 to 1; used only when `drawTwoSided` is true
         * @default 1
         * @minimum 0
         * @maximum 1
         * @step 0.1
         */
        backFaceOpacity = 1;
    }
    /**
     * The options `draw.drawAnyAsync` passes on when the entity is a list of JSCAD solids or 2D shapes:
     * colors, opacity, visibility, the two-sided rendering and the parent mesh to reuse when redrawing.
     */
    export class DrawSolidMeshesDto<T> {
        /**
         * Provide options without default values
         */
        constructor(meshes?: JSCADEntity[], opacity?: number, colours?: string | string[], updatable?: boolean, hidden?: boolean, jscadMesh?: T, drawTwoSided?: boolean, backFaceColour?: string, backFaceOpacity?: number) {
            if (meshes !== undefined) { this.meshes = meshes; }
            if (opacity !== undefined) { this.opacity = opacity; }
            if (colours !== undefined) { this.colours = colours; }
            if (updatable !== undefined) { this.updatable = updatable; }
            if (hidden !== undefined) { this.hidden = hidden; }
            if (jscadMesh !== undefined) { this.jscadMesh = jscadMesh; }
            if (drawTwoSided !== undefined) { this.drawTwoSided = drawTwoSided; }
            if (backFaceColour !== undefined) { this.backFaceColour = backFaceColour; }
            if (backFaceOpacity !== undefined) { this.backFaceOpacity = backFaceOpacity; }
        }
        /**
         * The solids or flat 2D shapes to draw, each becoming a child of one parent mesh
         * @default undefined
         * @optional true
         */
        meshes!: JSCADEntity[];
        /**
         * How opaque the faces are, from 0 for invisible to 1 for solid
         * @default 1
         * @minimum 0
         * @maximum 1
         * @step 0.1
         */
        opacity = 1;
        /**
         * Hex color of the faces; a list with one entry per entity colors each in turn, any other list
         * uses its first entry. Colorized entities keep their own color
         * @default #444444
         */
        colours: string | string[] = "#444444";
        /**
         * When true, the drawn meshes can be refreshed in place on later draws by passing the parent
         * back as `jscadMesh`
         * @default false
         */
        updatable = false;
        /**
         * When true, the meshes are created but not shown until they are made visible
         * @default false
         */
        hidden = false;
        /**
         * The parent mesh from an earlier draw to refresh instead of creating a new one; used only when
         * `updatable` is true
         * @default undefined
         * @optional true
         * @ignore true
         */
        jscadMesh?: T | undefined;
        /**
         * When true, the back of every face is drawn as well, in `backFaceColour`, which helps to see
         * face orientation
         * @default true
         */
        drawTwoSided = true;
        /**
         * Hex color of the back faces, the side the face normal points away from; used only when
         * `drawTwoSided` is true
         * @default #0000ff
         */
        backFaceColour = "#0000ff";
        /**
         * How opaque the back faces are, from 0 to 1; used only when `drawTwoSided` is true
         * @default 1
         * @minimum 0
         * @maximum 1
         * @step 0.1
         */
        backFaceOpacity = 1;
    }
    /**
     * The options `draw.drawAnyAsync` passes on when the entity is a JSCAD 2D path, drawn as a line
     * through its points: color, opacity, line width and the line to reuse when redrawing.
     */
    export class DrawPathDto<T> {
        /**
         * Provide options without default values
         */
        constructor(path?: JSCADEntity, colour?: string, opacity?: number, width?: number, updatable?: boolean, pathMesh?: T) {
            if (path !== undefined) { this.path = path; }
            if (colour !== undefined) { this.colour = colour; }
            if (opacity !== undefined) { this.opacity = opacity; }
            if (width !== undefined) { this.width = width; }
            if (updatable !== undefined) { this.updatable = updatable; }
            if (pathMesh !== undefined) { this.pathMesh = pathMesh; }
        }
        /**
         * The 2D path to draw as a line; a closed path is drawn back to its first point
         * @default undefined
         */
        path!: JSCADEntity;
        /**
         * Hex color of the line; a path colored with `colors.colorize` keeps its own color instead
         * @default #444444
         */
        colour = "#444444";
        /**
         * How opaque the line is, from 0 for invisible to 1 for solid
         * @default 1
         * @minimum 0
         * @maximum 1
         * @step 0.1
         */
        opacity = 1;
        /**
         * Thickness of the drawn line
         * @default 10
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        width = 10;
        /**
         * When true, the drawn line can be refreshed in place on later draws by passing it back as
         * `pathMesh`
         * @default false
         */
        updatable = false;
        /**
         * A line from an earlier draw to refresh instead of creating a new one; used only when
         * `updatable` is true
         * @default undefined
         * @optional true
         * @ignore true
         */
        pathMesh?: T | undefined;
    }
    /**
     * Feeds `transformSolids` on the JSCAD service: the solids to move and the matrix, or matrices,
     * applied to each of them.
     */
    export class TransformSolidsDto {
        constructor(meshes?: JSCADEntity[], transformation?: Base.TransformMatrixes) {
            if (meshes !== undefined) { this.meshes = meshes; }
            if (transformation !== undefined) { this.transformation = transformation; }
        }
        /**
         * The solids to transform; they stay as they are and transformed copies come back in the same
         * order
         * @default undefined
         */
        meshes!: JSCADEntity[];
        /**
         * One 4x4 matrix, a list of matrices applied in order, or a list of such lists, as the
         * `transforms` methods produce
         * @default undefined
         */
        transformation!: Base.TransformMatrixes;
    }
    /**
     * Feeds `transformSolid` on the JSCAD service: the solid to move and the matrix, or matrices,
     * applied to it.
     */
    export class TransformSolidDto {
        constructor(mesh?: JSCADEntity, transformation?: Base.TransformMatrixes) {
            if (mesh !== undefined) { this.mesh = mesh; }
            if (transformation !== undefined) { this.transformation = transformation; }
        }
        /**
         * The solid to transform; it stays as it is and a transformed copy comes back. A 2D shape or a
         * path throws an error
         * @default undefined
         */
        mesh!: JSCADEntity;
        /**
         * One 4x4 matrix, a list of matrices applied in order, or a list of such lists, as the
         * `transforms` methods produce
         * @default undefined
         */
        transformation!: Base.TransformMatrixes;
    }
    /**
     * Feeds `downloadSolidSTL` on the JSCAD service: the solid to write and the name of the STL file.
     */
    export class DownloadSolidDto {
        constructor(mesh?: JSCADEntity, fileName?: string) {
            if (mesh !== undefined) { this.mesh = mesh; }
            if (fileName !== undefined) { this.fileName = fileName; }
        }
        /**
         * The solid to write to the file
         * @default undefined
         */
        mesh!: JSCADEntity;
        /**
         * Name of the downloaded file without the extension, which is added
         * @default undefined
         */
        fileName!: string;
    }
    /**
     * Feeds `downloadGeometryDxf` and `downloadGeometry3MF` on the JSCAD service: the geometry to
     * write, the file name and optional options for the file writer.
     */
    export class DownloadGeometryDto {
        constructor(geometry?: JSCADEntity | JSCADEntity[], fileName?: string, options?: any) {
            if (geometry !== undefined) { this.geometry = geometry; }
            if (fileName !== undefined) { this.fileName = fileName; }
            if (options !== undefined) { this.options = options; }
        }
        /**
         * A solid, a 2D shape, a path, or a list of them, all written into one file
         * @default undefined
         */
        geometry!: JSCADEntity | JSCADEntity[];
        /**
         * Name of the downloaded file without the extension, which is added
         * @default jscad-geometry
         */
        fileName = "jscad-geometry";
        /**
         * Options handed to the DXF or 3MF writer as they are; leave it out for the defaults
         * @default undefined
         * @optional true
         */
        options;
    }
    /**
     * Feeds `downloadSolidsSTL` on the JSCAD service: the solids to write into one STL file and the
     * file's name.
     */
    export class DownloadSolidsDto {
        constructor(meshes?: JSCADEntity[], fileName?: string) {
            if (meshes !== undefined) { this.meshes = meshes; }
            if (fileName !== undefined) { this.fileName = fileName; }
        }
        /**
         * The solids to write, all into the same file
         * @default undefined
         */
        meshes!: JSCADEntity[];
        /**
         * Name of the downloaded file without the extension, which is added
         * @default undefined
         */
        fileName!: string;
    }
    /**
     * Feeds `colors.colorize`: the geometry to tint, one entity or a list, and the color it is drawn in
     * from then on.
     */
    export class ColorizeDto {
        constructor(geometry?: JSCADEntity, color?: string) {
            if (geometry !== undefined) { this.geometry = geometry; }
            if (color !== undefined) { this.color = color; }
        }
        /**
         * A solid, a 2D shape, a path, or a list of them; colored copies come back in the same shape as
         * the input
         * @default undefined
         */
        geometry!: JSCADEntity | JSCADEntity[];
        /**
         * Hex color string the geometry is always drawn in, ahead of the drawing options
         * @default #0000ff
         */
        color = "#0000ff";
    }
    /**
     * Feeds `booleans.union`, `booleans.intersect` and `booleans.subtract` with any number of inputs;
     * for `subtract` the first entry is the one being cut. All entries must be of one kind, solids or
     * 2D shapes.
     */
    export class BooleanObjectsDto {
        constructor(meshes?: JSCADEntity[]) {
            if (meshes !== undefined) { this.meshes = meshes; }
        }
        /**
         * The solids, or the 2D shapes, to combine; the inputs stay as they are and a new entity comes
         * back
         * @default undefined
         */
        meshes!: JSCADEntity[];
    }
    /**
     * Feeds `booleans.unionTwo`, `booleans.intersectTwo` and `booleans.subtractTwo` with exactly two
     * inputs of one kind, solids or 2D shapes; for `subtractTwo`, `second` is cut out of `first`.
     */
    export class BooleanTwoObjectsDto {
        constructor(first?: JSCADEntity, second?: JSCADEntity) {
            if (first !== undefined) { this.first = first; }
            if (second !== undefined) { this.second = second; }
        }
        /**
         * The first solid or 2D shape, the one that is kept and cut in a subtraction
         * @default undefined
         */
        first!: JSCADEntity;
        /**
         * The second solid or 2D shape, of the same kind as `first`
         * @default undefined
         */
        second!: JSCADEntity;
    }
    /**
     * Feeds `booleans.subtractFrom`: `from` is the base and every entry of `meshes` is cut out of it.
     * All must be of one kind, solids or 2D shapes.
     */
    export class BooleanObjectsFromDto {
        constructor(from?: JSCADEntity, meshes?: JSCADEntity[]) {
            if (from !== undefined) { this.from = from; }
            if (meshes !== undefined) { this.meshes = meshes; }
        }
        /**
         * The solid or 2D shape to cut from; it stays as it is and a cut copy comes back
         * @default undefined
         */
        from!: JSCADEntity;
        /**
         * The solids or 2D shapes to cut out of `from`, of the same kind as it
         * @default undefined
         */
        meshes!: JSCADEntity[];
    }
    /**
     * Feeds `expansions.expand` and `expansions.offset`: the geometry, the signed distance to move its
     * boundary by and how the corners are shaped on the way.
     */
    export class ExpansionDto {
        constructor(geometry?: JSCADEntity, delta?: number, corners?: solidCornerTypeEnum, segments?: number) {
            if (geometry !== undefined) { this.geometry = geometry; }
            if (delta !== undefined) { this.delta = delta; }
            if (corners !== undefined) { this.corners = corners; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The 2D shape, path or solid to grow; `offset` takes 2D shapes and paths only. It stays as it
         * is and a new entity comes back
         * @default undefined
         */
        geometry!: JSCADEntity;
        /**
         * How far the boundary moves, in model units: positive grows the geometry, negative shrinks it
         * (a solid accepts positive only)
         * @default 0.1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        delta = 0.1;
        /**
         * How a convex corner is shaped: `edge` keeps it sharp, `chamfer` cuts it flat, `round` curves
         * it; a solid accepts `round` only
         * @default edge
         */
        corners: solidCornerTypeEnum = solidCornerTypeEnum.edge;
        /**
         * Number of straight pieces a `round` corner is made of over a full circle; more makes it
         * smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * The offset options, mirroring `ExpansionDto`: the geometry, the signed distance and the corner
     * shaping. `expansions.offset` reads `ExpansionDto`, so this class is here for symmetry.
     */
    export class OffsetDto {
        constructor(geometry?: JSCADEntity, delta?: number, corners?: solidCornerTypeEnum, segments?: number) {
            if (geometry !== undefined) { this.geometry = geometry; }
            if (delta !== undefined) { this.delta = delta; }
            if (corners !== undefined) { this.corners = corners; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The 2D shape or path whose outline is moved; it stays as it is and a new entity comes back
         * @default undefined
         */
        geometry!: JSCADEntity;
        /**
         * How far the outline moves, in model units: positive outward, negative inward
         * @default 0.1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        delta = 0.1;
        /**
         * How a convex corner is shaped: `edge` keeps it sharp, `chamfer` cuts it flat, `round` curves
         * it
         * @default edge
         */
        corners: solidCornerTypeEnum = solidCornerTypeEnum.edge;
        /**
         * Number of straight pieces a `round` corner is made of over a full circle; more makes it
         * smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `extrusions.extrudeLinear`: the flat shape, how far it rises along Z and the optional twist
     * applied on the way up.
     */
    export class ExtrudeLinearDto {
        constructor(geometry?: JSCADEntity, height?: number, twistAngle?: number, twistSteps?: number) {
            if (geometry !== undefined) { this.geometry = geometry; }
            if (height !== undefined) { this.height = height; }
            if (twistAngle !== undefined) { this.twistAngle = twistAngle; }
            if (twistSteps !== undefined) { this.twistSteps = twistSteps; }
        }
        /**
         * The flat 2D shape in the XY plane to raise into a solid; a closed path also works, an open
         * one throws an error
         * @default undefined
         */
        geometry!: JSCADEntity;
        /**
         * How far the shape rises along Z, in model units; negative extrudes downward
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * How far the top is turned relative to the bottom around Z, in degrees; 0 gives a straight
         * extrusion
         * @default 90
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        twistAngle = 90;
        /**
         * Number of slices the twist is built from, at least 1; more makes a smoother twist and a
         * heavier mesh
         * @default 15
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        twistSteps = 15;
    }

    /**
     * Feeds `hulls.hull` and `hulls.hullChain` with the entities to wrap, all of one kind: solids, 2D
     * shapes or paths. For `hullChain` the order is the order they connect in.
     */
    export class HullDto {
        constructor(meshes?: JSCADEntity[]) {
            if (meshes !== undefined) { this.meshes = meshes; }
        }
        /**
         * The solids, 2D shapes or paths to wrap, all of one kind; for a chain, in the order they
         * connect
         * @default undefined
         */
        meshes!: JSCADEntity[];
    }
    /**
     * Feeds `extrusions.extrudeRectangular`: the outline to build a wall along, the wall's height along
     * Z and its half thickness.
     */
    export class ExtrudeRectangularDto {
        constructor(geometry?: JSCADEntity, height?: number, size?: number) {
            if (geometry !== undefined) { this.geometry = geometry; }
            if (height !== undefined) { this.height = height; }
            if (size !== undefined) { this.size = size; }
        }
        /**
         * The 2D shape or path whose outline the wall follows; the inside of a shape stays empty
         * @default undefined
         */
        geometry!: JSCADEntity;
        /**
         * How tall the wall is along Z, in model units, standing on the XY plane
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * How far the wall reaches to each side of the outline, in model units, so the wall is twice
         * this thick
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        size = 1;
    }
    /**
     * Feeds `extrusions.extrudeRectangularPoints`: the points of the line to build a wall along, the
     * wall's height along Z and its half thickness.
     */
    export class ExtrudeRectangularPointsDto {
        constructor(points?: Base.Point3[], height?: number, size?: number) {
            if (points !== undefined) { this.points = points; }
            if (height !== undefined) { this.height = height; }
            if (size !== undefined) { this.size = size; }
        }
        /**
         * The corner points of the line the wall follows, in order; only X and Y are used
         * @default undefined
         */
        points!: Base.Point3[];
        /**
         * How tall the wall is along Z, in model units, standing on the XY plane
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * How far the wall reaches to each side of the line, in model units, so the wall is twice this
         * thick
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        size = 1;
    }
    /**
     * Feeds `extrusions.extrudeRotate`: the flat profile to spin around the Z axis, how far and from
     * where to spin it, and how finely the round result is faceted.
     */
    export class ExtrudeRotateDto {
        constructor(polygon?: JSCADEntity, angle?: number, startAngle?: number, segments?: number) {
            if (polygon !== undefined) { this.polygon = polygon; }
            if (angle !== undefined) { this.angle = angle; }
            if (startAngle !== undefined) { this.startAngle = startAngle; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The flat 2D shape in the XY plane to revolve around the Z axis; its X coordinates are the
         * distances from the axis, which clips it where it crosses
         * @default undefined
         */
        polygon!: JSCADEntity;
        /**
         * How far to revolve, in degrees: 360 makes a full ring, the default 90 a quarter
         * @default 90
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        angle = 90;
        /**
         * Where the revolution starts, in degrees from the X axis
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        startAngle = 0;
        /**
         * Number of steps in a full turn; a partial angle uses proportionally fewer. Fewer than 3
         * throws an error
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `polygon.createFromPolyline` with the polyline whose points become the outline of a filled
     * 2D shape.
     */
    export class PolylineDto {
        constructor(polyline?: PolylinePropertiesDto) {
            if (polyline !== undefined) { this.polyline = polyline; }
        }
        /**
         * The polyline whose points, in order, outline the shape; only X and Y are used
         */
        polyline!: PolylinePropertiesDto;
    }
    /**
     * Feeds `polygon.createFromCurve` with a NURBS curve, which is sampled into points to outline a
     * filled 2D shape.
     */
    export class CurveDto {
        constructor(curve?: any) {
            if (curve !== undefined) { this.curve = curve; }
        }
        /**
         * A NURBS curve that can be sampled into points; only X and Y of the samples are used
         */
        curve: any;
    }
    /**
     * Feeds `polygon.createFromPoints` with the outline points of a filled 2D shape, listed in order
     * around it.
     */
    export class PointsDto {
        constructor(points?: Base.Point3[]) {
            if (points !== undefined) { this.points = points; }
        }
        /**
         * The outline points in order, at least three; only X and Y are used
         */
        points!: Base.Point3[];
    }
    /**
     * Feeds `path.close` and `polygon.createFromPath` with the one 2D path to work on; a 2D shape or a
     * solid throws an error.
     */
    export class PathDto {
        constructor(path?: JSCADEntity) {
            if (path !== undefined) { this.path = path; }
        }
        /**
         * The 2D path to work on; it stays as it is and a new path or shape comes back
         * @default undefined
         */
        path!: JSCADEntity;
    }
    /**
     * Feeds `path.createFromPoints`: the points a new 2D path runs through and whether it closes back
     * to the first.
     */
    export class PathFromPointsDto {
        constructor(points?: Base.Point2[], closed?: boolean) {
            if (points !== undefined) { this.points = points; }
            if (closed !== undefined) { this.closed = closed; }
        }
        /**
         * The points the path runs through, in order; only X and Y are used and repeated consecutive
         * points are dropped
         * @default undefined
         */
        points!: Base.Point2[];
        /**
         * When true, the last point joins back to the first and the path accepts no more points
         * @default false
         */
        closed = false;
    }
    /**
     * Feeds `path.createPathsFromPoints` with several point lists, one 2D path each; a list ending on
     * its first point makes a closed path.
     */
    export class PathsFromPointsDto {
        constructor(pointsLists?: Base.Point3[][] | Base.Point2[][]) {
            if (pointsLists !== undefined) { this.pointsLists = pointsLists; }
        }
        /**
         * One list of points per path, in the order the paths should come back; a list whose last point
         * equals its first gives a closed path
         * @default undefined
         */
        pointsLists!: Base.Point3[][] | Base.Point2[][];
    }
    /**
     * Feeds `path.createFromPolyline`: the polyline a new 2D path runs through and whether it closes
     * back to the first point.
     */
    export class PathFromPolylineDto {
        constructor(polyline?: PolylinePropertiesDto, closed?: boolean) {
            if (polyline !== undefined) { this.polyline = polyline; }
            if (closed !== undefined) { this.closed = closed; }
        }
        /**
         * The polyline whose points the path runs through; only X and Y are used and its own closed
         * flag is ignored
         * @default undefined
         */
        polyline!: PolylinePropertiesDto;
        /**
         * When true, the last point joins back to the first and the path accepts no more points
         * @default false
         */
        closed = false;
    }
    /**
     * A 2D path and a NURBS curve to add to its end. No method reads it at present; sample the curve
     * into points and use `path.appendPoints` instead.
     */
    export class PathAppendCurveDto {
        constructor(curve?: JSCADEntity, path?: JSCADEntity) {
            if (curve !== undefined) { this.curve = curve; }
            if (path !== undefined) { this.path = path; }
        }
        /**
         * A NURBS curve whose sampled points would extend the path
         * @default undefined
         */
        curve!: JSCADEntity;
        /**
         * The open 2D path that would be extended
         * @default undefined
         */
        path!: JSCADEntity;
    }
    /**
     * Feeds `path.appendPoints`: an open 2D path and the points to add after its last point.
     */
    export class PathAppendPointsDto {
        constructor(points?: Base.Point2[], path?: JSCADEntity) {
            if (points !== undefined) { this.points = points; }
            if (path !== undefined) { this.path = path; }
        }
        /**
         * The points to add after the path's last point, in order; only X and Y are used
         * @default undefined
         */
        points!: Base.Point2[];
        /**
         * The open 2D path to extend; it stays as it is and a longer copy comes back. A closed path
         * throws an error
         * @default undefined
         */
        path!: JSCADEntity;
    }
    /**
     * Feeds `path.appendPolyline`: an open 2D path and the polyline whose points are added after its
     * last point.
     */
    export class PathAppendPolylineDto {
        constructor(polyline?: PolylinePropertiesDto, path?: JSCADEntity) {
            if (polyline !== undefined) { this.polyline = polyline; }
            if (path !== undefined) { this.path = path; }
        }
        /**
         * The polyline whose points are added after the path's last point; only X and Y are used
         * @default undefined
         */
        polyline!: PolylinePropertiesDto;
        /**
         * The open 2D path to extend; it stays as it is and a longer copy comes back. A closed path
         * throws an error
         * @default undefined
         */
        path!: JSCADEntity;
    }
    /**
     * Feeds `path.appendArc`: an open 2D path with at least one point, the point the arc ends on, the
     * ellipse the arc is cut from and which of the four fitting arcs to take.
     */
    export class PathAppendArcDto {
        constructor(path?: JSCADEntity, endPoint?: Base.Point2, xAxisRotation?: number, clockwise?: boolean, large?: boolean, segments?: number, radiusX?: number, radiusY?: number) {
            if (path !== undefined) { this.path = path; }
            if (endPoint !== undefined) { this.endPoint = endPoint; }
            if (xAxisRotation !== undefined) { this.xAxisRotation = xAxisRotation; }
            if (clockwise !== undefined) { this.clockwise = clockwise; }
            if (large !== undefined) { this.large = large; }
            if (segments !== undefined) { this.segments = segments; }
            if (radiusX !== undefined) { this.radiusX = radiusX; }
            if (radiusY !== undefined) { this.radiusY = radiusY; }
        }
        /**
         * The open 2D path to extend, with at least one point; the arc starts at its last point
         * @default undefined
         */
        path!: JSCADEntity;
        /**
         * Where the arc ends, as a 2D point in the XY plane
         * @default [1, 1]
         */
        endPoint: Base.Point2 = [1, 1];
        /**
         * Tilt of the ellipse the arc is cut from, in degrees from the X axis; it changes nothing for a
         * circle
         * @default 90
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        xAxisRotation = 90;
        /**
         * When true, the arc turns clockwise from the start to the end point; false turns
         * counter-clockwise
         * @default true
         */
        clockwise = true;
        /**
         * When true, the longer of the two arcs between the points is taken, more than half the ellipse
         * @default false
         */
        large = false;
        /**
         * Number of straight pieces for a full ellipse; the arc gets its proportional share
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
        /**
         * Half width of the ellipse along its own X axis, in model units; scaled up when too small to
         * reach the end point
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        radiusX = 1;
        /**
         * Half height of the ellipse along its own Y axis, in model units; equal to `radiusX` for a
         * circular arc
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        radiusY = 1;
    }
    /**
     * Feeds `polygon.circle`: a filled circle in the XY plane, given by its 2D center, radius and the
     * number of straight sides that approximate it.
     */
    export class CircleDto {
        constructor(center?: Base.Point2, radius?: number, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The 2D center point, as X and Y in the plane
         * @default [0, 0]
         */
        center: Base.Point2 = [0, 0];
        /**
         * Distance from the center to the rim, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of straight sides around the circle; more makes it rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `polygon.ellipse`: a filled ellipse in the XY plane, given by its 2D center, its two
     * half-sizes and the number of straight sides that approximate it.
     */
    export class EllipseDto {
        constructor(center?: Base.Point2, radius?: Base.Point2, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The 2D center point, as X and Y in the plane
         * @default [0, 0]
         */
        center: Base.Point2 = [0, 0];
        /**
         * The half width along X and the half height along Y, in model units, as `[x, y]`
         * @default [1, 2]
         */
        radius: Base.Point2 = [1, 2];
        /**
         * Number of straight sides around the ellipse; more makes it rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `polygon.square`: a filled square in the XY plane with sides parallel to the axes, given by
     * its 2D center and side length.
     */
    export class SquareDto {
        constructor(center?: Base.Point2, size?: number) {
            if (center !== undefined) { this.center = center; }
            if (size !== undefined) { this.size = size; }
        }
        /**
         * The 2D center point, as X and Y in the plane
         * @default [0, 0]
         */
        center: Base.Point2 = [0, 0];
        /**
         * Length of each side, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        size = 1;

    }
    /**
     * Feeds `polygon.rectangle`: a filled rectangle in the XY plane with sides parallel to the axes,
     * given by its 2D center, width along X and length along Y.
     */
    export class RectangleDto {
        constructor(center?: Base.Point2, width?: number, length?: number) {
            if (center !== undefined) { this.center = center; }
            if (width !== undefined) { this.width = width; }
            if (length !== undefined) { this.length = length; }
        }
        /**
         * The 2D center point, as X and Y in the plane
         * @default [0, 0]
         */
        center: Base.Point2 = [0, 0];
        /**
         * Full size along X, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        width = 1;
        /**
         * Full size along Y, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        length = 1;
    }
    /**
     * Feeds `polygon.roundedRectangle`: a filled rectangle in the XY plane whose four corners are
     * rounded, given by its 2D center, its sizes, the corner radius and how finely the corners are
     * faceted.
     */
    export class RoundedRectangleDto {
        constructor(center?: Base.Point2, roundRadius?: number, segments?: number, width?: number, length?: number) {
            if (center !== undefined) { this.center = center; }
            if (roundRadius !== undefined) { this.roundRadius = roundRadius; }
            if (segments !== undefined) { this.segments = segments; }
            if (width !== undefined) { this.width = width; }
            if (length !== undefined) { this.length = length; }
        }
        /**
         * The 2D center point, as X and Y in the plane
         * @default [0, 0]
         */
        center: Base.Point2 = [0, 0];
        /**
         * Radius of each rounded corner, in model units; it must be less than half of the smaller side
         * or an error is thrown
         * @default 0.2
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        roundRadius = 0.2;
        /**
         * Number of straight pieces a full circle of rounding is made of, so each corner gets a
         * quarter; more makes it smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
        /**
         * Full size along X, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        width = 1;
        /**
         * Full size along Y, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        length = 1;
    }
    /**
     * Feeds `polygon.star`: a filled star in the XY plane, given by its 2D center, how many tips it
     * has, how far the tips and the notches between them reach and where the first tip points.
     */
    export class StarDto {
        constructor(center?: Base.Point2, vertices?: number, density?: number, outerRadius?: number, innerRadius?: number, startAngle?: number) {
            if (center !== undefined) { this.center = center; }
            if (vertices !== undefined) { this.vertices = vertices; }
            if (density !== undefined) { this.density = density; }
            if (outerRadius !== undefined) { this.outerRadius = outerRadius; }
            if (innerRadius !== undefined) { this.innerRadius = innerRadius; }
            if (startAngle !== undefined) { this.startAngle = startAngle; }
        }
        /**
         * The 2D center point, as X and Y in the plane
         * @default [0, 0]
         */
        center: Base.Point2 = [0, 0];
        /**
         * Number of tips; the star has as many notches between them
         * @default 10
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        vertices = 10;
        /**
         * Read only when `innerRadius` is 0: how many tips apart the edges connect, 2 for a pentagram,
         * from which the notch radius is derived
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        density = 1;
        /**
         * Distance from the center to each tip, in model units
         * @default 2
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        outerRadius = 2;
        /**
         * Distance from the center to each notch, in model units; 0 lets `density` decide it
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        innerRadius = 1;
        /**
         * Direction of the first tip, in degrees counter-clockwise from the X axis
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        startAngle = 0;
    }
    /**
     * Feeds `shapes.cube`: a cube with faces parallel to the axes, given by its center point and edge
     * length.
     */
    export class CubeDto {
        constructor(center?: Base.Point3, size?: number) {
            if (center !== undefined) { this.center = center; }
            if (size !== undefined) { this.size = size; }
        }
        /**
         * The point the cube is centered on, so half the edge length lies on each side of it
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Length of every edge, in model units
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        size = 1;
    }
    /**
     * Feeds `shapes.cubesOnCenterPoints`: one cube of the same edge length on every center point,
     * coming back in the same order.
     */
    export class CubeCentersDto {
        constructor(centers?: Base.Point3[], size?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (size !== undefined) { this.size = size; }
        }
        /**
         * The points the cubes are centered on, one cube each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Length of every edge of every cube, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        size = 1;
    }
    /**
     * Feeds `shapes.cuboid`: a box with faces parallel to the axes, given by its center point and its
     * sizes along X, Y and Z.
     */
    export class CuboidDto {
        constructor(center?: Base.Point3, width?: number, length?: number, height?: number) {
            if (center !== undefined) { this.center = center; }
            if (width !== undefined) { this.width = width; }
            if (length !== undefined) { this.length = length; }
            if (height !== undefined) { this.height = height; }
        }
        /**
         * The point the box is centered on, so half of each size lies on each side of it
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Full size along X, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        width = 1;
        /**
         * Full size along Z, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        length = 1;
        /**
         * Full size along Y, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
    }
    /**
     * Feeds `shapes.cuboidsOnCenterPoints`: one box of the same sizes on every center point, coming
     * back in the same order.
     */
    export class CuboidCentersDto {
        constructor(centers?: Base.Point3[], width?: number, length?: number, height?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (width !== undefined) { this.width = width; }
            if (length !== undefined) { this.length = length; }
            if (height !== undefined) { this.height = height; }
        }
        /**
         * The points the boxes are centered on, one box each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Full size of every box along X, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        width = 1;
        /**
         * Full size of every box along Z, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        length = 1;
        /**
         * Full size of every box along Y, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
    }
    /**
     * Feeds `shapes.roundedCuboid`: a box with every edge and corner rounded, given by its center, its
     * sizes along X, Y and Z, the rounding radius and how finely the rounding is faceted.
     */
    export class RoundedCuboidDto {
        constructor(center?: Base.Point3, roundRadius?: number, width?: number, length?: number, height?: number, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (roundRadius !== undefined) { this.roundRadius = roundRadius; }
            if (width !== undefined) { this.width = width; }
            if (length !== undefined) { this.length = length; }
            if (height !== undefined) { this.height = height; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The point the box is centered on, so half of each size lies on each side of it
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Radius of the rounding on every edge, in model units; it must be less than half of the
         * smallest side or an error is thrown
         * @default 0.1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        roundRadius = 1;
        /**
         * Full size along X, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        width = 1;
        /**
         * Full size along Z, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        length = 1;
        /**
         * Full size along Y, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Number of straight pieces a full circle of rounding is made of; more makes the edges smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.roundedCuboidsOnCenterPoints`: one rounded box of the same sizes and rounding on
     * every center point, coming back in the same order.
     */
    export class RoundedCuboidCentersDto {
        constructor(centers?: Base.Point3[], roundRadius?: number, width?: number, length?: number, height?: number, segments?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (roundRadius !== undefined) { this.roundRadius = roundRadius; }
            if (width !== undefined) { this.width = width; }
            if (length !== undefined) { this.length = length; }
            if (height !== undefined) { this.height = height; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The points the boxes are centered on, one box each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Radius of the rounding on every edge, in model units; it must be less than half of the
         * smallest side or an error is thrown
         * @default 0.1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        roundRadius = 0.1;
        /**
         * Full size of every box along X, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        width = 1;
        /**
         * Full size of every box along Z, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        length = 1;
        /**
         * Full size of every box along Y, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Number of straight pieces a full circle of rounding is made of; more makes the edges smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.cylinderElliptic`: a cylinder standing along Z with an elliptical cross-section
     * that can differ between its two ends, so it also makes cones and tapers.
     */
    export class CylidnerEllipticDto {
        constructor(center?: Base.Point3, height?: number, startRadius?: Base.Point2, endRadius?: Base.Point2, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (height !== undefined) { this.height = height; }
            if (startRadius !== undefined) { this.startRadius = startRadius; }
            if (endRadius !== undefined) { this.endRadius = endRadius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The point halfway up the axis; half the height lies above it along Z and half below
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Full length along Z, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * The X and Y radii of the bottom end, in model units, as `[x, y]`
         * @default [1, 2]
         */
        startRadius: Base.Vector2 = [1, 2];
        /**
         * The X and Y radii of the top end, in model units, as `[x, y]`; `[0, 0]` closes it to a point
         * @default [2, 3]
         */
        endRadius: Base.Vector2 = [2, 3];
        /**
         * Number of flat sides around the cylinder; more makes it rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.cylinderEllipticOnCenterPoints`: one elliptic cylinder of the same size on every
     * center point, coming back in the same order.
     */
    export class CylidnerCentersEllipticDto {
        constructor(centers?: Base.Point3[], height?: number, startRadius?: Base.Point2, endRadius?: Base.Point2, segments?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (height !== undefined) { this.height = height; }
            if (startRadius !== undefined) { this.startRadius = startRadius; }
            if (endRadius !== undefined) { this.endRadius = endRadius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The points halfway up each axis, one cylinder each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Full length of every cylinder along Z, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * The X and Y radii of every bottom end, in model units, as `[x, y]`
         * @default [1, 2]
         */
        startRadius: Base.Point2 = [1, 2];
        /**
         * The X and Y radii of every top end, in model units, as `[x, y]`; `[0, 0]` closes them to a
         * point
         * @default [2, 3]
         */
        endRadius: Base.Point2 = [2, 3];
        /**
         * Number of flat sides around each cylinder; more makes them rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.cylinder`: a round cylinder standing along Z, given by the point halfway up its
     * axis, its height, its radius and how many flat sides approximate it.
     */
    export class CylidnerDto {
        constructor(center?: Base.Point3, height?: number, radius?: number, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (height !== undefined) { this.height = height; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The point halfway up the axis; half the height lies above it along Z and half below
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Full length along Z, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Distance from the axis to the side, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of flat sides around the cylinder; more makes it rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.roundedCylinder`: a cylinder standing along Z whose two rims are rounded, given by
     * the point halfway up its axis, the rounding radius, its height and radius and how finely it is
     * faceted.
     */
    export class RoundedCylidnerDto {
        constructor(center?: Base.Point3, roundRadius?: number, height?: number, radius?: number, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (roundRadius !== undefined) { this.roundRadius = roundRadius; }
            if (height !== undefined) { this.height = height; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The point halfway up the axis; half the height lies above it along Z and half below
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Radius of the rounding on both rims, in model units; the height must be more than twice it or
         * an error is thrown
         * @default 0.1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        roundRadius = 0.1;
        /**
         * Full length along Z, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Distance from the axis to the side, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of flat sides around the cylinder and pieces in the rounding; more makes it smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.ellipsoid`: a sphere stretched separately along X, Y and Z, given by its center,
     * its three radii and how finely it is faceted.
     */
    export class EllipsoidDto {
        constructor(center?: Base.Point3, radius?: Base.Point3, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The point the ellipsoid is centered on
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * The half sizes along X, Y and Z, in model units, as `[x, y, z]`; equal values make a sphere
         * @default [1, 2, 3]
         */
        radius: Base.Point3 = [1, 2, 3];
        /**
         * Number of facets around the ellipsoid; more makes it smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.ellipsoidsOnCenterPoints`: one ellipsoid of the same radii on every center point,
     * coming back in the same order.
     */
    export class EllipsoidCentersDto {
        constructor(centers?: Base.Point3[], radius?: Base.Point3, segments?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The points the ellipsoids are centered on, one each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * The half sizes of every ellipsoid along X, Y and Z, in model units, as `[x, y, z]`
         * @default [1, 2, 3]
         */
        radius: Base.Point3 = [1, 2, 3];
        /**
         * Number of facets around each ellipsoid; more makes them smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.geodesicSphere`: a sphere made of evenly sized triangles, given by its center, its
     * radius and how finely the twenty starting faces are subdivided.
     */
    export class GeodesicSphereDto {
        constructor(center?: Base.Point3, radius?: number, frequency?: number) {
            if (center !== undefined) { this.center = center; }
            if (radius !== undefined) { this.radius = radius; }
            if (frequency !== undefined) { this.frequency = frequency; }
        }
        /**
         * The point the sphere is centered on
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Distance from the center to the surface, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * How finely each of the twenty starting faces is subdivided; used in whole multiples of 6, at
         * least 6, and higher is rounder
         * @default 12
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        frequency = 12;
    }
    /**
     * Feeds `shapes.geodesicSpheresOnCenterPoints`: one geodesic sphere of the same radius on every
     * center point, coming back in the same order.
     */
    export class GeodesicSphereCentersDto {
        constructor(centers?: Base.Point3[], radius?: number, frequency?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (radius !== undefined) { this.radius = radius; }
            if (frequency !== undefined) { this.frequency = frequency; }
        }
        /**
         * The points the spheres are centered on, one each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Distance from each center to its surface, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * How finely each of the twenty starting faces is subdivided; used in whole multiples of 6, at
         * least 6, and higher is rounder
         * @default 12
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        frequency = 12;
    }
    /**
     * Feeds `shapes.cylindersOnCenterPoints`: one round cylinder of the same size standing along Z on
     * every center point, coming back in the same order.
     */
    export class CylidnerCentersDto {
        constructor(centers?: Base.Point3[], height?: number, radius?: number, segments?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (height !== undefined) { this.height = height; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The points halfway up each axis, one cylinder each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Full length of every cylinder along Z, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Distance from the axis to the side of every cylinder, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of flat sides around each cylinder; more makes them rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.roundedCylindersOnCenterPoints`: one rounded cylinder of the same size on every
     * center point, coming back in the same order.
     */
    export class RoundedCylidnerCentersDto {
        constructor(centers?: Base.Point3[], roundRadius?: number, height?: number, radius?: number, segments?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (roundRadius !== undefined) { this.roundRadius = roundRadius; }
            if (height !== undefined) { this.height = height; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The points halfway up each axis, one cylinder each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Radius of the rounding on both rims of every cylinder, in model units; the height must be
         * more than twice it or an error is thrown
         * @default 0.1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        roundRadius = 0.1;
        /**
         * Full length of every cylinder along Z, in model units, rounding included
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Distance from the axis to the side of every cylinder, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of flat sides around each cylinder and pieces in the rounding; more makes them
         * smoother
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.sphere`: a sphere given by its center point, its radius and how many facets
     * approximate it.
     */
    export class SphereDto {
        constructor(center?: Base.Point3, radius?: number, segments?: number) {
            if (center !== undefined) { this.center = center; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The point the sphere is centered on
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Distance from the center to the surface, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of facets around the sphere; more makes it rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.spheresOnCenterPoints`: one sphere of the same radius on every center point, coming
     * back in the same order.
     */
    export class SphereCentersDto {
        constructor(centers?: Base.Point3[], radius?: number, segments?: number) {
            if (centers !== undefined) { this.centers = centers; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
        }
        /**
         * The points the spheres are centered on, one each, in the order the results come back
         * @default undefined
         */
        centers!: Base.Point3[];
        /**
         * Distance from each center to its surface, in model units
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 1;
        /**
         * Number of facets around each sphere; more makes them rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
    }
    /**
     * Feeds `shapes.torus`: a ring with a round cross-section lying flat in the XY plane around the
     * origin, given by the ring and tube radii, the facet counts of each and the angles that can leave
     * the ring partly open.
     */
    export class TorusDto {
        constructor(center?: Base.Point3, innerRadius?: number, outerRadius?: number, innerSegments?: number, outerSegments?: number, innerRotation?: number, outerRotation?: number, startAngle?: number) {
            if (center !== undefined) { this.center = center; }
            if (innerRadius !== undefined) { this.innerRadius = innerRadius; }
            if (outerRadius !== undefined) { this.outerRadius = outerRadius; }
            if (innerSegments !== undefined) { this.innerSegments = innerSegments; }
            if (outerSegments !== undefined) { this.outerSegments = outerSegments; }
            if (innerRotation !== undefined) { this.innerRotation = innerRotation; }
            if (outerRotation !== undefined) { this.outerRotation = outerRotation; }
            if (startAngle !== undefined) { this.startAngle = startAngle; }
        }
        /**
         * Meant to be the ring's center; it is not applied at present, the torus is built around the
         * origin, so move it with `transformSolid`
         * @default [0, 0, 0]
         */
        center: Base.Point3 = [0, 0, 0];
        /**
         * Radius of the tube itself, in model units; it must be less than `outerRadius`
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        innerRadius = 1;
        /**
         * Distance from the ring's center to the middle of the tube, in model units, so the ring spans
         * twice the sum of both radii
         * @default 2
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        outerRadius = 2;
        /**
         * Number of flat pieces around the tube's cross-section; more makes the tube rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        innerSegments = 24;
        /**
         * Number of flat pieces around the ring; more makes the ring rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        outerSegments = 24;
        /**
         * Turn of the tube's cross-section about its own center, in degrees; it shows when
         * `innerSegments` is low enough for the facets to be visible
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        innerRotation = 0;
        /**
         * How far the tube is swept around the ring, in degrees; 360 closes the ring and less leaves it
         * open
         * @default 360
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        outerRotation = 360;
        /**
         * Where the sweep around the ring starts, in degrees from the X axis
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 1
         */
        startAngle = 0;
    }
    /**
     * Feeds `text.createVectorText` with the text and the font options: where the text starts, how tall
     * a capital letter is, the spacing of lines and letters, the alignment of several lines and the
     * stroke compensation. `CylinderTextDto` and `SphereTextDto` reuse them.
     */
    export class TextDto {
        constructor(text?: string, segments?: number, xOffset?: number, yOffset?: number, height?: number, lineSpacing?: number, letterSpacing?: number, align?: jscadTextAlignEnum, extrudeOffset?: number) {
            if (text !== undefined) { this.text = text; }
            if (segments !== undefined) { this.segments = segments; }
            if (xOffset !== undefined) { this.xOffset = xOffset; }
            if (yOffset !== undefined) { this.yOffset = yOffset; }
            if (height !== undefined) { this.height = height; }
            if (lineSpacing !== undefined) { this.lineSpacing = lineSpacing; }
            if (letterSpacing !== undefined) { this.letterSpacing = letterSpacing; }
            if (align !== undefined) { this.align = align; }
            if (extrudeOffset !== undefined) { this.extrudeOffset = extrudeOffset; }
        }
        /**
         * The characters to write; a newline starts a new line and a character outside plain ASCII
         * becomes a question mark
         * @default Hello World
         */
        text = "Hello World";
        /**
         * Number of straight pieces used for curved strokes; more makes letters rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
        /**
         * Where the text starts along X, in model units
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        xOffset = 0;
        /**
         * Where the baseline of the first line sits along Y, in model units
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        yOffset = 0;
        /**
         * Height of a capital letter, in model units; the whole text scales with it
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Step from one line down to the next as a multiple of the letter height; 1.4 leaves a 40
         * percent gap
         * @default 1.4
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        lineSpacing = 1.4;
        /**
         * Multiplies the step from one letter to the next; 1 is the font's own spacing and 2 spreads
         * letters twice as far apart
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        letterSpacing = 1;
        /**
         * How the lines of a multi-line text line up: to the left, the center or the right
         * @default center
         */
        align = jscadTextAlignEnum.center;
        /**
         * Thickness the strokes will get later, in model units; the outlines are pulled in by half of
         * it so letters keep their size once thick
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        extrudeOffset = 0;
    }
    /**
     * Feeds `text.cylindricalText`: the text and font options of `TextDto` plus the size of the
     * cylinders every stroke is chained from.
     */
    export class CylinderTextDto {
        constructor(text?: string, extrusionHeight?: number, extrusionSize?: number, segments?: number, xOffset?: number, yOffset?: number, height?: number, lineSpacing?: number, letterSpacing?: number, align?: jscadTextAlignEnum, extrudeOffset?: number) {
            if (text !== undefined) { this.text = text; }
            if (extrusionHeight !== undefined) { this.extrusionHeight = extrusionHeight; }
            if (extrusionSize !== undefined) { this.extrusionSize = extrusionSize; }
            if (segments !== undefined) { this.segments = segments; }
            if (xOffset !== undefined) { this.xOffset = xOffset; }
            if (yOffset !== undefined) { this.yOffset = yOffset; }
            if (height !== undefined) { this.height = height; }
            if (lineSpacing !== undefined) { this.lineSpacing = lineSpacing; }
            if (letterSpacing !== undefined) { this.letterSpacing = letterSpacing; }
            if (align !== undefined) { this.align = align; }
            if (extrudeOffset !== undefined) { this.extrudeOffset = extrudeOffset; }
        }
        /**
         * The characters to write; a newline starts a new line and a character outside plain ASCII
         * becomes a question mark
         * @default Hello World
         */
        text = "Hello World";
        /**
         * Length of the cylinders along Z, in model units; the strokes sit on the XY plane with half of
         * it on each side
         * @default 0.5
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        extrusionHeight = 0.5;
        /**
         * Radius of the cylinders, in model units, which is half the thickness of the strokes
         * @default 0.1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        extrusionSize = 0.1;
        /**
         * Number of flat sides around each cylinder and pieces in curved strokes; more makes the
         * letters rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
        /**
         * Where the text starts along X before it is centered, in model units
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        xOffset = 0;
        /**
         * Where the baseline of the first line sits along Y, in model units
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        yOffset = 0;
        /**
         * Height of a capital letter, in model units; the whole text scales with it
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Step from one line down to the next as a multiple of the letter height; 1.4 leaves a 40
         * percent gap
         * @default 1.4
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        lineSpacing = 1.4;
        /**
         * Multiplies the step from one letter to the next; 1 is the font's own spacing and 2 spreads
         * letters twice as far apart
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        letterSpacing = 1;
        /**
         * How the lines of a multi-line text line up: to the left, the center or the right
         * @default center
         */
        align = jscadTextAlignEnum.center;
        /**
         * Pulls the strokes inward by half this amount, in model units, so thick strokes keep the
         * intended letter size
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        extrudeOffset = 0;
    }
    /**
     * Feeds `text.sphericalText`: the text and font options of `TextDto` plus the size of the spheres
     * every stroke is chained from.
     */
    export class SphereTextDto {
        constructor(text?: string, radius?: number, segments?: number, xOffset?: number, yOffset?: number, height?: number, lineSpacing?: number, letterSpacing?: number, align?: jscadTextAlignEnum, extrudeOffset?: number) {
            if (text !== undefined) { this.text = text; }
            if (radius !== undefined) { this.radius = radius; }
            if (segments !== undefined) { this.segments = segments; }
            if (xOffset !== undefined) { this.xOffset = xOffset; }
            if (yOffset !== undefined) { this.yOffset = yOffset; }
            if (height !== undefined) { this.height = height; }
            if (lineSpacing !== undefined) { this.lineSpacing = lineSpacing; }
            if (letterSpacing !== undefined) { this.letterSpacing = letterSpacing; }
            if (align !== undefined) { this.align = align; }
            if (extrudeOffset !== undefined) { this.extrudeOffset = extrudeOffset; }
        }
        /**
         * The characters to write; a newline starts a new line and a character outside plain ASCII
         * becomes a question mark
         * @default Hello World
         */
        text = "Hello World";
        /**
         * Radius of the spheres, in model units, which is half the thickness of the strokes
         * @default 0.1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        radius = 0.1;
        /**
         * Number of facets around each sphere and pieces in curved strokes; more makes the letters
         * rounder
         * @default 24
         * @minimum 0
         * @maximum Infinity
         * @step 1
         */
        segments = 24;
        /**
         * Where the text starts along X before it is centered, in model units
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        xOffset = 0;
        /**
         * Where the baseline of the first line sits along Y, in model units
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        yOffset = 0;
        /**
         * Height of a capital letter, in model units; the whole text scales with it
         * @default 1
         * @minimum 0
         * @maximum Infinity
         * @step 0.1
         */
        height = 1;
        /**
         * Step from one line down to the next as a multiple of the letter height; 1.4 leaves a 40
         * percent gap
         * @default 1.4
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        lineSpacing = 1.4;
        /**
         * Multiplies the step from one letter to the next; 1 is the font's own spacing and 2 spreads
         * letters twice as far apart
         * @default 1
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        letterSpacing = 1;
        /**
         * How the lines of a multi-line text line up: to the left, the center or the right
         * @default center
         */
        align = jscadTextAlignEnum.center;
        /**
         * Pulls the strokes inward by half this amount, in model units, so thick strokes keep the
         * intended letter size
         * @default 0
         * @minimum -Infinity
         * @maximum Infinity
         * @step 0.1
         */
        extrudeOffset = 0;
    }
    /**
     * Feeds `shapes.fromPolygonPoints` with the faces of a solid, each as the list of points around it,
     * listed clockwise as seen from outside.
     */
    export class FromPolygonPoints {
        constructor(polygonPoints?: Base.Point3[][]) {
            if (polygonPoints !== undefined) { this.polygonPoints = polygonPoints; }
        }
        /**
         * One list of points per face, each going around the face clockwise as seen from outside; the
         * lists are reversed in place while the solid is built
         */
        polygonPoints!: Base.Point3[][];
    }
}
