// GENERATED by scripts/gen-worker-api.mjs from packages/dev/occt/lib/services/sketch/sketch.ts - do not edit.
// The kernel class is the source of the docs, the signatures and the member order.
// Regenerate with `npm run gen:worker-api` at the repository root.
import { Inputs, Models } from "@bitbybit-dev/occt";
import { OCCTWorkerManager } from "../../../occ-worker/occ-worker-manager";
import { OCCTSketchCommands } from "./commands";

/**
 * Drawing flat outlines with a pen: a start point and a list of moves (lines, arcs, Bezier curves,
 * rounded and beveled corners) become one exact wire, or a face when the outline closes, in the plane
 * of a frame. `commands` makes the moves one at a time; `stroke` and `hull` outline wires and wrap
 * shapes. A sketch's x axis is the frame's direction and its y axis the normal crossed with it.
 */
export class OCCTSketch {
    public readonly commands: OCCTSketchCommands;

    constructor(
        private readonly occWorkerManager: OCCTWorkerManager
    ) {
        this.commands = new OCCTSketchCommands(occWorkerManager);
    }

    /**
     * Draws an outline with a pen, from a start point through a list of moves, in a frame's plane.
     *
     * Each command draws on from where the previous one ended, and lines and arcs come out as exact
     * lines and circles. `makeFace` turns a closed outline into a face facing along the frame's
     * normal; one that crosses itself is refused.
     * @param inputs - The commands, the start point, the frame and whether to make a face
     * @returns The outline as a wire, or a face when `makeFace` is true
     * @group draw
     * @shortname pen
     * @drawable true
     * @example
     * ```typescript
     * const plate = await bitbybit.occt.sketch.pen({
     *     commands: [
     *         { type: "hLine", length: 40 },
     *         { type: "vLine", length: 10 },
     *         { type: "filletCorner", radius: 2 },
     *         { type: "tangentArc", to: [-10, 10], relative: true },
     *         { type: "close" },
     *     ],
     *     makeFace: true,
     * });
     * ```
     */
    pen(inputs: Inputs.OCCT.SketchPenDto): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("sketch.pen", inputs);
    }

    /**
     * Draws an outline as `pen` does and reports which edges each command drew, so later steps can
     * find the edges and faces a command made by its `id`.
     *
     * Edges are numbered as `shapes.edge.getEdges` numbers them on the result. A command without an
     * `id` is named by its position, and a command that drew nothing is left out.
     * @param inputs - The commands, the start point, the frame and whether to make a face
     * @returns The outline and, per command, the edges it drew
     * @group draw
     * @shortname pen with segments
     * @drawable false
     * @example
     * ```typescript
     * const drawn = await bitbybit.occt.sketch.penWithSegments({
     *     commands: [{ type: "hLine", id: "base", length: 40 }, { type: "vLine", id: "side", length: 10 }, { type: "close", id: "slope" }],
     *     makeFace: true,
     * });
     * console.log(drawn.segments.find(segment => segment.id === "slope")?.edges);
     * ```
     */
    penWithSegments(inputs: Inputs.OCCT.SketchPenDto): Promise<Models.OCCT.SketchWithSegments<Inputs.OCCT.TopoDSShapePointer>> {
        return this.occWorkerManager.genericCallToWorkerPromise("sketch.penWithSegments", inputs);
    }

    /**
     * Outlines a wire as if it were drawn with a pen of a given width, in a frame's plane.
     *
     * Half of `width` lies to each side; `cap` finishes an open wire's ends and `join` its corners.
     * A closed wire gives a ring: a face with one hole, or its two wires in a compound without
     * `makeFace`.
     * @param inputs - The wire, the width, the end and corner styles, the frame and whether to make a face
     * @returns The outline as a face, or as a wire or compound of wires when `makeFace` is false
     * @group outline
     * @shortname stroke
     * @drawable true
     * @example
     * ```typescript
     * const path = await bitbybit.occt.sketch.pen({ commands: [{ type: "hLine", length: 30 }, { type: "tangentArc", to: [10, 10], relative: true }] });
     * const slot = await bitbybit.occt.sketch.stroke({ shape: path, width: 4, cap: Bit.Inputs.OCCT.strokeCapEnum.round });
     * ```
     */
    stroke(inputs: Inputs.OCCT.SketchStrokeDto<Inputs.OCCT.TopoDSWirePointer | Inputs.OCCT.TopoDSEdgePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("sketch.stroke", inputs);
    }

    /**
     * Wraps vertices, straight edges and circular edges lying in a frame's plane in the tightest
     * convex outline around them.
     *
     * The outline is exact: straight where it spans between shapes, following a circle where a circle
     * or an arc bulges out. Other curves are refused, as are shapes off the frame's plane or circles
     * tilted out of it.
     * @param inputs - The shapes, the frame and whether to make a face
     * @returns The hull as a face, or as a wire when `makeFace` is false
     * @group outline
     * @shortname hull
     * @drawable true
     * @example
     * ```typescript
     * const left = await bitbybit.occt.shapes.wire.createCircleWire({ radius: 5, center: [0, 0, 0], direction: [0, 1, 0] });
     * const right = await bitbybit.occt.shapes.wire.createCircleWire({ radius: 2, center: [20, 0, 0], direction: [0, 1, 0] });
     * const lever = await bitbybit.occt.sketch.hull({ shapes: [left, right] });
     * ```
     */
    hull(inputs: Inputs.OCCT.SketchHullDto<Inputs.OCCT.TopoDSShapePointer>): Promise<Inputs.OCCT.TopoDSShapePointer> {
        return this.occWorkerManager.genericCallToWorkerPromise("sketch.hull", inputs);
    }
}
