// GENERATED by scripts/gen-dto-meta.mjs from the inputs DTOs - do not edit.
// Regenerate with `npm run gen:dto-meta` at the repository root.
/* eslint-disable @typescript-eslint/no-namespace */
import { WithDefaults } from "@bitbybit-dev/base";
import * as Inputs from "../inputs";
export * from "@bitbybit-dev/base/lib/api/resolved-inputs";

/**
 * The JSCAD inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace JSCAD {
    export type BooleanObjectsDto = Inputs.JSCAD.BooleanObjectsDto;
    export type BooleanObjectsFromDto = Inputs.JSCAD.BooleanObjectsFromDto;
    export type BooleanTwoObjectsDto = Inputs.JSCAD.BooleanTwoObjectsDto;
    export type CircleDto = WithDefaults<Inputs.JSCAD.CircleDto, "center" | "radius" | "segments">;
    export type ColorizeDto = WithDefaults<Inputs.JSCAD.ColorizeDto, "color">;
    export type CubeCentersDto = WithDefaults<Inputs.JSCAD.CubeCentersDto, "size">;
    export type CubeDto = WithDefaults<Inputs.JSCAD.CubeDto, "center" | "size">;
    export type CuboidBaseDto = WithDefaults<Inputs.JSCAD.CuboidBaseDto, "width" | "length" | "height">;
    export type CuboidCentersDto = WithDefaults<Inputs.JSCAD.CuboidCentersDto, "width" | "length" | "height">;
    export type CuboidDto = WithDefaults<Inputs.JSCAD.CuboidDto, "width" | "length" | "height" | "center">;
    export type CurveDto = Inputs.JSCAD.CurveDto;
    export type CylidnerCentersDto = WithDefaults<Inputs.JSCAD.CylidnerCentersDto, "height" | "radius" | "segments">;
    export type CylidnerCentersEllipticDto = WithDefaults<Inputs.JSCAD.CylidnerCentersEllipticDto, "height" | "startRadius" | "endRadius" | "segments">;
    export type CylidnerDto = WithDefaults<Inputs.JSCAD.CylidnerDto, "height" | "radius" | "segments" | "center">;
    export type CylidnerEllipticDto = WithDefaults<Inputs.JSCAD.CylidnerEllipticDto, "center" | "height" | "startRadius" | "endRadius" | "segments">;
    export type CylinderBaseDto = WithDefaults<Inputs.JSCAD.CylinderBaseDto, "height" | "radius" | "segments">;
    export type CylinderTextDto = WithDefaults<Inputs.JSCAD.CylinderTextDto, "text" | "extrusionHeight" | "extrusionSize" | "segments" | "xOffset" | "yOffset" | "height" | "lineSpacing" | "letterSpacing" | "align" | "extrudeOffset">;
    export type DownloadGeometryDto = WithDefaults<Inputs.JSCAD.DownloadGeometryDto, "fileName">;
    export type DownloadSolidDto = Inputs.JSCAD.DownloadSolidDto;
    export type DownloadSolidsDto = Inputs.JSCAD.DownloadSolidsDto;
    export type DrawPathDto<T> = WithDefaults<Inputs.JSCAD.DrawPathDto<T>, "colour" | "opacity" | "width" | "updatable">;
    export type DrawSolidMeshDto<T> = WithDefaults<Inputs.JSCAD.DrawSolidMeshDto<T>, "opacity" | "colours" | "updatable" | "hidden" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity">;
    export type DrawSolidMeshesDto<T> = WithDefaults<Inputs.JSCAD.DrawSolidMeshesDto<T>, "opacity" | "colours" | "updatable" | "hidden" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity">;
    export type EllipseDto = WithDefaults<Inputs.JSCAD.EllipseDto, "center" | "radius" | "segments">;
    export type EllipsoidBaseDto = WithDefaults<Inputs.JSCAD.EllipsoidBaseDto, "radius" | "segments">;
    export type EllipsoidCentersDto = WithDefaults<Inputs.JSCAD.EllipsoidCentersDto, "radius" | "segments">;
    export type EllipsoidDto = WithDefaults<Inputs.JSCAD.EllipsoidDto, "radius" | "segments" | "center">;
    export type ExpansionDto = WithDefaults<Inputs.JSCAD.ExpansionDto, "delta" | "corners" | "segments">;
    export type ExtrudeLinearDto = WithDefaults<Inputs.JSCAD.ExtrudeLinearDto, "height" | "twistAngle" | "twistSteps">;
    export type ExtrudeRectangularBaseDto = WithDefaults<Inputs.JSCAD.ExtrudeRectangularBaseDto, "height" | "size">;
    export type ExtrudeRectangularDto = WithDefaults<Inputs.JSCAD.ExtrudeRectangularDto, "height" | "size">;
    export type ExtrudeRectangularPointsDto = WithDefaults<Inputs.JSCAD.ExtrudeRectangularPointsDto, "height" | "size">;
    export type ExtrudeRotateDto = WithDefaults<Inputs.JSCAD.ExtrudeRotateDto, "angle" | "startAngle" | "segments">;
    export type FromPolygonPoints = Inputs.JSCAD.FromPolygonPoints;
    export type GeodesicSphereBaseDto = WithDefaults<Inputs.JSCAD.GeodesicSphereBaseDto, "radius" | "frequency">;
    export type GeodesicSphereCentersDto = WithDefaults<Inputs.JSCAD.GeodesicSphereCentersDto, "radius" | "frequency">;
    export type GeodesicSphereDto = WithDefaults<Inputs.JSCAD.GeodesicSphereDto, "radius" | "frequency" | "center">;
    export type HullDto = Inputs.JSCAD.HullDto;
    export type MeshDto = Inputs.JSCAD.MeshDto;
    export type MeshesDto = Inputs.JSCAD.MeshesDto;
    export type MinkowskiSumDto = Inputs.JSCAD.MinkowskiSumDto;
    export type PathAppendArcDto = WithDefaults<Inputs.JSCAD.PathAppendArcDto, "endPoint" | "xAxisRotation" | "clockwise" | "large" | "segments" | "radiusX" | "radiusY">;
    export type PathAppendPointsDto = Inputs.JSCAD.PathAppendPointsDto;
    export type PathAppendPolylineDto = Inputs.JSCAD.PathAppendPolylineDto;
    export type PathDto = Inputs.JSCAD.PathDto;
    export type PathFromPointsDto = WithDefaults<Inputs.JSCAD.PathFromPointsDto, "closed">;
    export type PathFromPolylineDto = WithDefaults<Inputs.JSCAD.PathFromPolylineDto, "closed">;
    export type PathsFromPointsDto = Inputs.JSCAD.PathsFromPointsDto;
    export type PointsDto = Inputs.JSCAD.PointsDto;
    export type PolygonPointsDto = Inputs.JSCAD.PolygonPointsDto;
    export type PolylineDto = Inputs.JSCAD.PolylineDto;
    export type PolylinePropertiesDto = WithDefaults<Inputs.JSCAD.PolylinePropertiesDto, "isClosed">;
    export type RectangleDto = WithDefaults<Inputs.JSCAD.RectangleDto, "center" | "width" | "length">;
    export type RoundedCuboidBaseDto = WithDefaults<Inputs.JSCAD.RoundedCuboidBaseDto, "roundRadius" | "width" | "length" | "height" | "segments">;
    export type RoundedCuboidCentersDto = WithDefaults<Inputs.JSCAD.RoundedCuboidCentersDto, "roundRadius" | "width" | "length" | "height" | "segments">;
    export type RoundedCuboidDto = WithDefaults<Inputs.JSCAD.RoundedCuboidDto, "roundRadius" | "width" | "length" | "height" | "segments" | "center">;
    export type RoundedCylidnerCentersDto = WithDefaults<Inputs.JSCAD.RoundedCylidnerCentersDto, "roundRadius" | "height" | "radius" | "segments">;
    export type RoundedCylidnerDto = WithDefaults<Inputs.JSCAD.RoundedCylidnerDto, "roundRadius" | "height" | "radius" | "segments" | "center">;
    export type RoundedCylinderBaseDto = WithDefaults<Inputs.JSCAD.RoundedCylinderBaseDto, "roundRadius" | "height" | "radius" | "segments">;
    export type RoundedRectangleDto = WithDefaults<Inputs.JSCAD.RoundedRectangleDto, "center" | "roundRadius" | "segments" | "width" | "length">;
    export type SolidDto = Inputs.JSCAD.SolidDto;
    export type SphereBaseDto = WithDefaults<Inputs.JSCAD.SphereBaseDto, "radius" | "segments">;
    export type SphereCentersDto = WithDefaults<Inputs.JSCAD.SphereCentersDto, "radius" | "segments">;
    export type SphereDto = WithDefaults<Inputs.JSCAD.SphereDto, "radius" | "segments" | "center">;
    export type SphereTextDto = WithDefaults<Inputs.JSCAD.SphereTextDto, "text" | "radius" | "segments" | "xOffset" | "yOffset" | "height" | "lineSpacing" | "letterSpacing" | "align" | "extrudeOffset">;
    export type SquareDto = WithDefaults<Inputs.JSCAD.SquareDto, "center" | "size">;
    export type StarDto = WithDefaults<Inputs.JSCAD.StarDto, "center" | "vertices" | "density" | "outerRadius" | "innerRadius" | "startAngle">;
    export type TextDto = WithDefaults<Inputs.JSCAD.TextDto, "text" | "segments" | "xOffset" | "yOffset" | "height" | "lineSpacing" | "letterSpacing" | "align" | "extrudeOffset">;
    export type TorusDto = WithDefaults<Inputs.JSCAD.TorusDto, "center" | "innerRadius" | "outerRadius" | "innerSegments" | "outerSegments" | "innerRotation" | "outerRotation" | "startAngle">;
    export type TransformSolidDto = Inputs.JSCAD.TransformSolidDto;
    export type TransformSolidsDto = Inputs.JSCAD.TransformSolidsDto;
}
