// GENERATED by scripts/gen-dto-meta.mjs from the Jscad surface - do not edit; regenerate with `npm run gen:dto-meta`.
import { constraintKinds as k, DtoConstraints, DtoRegistry } from "@bitbybit-dev/base";
import * as Inputs from "./inputs";

const JSCAD_BooleanObjectsDto: DtoConstraints = { meshes: k.required(k.list(k.opaque)) };
const JSCAD_BooleanObjectsFromDto: DtoConstraints = { from: k.required(k.opaque), meshes: k.required(k.list(k.opaque)) };
const JSCAD_BooleanTwoObjectsDto: DtoConstraints = { first: k.required(k.opaque), second: k.required(k.opaque) };
const JSCAD_CircleDto: DtoConstraints = { center: k.point2, radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 3 }) };
const JSCAD_ColorizeDto: DtoConstraints = { geometry: k.required(k.opaque), color: k.string };
const JSCAD_CubeCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), size: k.between(k.number, { min: 0 }) };
const JSCAD_CubeDto: DtoConstraints = { center: k.point3, size: k.between(k.number, { min: 0 }) };
const JSCAD_CuboidCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), width: k.between(k.number, { min: 0 }), length: k.between(k.number, { min: 0 }), height: k.between(k.number, { min: 0 }) };
const JSCAD_CuboidDto: DtoConstraints = { center: k.point3, width: k.between(k.number, { min: 0 }), length: k.between(k.number, { min: 0 }), height: k.between(k.number, { min: 0 }) };
const JSCAD_CurveDto: DtoConstraints = { curve: k.required(k.opaque) };
const JSCAD_CylidnerCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), height: k.between(k.number, { min: 0 }), radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_CylidnerCentersEllipticDto: DtoConstraints = { centers: k.required(k.list(k.point3)), height: k.between(k.number, { min: 0, exclusiveMin: true }), startRadius: k.point2, endRadius: k.point2, segments: k.between(k.number, { min: 4 }) };
const JSCAD_CylidnerDto: DtoConstraints = { center: k.point3, height: k.between(k.number, { min: 0 }), radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_CylidnerEllipticDto: DtoConstraints = { center: k.point3, height: k.between(k.number, { min: 0, exclusiveMin: true }), startRadius: k.vector2, endRadius: k.vector2, segments: k.between(k.number, { min: 4 }) };
const JSCAD_CylinderTextDto: DtoConstraints = { text: k.string, extrusionHeight: k.between(k.number, { min: 0 }), extrusionSize: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }), xOffset: k.number, yOffset: k.number, height: k.between(k.number, { min: 0 }), lineSpacing: k.number, letterSpacing: k.number, align: k.oneOf(["left", "center", "right"]), extrudeOffset: k.number };
const JSCAD_DownloadGeometryDto: DtoConstraints = { geometry: k.required(k.opaque), fileName: k.string, options: k.opaque };
const JSCAD_DownloadSolidDto: DtoConstraints = { mesh: k.required(k.opaque), fileName: k.required(k.string) };
const JSCAD_DownloadSolidsDto: DtoConstraints = { meshes: k.required(k.list(k.opaque)), fileName: k.required(k.string) };
const JSCAD_EllipseDto: DtoConstraints = { center: k.point2, radius: k.point2, segments: k.between(k.number, { min: 3 }) };
const JSCAD_EllipsoidCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), radius: k.point3, segments: k.between(k.number, { min: 4 }) };
const JSCAD_EllipsoidDto: DtoConstraints = { center: k.point3, radius: k.point3, segments: k.between(k.number, { min: 4 }) };
const JSCAD_ExpandDto: DtoConstraints = { geometry: k.required(k.opaque), delta: k.number, corners: k.oneOf(["edge", "round", "chamfer"]), segments: k.between(k.number, { min: 0 }) };
const JSCAD_ExpansionDto: DtoConstraints = { geometry: k.required(k.opaque), delta: k.number, corners: k.oneOf(["edge", "round", "chamfer"]), segments: k.between(k.number, { min: 0 }) };
const JSCAD_ExtrudeLinearDto: DtoConstraints = { geometry: k.required(k.opaque), height: k.number, twistAngle: k.number, twistSteps: k.between(k.number, { min: 1 }) };
const JSCAD_ExtrudeRectangularDto: DtoConstraints = { geometry: k.required(k.opaque), height: k.between(k.number, { min: 0, exclusiveMin: true }), size: k.between(k.number, { min: 0, exclusiveMin: true }) };
const JSCAD_ExtrudeRectangularPointsDto: DtoConstraints = { points: k.required(k.list(k.point3)), height: k.between(k.number, { min: 0, exclusiveMin: true }), size: k.between(k.number, { min: 0, exclusiveMin: true }) };
const JSCAD_ExtrudeRotateDto: DtoConstraints = { polygon: k.required(k.opaque), angle: k.number, startAngle: k.number, segments: k.between(k.number, { min: 3 }) };
const JSCAD_FromPolygonPoints: DtoConstraints = { polygonPoints: k.required(k.list(k.list(k.point3))) };
const JSCAD_GeodesicSphereCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), radius: k.between(k.number, { min: 0 }), frequency: k.between(k.number, { min: 6 }) };
const JSCAD_GeodesicSphereDto: DtoConstraints = { center: k.point3, radius: k.between(k.number, { min: 0 }), frequency: k.between(k.number, { min: 6 }) };
const JSCAD_HullDto: DtoConstraints = { meshes: k.required(k.list(k.opaque)) };
const JSCAD_MeshDto: DtoConstraints = { mesh: k.required(k.opaque) };
const JSCAD_MeshesDto: DtoConstraints = { meshes: k.required(k.list(k.opaque)) };
const JSCAD_MinkowskiSumDto: DtoConstraints = { meshes: k.required(k.list(k.opaque)) };
const JSCAD_PathAppendArcDto: DtoConstraints = { path: k.required(k.opaque), endPoint: k.point2, xAxisRotation: k.number, clockwise: k.boolean, large: k.boolean, segments: k.between(k.number, { min: 4 }), radiusX: k.between(k.number, { min: 0 }), radiusY: k.between(k.number, { min: 0 }) };
const JSCAD_PathAppendPointsDto: DtoConstraints = { points: k.required(k.list(k.point2)), path: k.required(k.opaque) };
const JSCAD_PathAppendPolylineDto: DtoConstraints = { polyline: k.required(k.opaque), path: k.required(k.opaque) };
const JSCAD_PathDto: DtoConstraints = { path: k.required(k.opaque) };
const JSCAD_PathFromPointsDto: DtoConstraints = { points: k.required(k.list(k.point2)), closed: k.boolean };
const JSCAD_PathFromPolylineDto: DtoConstraints = { polyline: k.required(k.opaque), closed: k.boolean };
const JSCAD_PathsFromPointsDto: DtoConstraints = { pointsLists: k.required(k.opaque) };
const JSCAD_PointsDto: DtoConstraints = { points: k.required(k.list(k.point)) };
const JSCAD_PolylineDto: DtoConstraints = { polyline: k.required(k.opaque) };
const JSCAD_RectangleDto: DtoConstraints = { center: k.point2, width: k.between(k.number, { min: 0 }), length: k.between(k.number, { min: 0 }) };
const JSCAD_RoundedCuboidCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), roundRadius: k.between(k.number, { min: 0 }), width: k.between(k.number, { min: 0 }), length: k.between(k.number, { min: 0 }), height: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_RoundedCuboidDto: DtoConstraints = { center: k.point3, roundRadius: k.between(k.number, { min: 0 }), width: k.between(k.number, { min: 0 }), length: k.between(k.number, { min: 0 }), height: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_RoundedCylidnerCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), roundRadius: k.between(k.number, { min: 0 }), height: k.between(k.number, { min: 0 }), radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_RoundedCylidnerDto: DtoConstraints = { center: k.point3, roundRadius: k.between(k.number, { min: 0 }), height: k.between(k.number, { min: 0 }), radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_RoundedRectangleDto: DtoConstraints = { center: k.point2, roundRadius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }), width: k.between(k.number, { min: 0 }), length: k.between(k.number, { min: 0 }) };
const JSCAD_SolidDto: DtoConstraints = { mesh: k.required(k.opaque) };
const JSCAD_SphereCentersDto: DtoConstraints = { centers: k.required(k.list(k.point3)), radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_SphereDto: DtoConstraints = { center: k.point3, radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }) };
const JSCAD_SphereTextDto: DtoConstraints = { text: k.string, radius: k.between(k.number, { min: 0 }), segments: k.between(k.number, { min: 4 }), xOffset: k.number, yOffset: k.number, height: k.between(k.number, { min: 0 }), lineSpacing: k.number, letterSpacing: k.number, align: k.oneOf(["left", "center", "right"]), extrudeOffset: k.number };
const JSCAD_SquareDto: DtoConstraints = { center: k.point2, size: k.between(k.number, { min: 0 }) };
const JSCAD_StarDto: DtoConstraints = { center: k.point2, vertices: k.between(k.number, { min: 2 }), density: k.between(k.number, { min: 0 }), outerRadius: k.between(k.number, { min: 0, exclusiveMin: true }), innerRadius: k.between(k.number, { min: 0 }), startAngle: k.between(k.number, { min: 0 }) };
const JSCAD_TextDto: DtoConstraints = { text: k.string, segments: k.between(k.number, { min: 0 }), xOffset: k.number, yOffset: k.number, height: k.between(k.number, { min: 0 }), lineSpacing: k.number, letterSpacing: k.number, align: k.oneOf(["left", "center", "right"]), extrudeOffset: k.number };
const JSCAD_TorusDto: DtoConstraints = { center: k.point3, innerRadius: k.between(k.number, { min: 0, exclusiveMin: true }), outerRadius: k.between(k.number, { min: 0, exclusiveMin: true }), innerSegments: k.between(k.number, { min: 3 }), outerSegments: k.between(k.number, { min: 3 }), innerRotation: k.number, outerRotation: k.between(k.number, { min: 0, exclusiveMin: true }), startAngle: k.between(k.number, { min: 0 }) };
const JSCAD_TransformSolidDto: DtoConstraints = { mesh: k.required(k.opaque), transformation: k.required(k.opaque) };
const JSCAD_TransformSolidsDto: DtoConstraints = { meshes: k.required(k.list(k.opaque)), transformation: k.required(k.opaque) };

/**
 * Every public operation of the JSCAD kernel by its dotted path, the inputs DTO it
 * takes, and what each property of that DTO accepts. `resolveInputs` from the base package reads
 * it to lay a caller's properties over that DTO's defaults before the kernel runs, and
 * `validateInputs` to check what the call was given.
 */
export const jscadDtoRegistry: DtoRegistry = {
    "booleans.intersect": { dto: Inputs.JSCAD.BooleanObjectsDto, constraints: JSCAD_BooleanObjectsDto },
    "booleans.intersectTwo": { dto: Inputs.JSCAD.BooleanTwoObjectsDto, constraints: JSCAD_BooleanTwoObjectsDto },
    "booleans.minkowskiSum": { dto: Inputs.JSCAD.MinkowskiSumDto, constraints: JSCAD_MinkowskiSumDto },
    "booleans.subtract": { dto: Inputs.JSCAD.BooleanObjectsDto, constraints: JSCAD_BooleanObjectsDto },
    "booleans.subtractFrom": { dto: Inputs.JSCAD.BooleanObjectsFromDto, constraints: JSCAD_BooleanObjectsFromDto },
    "booleans.subtractTwo": { dto: Inputs.JSCAD.BooleanTwoObjectsDto, constraints: JSCAD_BooleanTwoObjectsDto },
    "booleans.union": { dto: Inputs.JSCAD.BooleanObjectsDto, constraints: JSCAD_BooleanObjectsDto },
    "booleans.unionTwo": { dto: Inputs.JSCAD.BooleanTwoObjectsDto, constraints: JSCAD_BooleanTwoObjectsDto },
    "colors.colorize": { dto: Inputs.JSCAD.ColorizeDto, constraints: JSCAD_ColorizeDto },
    "downloadGeometry3MF": { dto: Inputs.JSCAD.DownloadGeometryDto, constraints: JSCAD_DownloadGeometryDto },
    "downloadGeometryDxf": { dto: Inputs.JSCAD.DownloadGeometryDto, constraints: JSCAD_DownloadGeometryDto },
    "downloadSolidsSTL": { dto: Inputs.JSCAD.DownloadSolidsDto, constraints: JSCAD_DownloadSolidsDto },
    "downloadSolidSTL": { dto: Inputs.JSCAD.DownloadSolidDto, constraints: JSCAD_DownloadSolidDto },
    "expansions.expand": { dto: Inputs.JSCAD.ExpandDto, constraints: JSCAD_ExpandDto },
    "expansions.offset": { dto: Inputs.JSCAD.ExpansionDto, constraints: JSCAD_ExpansionDto },
    "extrusions.extrudeLinear": { dto: Inputs.JSCAD.ExtrudeLinearDto, constraints: JSCAD_ExtrudeLinearDto },
    "extrusions.extrudeRectangular": { dto: Inputs.JSCAD.ExtrudeRectangularDto, constraints: JSCAD_ExtrudeRectangularDto },
    "extrusions.extrudeRectangularPoints": { dto: Inputs.JSCAD.ExtrudeRectangularPointsDto, constraints: JSCAD_ExtrudeRectangularPointsDto },
    "extrusions.extrudeRotate": { dto: Inputs.JSCAD.ExtrudeRotateDto, constraints: JSCAD_ExtrudeRotateDto },
    "hulls.hull": { dto: Inputs.JSCAD.HullDto, constraints: JSCAD_HullDto },
    "hulls.hullChain": { dto: Inputs.JSCAD.HullDto, constraints: JSCAD_HullDto },
    "hulls.isConvex": { dto: Inputs.JSCAD.SolidDto, constraints: JSCAD_SolidDto },
    "path.appendArc": { dto: Inputs.JSCAD.PathAppendArcDto, constraints: JSCAD_PathAppendArcDto },
    "path.appendPoints": { dto: Inputs.JSCAD.PathAppendPointsDto, constraints: JSCAD_PathAppendPointsDto },
    "path.appendPolyline": { dto: Inputs.JSCAD.PathAppendPolylineDto, nested: { polyline: Inputs.JSCAD.PolylinePropertiesDto }, constraints: JSCAD_PathAppendPolylineDto },
    "path.close": { dto: Inputs.JSCAD.PathDto, constraints: JSCAD_PathDto },
    "path.createEmpty": {},
    "path.createFromPoints": { dto: Inputs.JSCAD.PathFromPointsDto, constraints: JSCAD_PathFromPointsDto },
    "path.createFromPolyline": { dto: Inputs.JSCAD.PathFromPolylineDto, nested: { polyline: Inputs.JSCAD.PolylinePropertiesDto }, constraints: JSCAD_PathFromPolylineDto },
    "path.createPathsFromPoints": { dto: Inputs.JSCAD.PathsFromPointsDto, constraints: JSCAD_PathsFromPointsDto },
    "polygon.circle": { dto: Inputs.JSCAD.CircleDto, constraints: JSCAD_CircleDto },
    "polygon.createFromCurve": { dto: Inputs.JSCAD.CurveDto, constraints: JSCAD_CurveDto },
    "polygon.createFromPath": { dto: Inputs.JSCAD.PathDto, constraints: JSCAD_PathDto },
    "polygon.createFromPoints": { dto: Inputs.JSCAD.PointsDto, constraints: JSCAD_PointsDto },
    "polygon.createFromPolyline": { dto: Inputs.JSCAD.PolylineDto, nested: { polyline: Inputs.JSCAD.PolylinePropertiesDto }, constraints: JSCAD_PolylineDto },
    "polygon.ellipse": { dto: Inputs.JSCAD.EllipseDto, constraints: JSCAD_EllipseDto },
    "polygon.rectangle": { dto: Inputs.JSCAD.RectangleDto, constraints: JSCAD_RectangleDto },
    "polygon.roundedRectangle": { dto: Inputs.JSCAD.RoundedRectangleDto, constraints: JSCAD_RoundedRectangleDto },
    "polygon.square": { dto: Inputs.JSCAD.SquareDto, constraints: JSCAD_SquareDto },
    "polygon.star": { dto: Inputs.JSCAD.StarDto, constraints: JSCAD_StarDto },
    "shapes.cube": { dto: Inputs.JSCAD.CubeDto, constraints: JSCAD_CubeDto },
    "shapes.cubesOnCenterPoints": { dto: Inputs.JSCAD.CubeCentersDto, constraints: JSCAD_CubeCentersDto },
    "shapes.cuboid": { dto: Inputs.JSCAD.CuboidDto, constraints: JSCAD_CuboidDto },
    "shapes.cuboidsOnCenterPoints": { dto: Inputs.JSCAD.CuboidCentersDto, constraints: JSCAD_CuboidCentersDto },
    "shapes.cylinder": { dto: Inputs.JSCAD.CylidnerDto, constraints: JSCAD_CylidnerDto },
    "shapes.cylinderElliptic": { dto: Inputs.JSCAD.CylidnerEllipticDto, constraints: JSCAD_CylidnerEllipticDto },
    "shapes.cylinderEllipticOnCenterPoints": { dto: Inputs.JSCAD.CylidnerCentersEllipticDto, constraints: JSCAD_CylidnerCentersEllipticDto },
    "shapes.cylindersOnCenterPoints": { dto: Inputs.JSCAD.CylidnerCentersDto, constraints: JSCAD_CylidnerCentersDto },
    "shapes.ellipsoid": { dto: Inputs.JSCAD.EllipsoidDto, constraints: JSCAD_EllipsoidDto },
    "shapes.ellipsoidsOnCenterPoints": { dto: Inputs.JSCAD.EllipsoidCentersDto, constraints: JSCAD_EllipsoidCentersDto },
    "shapes.fromPolygonPoints": { dto: Inputs.JSCAD.FromPolygonPoints, constraints: JSCAD_FromPolygonPoints },
    "shapes.geodesicSphere": { dto: Inputs.JSCAD.GeodesicSphereDto, constraints: JSCAD_GeodesicSphereDto },
    "shapes.geodesicSpheresOnCenterPoints": { dto: Inputs.JSCAD.GeodesicSphereCentersDto, constraints: JSCAD_GeodesicSphereCentersDto },
    "shapes.roundedCuboid": { dto: Inputs.JSCAD.RoundedCuboidDto, constraints: JSCAD_RoundedCuboidDto },
    "shapes.roundedCuboidsOnCenterPoints": { dto: Inputs.JSCAD.RoundedCuboidCentersDto, constraints: JSCAD_RoundedCuboidCentersDto },
    "shapes.roundedCylinder": { dto: Inputs.JSCAD.RoundedCylidnerDto, constraints: JSCAD_RoundedCylidnerDto },
    "shapes.roundedCylindersOnCenterPoints": { dto: Inputs.JSCAD.RoundedCylidnerCentersDto, constraints: JSCAD_RoundedCylidnerCentersDto },
    "shapes.sphere": { dto: Inputs.JSCAD.SphereDto, constraints: JSCAD_SphereDto },
    "shapes.spheresOnCenterPoints": { dto: Inputs.JSCAD.SphereCentersDto, constraints: JSCAD_SphereCentersDto },
    "shapes.torus": { dto: Inputs.JSCAD.TorusDto, constraints: JSCAD_TorusDto },
    "shapesToMeshes": { dto: Inputs.JSCAD.MeshesDto, constraints: JSCAD_MeshesDto },
    "shapeToMesh": { dto: Inputs.JSCAD.MeshDto, constraints: JSCAD_MeshDto },
    "text.createVectorText": { dto: Inputs.JSCAD.TextDto, constraints: JSCAD_TextDto },
    "text.cylindricalText": { dto: Inputs.JSCAD.CylinderTextDto, constraints: JSCAD_CylinderTextDto },
    "text.sphericalText": { dto: Inputs.JSCAD.SphereTextDto, constraints: JSCAD_SphereTextDto },
    "toPolygonPoints": { dto: Inputs.JSCAD.MeshDto, constraints: JSCAD_MeshDto },
    "transformSolid": { dto: Inputs.JSCAD.TransformSolidDto, constraints: JSCAD_TransformSolidDto },
    "transformSolids": { dto: Inputs.JSCAD.TransformSolidsDto, constraints: JSCAD_TransformSolidsDto },
};
