// GENERATED by scripts/gen-worker-api.mjs from packages/dev/ifc/lib/api/services/quantities.ts - do not edit; regenerate with `npm run gen:worker-api`.
import * as Inputs from "@bitbybit-dev/ifc/lib/api/inputs";
import { IFCWorkerManager } from "../ifc-worker/ifc-worker-manager";

/**
 * Quantities: the base quantity sets IFC defines, such as `Qto_WallBaseQuantities` with a wall's
 * length, side areas and volumes net of its openings, measured from the elements' own geometry, so
 * other tools schedule and price them.
 * @beta
 */
export class IFCQuantities {
    constructor(
        private readonly ifcWorkerManager: IFCWorkerManager,
    ) {
    }

    /**
     * Measures elements and writes their base quantity sets, replacing any set of the same name: walls,
     * slabs, columns, beams, members, doors, windows, wall openings, spaces and roofs. A wall's volume
     * and side area follow its clippings and lose its openings. Measure again after changing elements.
     * @param inputs - The model and, optionally, the elements to measure
     * @returns A new model with the quantity sets
     * @group quantities
     * @shortname compute quantities
     * @drawable false
     * @example
     * ```typescript
     * model = await bitbybit.ifc.quantities.compute({ model });
     * ```
     */
    compute(inputs: Inputs.IFC.ComputeQuantitiesDto<Inputs.IFC.IfcModelPointer>): Promise<Inputs.IFC.IfcModelPointer> {
        return this.ifcWorkerManager.genericCallToWorkerPromise("quantities.compute", inputs);
    }

    /**
     * Reads the quantity sets of an element, with each quantity's value by name.
     * @param inputs - The model and the element
     * @returns The element's quantity sets
     * @group quantities
     * @shortname get quantities
     * @drawable false
     * @example
     * ```typescript
     * const sets = await bitbybit.ifc.quantities.get({ model, element: "south" });
     * ```
     */
    get(inputs: Inputs.IFC.ElementDto<Inputs.IFC.IfcModelPointer>): Promise<Inputs.IFC.QuantitySetInfoDto[]> {
        return this.ifcWorkerManager.genericCallToWorkerPromise("quantities.get", inputs);
    }
}
