// GENERATED by scripts/gen-worker-api.mjs from packages/dev/ifc/lib/api/services/windows.ts - do not edit; regenerate with `npm run gen:worker-api`.
import * as Inputs from "@bitbybit-dev/ifc/lib/api/inputs";
import { IFCWorkerManager } from "../ifc-worker/ifc-worker-manager";

/**
 * Windows: window types, each a frame around one pane of glass, and windows of those types placed
 * in walls. A window cuts its own opening and shares its type's geometry, so a type placed many
 * times is written once.
 * @beta
 */
export class IFCWindows {
    constructor(
        private readonly ifcWorkerManager: IFCWorkerManager,
    ) {
    }

    /**
     * Adds a window type: a frame around one pane, `width` by `height`, which windows are then
     * placed from.
     *
     * The frame's members are `frameThickness` wide and `frameDepth` deep; the glass sits in the
     * middle of the depth.
     * @param inputs - The model, the type's id and name, and its sizes
     * @returns A new model with the window type
     * @group types
     * @shortname add window type
     * @drawable false
     * @example
     * ```typescript
     * model = await bitbybit.ifc.windows.addType({ model, id: "window-120", name: "Window 1200", width: 1200, height: 1400 });
     * ```
     */
    addType(inputs: Inputs.IFC.AddWindowTypeDto<Inputs.IFC.IfcModelPointer>): Promise<Inputs.IFC.IfcModelPointer> {
        return this.ifcWorkerManager.genericCallToWorkerPromise("windows.addType", inputs);
    }

    /**
     * Places a window of a window type in a wall, `offset` along the wall's axis from its start and
     * `sill` above its base, cutting an opening as wide and high as the type.
     *
     * The window is centred in the wall's thickness and belongs to the wall's storey. It must fit
     * along the wall.
     * @param inputs - The model, the wall, the window type, and where the window goes
     * @returns A new model with the window
     * @group create
     * @shortname add window
     * @drawable false
     * @example
     * ```typescript
     * model = await bitbybit.ifc.windows.add({ model, wall: "south", windowType: "window-120", offset: 6000, sill: 900 });
     * ```
     */
    add(inputs: Inputs.IFC.AddWindowDto<Inputs.IFC.IfcModelPointer>): Promise<Inputs.IFC.IfcModelPointer> {
        return this.ifcWorkerManager.genericCallToWorkerPromise("windows.add", inputs);
    }
}
