import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    api: [
        "intro",
        {
            type: "category",
            label: "SDK",
            items: [
                {
                    type: "category",
                    label: "TypeScript",
                    link: {
                        type: "doc",
                        id: "sdk/typescript/intro",
                    },
                    items: [
                        "sdk/typescript/models",
                        "sdk/typescript/cad-operations",
                        "sdk/typescript/conversion",
                        "sdk/typescript/tasks",
                        "sdk/typescript/files",
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Studio",
            items: [
                "studio/intro",
            ],
        },

        // Auto-generated OpenAPI reference pages
        {
            type: "category",
            label: "API Reference",
            link: {
                type: "generated-index",
                title: "Bitbybit CAD Cloud API",
                description: "Full endpoint reference — models, tasks, CAD operations, conversion, and files.",
                slug: "/api-reference",
            },
            items: [
                { type: "autogenerated", dirName: "openapi-docs" },
            ],
        },
    ],
};

export default sidebars;
