// GENERATED by scripts/gen-dto-meta.mjs from the inputs DTOs - do not edit.
// Regenerate with `npm run gen:dto-meta` at the repository root.
/* eslint-disable @typescript-eslint/no-namespace */
import { WithDefaults } from "@bitbybit-dev/base";
import * as Inputs from "../inputs";
export type { Asset, CSV, JSON, JSCAD, Manifold, OCCT, Tag, Time, Verb, Color, Dates, IO, Line, Lists, Logic, Math, Mesh, Point, Polyline, Text, Transforms, Vector } from "@bitbybit-dev/core/lib/api/resolved-inputs";

/**
 * The BabylonCamera inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonCamera {
    export type ArcRotateCameraDto = WithDefaults<Inputs.BabylonCamera.ArcRotateCameraDto, "radius" | "target" | "alpha" | "beta" | "lowerBetaLimit" | "upperBetaLimit" | "angularSensibilityX" | "angularSensibilityY" | "panningSensibility" | "wheelPrecision" | "maxZ">;
    export type CameraDto = Inputs.BabylonCamera.CameraDto;
    export type FreeCameraDto = WithDefaults<Inputs.BabylonCamera.FreeCameraDto, "position" | "target">;
    export type MaxZDto = WithDefaults<Inputs.BabylonCamera.MaxZDto, "maxZ">;
    export type MinZDto = WithDefaults<Inputs.BabylonCamera.MinZDto, "minZ">;
    export type OrthographicDto = WithDefaults<Inputs.BabylonCamera.OrthographicDto, "orthoLeft" | "orthoRight" | "orthoBottom" | "orthoTop">;
    export type PositionDto = WithDefaults<Inputs.BabylonCamera.PositionDto, "position">;
    export type SpeedDto = WithDefaults<Inputs.BabylonCamera.SpeedDto, "speed">;
    export type TargetCameraDto = WithDefaults<Inputs.BabylonCamera.TargetCameraDto, "position" | "target">;
    export type TargetDto = WithDefaults<Inputs.BabylonCamera.TargetDto, "target">;
}

/**
 * The BabylonDecal inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonDecal {
    export type CreateMeshDecalDto = WithDefaults<Inputs.BabylonDecal.CreateMeshDecalDto, "position" | "normal" | "size" | "angle" | "cullBackFaces" | "localMode" | "zOffset">;
    export type DecalMapDto = Inputs.BabylonDecal.DecalMapDto;
    export type EnableDecalMapDto = WithDefaults<Inputs.BabylonDecal.EnableDecalMapDto, "width" | "height">;
    export type ProjectDecalDto = WithDefaults<Inputs.BabylonDecal.ProjectDecalDto, "position" | "normal" | "size" | "angle">;
}

/**
 * The BabylonGaussianSplatting inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonGaussianSplatting {
    export type CreateGaussianSplattingMeshDto = Inputs.BabylonGaussianSplatting.CreateGaussianSplattingMeshDto;
    export type GaussianSplattingMeshDto = Inputs.BabylonGaussianSplatting.GaussianSplattingMeshDto;
}

/**
 * The BabylonGizmo inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonGizmo {
    export type AttachToMeshDto = Inputs.BabylonGizmo.AttachToMeshDto;
    export type AxisDragGizmoDto = Inputs.BabylonGizmo.AxisDragGizmoDto;
    export type AxisScaleGizmoDto = Inputs.BabylonGizmo.AxisScaleGizmoDto;
    export type BoundingBoxGizmoDto = Inputs.BabylonGizmo.BoundingBoxGizmoDto;
    export type BoundingBoxGizmoObservableSelectorDto = Inputs.BabylonGizmo.BoundingBoxGizmoObservableSelectorDto;
    export type CreateGizmoDto = WithDefaults<Inputs.BabylonGizmo.CreateGizmoDto, "positionGizmoEnabled" | "rotationGizmoEnabled" | "scaleGizmoEnabled" | "boundingBoxGizmoEnabled" | "usePointerToAttachGizmos" | "clearGizmoOnEmptyPointerEvent" | "scaleRatio">;
    export type GizmoDto = Inputs.BabylonGizmo.GizmoDto;
    export type GizmoManagerDto = Inputs.BabylonGizmo.GizmoManagerDto;
    export type PlaneDragGizmoDto = Inputs.BabylonGizmo.PlaneDragGizmoDto;
    export type PlaneRotationGizmoDto = Inputs.BabylonGizmo.PlaneRotationGizmoDto;
    export type PositionGizmoDto = Inputs.BabylonGizmo.PositionGizmoDto;
    export type PositionGizmoObservableSelectorDto = Inputs.BabylonGizmo.PositionGizmoObservableSelectorDto;
    export type RotationGizmoDto = Inputs.BabylonGizmo.RotationGizmoDto;
    export type RotationGizmoObservableSelectorDto = Inputs.BabylonGizmo.RotationGizmoObservableSelectorDto;
    export type ScaleGizmoDto = Inputs.BabylonGizmo.ScaleGizmoDto;
    export type ScaleGizmoObservableSelectorDto = Inputs.BabylonGizmo.ScaleGizmoObservableSelectorDto;
    export type SetBoundingBoxGizmoAxisFactorDto = Inputs.BabylonGizmo.SetBoundingBoxGizmoAxisFactorDto;
    export type SetBoundingBoxGizmoFixedDragMeshBoundsSizeDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoFixedDragMeshBoundsSizeDto, "fixedDragMeshBoundsSize">;
    export type SetBoundingBoxGizmoFixedDragMeshScreenSizeDistanceFactorDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoFixedDragMeshScreenSizeDistanceFactorDto, "fixedDragMeshScreenSizeDistanceFactor">;
    export type SetBoundingBoxGizmoFixedDragMeshScreenSizeDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoFixedDragMeshScreenSizeDto, "fixedDragMeshScreenSize">;
    export type SetBoundingBoxGizmoIncrementalSnapDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoIncrementalSnapDto, "incrementalSnap">;
    export type SetBoundingBoxGizmoRotationSnapDistanceDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoRotationSnapDistanceDto, "rotationSnapDistance">;
    export type SetBoundingBoxGizmoRotationSphereSizeDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoRotationSphereSizeDto, "rotationSphereSize">;
    export type SetBoundingBoxGizmoScaleBoxSizeDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoScaleBoxSizeDto, "scaleBoxSize">;
    export type SetBoundingBoxGizmoScaleDragSpeedDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoScaleDragSpeedDto, "scaleDragSpeed">;
    export type SetBoundingBoxGizmoScalePivotDto = Inputs.BabylonGizmo.SetBoundingBoxGizmoScalePivotDto;
    export type SetBoundingBoxGizmoScalingSnapDistanceDto = WithDefaults<Inputs.BabylonGizmo.SetBoundingBoxGizmoScalingSnapDistanceDto, "scalingSnapDistance">;
    export type SetGizmoScaleRatioDto = WithDefaults<Inputs.BabylonGizmo.SetGizmoScaleRatioDto, "scaleRatio">;
    export type SetIsEnabledAxisDragGizmoDto = WithDefaults<Inputs.BabylonGizmo.SetIsEnabledAxisDragGizmoDto, "isEnabled">;
    export type SetIsEnabledAxisScaleGizmoDto = WithDefaults<Inputs.BabylonGizmo.SetIsEnabledAxisScaleGizmoDto, "isEnabled">;
    export type SetIsEnabledPlaneDragGizmoDto = WithDefaults<Inputs.BabylonGizmo.SetIsEnabledPlaneDragGizmoDto, "isEnabled">;
    export type SetIsEnabledPlaneRotationGizmoDto = WithDefaults<Inputs.BabylonGizmo.SetIsEnabledPlaneRotationGizmoDto, "isEnabled">;
    export type SetPlanarGizmoEnabled = WithDefaults<Inputs.BabylonGizmo.SetPlanarGizmoEnabled, "planarGizmoEnabled">;
    export type SetPositionGizmoSnapDistanceDto = WithDefaults<Inputs.BabylonGizmo.SetPositionGizmoSnapDistanceDto, "snapDistance">;
    export type SetRotationGizmoSensitivityDto = WithDefaults<Inputs.BabylonGizmo.SetRotationGizmoSensitivityDto, "sensitivity">;
    export type SetRotationGizmoSnapDistanceDto = WithDefaults<Inputs.BabylonGizmo.SetRotationGizmoSnapDistanceDto, "snapDistance">;
    export type SetScaleGizmoIncrementalSnapDto = WithDefaults<Inputs.BabylonGizmo.SetScaleGizmoIncrementalSnapDto, "incrementalSnap">;
    export type SetScaleGizmoSensitivityDto = WithDefaults<Inputs.BabylonGizmo.SetScaleGizmoSensitivityDto, "sensitivity">;
    export type SetScaleGizmoSnapDistanceDto = WithDefaults<Inputs.BabylonGizmo.SetScaleGizmoSnapDistanceDto, "snapDistance">;
}

/**
 * The BabylonGltf inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonGltf {
    export type AnimationGroupDto = Inputs.BabylonGltf.AnimationGroupDto;
    export type AssetContainerDto = Inputs.BabylonGltf.AssetContainerDto;
    export type GltfRootNodeDto = Inputs.BabylonGltf.GltfRootNodeDto;
    export type PlayAnimationGroupDto = WithDefaults<Inputs.BabylonGltf.PlayAnimationGroupDto, "loop" | "speedRatio">;
    export type SelectVariantDto = Inputs.BabylonGltf.SelectVariantDto;
}

/**
 * The BabylonGui inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonGui {
    export type AddControlsToContainerDto = WithDefaults<Inputs.BabylonGui.AddControlsToContainerDto, "clearControlsFirst">;
    export type AlignmentDto<T> = WithDefaults<Inputs.BabylonGui.AlignmentDto<T>, "horizontalAlignment" | "verticalAlignment">;
    export type ButtonDto = Inputs.BabylonGui.ButtonDto;
    export type CheckboxDto = Inputs.BabylonGui.CheckboxDto;
    export type CheckboxObservableSelectorDto = WithDefaults<Inputs.BabylonGui.CheckboxObservableSelectorDto, "selector">;
    export type CloneControlDto = WithDefaults<Inputs.BabylonGui.CloneControlDto, "name">;
    export type ColorPickerDto = Inputs.BabylonGui.ColorPickerDto;
    export type ColorPickerObservableSelectorDto = WithDefaults<Inputs.BabylonGui.ColorPickerObservableSelectorDto, "selector">;
    export type ContainerDto = Inputs.BabylonGui.ContainerDto;
    export type ControlDto = Inputs.BabylonGui.ControlDto;
    export type ControlObservableSelectorDto = WithDefaults<Inputs.BabylonGui.ControlObservableSelectorDto, "selector">;
    export type CreateButtonDto = WithDefaults<Inputs.BabylonGui.CreateButtonDto, "name" | "label" | "color" | "background" | "fontSize">;
    export type CreateCheckboxDto = WithDefaults<Inputs.BabylonGui.CreateCheckboxDto, "name" | "isChecked" | "checkSizeRatio" | "color" | "background">;
    export type CreateColorPickerDto = WithDefaults<Inputs.BabylonGui.CreateColorPickerDto, "name" | "defaultColor" | "color">;
    export type CreateForMeshDto = WithDefaults<Inputs.BabylonGui.CreateForMeshDto, "supportPointerMove" | "onlyAlphaTesting" | "invertY" | "sampling">;
    export type CreateFullScreenUIDto = WithDefaults<Inputs.BabylonGui.CreateFullScreenUIDto, "name" | "foreground" | "adaptiveScaling">;
    export type CreateImageDto = WithDefaults<Inputs.BabylonGui.CreateImageDto, "name" | "color">;
    export type CreateInputTextDto = WithDefaults<Inputs.BabylonGui.CreateInputTextDto, "name" | "text" | "placeholder" | "color" | "background">;
    export type CreateRadioButtonDto = WithDefaults<Inputs.BabylonGui.CreateRadioButtonDto, "name" | "isChecked" | "checkSizeRatio" | "color" | "background">;
    export type CreateSliderDto = WithDefaults<Inputs.BabylonGui.CreateSliderDto, "name" | "minimum" | "maximum" | "value" | "step" | "isVertical" | "color" | "background" | "displayThumb">;
    export type CreateStackPanelDto = WithDefaults<Inputs.BabylonGui.CreateStackPanelDto, "name" | "isVertical" | "spacing" | "color" | "background">;
    export type CreateTextBlockDto = WithDefaults<Inputs.BabylonGui.CreateTextBlockDto, "name" | "text" | "color" | "fontSize">;
    export type GetControlByNameDto = WithDefaults<Inputs.BabylonGui.GetControlByNameDto, "name">;
    export type ImageDto = Inputs.BabylonGui.ImageDto;
    export type InputTextDto = Inputs.BabylonGui.InputTextDto;
    export type InputTextObservableSelectorDto = WithDefaults<Inputs.BabylonGui.InputTextObservableSelectorDto, "selector">;
    export type PaddingLeftRightTopBottomDto = Inputs.BabylonGui.PaddingLeftRightTopBottomDto;
    export type RadioButtonDto = Inputs.BabylonGui.RadioButtonDto;
    export type RadioButtonObservableSelectorDto = WithDefaults<Inputs.BabylonGui.RadioButtonObservableSelectorDto, "selector">;
    export type SetButtonTextDto = WithDefaults<Inputs.BabylonGui.SetButtonTextDto, "text">;
    export type SetCheckboxBackgroundDto = WithDefaults<Inputs.BabylonGui.SetCheckboxBackgroundDto, "background">;
    export type SetCheckboxCheckSizeRatioDto = WithDefaults<Inputs.BabylonGui.SetCheckboxCheckSizeRatioDto, "checkSizeRatio">;
    export type SetCheckboxIsCheckedDto = WithDefaults<Inputs.BabylonGui.SetCheckboxIsCheckedDto, "isChecked">;
    export type SetColorPickerSizeDto = WithDefaults<Inputs.BabylonGui.SetColorPickerSizeDto, "size">;
    export type SetColorPickerValueDto = Inputs.BabylonGui.SetColorPickerValueDto;
    export type SetContainerBackgroundDto = WithDefaults<Inputs.BabylonGui.SetContainerBackgroundDto, "background">;
    export type SetContainerIsReadonlyDto = WithDefaults<Inputs.BabylonGui.SetContainerIsReadonlyDto, "isReadOnly">;
    export type SetControlColorDto = WithDefaults<Inputs.BabylonGui.SetControlColorDto, "color">;
    export type SetControlFontSizeDto = WithDefaults<Inputs.BabylonGui.SetControlFontSizeDto, "fontSize">;
    export type SetControlHeightDto = Inputs.BabylonGui.SetControlHeightDto;
    export type SetControlIsEnabledDto = WithDefaults<Inputs.BabylonGui.SetControlIsEnabledDto, "isEnabled">;
    export type SetControlIsReadonlyDto = WithDefaults<Inputs.BabylonGui.SetControlIsReadonlyDto, "isReadOnly">;
    export type SetControlIsVisibleDto = WithDefaults<Inputs.BabylonGui.SetControlIsVisibleDto, "isVisible">;
    export type SetControlWidthDto = Inputs.BabylonGui.SetControlWidthDto;
    export type SetImageUrlDto = Inputs.BabylonGui.SetImageUrlDto;
    export type SetInputTextBackgroundDto = WithDefaults<Inputs.BabylonGui.SetInputTextBackgroundDto, "background">;
    export type SetInputTextPlaceholderDto = WithDefaults<Inputs.BabylonGui.SetInputTextPlaceholderDto, "placeholder">;
    export type SetInputTextTextDto = WithDefaults<Inputs.BabylonGui.SetInputTextTextDto, "text">;
    export type SetRadioButtonBackgroundDto = WithDefaults<Inputs.BabylonGui.SetRadioButtonBackgroundDto, "background">;
    export type SetRadioButtonCheckSizeRatioDto = WithDefaults<Inputs.BabylonGui.SetRadioButtonCheckSizeRatioDto, "checkSizeRatio">;
    export type SetRadioButtonGroupDto = WithDefaults<Inputs.BabylonGui.SetRadioButtonGroupDto, "group">;
    export type SetSliderValueDto = WithDefaults<Inputs.BabylonGui.SetSliderValueDto, "value">;
    export type SetStackPanelHeightDto = Inputs.BabylonGui.SetStackPanelHeightDto;
    export type SetStackPanelIsVerticalDto = WithDefaults<Inputs.BabylonGui.SetStackPanelIsVerticalDto, "isVertical">;
    export type SetStackPanelSpacingDto = WithDefaults<Inputs.BabylonGui.SetStackPanelSpacingDto, "spacing">;
    export type SetStackPanelWidthDto = Inputs.BabylonGui.SetStackPanelWidthDto;
    export type SetTextBlockLineSpacingDto = Inputs.BabylonGui.SetTextBlockLineSpacingDto;
    export type SetTextBlockResizeToFitDto = WithDefaults<Inputs.BabylonGui.SetTextBlockResizeToFitDto, "resizeToFit">;
    export type SetTextBlockTextDto = Inputs.BabylonGui.SetTextBlockTextDto;
    export type SetTextBlockTextOutlineDto = WithDefaults<Inputs.BabylonGui.SetTextBlockTextOutlineDto, "outlineWidth" | "outlineColor">;
    export type SetTextBlockTextWrappingDto = Inputs.BabylonGui.SetTextBlockTextWrappingDto;
    export type SliderBackgroundColorDto = WithDefaults<Inputs.BabylonGui.SliderBackgroundColorDto, "backgroundColor">;
    export type SliderBorderColorDto = WithDefaults<Inputs.BabylonGui.SliderBorderColorDto, "borderColor">;
    export type SliderDto = Inputs.BabylonGui.SliderDto;
    export type SliderObservableSelectorDto = WithDefaults<Inputs.BabylonGui.SliderObservableSelectorDto, "selector">;
    export type SliderThumbDto = WithDefaults<Inputs.BabylonGui.SliderThumbDto, "isThumbCircle" | "thumbColor" | "isThumbClamped" | "displayThumb">;
    export type StackPanelDto = Inputs.BabylonGui.StackPanelDto;
    export type TextBlockDto = Inputs.BabylonGui.TextBlockDto;
    export type TextBlockObservableSelectorDto = WithDefaults<Inputs.BabylonGui.TextBlockObservableSelectorDto, "selector">;
}

/**
 * The BabylonIO inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonIO {
    export type ExportMeshesToStlDto = WithDefaults<Inputs.BabylonIO.ExportMeshesToStlDto, "fileName">;
    export type ExportMeshToStlDto = WithDefaults<Inputs.BabylonIO.ExportMeshToStlDto, "fileName">;
    export type ExportSceneDto = WithDefaults<Inputs.BabylonIO.ExportSceneDto, "fileName">;
    export type ExportSceneGlbBytesDto = WithDefaults<Inputs.BabylonIO.ExportSceneGlbBytesDto, "discardSkyboxAndGrid" | "compressWithDraco">;
    export type ExportSceneGlbDto = WithDefaults<Inputs.BabylonIO.ExportSceneGlbDto, "fileName" | "discardSkyboxAndGrid">;
}

/**
 * The BabylonJSScene inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonJSScene {
    export type InitBabylonJSDto = WithDefaults<Inputs.BabylonJSScene.InitBabylonJSDto, "sceneSize" | "backgroundColor" | "enableShadows" | "enableGround" | "groundCenter" | "groundScaleFactor" | "groundColor" | "groundOpacity" | "hemisphereLightSkyColor" | "hemisphereLightGroundColor" | "hemisphereLightIntensity" | "directionalLightColor" | "directionalLightIntensity" | "shadowMapSize" | "enableArcRotateCamera">;
}

/**
 * The BabylonLight inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonLight {
    export type ShadowLightDirectionToTargetDto = Inputs.BabylonLight.ShadowLightDirectionToTargetDto;
    export type ShadowLightPositionDto = Inputs.BabylonLight.ShadowLightPositionDto;
}

/**
 * The BabylonMaterial inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonMaterial {
    export type AlphaDto = WithDefaults<Inputs.BabylonMaterial.AlphaDto, "alpha">;
    export type AzimuthDto = WithDefaults<Inputs.BabylonMaterial.AzimuthDto, "azimuth">;
    export type BackFaceCullingDto = WithDefaults<Inputs.BabylonMaterial.BackFaceCullingDto, "backFaceCulling">;
    export type BaseColorDto = WithDefaults<Inputs.BabylonMaterial.BaseColorDto, "baseColor">;
    export type BaseTextureDto = Inputs.BabylonMaterial.BaseTextureDto;
    export type CameraOffsetDto = Inputs.BabylonMaterial.CameraOffsetDto;
    export type DistanceDto = WithDefaults<Inputs.BabylonMaterial.DistanceDto, "distance">;
    export type DitheringDto = WithDefaults<Inputs.BabylonMaterial.DitheringDto, "dithering">;
    export type InclinationDto = WithDefaults<Inputs.BabylonMaterial.InclinationDto, "inclination">;
    export type LuminanceDto = WithDefaults<Inputs.BabylonMaterial.LuminanceDto, "luminance">;
    export type MaterialPropDto = Inputs.BabylonMaterial.MaterialPropDto;
    export type MetallicDto = WithDefaults<Inputs.BabylonMaterial.MetallicDto, "metallic">;
    export type MieCoefficientDto = WithDefaults<Inputs.BabylonMaterial.MieCoefficientDto, "mieCoefficient">;
    export type MieDirectionalGDto = WithDefaults<Inputs.BabylonMaterial.MieDirectionalGDto, "mieDirectionalG">;
    export type PBRMetallicRoughnessDto = WithDefaults<Inputs.BabylonMaterial.PBRMetallicRoughnessDto, "name" | "baseColor" | "emissiveColor" | "metallic" | "roughness" | "alpha" | "backFaceCulling" | "zOffset">;
    export type RayleighDto = WithDefaults<Inputs.BabylonMaterial.RayleighDto, "rayleigh">;
    export type RoughnessDto = WithDefaults<Inputs.BabylonMaterial.RoughnessDto, "roughness">;
    export type SkyMaterialDto = WithDefaults<Inputs.BabylonMaterial.SkyMaterialDto, "luminance" | "turbidity" | "rayleigh" | "mieCoefficient" | "mieDirectionalG" | "distance" | "inclination" | "azimuth" | "useSunPosition" | "up" | "dithering">;
    export type SkyMaterialPropDto = Inputs.BabylonMaterial.SkyMaterialPropDto;
    export type SunPositionDto = Inputs.BabylonMaterial.SunPositionDto;
    export type TurbidityDto = WithDefaults<Inputs.BabylonMaterial.TurbidityDto, "turbidity">;
    export type UpDto = Inputs.BabylonMaterial.UpDto;
    export type UseSunPositionDto = WithDefaults<Inputs.BabylonMaterial.UseSunPositionDto, "useSunPosition">;
}

/**
 * The BabylonMesh inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonMesh {
    export type BabylonMeshDto = Inputs.BabylonMesh.BabylonMeshDto;
    export type BabylonMeshWithChildrenDto = WithDefaults<Inputs.BabylonMesh.BabylonMeshWithChildrenDto, "includeChildren">;
    export type ByIdBabylonMeshDto = Inputs.BabylonMesh.ByIdBabylonMeshDto;
    export type ByNameBabylonMeshDto = Inputs.BabylonMesh.ByNameBabylonMeshDto;
    export type CheckCollisionsBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.CheckCollisionsBabylonMeshDto, "checkCollisions" | "includeChildren">;
    export type ChildMeshesBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.ChildMeshesBabylonMeshDto, "directDescendantsOnly">;
    export type CloneBabylonMeshDto = Inputs.BabylonMesh.CloneBabylonMeshDto;
    export type CloneToPositionsDto = WithDefaults<Inputs.BabylonMesh.CloneToPositionsDto, "positions">;
    export type IdBabylonMeshDto = Inputs.BabylonMesh.IdBabylonMeshDto;
    export type IntersectsMeshDto = WithDefaults<Inputs.BabylonMesh.IntersectsMeshDto, "precise" | "includeDescendants">;
    export type IntersectsPointDto = Inputs.BabylonMesh.IntersectsPointDto;
    export type MaterialBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.MaterialBabylonMeshDto, "includeChildren">;
    export type MergeMeshesDto = WithDefaults<Inputs.BabylonMesh.MergeMeshesDto, "disposeSource" | "allow32BitsIndices" | "subdivideWithSubMeshes" | "multiMultiMaterials">;
    export type MeshInstanceAndTransformDto = Inputs.BabylonMesh.MeshInstanceAndTransformDto;
    export type MeshInstanceDto = Inputs.BabylonMesh.MeshInstanceDto;
    export type NameBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.NameBabylonMeshDto, "includeChildren">;
    export type PickableBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.PickableBabylonMeshDto, "pickable" | "includeChildren">;
    export type RotateAroundAxisNodeDto = WithDefaults<Inputs.BabylonMesh.RotateAroundAxisNodeDto, "position" | "axis" | "angle">;
    export type RotateBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.RotateBabylonMeshDto, "rotate">;
    export type ScaleInPlaceDto = WithDefaults<Inputs.BabylonMesh.ScaleInPlaceDto, "scale">;
    export type SetMeshVisibilityDto = WithDefaults<Inputs.BabylonMesh.SetMeshVisibilityDto, "visibility" | "includeChildren">;
    export type SetParentDto = Inputs.BabylonMesh.SetParentDto;
    export type ShowHideMeshDto = WithDefaults<Inputs.BabylonMesh.ShowHideMeshDto, "includeChildren">;
    export type TranslateBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.TranslateBabylonMeshDto, "distance">;
    export type UniqueIdBabylonMeshDto = WithDefaults<Inputs.BabylonMesh.UniqueIdBabylonMeshDto, "uniqueId">;
    export type UpdateDrawnBabylonMesh = Inputs.BabylonMesh.UpdateDrawnBabylonMesh;
    export type UpdateDrawnBabylonMeshPositionDto = Inputs.BabylonMesh.UpdateDrawnBabylonMeshPositionDto;
    export type UpdateDrawnBabylonMeshRotationDto = Inputs.BabylonMesh.UpdateDrawnBabylonMeshRotationDto;
    export type UpdateDrawnBabylonMeshScaleDto = Inputs.BabylonMesh.UpdateDrawnBabylonMeshScaleDto;
}

/**
 * The BabylonMeshBuilder inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonMeshBuilder {
    export type CreateBoxDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateBoxDto, "width" | "depth" | "height" | "sideOrientation" | "enableShadows">;
    export type CreateCapsuleDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateCapsuleDto, "subdivisions" | "tessellation" | "height" | "radius" | "capSubdivisions" | "radiusTop" | "radiusBottom" | "topCapSubdivisions" | "bottomCapSubdivisions" | "sideOrientation" | "enableShadows">;
    export type CreateCubeDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateCubeDto, "size" | "sideOrientation" | "enableShadows">;
    export type CreateCylinderDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateCylinderDto, "height" | "diameterTop" | "diameterBottom" | "tessellation" | "subdivisions" | "sideOrientation" | "enableShadows">;
    export type CreateDiscDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateDiscDto, "radius" | "tessellation" | "arc" | "sideOrientation" | "enableShadows">;
    export type CreateExtrudedShapeDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateExtrudedShapeDto, "scale" | "rotation" | "closeShape" | "closePath" | "cap" | "sideOrientation" | "enableShadows">;
    export type CreateGeodesicDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateGeodesicDto, "m" | "n" | "size" | "sizeX" | "sizeY" | "sizeZ" | "flat" | "subdivisions" | "sideOrientation" | "enableShadows">;
    export type CreateGoldbergDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateGoldbergDto, "m" | "n" | "size" | "sizeX" | "sizeY" | "sizeZ" | "sideOrientation" | "enableShadows">;
    export type CreateGroundDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateGroundDto, "width" | "height" | "subdivisionsX" | "subdivisionsY" | "sideOrientation" | "enableShadows">;
    export type CreateIcoSphereDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateIcoSphereDto, "radius" | "radiusX" | "radiusY" | "radiusZ" | "flat" | "subdivisions" | "sideOrientation" | "enableShadows">;
    export type CreateLatheDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateLatheDto, "radius" | "tessellation" | "arc" | "closed" | "sideOrientation" | "enableShadows">;
    export type CreatePolygonDto = WithDefaults<Inputs.BabylonMeshBuilder.CreatePolygonDto, "depth" | "smoothingThreshold" | "sideOrientation" | "wrap" | "enableShadows">;
    export type CreatePolyhedronDto = WithDefaults<Inputs.BabylonMeshBuilder.CreatePolyhedronDto, "size" | "type" | "sizeX" | "sizeY" | "sizeZ" | "flat" | "sideOrientation" | "enableShadows">;
    export type CreateRectanglePlaneDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateRectanglePlaneDto, "width" | "height" | "sideOrientation" | "enableShadows">;
    export type CreateRibbonDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateRibbonDto, "closeArray" | "closePath" | "offset" | "updatable" | "sideOrientation" | "enableShadows">;
    export type CreateSphereDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateSphereDto, "diameter" | "segments" | "sideOrientation" | "enableShadows">;
    export type CreateSquarePlaneDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateSquarePlaneDto, "size" | "sideOrientation" | "enableShadows">;
    export type CreateTorusDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateTorusDto, "diameter" | "thickness" | "tessellation" | "sideOrientation" | "enableShadows">;
    export type CreateTorusKnotDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateTorusKnotDto, "radius" | "tube" | "radialSegments" | "tubularSegments" | "p" | "q" | "sideOrientation" | "enableShadows">;
    export type CreateTubeDto = WithDefaults<Inputs.BabylonMeshBuilder.CreateTubeDto, "radius" | "tessellation" | "cap" | "arc" | "sideOrientation" | "enableShadows">;
    export type ExtrudePolygonDto = WithDefaults<Inputs.BabylonMeshBuilder.ExtrudePolygonDto, "depth" | "sideOrientation" | "wrap" | "enableShadows">;
}

/**
 * The BabylonNode inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonNode {
    export type CreateNodeFromRotationDto = WithDefaults<Inputs.BabylonNode.CreateNodeFromRotationDto, "origin" | "rotation">;
    export type DrawNodeDto = WithDefaults<Inputs.BabylonNode.DrawNodeDto, "colorX" | "colorY" | "colorZ" | "size">;
    export type DrawNodesDto = WithDefaults<Inputs.BabylonNode.DrawNodesDto, "colorX" | "colorY" | "colorZ" | "size">;
    export type DrawNodeSharedDto = WithDefaults<Inputs.BabylonNode.DrawNodeSharedDto, "colorX" | "colorY" | "colorZ" | "size">;
    export type NodeDirectionDto = Inputs.BabylonNode.NodeDirectionDto;
    export type NodeDto = Inputs.BabylonNode.NodeDto;
    export type NodeParentDto = Inputs.BabylonNode.NodeParentDto;
    export type NodePositionDto = Inputs.BabylonNode.NodePositionDto;
    export type NodeTranslationDto = Inputs.BabylonNode.NodeTranslationDto;
    export type RotateAroundAxisNodeDto = WithDefaults<Inputs.BabylonNode.RotateAroundAxisNodeDto, "position" | "axis" | "angle">;
    export type RotateNodeDto = WithDefaults<Inputs.BabylonNode.RotateNodeDto, "axis" | "angle">;
}

/**
 * The BabylonPick inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonPick {
    export type PickInfo = Inputs.BabylonPick.PickInfo;
    export type RayDto = Inputs.BabylonPick.RayDto;
}

/**
 * The BabylonRay inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonRay {
    export type BaseRayDto = Inputs.BabylonRay.BaseRayDto;
    export type FromToDto = Inputs.BabylonRay.FromToDto;
    export type RayDto = Inputs.BabylonRay.RayDto;
}

/**
 * The BabylonScene inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonScene {
    export type ActiveCameraDto = Inputs.BabylonScene.ActiveCameraDto;
    export type CameraConfigurationDto = WithDefaults<Inputs.BabylonScene.CameraConfigurationDto, "position" | "lookAt" | "lowerBetaLimit" | "upperBetaLimit" | "angularSensibilityX" | "angularSensibilityY" | "maxZ" | "panningSensibility" | "wheelPrecision">;
    export type DirectionalLightDto = WithDefaults<Inputs.BabylonScene.DirectionalLightDto, "direction" | "intensity" | "diffuse" | "specular" | "shadowGeneratorMapSize" | "enableShadows" | "shadowDarkness" | "shadowUsePercentageCloserFiltering" | "transparencyShadow" | "shadowContactHardeningLightSizeUVRatio" | "shadowBias" | "shadowNormalBias" | "shadowMaxZ" | "shadowMinZ" | "shadowRefreshRate">;
    export type EnablePhysicsDto = WithDefaults<Inputs.BabylonScene.EnablePhysicsDto, "vector">;
    export type FogDto = WithDefaults<Inputs.BabylonScene.FogDto, "mode" | "color" | "density" | "start" | "end">;
    export type PointerDto = Inputs.BabylonScene.PointerDto;
    export type PointLightDto = WithDefaults<Inputs.BabylonScene.PointLightDto, "position" | "intensity" | "diffuse" | "specular" | "radius" | "shadowGeneratorMapSize" | "enableShadows" | "shadowDarkness" | "transparencyShadow" | "shadowUsePercentageCloserFiltering" | "shadowContactHardeningLightSizeUVRatio" | "shadowBias" | "shadowNormalBias" | "shadowMaxZ" | "shadowMinZ" | "shadowRefreshRate">;
    export type SceneBackgroundColourDto = WithDefaults<Inputs.BabylonScene.SceneBackgroundColourDto, "colour">;
    export type SceneCanvasBackgroundImageDto = WithDefaults<Inputs.BabylonScene.SceneCanvasBackgroundImageDto, "repeat" | "size" | "position" | "attachment" | "origin" | "clip">;
    export type SceneCanvasCSSBackgroundImageDto = WithDefaults<Inputs.BabylonScene.SceneCanvasCSSBackgroundImageDto, "cssBackgroundImage">;
    export type SceneDto = Inputs.BabylonScene.SceneDto;
    export type SceneMultiColorLinearGradientDto = WithDefaults<Inputs.BabylonScene.SceneMultiColorLinearGradientDto, "colors" | "stops" | "direction">;
    export type SceneMultiColorRadialGradientDto = WithDefaults<Inputs.BabylonScene.SceneMultiColorRadialGradientDto, "colors" | "stops" | "position" | "shape">;
    export type SceneTwoColorLinearGradientDto = WithDefaults<Inputs.BabylonScene.SceneTwoColorLinearGradientDto, "colorFrom" | "colorTo" | "direction" | "stopFrom" | "stopTo">;
    export type SceneTwoColorRadialGradientDto = WithDefaults<Inputs.BabylonScene.SceneTwoColorRadialGradientDto, "colorFrom" | "colorTo" | "position" | "stopFrom" | "stopTo" | "shape">;
    export type SkyboxCustomTextureDto = WithDefaults<Inputs.BabylonScene.SkyboxCustomTextureDto, "textureSize" | "size" | "blur" | "environmentIntensity" | "hideSkybox" | "enableGroundProjection" | "projectedGroundRadius" | "projectedGroundHeight">;
    export type SkyboxDto = WithDefaults<Inputs.BabylonScene.SkyboxDto, "skybox" | "size" | "blur" | "environmentIntensity" | "hideSkybox" | "enableGroundProjection" | "projectedGroundRadius" | "projectedGroundHeight">;
    export type SkyboxFromTextureDto = WithDefaults<Inputs.BabylonScene.SkyboxFromTextureDto, "size" | "blur" | "environmentIntensity" | "hideSkybox" | "enableGroundProjection" | "projectedGroundRadius" | "projectedGroundHeight">;
    export type SkyboxSharedDto = WithDefaults<Inputs.BabylonScene.SkyboxSharedDto, "size" | "blur" | "environmentIntensity" | "hideSkybox" | "enableGroundProjection" | "projectedGroundRadius" | "projectedGroundHeight">;
    export type UseRightHandedSystemDto = WithDefaults<Inputs.BabylonScene.UseRightHandedSystemDto, "use">;
}

/**
 * The BabylonTexture inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonTexture {
    export type TextureImageDto = WithDefaults<Inputs.BabylonTexture.TextureImageDto, "name" | "hasAlpha" | "invertY" | "samplingMode">;
    export type TextureSimpleDto = WithDefaults<Inputs.BabylonTexture.TextureSimpleDto, "name" | "invertY" | "invertZ" | "wAng" | "uScale" | "vScale" | "uOffset" | "vOffset" | "samplingMode">;
}

/**
 * The BabylonTools inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonTools {
    export type ScreenshotDto = WithDefaults<Inputs.BabylonTools.ScreenshotDto, "width" | "height" | "mimeType" | "quality">;
}

/**
 * The BabylonTransforms inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonTransforms {
    export type RotationCenterAxisDto = WithDefaults<Inputs.BabylonTransforms.RotationCenterAxisDto, "angle" | "axis" | "center">;
    export type RotationCenterDto = WithDefaults<Inputs.BabylonTransforms.RotationCenterDto, "angle" | "center">;
    export type RotationCenterYawPitchRollDto = WithDefaults<Inputs.BabylonTransforms.RotationCenterYawPitchRollDto, "yaw" | "pitch" | "roll" | "center">;
    export type ScaleCenterXYZDto = WithDefaults<Inputs.BabylonTransforms.ScaleCenterXYZDto, "center" | "scaleXyz">;
    export type ScaleXYZDto = WithDefaults<Inputs.BabylonTransforms.ScaleXYZDto, "scaleXyz">;
    export type TransformBabylonMeshDto = Inputs.BabylonTransforms.TransformBabylonMeshDto;
    export type TranslationsXYZDto = Inputs.BabylonTransforms.TranslationsXYZDto;
    export type TranslationXYZDto = WithDefaults<Inputs.BabylonTransforms.TranslationXYZDto, "translation">;
    export type UniformScaleDto = WithDefaults<Inputs.BabylonTransforms.UniformScaleDto, "scale">;
    export type UniformScaleFromCenterDto = WithDefaults<Inputs.BabylonTransforms.UniformScaleFromCenterDto, "scale" | "center">;
}

/**
 * The BabylonWebXR inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace BabylonWebXR {
    export type DefaultWebXRWithTeleportationDto = Inputs.BabylonWebXR.DefaultWebXRWithTeleportationDto;
    export type WebXRDefaultExperienceDto = Inputs.BabylonWebXR.WebXRDefaultExperienceDto;
    export type WebXRDefaultExperienceOptions = Inputs.BabylonWebXR.WebXRDefaultExperienceOptions;
    export type WebXRExperienceHelperDto = Inputs.BabylonWebXR.WebXRExperienceHelperDto;
}

/**
 * The Draw inputs DTOs as their defaults leave them: every property with a default is present,
 * the way `resolveDto` hands a DTO to the code that reads it.
 */
export namespace Draw {
    export type DrawAny<E extends Inputs.Draw.Entity = Inputs.Draw.Entity> = Inputs.Draw.DrawAny<E>;
    export type DrawBasicGeometryOptions = WithDefaults<Inputs.Draw.DrawBasicGeometryOptions, "colours" | "colorMapStrategy" | "size" | "opacity" | "updatable" | "hidden" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity" | "arrowSize" | "arrowAngle">;
    export type DrawManifoldOrCrossSectionOptions = WithDefaults<Inputs.Draw.DrawManifoldOrCrossSectionOptions, "faceOpacity" | "faceColour" | "crossSectionColour" | "crossSectionWidth" | "crossSectionOpacity" | "computeNormals" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity">;
    export type DrawNodeOptions = WithDefaults<Inputs.Draw.DrawNodeOptions, "colorX" | "colorY" | "colorZ" | "size">;
    export type DrawOcctShapeMaterialOptions = WithDefaults<Inputs.Draw.DrawOcctShapeMaterialOptions, "precision" | "drawEdges" | "edgeColour" | "edgeWidth">;
    export type DrawOcctShapeOptions = WithDefaults<Inputs.Draw.DrawOcctShapeOptions, "faceOpacity" | "edgeOpacity" | "edgeColour" | "faceColour" | "vertexColour" | "edgeWidth" | "vertexSize" | "drawEdges" | "drawFaces" | "drawVertices" | "precision" | "drawEdgeIndexes" | "edgeIndexHeight" | "edgeIndexColour" | "drawFaceIndexes" | "faceIndexHeight" | "faceIndexColour" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity" | "edgeArrowSize" | "edgeArrowAngle" | "keepMeshData" | "allowQualityDecrease" | "forceFaceDeflection">;
    export type DrawOcctShapeSimpleOptions = WithDefaults<Inputs.Draw.DrawOcctShapeSimpleOptions, "precision" | "drawFaces" | "faceColour" | "drawEdges" | "edgeColour" | "edgeWidth" | "drawTwoSided" | "backFaceColour" | "backFaceOpacity">;
    export type GenericPBRMaterialDto = WithDefaults<Inputs.Draw.GenericPBRMaterialDto, "name" | "baseColor" | "metallic" | "roughness" | "alpha" | "emissiveColor" | "emissiveIntensity" | "zOffset" | "zOffsetUnits" | "alphaMode" | "alphaCutoff" | "doubleSided" | "wireframe" | "unlit">;
    export type GenericTextureDto = WithDefaults<Inputs.Draw.GenericTextureDto, "name" | "uScale" | "vScale" | "uOffset" | "vOffset" | "wAng" | "invertY" | "invertZ" | "samplingMode">;
    export type SceneDrawGridMeshDto = WithDefaults<Inputs.Draw.SceneDrawGridMeshDto, "width" | "height" | "subdivisions" | "majorUnitFrequency" | "minorUnitVisibility" | "gridRatio" | "opacity" | "backFaceCulling" | "mainColor" | "secondaryColor">;
}
