// GENERATED by scripts/gen-worker-api.mjs from packages/dev/manifold/lib/api/services/mesh/mesh.ts - do not edit.
// The kernel class is the source of the docs, the signatures and the member order.
// Regenerate with `npm run gen:worker-api` at the repository root.
import { ManifoldWorkerManager } from "../../manifold-worker/manifold-worker-manager";
import { MeshOperations } from "./operations";
import { MeshEvaluate } from "./evaluate";

/**
 * The plain triangle data of a Manifold solid, as `manifold.manifoldToMesh` hands it out:
 * `evaluate` reads vertices, triangles, tangents and the runs that group triangles by their
 * original shape, and `operations` repairs merge information. A mesh is what crosses from the
 * kernel to a renderer or a file.
 */
export class Mesh {
    public readonly operations: MeshOperations;
    public readonly evaluate: MeshEvaluate;

    constructor(
        manifoldWorkerManager: ManifoldWorkerManager
    ) {
        this.operations = new MeshOperations(manifoldWorkerManager);
        this.evaluate = new MeshEvaluate(manifoldWorkerManager);
    }
}
